### ISSUE TITLE
Consolidate Github Charts

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#102]
There are several charts which are basically just "Github Stat X by time and repository/repository group".  We'd like to consolidate these down to two charts:

1. Github Stats by Repository Group
2. Github Stats by Repository

This would contain the same selectors you see for Issues by Repository group: Period, Repo Group (or repository), and releases checkbox.  But we'd add a "statistic" selector, which would offer the following options:

* Commits
* Issues Opened
* Issues Closed
* PRs Opened
* PRs Merged
* PRs Closed (but not merged)
* Reviewers
* PR Comments
* Issue Comments

This would replace the following charts:

* Commits repository groups
* Issues repository group
* New PRs repository groups
* PRs merged repos
* PRs merged repository groups
* Reviewers repository groups
* Commenters in Repository Groups
* Comments in Repository Groups

This request has been already approved by @Phillels

**Comment by lukaszgryglicki** [comment]
Ok will work on this.

**Comment by lukaszgryglicki** [comment]
I'm starting work on this (first checking which data is returned by those dashboards and then I'll try to merge them).

**Comment by lukaszgryglicki** [comment]
Actually I can start working on this just now. I had other task last days...

**Comment by lukaszgryglicki** [comment]
Some of those charts has only "repo groups" version.
There will be two charts finally, and each of them will contain all metrics defined for both "repo" and "repo groups" versions. So I will have to add few metrics under the hood, but no problem.
This is rather big and will take few days IMHO.
- PRs Closed (but not merged) - this one is new.

**Comment by lukaszgryglicki** [comment]
I've created Postgres [SQL](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/github_stats_by_repo_groups.sql) that gets data for "repo groups" version of the new chart.
SQL for "repos" version tomorrow. Then YAML, InfluxDB, Dashboard JSON and dropping old data and generating new data first on the test next on the prod.

**Comment by lukaszgryglicki** [comment]
Need to switch for a small one day task. Removing `wip` label.

**Comment by lukaszgryglicki** [comment]
And query per repo (not repo group) also [ready](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/github_stats_by_repos.sql)

**Comment by lukaszgryglicki** [comment]
"Repositroy groups" consolidated version ready (only on the test).
- https://k8s.cncftest.io/d/q5EuHkMmz/github-stats-by-repository-group?orgId=1

Now I need to delete dashboards no more needed, drop all unneeded influx data, possibly regenerate database (not sure yet).
I'll add another dashboard on the test server tomorrow. make sure all works OK and there are no unneeded series anymore and finally I'll install on prod.

**Comment by lukaszgryglicki** [comment]
Ohh and I see it received random uid - ugly one. I'll also fix this tomorrow.

**Comment by lukaszgryglicki** [comment]
Ugly uid fixed, query for "repos" version ready, now Influx data generating for all time data.

**Comment by lukaszgryglicki** [comment]
This is the first version of "Repository" chart, but it contains "duplicate repos bug"
https://k8s.cncftest.io/d/49/github-stats-by-repository?orgId=1

I'll fix this soon.
This is due to repo renames - so it displays the same data twice or more, while this is just the same renamed repo.
I'll only show the current repo name in the next version.

**Comment by lukaszgryglicki** [comment]
This is a bit deeper than I thought, need to examine some other charts and tags to see hwo to handle this.
Basically I'll group all repos with the same ID under their newest name.
But need to take a step back here.

**Comment by lukaszgryglicki** [comment]
I probably have a solution, I'll first check all other dashboards that use repo names (not groups) because later I would have to regenerate k8s influx db anyway (to avoid manually dropping series and actually this is a good idea once per some longer period). All on the test server of course.

**Comment by lukaszgryglicki** [comment]
Reviewers dashboard had documentation I will move it to new GitHub stats - repos/repo groups.

**Comment by lukaszgryglicki** [comment]
OK I'll do final regenerate influx DB now, so test server can be unavailable.
I'll update here when done.

**Comment by lukaszgryglicki** [comment]
Database is regenerated (temp).
I've switched Grafana to use new database that was just generated.
After it is copied to original I'll switch back.
That way there'll be no downtime.

Two new reports are available now (corrected) and 7 requested dahsboards were dropped.

**Comment by lukaszgryglicki** [comment]
All regenerated on the test server, I'll update prod tomorrow.
I'll also add delete support for `sqlite` tool (so it will supprt full CRUD on dashboards) and investigate bug with slow histogram on 'All CNCF' project (detected today when analysing logs to see why "All" project sync takes so long).
Will ether speedup slow metric (when I find which one) or maye add some support for specifying how often sync very long periods (for "All" which doesn't have annotations from the repo it is probably since first CNCF project join date to now - will see tomorrow during prod database regenerating.)
There will be no downtime on prod - I'll do the same as I did today on the test - it worked.

**Comment by lukaszgryglicki** [comment]
Ported documentation from dropped Reviewers dashboard.
It will only appear when "reviewers" statistic is selected from the drop down.
For other stats other docs **will** appear - but currently there are no other docs, so it will either show or hide.
![screen shot 2018-04-27 at 11 29 41](https://user-images.githubusercontent.com/2469783/39355807-7be7c8be-4a0e-11e8-8821-7ef8f33d7e05.png)

**Comment by lukaszgryglicki** [comment]
Added on production:
- https://k8s.devstats.cncf.io/d/49/github-stats-by-repository?orgId=1
- https://k8s.devstats.cncf.io/d/48/github-stats-by-repository-group?orgId=1

Closing, please reopen if needed.
