### ISSUE TITLE
Use config files to configure grafana data sources

### ISSUE THREAD

**Issue by jlewi** [cncf/devstats.archive#103]
Right now the [instructions](https://github.com/cncf/devstats/blob/master/GRAFANA.md) configure Grafana via the UI.

It would be nice if instead grafana could be configured via [config files](http://docs.grafana.org/features/datasources/influxdb/).

This would make it easier to migrate to managing devstats deployments completely declaratively which would make it a lot easier for folks to deploy and manage devstats themselves for their own projects. 

Related to #72 & kubeflow/community#34

**Comment by lukaszgryglicki** [comment]
This is half manual right now.
Automatic deploy script creates customized/branded Grafana installation, see:
`devel/create_grafana.sh`.

Some work still needs to be done manually. Full Grafana config can be fetched from the test server.
We're configuring N Grafanas on the single host and we're branding them. This is rather CNCF specific. So you may want to change this workflow for your case.
Same with https: we're using apache proxy + Let's encrypt certbot.

I understand some parts are really CNCF specific, so possibly special/ another workflow will be needed in your case here.

I will also update `sqlitedb` tool to allow adding new dashboards from JSONs.

**Comment by lukaszgryglicki** [comment]
Added support for importing new dashboards from command line using `sqlite` tool.
See: https://github.com/cncf/devstats/blob/master/devel/import_jsons_to_sqlite.sh

It is now connected as a part of automatic deploy for new projects: https://github.com/cncf/devstats/blob/master/devel/create_grafana.sh#L148-L151

[sqlite tool](https://github.com/cncf/devstats/blob/master/cmd/sqlitedb/sqlitedb.go#L182) now is able to create new dashboards (it only supported updating existing ones before).
Closing this.

**Comment by lukaszgryglicki** [comment]
Production fininshed delete.
But test is still running `singe delete query` 5h40m already.
