### ISSUE TITLE
K8s DevStats - Link is not working

### ISSUE THREAD

**Issue by isamrish** [cncf/devstats.archive#105]
Hi,
   I was going through k8s dashboards ( main dashbaord ), then I found a link in not working.

![k8s](https://user-images.githubusercontent.com/6524419/39430996-07ab40ba-4cad-11e8-9433-6fd226ae71fb.png)

In above pics, the postgres sql file link is not working.

I think , this can be solved by changing links in **docs/dashboards/dashboards.md**

**Comment by lukaszgryglicki** [comment]
Will fix today.
dashboards were renamed several times recently.

**Comment by isamrish** [comment]
if anything I can help you??
I am learning about devstats for sometime.

**Comment by lukaszgryglicki** [comment]
Fixed everywhere.
Closing.
Thanks for reporting.
