### ISSUE TITLE
Investigate correctness and performance of using Postgres as a TSDB

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#107]
Investigate speed, correctness of my idea of using Postgres as a time-series DB (PSQLaaTSDB):
All emulation is written [here](https://github.com/cncf/devstats/blob/master/pg_conn.go), function `WriteTSPoints`).
Requested by @jberkus

**Comment by jberkus** [comment]
I'm having trouble picturing how this is being stored in the DB from the code.  Do we have a version of the DB which is already using this storage?

**Comment by lukaszgryglicki** [comment]
Use ssh bastion.
Default gha database already has that data:
- Tables starting with "s" stores time series data.
- Tables starting with "t" stores tags data.
- Other tables are just GHA data.

**Comment by lukaszgryglicki** [comment]
As discussed on slack, you should have access to tables now.

**Comment by jberkus** [comment]
Can we close this?  None of our current issues have anything to do with data storage backend.
