### ISSUE TITLE
GDPR compliance for Devstats

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#108]
Devstats is one of the few self-hosted resources for Kubernetes/CNCF which contains personal information. As such, we need to have a GDPR policy for it.

Here's my draft set of recommendations:

1.  Create a gdpr@ alias for requests, to go to a commitee (Elsie/me/Lukasz currently).
2.  Removal requests: replace any user who requests removal with anon-# for their github handle.  As in, we won't delete their data because it is important historically, but we will anonymize them.
3. Information requests: all devstats data is public.  However, we can also do database queries to get all of a specific user's data.
4. Publish a policy somewhere on devstats.io.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Done.
- I've added instructions how to request some data to be hidden [here](https://github.com/cncf/devstats/blob/master/HIDE_DATA.md), referenced [from README.md](https://github.com/cncf/devstats#data-hiding)
- I've added [hide_data](https://github.com/cncf/devstats/blob/master/cmd/hide_data/hide_data.go) tool that updates [hide/hide.csv](https://github.com/cncf/devstats/blob/master/hide/hide.csv). User requests to hide "some data" and tool calculates SHA-1 value and puts it there. User then creates PR and we're merging this.
- `hide_data` tool also supports reading "forbiden" values from its config file and processing all projects, all tables to replace data as needed. This can be done manually after merging PR with new data to hide.
- Standard process enhanced to hide sensitive data on-the fly (updated [gha2db](https://github.com/cncf/devstats/blob/master/cmd/gha2db/gha2db.go) and [import_affs](https://github.com/cncf/devstats/blob/master/cmd/import_affs/import_affs.go) tools - they are the only source of user-sensitive data in devstats data flow). Search for `maybeHide`.
- They both use new shared functionality `maybeHide` implemented [here](https://github.com/cncf/devstats/blob/master/string.go#L66-L108) (search for "maybeHide"), test coverage [here](https://github.com/cncf/devstats/blob/master/string_test.go#L44-L105).

**Comment by jberkus** [comment]
OK, the tool is great!

However, we still need a statement linked from the Devstats homepage.

**Comment by lukaszgryglicki** [comment]
It will be discussed on the community meeting.

**Comment by lukaszgryglicki** [comment]
Closing this for now. let me know if I need to reopen or do anythign more for this.
Anonymizing data support was added but currently there is no single SHA disabled.

**Comment by karnauskas** [comment]
What about contacting _every_ single person via collected email address, and asking if it's OK to scrap their LinkedIn account and store information on GitHub? I was always wondering why there was one of my emails popping up once a while there was data breach.

**Comment by lukaszgryglicki** [comment]
We can do that and in the meantime, you can request your personal data to be removed if you want to.
