### ISSUE TITLE
Drop Graphs from Kubernetes DevStats Dashboard 

### ISSUE THREAD

**Issue by Phillels** [cncf/devstats.archive#109]
ephillip@redhat.com

Please drop the following graphs from the dashboard: 

-Activity repository groups
-Approvers repository groups
-PRs Approval repository groups stacked
-PRs Authors Companies table
-SIG mentions categories
-SIG mentions using labels
-Suggested approvers by repository groups

They have been reviewed by the DevStats subproject committee and have been judged to be lacking in value for the project or confusing.

**Comment by lukaszgryglicki** [comment]
I'm in the middle of porting time-series from Influx to Postgres.
I've already ported all K8s dashboards, so I will drop them.
But this will be done when I finish porting, to avoid doing this twice: on the prod and on the test.
Is this ok?

**Comment by lukaszgryglicki** [comment]
Done o the test server.
It will be done on prod server when I finish porting TS from influx to Postgres:
- https://k8s.cncftest.io

**Comment by lukaszgryglicki** [comment]
Done on both test & prod.
BTW: 
- devstats now use postgres as a time series DB on both test & prod servers.
- OS was updated on both servers to Ubuntu 18.04 LTS on both servers
- Postgres was updated on both to 10.3.
