### ISSUE TITLE
Consider SIGs as a top level dashboard object

### ISSUE THREAD

**Issue by castrojo** [cncf/devstats.archive#11]
I think it'd be a useful tool for the SIGs if the metrics being measured could be made available to them on a SIG level. So for example it'd be nice for SIGs to know how they'd been doing cycle to cycle or perhaps allow people to ascertain which SIGs need more reviewers or more hands on deck, which ones are running smooth, those sorts of things. 

"But wait, there's no way for us to tell what which SIGs own which parts of the codebase!" Perhaps we can start encouraging people to start moving towards that model.

**Comment by lukaszgryglicki** [comment]
What exactly is expected here?

**Comment by dankohn** [comment]
@castrojo I know that every test is now owned by a SIG. I wonder if it's possible to use a coverage tool to show what code is being triggered by what test, and allocate it that way. That said, it seems like that is a way bigger project than an additional dashboard view.

**Comment by castrojo** [comment]
Yes, indeed I think this is larger than just "add a bunch of dashboards for each SIG", I was thinking maybe adding this as a topic for the next contrib-ex meeting, or perhaps we could have a quick sync at the contributor summit with the leads to hash out an overarching goal of how SIGs could best use the metrics?

**Comment by castrojo** [comment]
After discussing this at kubecon this is way too broad, I'll just monitor how the sig labels map out to charts and then file bugs if necessary.
