### ISSUE TITLE
Combine PR Time to Merge and Time Metrics

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#110]
Per meeting discussion:
These two graphs seem to show the same data:

- PR Time to Merge
- Time Metrics by Repository Group

Of the two, "Time Metrics" has richer data, so I propose dropping "PR Time to Merge", and renaming "Time Metrics" to "PR Time to Approve and Merge"

**Comment by lukaszgryglicki** [comment]
I'll confirm this tomorrow and eventually drop.
If I found some other differences I'll ask here.

**Comment by lukaszgryglicki** [comment]
Working on this.
Confirmed that time metrics is a pr time to merge's superset.

**Comment by lukaszgryglicki** [comment]
Done. Closing.
