### ISSUE TITLE
Investigate TimescaleDB

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#112]
Investigate [this](http://docs.timescale.com/v0.9/introduction/timescaledb-vs-postgres) approach.
Maybe we can make our current solution even faster?
But the question is - do we need this now?
Maybe it is an over-optimization?
Current solution is fast enough now, and all problems that we had with [b]influx[/b] are gone.

https://github.com/timescale/timescaledb
cc @jberkus @dankohn

**Comment by jberkus** [comment]
I think we should look at it later.  Right now we have more serious data issues, and migration from Postgres should be simple whenever we do it.

**Comment by lukaszgryglicki** [comment]
OK, so I'm adding `wonfix` now.

**Comment by lukaszgryglicki** [comment]
Closing this.
