### ISSUE TITLE
Missing author login from gha_commits

### ISSUE THREAD

**Issue by dgrizzanti** [cncf/devstats.archive#118]
I've noticed that the actor login being stored in gha_commits for a merged PR is the person who merged the PR. The `author_name` field has the commit author's name, but it would be helpful if the `author_login` was also stored. 

Was it intentional to leave this out or just an oversight? I think it would be helpful when gathering metrics for commits to have the unique author username.

Here is an example

```
gha=> select author_name, dup_actor_id, event_id, dup_actor_login,dup_created_at from gha_commits where dup_repo_name = 'Comcast/trickster' order by dup_created_at;
....
 Ben Kochie          |       883928 | 7778402628 | jranson         | 2018-06-05 14:06:04
 Ben Kochie          |       883928 | 7778402628 | jranson         | 2018-06-05 14:06:04
 James Ranson        |       883928 | 7778402628 | jranson         | 2018-06-05 14:06:04
```

PR reference for above commits ^ https://github.com/Comcast/trickster/pull/52

**Comment by lukaszgryglicki** [comment]
We are not skipping data from GH events.
This is what we get from GHA for `PushEvent` (for example merge):
https://github.com/cncf/devstats/blob/master/analysis/new_0.json
For `commit` part we only have author's name and email (but email is encoded and not usable):
```
      {
        "author": {
          "email": "016a89679ee671165f3d6b3ef1169b5a1b388d92@gmail.com",
          "name": "Julien Marrec"
        },
        "distinct": true,
        "message": "Detabify",
        "sha": "475dfc42c1ce0e23040289086a1a0393e52982ef",
        "url": "https://api.github.com/repos/jmarrec/OpenStudio/commits/475dfc42c1ce0e23040289086a1a0393e52982ef"
      }
```
https://github.com/cncf/devstats/blob/master/analysis/new_0.json#L14-L24

We also have data for actor who made a `PushEvent` (login is available here):
```
  "actor": {
    "avatar_url": "https://avatars.githubusercontent.com/u/5479063?",
    "display_login": "jmarrec",
    "gravatar_id": "",
    "id": 5479063.0,
    "login": "jmarrec",
    "url": "https://api.github.com/users/jmarrec"
  },
```
https://github.com/cncf/devstats/blob/master/analysis/new_0.json#L2-L9
But this is not a part of `gha_commits` table (this actor can push many commits belonging to different people when merging something).
This actor is stored in `gha_actors` table and is `gha_event`'s creator.
All fields starting with `dup_` are just duplicates of main event's data.
This is to allow faster queries without needing to join up to the `gha_event` table.

One can commit without even having GitHub login - only git is needed to commit.
To do actual push to repository - GitHub login *is* needed. So this is why we don't have GitHub login for commits IMHO.

So the data on `gha_commits` is a combination of what we can get from a commit part of a JSON + duplicated data of the merge event (like type, actor, etc.)

This is how commit is defined: https://github.com/cncf/devstats/blob/master/gha.go#L319-L324
This is how event is defined: https://github.com/cncf/devstats/blob/master/gha.go#L44-L53
And this is the actual insert to `gha_commits`: https://github.com/cncf/devstats/blob/master/cmd/gha2db/gha2db.go#L1167-L1187
We insert what we have: author name from the commit (there is no author login data available) and `dup_actor_login` comes from main GHA event: `ev.Actor.Login`
```
			"insert into gha_commits("+
				"sha, event_id, author_name, message, is_distinct, "+
				"dup_actor_id, dup_actor_login, dup_repo_id, dup_repo_name, dup_type, dup_created_at"+
				") "+lib.NValues(11),
			lib.AnyArray{
				sha,
				eventID,
				maybeHide(lib.TruncToBytes(commit.Author.Name, 160)),
				lib.TruncToBytes(commit.Message, 0xffff),
				commit.Distinct,
				ev.Actor.ID,
				maybeHide(ev.Actor.Login),
				ev.Repo.ID,
				ev.Repo.Name,
				ev.Type,
				ev.CreatedAt,
			}...,
```

**Comment by dgrizzanti** [comment]
@lukaszgryglicki understood and thanks for the explanation. Kind of a bummer that this info isn't available but you explanation makes sense. Feel free to close this.

**Comment by lukaszgryglicki** [comment]
OK, so closing then.
