### ISSUE TITLE
Inactive Org Members

### ISSUE THREAD

**Issue by cblecker** [cncf/devstats.archive#124]
I don't know if this is something dev stats can do, but I wanted to put it out there.

I'm interested in identifying inactive members of the Kubernetes org. From a defined set of Github users, I'd want to flag anyone who hasn't taken a GH action (comment, review, open issue, open PR) on any Kubernetes org repo in the last 3 months, and identify their username and the time since last action on a report.

cc: @Phillels @parispittman @grodrigues3

**Comment by lukaszgryglicki** [comment]
No problem, I just need that "defined set of GitHub users"
I can even do more - I can identify GitHub users who have been active but more than 3 months ago.
This can be a dashboard but I can also just execute SQL to provide this info one time.

**Comment by grodrigues3** [comment]
This sounds great.

**Comment by lukaszgryglicki** [comment]
Just let me know what do you want, I'll work on this on Monday.
The more details the faster I'll do it.

**Comment by cblecker** [comment]
@lukaszgryglicki That's awesome! Let me get back to you on the list.. right now org membership isn't completely public, and I'm trying to find out what that's going to look like. Might take a few days to figure out, but this isn't a super urgent task either.

**Comment by cblecker** [comment]
@lukaszgryglicki Thanks for your patience! Got a copy of the org posted here: https://github.com/kubernetes/org/blob/master/kubernetes/org.yaml

Priority wise, again, this isn't super urgent. A nice to have when there is cycles. Thank you!

**Comment by lukaszgryglicki** [comment]
This is my last day before 2 weeks vacation. I'll try to get that list for you today.

**Comment by lukaszgryglicki** [comment]
So this is done:

- Created [sql query](https://github.com/cncf/devstats/blob/master/util_sql/inactive_org_members.sql) that returns inactive org members data for given `{{period}}`.
- Created [shell script](https://github.com/cncf/devstats/blob/master/util_sh/inactive_org_members.sh) to run that query, you can run it like this: `PG_PASS=... ./util_sh/inactive_org_members.sh '3 months'`.
- Saved results [as csv](https://github.com/cncf/devstats/blob/master/util_sql/inactive_org_members.csv).

CSV lists members that were not active during last 3 months (active means comment, review, open issue, open PR) and shows last activity date (that is either before last 3 months or "Never").

Is it OK for you?

**Comment by lukaszgryglicki** [comment]
Closing this, please let me know if you want to reopen.
