### ISSUE TITLE
Impossible to install with current HEAD

### ISSUE THREAD

**Issue by alexcourouble** [cncf/devstats.archive#126]
Hi,

I wasn't able to install devstats with the current head. I checked out [this commit](https://github.com/cncf/devstats/commit/d1e70145586da0ad4789b50c736f19081bfb471f), which seems to work.

I don't have the exact error message, but the error occured while executing `make`. It seemed to be related to the vet package.

**Comment by lukaszgryglicki** [comment]
Will check on the next build.
You should try `production` branch - this should always work. `master` can be sometimes broken.

Please give me an exact error output because I don't know which exact commit you used.

**Comment by alexcourouble** [comment]
This is the error message:

```
acourouble@ubuntu:~/data/dev/src/devstats$ make
./for_each_go_file.sh "gofmt -s -w"
./for_each_go_file.sh "golint -set_exit_status"
./for_each_go_file.sh "goimports -w"
./vet_files.sh "go vet"
ghapi.go:954: arg ghaLocked for printf verb %s of wrong type: bool
ghapi.go:1188: arg ic for printf verb %d of wrong type: devstats.IssueConfig
exit status 1
Makefile:96: recipe for target 'vet' failed
make: *** [vet] Error 1
```

The documentation does specify the user should change to the production branch after cloning the repo. Shall I create a pull request?

**Comment by lukaszgryglicki** [comment]
Strange. My `go vet` is not detecting this error, but you are right.
Can you check now?
What is your go version?

**Comment by lukaszgryglicki** [comment]
Closing because I've fixed warnings generated by `go vet`.
