### ISSUE TITLE
[dashboards] repository groups are unclear

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#13]
What concrete repositories do the repository groups map to?

Personally I would prefer to have the ability to select individual repositories everywhere I can only use repository groups

**Comment by lukaszgryglicki** [comment]
Well that was specially requested on me to define such repository groups:
They're defined here:
https://github.com/cncf/devstats/blob/master/scripts/repo_groups.sql
https://github.com/cncf/devstats/blob/master/setup_repo_groups.sh

They're described in [USAGE.md](https://github.com/cncf/devstats/blob/master/USAGE.md) "Repositoy groups"

**Comment by dankohn** [comment]
Aaron, please review what we're doing now. If you believe being able to
drill into specific repos is important, we can add that. I'm unclear
whether it would be possible to add to the current view or would need a new
view.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Mon, Oct 23, 2017 at 10:30 PM, Łukasz Gryglicki <notifications@github.com

**Comment by lukaszgryglicki** [comment]
That would need another view, Postgres metrics would be almost the same (group by different column is the only difference), we also already have influxDB tags to show all repositories drop downs so this would require saving dashboard as a new with slightly different metrics connected - can be done very quickly.
I would need a list of dashboards that need this detailed per repo view, some of them were even using repos at the beginning and were changed to show repo groups instead because repo drop down was so huge!

**Comment by lukaszgryglicki** [comment]
So I need a list of dashboards that should also have a per-repo version instead of per-repo-group, to start working on this.

**Comment by spiffxp** [comment]
I don't have concrete use cases at the moment where I require per-repo instead of per-repo-group, I'll ask at sig-contribex meeting tomorrow to see if anyone has suggestions.

Making https://github.com/cncf/devstats/blob/master/scripts/repo_groups.sql or its data more prominent would help.  eg: I suspect sig-apps would probably want kubernetes/kubectl to be included as a sig-cli repo

**Comment by lukaszgryglicki** [comment]
Then I can put that repo into sig-cli group or You can create PR with suggested changes.

**Comment by dankohn** [comment]
Lukasz, please link to that file from near the top of the Readme.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Done.
