### ISSUE TITLE
Graph Grouping 

### ISSUE THREAD

**Issue by Phillels** [cncf/devstats.archive#130]
ephillip@redhat.com

Please group graphs according to the second tab of this sheet: https://docs.google.com/spreadsheets/d/1qjjkrDzzKf4ct2rMpdfiLPHOyGFrsjA8VI9s8kIH7qc/edit?usp=sharing

**Comment by lukaszgryglicki** [comment]
I'll try to use Grafana dashboard folders. I'll first implement on the test server for review.

**Comment by lukaszgryglicki** [comment]
Home dashboard (main page) cannot be moved to the subfolder. It is a special dashboard that needs to be in the main folder and must be starred to be able to serve as the main page. Updated linked google doc.

**Comment by lukaszgryglicki** [comment]
So I've added grouping by folders in addition to selecting them by tags.
You can expand/collapse folders when selecting from the main dashboards drop down.
You can see separate folders list in the home dashboard panels.
![screen shot 2018-07-27 at 09 17 22](https://user-images.githubusercontent.com/2469783/43307263-02c03fa4-917e-11e8-9199-502de47a73d7.png)
![screen shot 2018-07-27 at 09 17 33](https://user-images.githubusercontent.com/2469783/43307264-02e22d1c-917e-11e8-9f7c-8527348b1da1.png)
![screen shot 2018-07-27 at 09 17 45](https://user-images.githubusercontent.com/2469783/43307266-03436eec-917e-11e8-89ee-e884cab0d575.png)
![screen shot 2018-07-27 at 09 17 51](https://user-images.githubusercontent.com/2469783/43307267-03635cde-917e-11e8-8819-072debee9544.png)
![screen shot 2018-07-27 at 09 18 09](https://user-images.githubusercontent.com/2469783/43307269-038546fa-917e-11e8-9434-d221121ba756.png)

**Comment by lukaszgryglicki** [comment]
Closing this, let me know if you want to reopen.
