### ISSUE TITLE
Incorrect GitHub developer company info

### ISSUE THREAD

**Issue by isaachier** [cncf/devstats.archive#132]
Incorrect company information for me. I work at Uber. Used to work at Bloomberg ~1 year ago.

**Comment by lukaszgryglicki** [comment]
I'll implement this on cncf/gitdm side and then sync devstats. Thanks for an info.

**Comment by lukaszgryglicki** [comment]
Updated cncf/gitdm, imported new config into cncf/devstats and regenerated all charts on both test & prod server, closing.

**Comment by isaachier** [comment]
Thanks!
