### ISSUE TITLE
Wrong categories in graph headers

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#134]
1. Scroll down to "Contributor statistics dashboards"
2. Click on "Bot activity"
3. See header on the Bot Activity graph page:

```
PR velocity / Bot commands repository groups
```

That should say:

```
Contributor Activity / Bot commands repository groups
```

**Comment by jberkus** [comment]
ON a further check, it looks like the category headers are having an "off by one" error.  Because the Community dashboards say "Contributor Statistics".

**Comment by lukaszgryglicki** [comment]
fixed, thanks for reporting.
