### ISSUE TITLE
Add TiKV

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#136]
https://github.com/tikv

TiKV is on its own to the CNCF Sandbox on Aug 28th

**Comment by lukaszgryglicki** [comment]
Thanks, I'll be prepared for this to enable during the OSS Vancouver.

**Comment by lukaszgryglicki** [comment]
TiKV is ready to be enabled anytime.

**Comment by lukaszgryglicki** [comment]
TiKV was added during the OSSummit Vancouver, closing.
