### ISSUE TITLE
Kubernetes orgs

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#137]
Following [this file](https://docs.google.com/spreadsheets/d/1MQwsWGuQvJc_RepCFgQ9HleQD2m3-_2k8utGcPaVHKY/edit#gid=289132963) kubernetes has 18 official orgs.
Currently, we're following 5 of them: `kubernetes,kubernetes-client,kubernetes-incubator,kubernetes-csi,kubernetes-helm` and `kubernetes-helm` belongs to `Helm` project.

Should I add all remaining official orgs to the kubernetes project?
cc @dankohn @jberkus @bgrant0607 

Note that `kubernetes-graveyard, kubernetes-incubator-retired, kubernetes-sig-testing, kubernetes-providers, kubernetes-addons, kubernetes-charts, kubernetes-extensions, kubernetes-federation, kubernetes-security, kubernetes-sidecars, kubernetes-tools, kubernetes-test` have no public repositories, only `kubernetes-retired` have some repositories.

`kubernetes-charts` should probably belong to the Helm project, right?

Seems like those orgs are prepared for the future use, so adding them to the list of tracking orgs will automatically add any repositories that will appear in those orgs in the future.

**Comment by dankohn** [comment]
Yes.



--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Ok, I've already added on the test server, so now I'll do the same on the prod.

**Comment by lukaszgryglicki** [comment]
Updated test & prod, closing.
