### ISSUE TITLE
How to get data straight from github archive?

### ISSUE THREAD

**Issue by huygaa11** [cncf/devstats.archive#138]
I am trying to run devstats without flag `GET=1` to pull data from github archive directly.

When I run the following command with `GET=1` flag, it populates the databases correctly, pulling from cnctest. I can see the Kubernetes dashboards on Grafana.

    EXTERNAL=1 SKIPTEMP=1 INIT=1 PG_PASS=p PG_PASS_RO=p PG_PASS_TEAM=p ONLY=kubernetes SKIPWWW=1 GET=1 GHA2DB_PROJECTS_OVERRIDE="+cncf" ./devel/deploy_all.sh

However, when I run it without the `GET=1` flag, it is only populating gha_* tables in gha database. It is not populating other relations such as `tall_repo_groups`. How can I populate the DB correctly? I am trying it on Kubernetes just to see if it works. 

Note: `./devel/deploy_all.sh` without `GET=1` eventually calls `gha2db_sync` script, which fails with a message `pq: relation "gha_logs" does not exist`

**Comment by huygaa11** [comment]
Overall, how can I download a non-cncf project data from github archive and populate the databases correctly?

**Comment by huygaa11** [comment]
It seems like log.go file is not cleaning up database logs properly. Skipped the db cleanup and it seems to proceed with metrics calculation. Some psql instructions are failing because the table name was too long (>63b)

**Comment by lukaszgryglicki** [comment]
```
Note: ./devel/deploy_all.sh without GET=1 eventually calls gha2db_sync script, which fails with a message pq: relation "gha_logs" does not exist
```
You will need a `devstats` database as well. `gha_logs` should be in `devstats` database. can you paste the exact output of your `deploy_all.sh` call?
```
Overall, how can I download a non-cncf project data from GitHub archive and populate the databases correctly?
```
You need to have a custom `projects.yaml` file. You need to remove all existing projects from this file and create new one, just like you would add new project following `ADDING_NEW_PROJECT.md`.
```
It seems like log.go file is not cleaning up database logs properly. Skipped the db cleanup and it seems to proceed with metrics calculation. Some psql instructions are failing because the table name was too long (>63b)
```
To clean up the logs, `log.go` needs `devstats` database, seems like you don't have one. The 63b names limit was a problem for me too. I've created metrics definitions to avoid this usually be specifying `merge_series: name` in `metrics.yaml` file.
If you just want to run gha2db for some project, you can just follow `./[[projectname]]/psql.sh` for some project to populate only GHA archive data and then eventually run `ONLY=[[projectname]] ./devel//reinit.sh`. You need to read `ADDING_NEW_PROJECT.md`.

I can also configure `devstats` for you if you give me an ssh access to your machine (probably with root access). It should take no more than a day or two (if I found some non-standard problems). After that, you will remove access and I will create a separate information in devstats about how to port to the other project(s).

I'm thinking about creating a detailed instruction about how to deploy devstats for your own project using this repository as a base.

**Comment by lukaszgryglicki** [comment]
I will have a step-by-step guide about how to install for a single project tomorrow.

**Comment by lukaszgryglicki** [comment]
@huygaa11 managed to create a step-by-step guide today.
- See [this repo](https://github.com/cncf/devstats-example). It implements simple DevStats deployment for a simple project (Homebrew org picked as an example).
- See [this link](http://147.75.97.234:3001) to see an effective deployment. - It uses no Apache proxy, no SSL certs, and no DNS / domain names. It is just a static IP server with Grafana running on 3001 port.

Follow `*.md` files (especially SETUP_OTHER_PROJECT.md) to see how to configure simple DevStats deployment for your project.

**Comment by lukaszgryglicki** [comment]
Closing, let me know if you need to reopen.
