### ISSUE TITLE
Contributor focused dashboard with commits, reviews

### ISSUE THREAD

**Issue by dims** [cncf/devstats.archive#139]
Background:
- https://github.com/kubernetes/community/issues/1808
- https://github.com/kubernetes/kubernetes/pull/67980

OWNERS files and OWNER_ALIASES files in various kubernetes repositories frequently go stale. This is because when folks drop out of active contributions when they move on to other projects etc, their entries are not updated. So we need a way to gauge a single contributor's activity.

- How often does the contributor file commits/PR? 
- Which directories do the files typically fall under?
- What was the last commit/PR? 
- How often does the contributor review code?
- Which directories are the files in the PR(s) that the contributor reviews?
- When was the last time the contributor reviewed code?
- How often does the contributor creates issues?
- When was the last time the contributor created an issue?

For all the above, we should be able to drill down to:
- Overall activity across repositories and also activity in a single github repository

Is this possible? Do we have enough data?

Thanks,
Dims

cc @spiffxp @cblecker @jdumars

**Comment by lukaszgryglicki** [comment]
I'm not sure what to do with this? Is this a new dashboard(s) request?

**Comment by dims** [comment]
@lukaszgryglicki yes, a new dashboard would be good!

**Comment by lukaszgryglicki** [comment]
I would need an exact description for each dashboard required. The more details, the faster new dashboard will be implemented. 
It should also go through [this](https://github.com/cncf/devstats/projects/1).

**Comment by lukaszgryglicki** [comment]
I can't start working on this without specs...

**Comment by lukaszgryglicki** [comment]
Closing, please reopen when you have more specs.
