### ISSUE TITLE
[Feature/Help request] Creating a new metric: Reviewer's load per day.

### ISSUE THREAD

**Issue by huygaa11** [cncf/devstats.archive#142]
Devstats currently have a metric for `user reviews per day`, which is fantastic for analyzing the volume of code reviews. In our project, we are interested in creating dashboards for recognizing overloaded reviewers.

### Metric definition
Active PR's pending review per reviewer. For example, it would look like:

user   |  Average daily active pending PR review requests
user1 | 10
user2 | 6
user12 | 2

Also, it would be great to have a timeseries dashboard showing the changes over time.

I would like to try implementing it for our project and possibly contribute directly to devstats if needed. I read through the [Adding new metrics](https://github.com/cncf/devstats/blob/master/METRICS.md), but it is a bit hard to digest. From my tiny knowledge of Grafana,  I assumed I could do most of the work using their UI. What is the best way to approach adding a new metric? Thanks.

**Comment by lukaszgryglicki** [comment]
First, you need to create a SQL query that will return this data. Once you have this, you need to add this metric in `metrics/shared/metrics.yaml` (and possibly some new tag in `metrics/shared/tags.yaml` if needed). Then you need to create Grafana dashboard using it - either via Grafana UI or by copying some dashboard from `grafana/dashboards/projectname/dashboard-name.json`).

**Comment by lukaszgryglicki** [comment]
Closing for now, please reopen if you have specs for it.
