### ISSUE TITLE
Incorrect golint installation procedure

### ISSUE THREAD

**Issue by hidekazuna** [cncf/devstats.archive#144]
This is a documentation bug  report.

"go get -u github.com/golang/lint/golint" is used in INSTALL_xx.md, but the command does not create binary. "go get -u golang.org/x/lint/golint" should be used.

**Comment by lukaszgryglicki** [comment]
Possible, this is vendored some time ago.
Please create a PR or I will take a look at this later.
Thanks.

**Comment by lukaszgryglicki** [comment]
Fixed by 443609e766d2e5cf4dd027a5f6410c94a47c1794, closing. Thanks.
