### ISSUE TITLE
[Bug] Database dump file restore error

### ISSUE THREAD

**Issue by frank-zsy** [cncf/devstats.archive#148]
On Ubuntu 16, follow instructions and no error in progress. But `sudo -u postgres pg_restore -d gha /tmp/gha.dump` command executed with following error message, not sure what's wrong.
```
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 226; 1259 6086054 SEQUENCE gha_logs_id_seq gha_admin
pg_restore: [archiver (db)] could not execute query: ERROR:  syntax error at or near "AS"
LINE 2:     AS integer
            ^
    Command was: CREATE SEQUENCE public.gha_logs_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
  ...
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "public.gha_logs_id_seq" does not exist
    Command was: ALTER TABLE public.gha_logs_id_seq OWNER TO gha_admin;

pg_restore: [archiver (db)] Error from TOC entry 6131; 0 0 SEQUENCE OWNED BY gha_logs_id_seq gha_admin
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "public.gha_logs_id_seq" does not exist
    Command was: ALTER SEQUENCE public.gha_logs_id_seq OWNED BY public.gha_logs.id;

pg_restore: [archiver (db)] Error from TOC entry 3547; 2604 6089944 DEFAULT gha_logs id gha_admin
pg_restore: [archiver (db)] could not execute query: ERROR:  relation "public.gha_logs_id_seq" does not exist
    Command was: ALTER TABLE ONLY public.gha_logs ALTER COLUMN id SET DEFAULT nextval('public.gha_logs_id_seq'::regclass);
`

**Comment by lukaszgryglicki** [comment]
There are ready to go scripts to do that:
- ./devel/restore_db_all.sh
- ./devel/restore_db.sh
Also restoring DB from the test server is a part of new production projects deployment, it worked last time.
- What exactly are you trying to do (step-by-step)?
- Do you have a required 10.x version of PostgreSQL?

**Comment by lukaszgryglicki** [comment]
-Tested now for a smaller DB (like TUF), restoring it into abc to avoid data loss.
- First abc database does not exists, all is OK:
```
2018-10-30 11:44:17 root@teststats:~/dev/go/src/devstats# cp /var/www/html/tuf.dump ./abc.dump
2018-10-30 11:45:25 root@teststats:~/dev/go/src/devstats# ./devel/restore_db.sh abc
Dropping abc
 pg_terminate_backend 
----------------------
(0 rows)

ERROR:  database "abc" does not exist
Dropped abc
Creating abc
Created abc
```

- Then restoring onto existing abc (also all OK):
```
2018-10-30 11:46:06 root@teststats:~/dev/go/src/devstats# ./devel/restore_db.sh abc
Dropping abc
 pg_terminate_backend 
----------------------
(0 rows)

DROP DATABASE
Dropped abc
Creating abc
Created abc
2018-10-30 11:46:51 root@teststats:~/dev/go/src/devstats# sudo -u postgres psql
psql (10.5 (Ubuntu 10.5-0ubuntu0.18.04))
Type "help" for help.

postgres=# drop database abc;
DROP DATABASE
postgres=# \q
2018-10-30 11:48:11 root@teststats:~/dev/go/src/devstats# 
```

All works OK IMHO.

**Comment by frank-zsy** [comment]
> There are ready to go scripts to do that:
> 
> * ./devel/restore_db_all.sh
> * ./devel/restore_db.sh
>   Also restoring DB from the test server is a part of new production projects deployment, it worked last time.
> * What exactly are you trying to do (step-by-step)?
> * Do you have a required 10.x version of PostgreSQL?

I do exactly as the document said step by step. But my PostgreSQL version is 9.5.14 and I can't install PostgreSQL 10.x on Ubuntu 16 LTS maybe because of my source repository setting, but there are several posts about this on Google too. So I will try the scripts to auto restore the db file or I can only upgrade my Ubuntu to 18 LTS.

BTW, I don't see any PostgreSQL version requirement in the installation documents.

**Comment by frank-zsy** [comment]
Update: encounter same error with `./devel/restor_db_all.sh` script

**Comment by frank-zsy** [comment]
Update:
I upgrade my Ubuntu to 18.04.1 LTS with go 1.10.4 and PostgreSQL 10.5, but I got an error message while running `make`
```
errcheck -asserts -ignore '[FS]?[Pp]rint*' -ignoretests 
Makefile:120: recipe for target 'errcheck' failed
make: *** [errcheck] Killed
```

**Comment by lukaszgryglicki** [comment]
Unfortunately cannot reproduce this, never saw something similar. You can just disable `errcheck` in Makefile.

**Comment by lukaszgryglicki** [comment]
errcheck, lint, usedexports, and all other "check" stuff are only needed for development to ensure correct code quality. If you just want to build you can skip even all checks.

**Comment by frank-zsy** [comment]
Thx, I will have a try later. I will close this issue for now and if I have further questions about this, I will comment under this issue as well.
