### ISSUE TITLE
Jaegar starts out of date?

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#149]
https://jaeger.devstats.cncf.io/d/4/companies-stats?orgId=1&var-period=y&var-metric=activity&var-repogroup_name=All&var-companies=All

this chart seems to have stopped updating on Jan 2018

cc: @lukaszgryglicki

**Comment by yurishkuro** [comment]
might be some alignment issue based on period=1Y. With smaller periods the stats are up to date.

**Comment by lukaszgryglicki** [comment]
Each period is only calculated when it is full. So 2018 will be completed 1/1/19 etc.
That behavior changed sometime in this year, so partial data for 2018 is left.
Oct 2018 will be complete 11/1/18, any week will be complete on Monday, 3rd Quarter is completed at 10/1/18 etc.

Why? Updating every possible period's state (even including moving averages) at every hour is too expensive for hourly sync.
