### ISSUE TITLE
Feature Request: New contributor dashboard for Kubernetes devstats

### ISSUE THREAD

**Issue by nikhita** [cncf/devstats.archive#151]
Similar to https://github.com/cncf/devstats/issues/150 but for Kubernetes devstats. And I think the right dashboard group for this would be `Contributor Statistics`.

/cc @lukaszgryglicki @dims @spiffxp 

---

Mentioning the Slack conversation that led to this issue:

@lukaszgryglicki said:

the question is: do we want this dashboard in Kubernetes Devstats?

For now it is possible to see Kubernetes data when using “All CNCF projects combined” and selecting “Kubernetes” repo group there (in All CNCF projects combined, each CNCF projects is mapped to a single repo group): https://all.devstats.cncf.io/d/52/new-contributors-table?orgId=1&var-repogroup_name=Kubernetes

@nikhita said:

IMO it will be useful to have it in k8s devstats as well. Because k8s folks will mostly visit the `k8s.devstats` link more than the `all.devstats` link for dashboards. It's also handy to have all k8s dashboards in one place.

**Comment by lukaszgryglicki** [comment]
What is the category for this dashboard?
Possibilities:
- Community sizing and health assessment dashboards
- Contributor statistics dashboards
- Issue velocity dashboards
- PR velocity dashboards

cc @dankohn

**Comment by nikhita** [comment]
> What is the category for this dashboard?

Contributor statistics seems apt.

**Comment by lukaszgryglicki** [comment]
OK, will be ready tomorrow.

**Comment by lukaszgryglicki** [comment]
Dashboard created: https://k8s.devstats.cncf.io/d/52/new-contributors?orgId=1
Used `New contributors` name instead of `Contributor Statistics`, because the latter is already used as a dashboards folder (grouping) name. I can change the name but not to `Contributor Statistics`.
Let me know if you need to change the dashboard name.

Allows filtering by:
- Repo group or summary for all (default)
- date range, default: last week.

**Comment by nikhita** [comment]
> Used New contributors name instead of Contributor Statistics

This is perfect, thanks @lukaszgryglicki! I just meant that the dashboard group it should be under should be `Contributor Statistics`. :)

**Comment by lukaszgryglicki** [comment]
Sorry, my bad, a bit of confusion here.
