### ISSUE TITLE
Add a readme to the  Kubernetes devstats repo 

### ISSUE THREAD

**Issue by Phillels** [cncf/devstats.archive#152]
Have a readme that explains common terms and specifies that the Contrib-X SIG has a subproject that is tied to devstats. Language can be taken from this document: https://docs.google.com/document/d/1WswlD0oi7svkca-46IvKcbfSogjG4rU6dI9FvP_ZpfM/edit?usp=sharing

**Comment by lukaszgryglicki** [comment]
Added link in the main project README [here](https://github.com/cncf/devstats#github-archives-and-git-grafana-visualization-dashboards) (`More information about Kubernetes dashboards here`)
Points to [README_K8s.md](https://github.com/cncf/devstats/blob/master/README_K8s.md) which is just a copy of GitHub section from [this document](https://docs.google.com/document/d/1WswlD0oi7svkca-46IvKcbfSogjG4rU6dI9FvP_ZpfM/edit#)
Now I will add a banner in the devstats page.
