### ISSUE TITLE
Add  banner to kubernetes devstats dashboard to point to readme

### ISSUE THREAD

**Issue by Phillels** [cncf/devstats.archive#153]
Could a banner be added to the top of k8s.devstats.cncf.io that points to a readme specifically for the Kubernetes devstats dashboard? Text for the banner could be taken from this doc: https://docs.google.com/document/d/1WswlD0oi7svkca-46IvKcbfSogjG4rU6dI9FvP_ZpfM/edit?usp=sharing

**Comment by lukaszgryglicki** [comment]
On it now...

**Comment by lukaszgryglicki** [comment]
I've merged the new banner text with the existing text about filing an issue, is this OK for you?
- https://k8s.teststats.cncf.io/d/12/dashboards
- https://k8s.devstats.cncf.io/d/12/dashboards

Closing for now.
