### ISSUE TITLE
Some K8s repos are not assigned to repo groups

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#158]
@spiffxp New K8s repo groups defined [here](https://github.com/cncf/devstats/pull/145) leaves many repositories unassigned to any repository group. 
What we can do:
- Ignore this.
- Update your PR to include all possible repositories (but this is very dynamic and change very often).
- Add them somewhere like 'Other' repo group (I can even add a fallback [here](https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql#L222))
- Create a single repository group for any unassigned repository - that will create 97 new repository groups and will cause an ugly crowd in the repository group drop-down.
- Other suggestions?

Unassigned repos are:
```
 kubernetes-csi/csi-lib-utils
 kubernetes-retired/kube-mesos-framework
 kubernetes/kubernetes.github.io
 kubernetes/kubedash
 kubernetes-sigs/aws_encryption-provider
 kubernetes-sigs/app
 kubernetes-graveyard/kube-ui
 kubernetes-sigs/
 kubernetes-client/client-python
 kubernetes-retired/kubedash
 kubernetes/enhancements
 kubernetes/rktlet
 kubernetes-incubator/
 kubernetes-sigs/node-feature-discovery
 kubernetes-sigs/alb-ingress-controller
 kubernetes/cluster-bootstrap
 kubernetes-csi/resources
 kubernetes-incubator/ocid
 kubernetes-incubator/cri-o
 kubernetes-sigs/kube-metacontroller
 kubernetes-retired/kubernetes-bootcamp
 kubernetes/md-format
 kubernetes-sigs/kubespray
 kubernetes-incubator/kube2consul
 kubernetes/demos-and-tutorials
 kubernetes-incubator/auger
 kubernetes-retired/kube-ui
 kubernetes-security/cloud-provider-azure
 kubernetes/md-check
 kubernetes-csi/cluster-driver-registrar
 kubernetes-sigs/
 kubernetes-incubator/cri-containerd
 kubernetes-retired/kubernetes-docs-ko
 kubernetes-sigs/clife_cluster-api
 kubernetes/application-images
 kubernetes-incubator-retired/kubedash
 kubernetes-csi/flex-provisioner
 kubernetes-incubator/kompose
 kubernetes/ocid
 kubernetes/console
 kubernetes-client
 kubernetes/cloud-provider-alibaba-cloud
 kubernetes-client/python
 kubernetes-incubator/
 kubernetes-csi/csi-flex-provisioner
 kubernetes-csi/external-attacher-csi
 kubernetes-retired/kubernetes-docs-zh
 kubernetes-sigs/compute-persistent-disk-csi-driver-
 kubernetes-sigs/foo
 kubernetes-client/community
 kubernetes-incubator/kube-mesos-framework
 kubernetes-client/typescript
 kubernetes-sigs/yaml
 kubernetes-retired/community
 kubernetes-sigs/aws-ebs-csi-driver
 kubernetes-incubator/cri-tools
 kubernetes-retired/typescript
 kubernetes/klog
 kubernetes/common
 kubernetes/ingress
 kubernetes-retired/md-check
 kubernetes/kubernetes-console
 kubernetes-sigs/meta-controller
 kubernetes-sigs/auger
 kubernetes/application-dm-templates
 kubernetes-sig-testing/frameworks
 kubernetes/node-api
 kubernetes-sigs/cluster-api-provider-digitalocean
 kubernetes-retired/application-images
 kubernetes-incubator/application-images
 kubernetes-sigs/apps_application
 kubernetes-incubator/kargo
 kubernetes-incubator/rescheduler
 kubernetes-graveyard/kube-mesos-framework
 kubernetes/cluster-proportional-autoscaler
 kubernetes/kubernetes-docs-cn
 kubernetes-retired/kubernetes-docs-ja
 kubernetes-sigs/scheduling_poseidon
 kubernetes/kubernetes-bootcamp
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes/
 kubernetes-csi/node-driver-registrar
 kubernetes-sigs/website-metadata
 kubernetes/horizontal-self-scaler
 kubernetes-csi/external-provisioner-csi
 kubernetes/kube-ui
 kubernetes/pr-bot
 kubernetes-graveyard/md-check
 kubernetes/kube2consul
 kubernetes-incubator/kube-arbitrator
 kubernetes/cloud-controller-manager
```

cc @dankohn

**Comment by spiffxp** [comment]
didn't notice this until just now

I am surprised many of these aren't in the groups, I'll take a crack at triaging later, noting to self here to bump for recency

**Comment by lukaszgryglicki** [comment]
OK, would be great to assign them somewhere or just create a fallback group "Other"
I'm in LA now BTW.

**Comment by lukaszgryglicki** [comment]
@spiffxp any feedback there? Leave it "as is" or just create "Other" repo group, or maybe just create one repo group for each unassigned repo?

**Comment by spiffxp** [comment]
Yet again this fell off my radar, and I'm not going to get to it in the next few days, but bumping for recency again.  Need to dig up the script I used to generate the last grouping.

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/community/issues/3305 so I can /assign for a better shot at finding this next time

**Comment by nikhita** [comment]
Created https://github.com/cncf/devstats/pull/167 to assign all k8s repos to repo groups

**Comment by lukaszgryglicki** [comment]
Great, please see [this comment](
https://github.com/cncf/devstats/pull/167#issuecomment-467309642)

**Comment by lukaszgryglicki** [comment]
Blocked by https://github.com/cncf/devstats/pull/167/files#diff-8edd0e6ac4b13658e73e02ece2d6a004R243

**Comment by lukaszgryglicki** [comment]
This should also include this [issue](https://github.com/cncf/devstats/issues/173).

**Comment by lukaszgryglicki** [comment]
Fixed by #192

**Comment by lukaszgryglicki** [comment]
New repos should be assigned to repo groups: https://github.com/kubernetes/community/issues/3305#issuecomment-583975176

**Comment by lukaszgryglicki** [comment]
New dashboard showing repository groups - repositories assignments implemented: https://github.com/cncf/devstats/issues/235#issuecomment-585110324

**Comment by lukaszgryglicki** [comment]
Blocked, awaiting data from the community.

**Comment by lukaszgryglicki** [comment]
Working on this, [see](https://github.com/kubernetes/community/issues/3305#issuecomment-587296386). It will be implemented on the test server first.

**Comment by lukaszgryglicki** [comment]
Implemented on both test & prod servers, closing.
