### ISSUE TITLE
possible to add release timeframes to Quick Ranges?

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#16]
I want to to use devstats to answer things like:
- how has X changed over the past 3 releases?
- is Y better or worse for the pending release vs. the last release we shipped?
- what is the histogram of people who did Z for the release we're about to ship?

Something that would be helpful is to have Quick Ranges that are defined by specific kubernetes releases, eg:
- specific releases: 1.8 release cycle, 1.7 release cycle
- relative release: last release, last two releases, last three releases, (to now, or to their end)

How can we make answers these sorts of release-date based questions easier?

**Comment by lukaszgryglicki** [comment]
Currently, we have tags for release, but this is not usable for this.
I need to think about this, I have no idea ATM - I'm open to suggestions.
cc @dankohn

**Comment by lukaszgryglicki** [comment]
Created Grafana feature request: https://github.com/grafana/grafana/issues/9814

**Comment by lukaszgryglicki** [comment]
Blocked on Grafana side, the only way to implement this is to create custom Grafana version for this purpose.

**Comment by lukaszgryglicki** [comment]
I'm not able to add custom data ranges to "Quick Ranges" - that requires changing/adding this feature on Grafana side.
But I've added ranges based on annotations/versions/tags in a tabular view.
Yoy can select values like "v1.1.0 - v1.2.0" or "v1.8.0 - now" or "Last [[period]]" where period is: Day, Week, Quarter etc.:
https://k8s.devstats.cncf.io/dashboard/db/companies-summary?orgId=1

So this allows getting some summaries.

**Comment by parispittman** [comment]
@lukaszgryglicki if we wanted to collect all of the handles for folks who had PRs in 1.9 - could we do that from here? I'm toggling with it now and don't see a way.

**Comment by lukaszgryglicki** [comment]
To see data since 1.8 You need to select "1.8.0 - now" from the drop-down.
Now, what do You mean by "all of the handles for folks who had PRs" ?
This report is a tabular report showing the number of PRs, issues, comments, committers, reviewers, events, etc. in a given date ranges.
Let me know what exactly do You need.
I will address tomorrow.

v1.9.0 ... we only have 1.9.0-alpha.3 released 2 weeks ago, I will add 1.9.0 when it is released.

**Comment by parispittman** [comment]
>"all of the handles..." 

Something similar to the Top Commenters where it lists GitHub Handles but for Unique PR Authors. 

Could we also do Top Commenters by release as well?

**Comment by lukaszgryglicki** [comment]
Yes, we can, I'll add custom ranges to Top Commenters report.
In the longer term, I'll add it to all tabular reports.

**Comment by lukaszgryglicki** [comment]
Now all tabular dashboards supports custom data ranges.
To see data for upcoming 1.9 just select "v1.8.0 -now" range in any of the following dashboards:
https://devstats.k8s.io/dashboard/db/companies-summary?orgId=1
https://devstats.k8s.io/dashboard/db/project-statistics?orgId=1
https://devstats.k8s.io/dashboard/db/approvers-histogram?orgId=1
https://devstats.k8s.io/dashboard/db/reviewers-histogram?orgId=1
https://devstats.k8s.io/dashboard/db/top-commenters?orgId=1
https://devstats.k8s.io/dashboard/db/prs-authors-histogram?orgId=1
https://devstats.k8s.io/dashboard/db/prs-authors-companies-histogram?orgId=1

Next step will be to add support for "custom ranges" in all tabular dashboards in the other projects, see:
https://devstats.k8s.io/dashboard/db/all-projects?refresh=15m&orgId=1

I'll let you know when I finish this.

**Comment by lukaszgryglicki** [comment]
Also added on all histogram and tabular dashboards on all remaining projects (Prometheus, OpenTracing, Fluentd, linkerd, gRPC currently):
- [Kubernetes](https://k8s.devstats.cncf.io)
- [Prometheus](https://prometheus.devstats.cncf.io)
- [OpenTracing](https://opentracing.devstats.cncf.io)
- [Fluentd](https://fluentd.devstats.cncf.io)
- [linkerd](https://linkerd.devstats.cncf.io)
- [gRPC](https://grpc.devstats.cncf.io)

Dashboards (on Kubernetes more dashboards, listed in the previous comment):
- Companies summary
- Project statistics
- PRs authors companies histogram
- PRs authors histogram
- Top commenters

**Comment by lukaszgryglicki** [comment]
I think this is implemented with new annotation based time ranges (for tabular views). Closing. Please reopen if needed.
