### ISSUE TITLE
Feature Request: Per dev stats, filtered by company

### ISSUE THREAD

**Issue by duglin** [cncf/devstats.archive#161]
Looking at this page: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=prs&var-repogroup_name=All&var-country_name=All
we can see the list of devs (by github id) that submitted PR across on all of Kube. It would be nice to also be able to filter this list by company - for example, so I can see the activity for just the IBMers. So, perhaps add a "Company" column that we can then sort/filter on.

I suspect there are probably other tables/views that might benefit from this type of data/filtering as well since it is not easy to know who works for which company when all we are shown is the github id.

**Comment by lukaszgryglicki** [comment]
Thanks for the feature request. Will work on that. Probably will add company drop-down which will default to 'All'.

**Comment by duglin** [comment]
yup - I think so. And if you could add a "Company" column to the table (so we could also sort by it) for cases where more than one company's dev show up, then I think that would address my needs.

**Comment by lukaszgryglicki** [comment]
I'll try to do that, not sure if that is possible without bigger changes to this dashboard because it would require extra data-per row and possibly custom view (other than a metric name - metric value). Anyway, this is only the matter of amount work needed to do that.

**Comment by lukaszgryglicki** [comment]
Please see [this comment](
https://github.com/cncf/devstats/issues/162#issuecomment-453937430)

**Comment by lukaszgryglicki** [comment]
Closing, please let me know if you need to reopen.

**Comment by dankohn** [comment]
We removed the email column from the dashboard because it was unacceptable to show email addresses publicly. More discussion can occur here.

**Comment by duglin** [comment]
We can put it back up w/o the emails then?  Being able to see who worked on what was really really really valuable to us.

**Comment by lukaszgryglicki** [comment]
The dashboard is still there, only `emails` column was removed.

**Comment by duglin** [comment]
Ah ok sorry, misread dan's comment

**Comment by lukaszgryglicki** [comment]
Closing this, the dashboard is ready and functional.
