### ISSUE TITLE
Feature Request: dev-centric activity table

### ISSUE THREAD

**Issue by duglin** [cncf/devstats.archive#162]
https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=prs&var-repogroup_name=All&var-country_name=All  is really useful when you want to have a holistic view of a dev's activity across all of Kube. There's also a filter that allows us to get those stats for just one github repo. However, for any one particular developer we don't know which repo to choose if we want to get a PR-count per dev per repo view.

Would it be possible to provide a table that went a bit deeper and had columns such as:
| github id | company | repo | count/metric |

This would allow me to see the metrics (PRs in this case) for each dev in each repo. This would be useful to me because I can then see which parts of Kube that dev was focused on. Of course, filtering on "company" would be nice too so I can just focus on my company's dev.

**Comment by lukaszgryglicki** [comment]
In this case, we would rather show "repo group" not repo to be consistent with other Devstats dashboards. I will see what I can do here.

**Comment by duglin** [comment]
would that allow me to get the next level of detail for each dev? Meaning, allow me to see for dev (github id) "foo" they submitted 3 PRs for sig-aaa and 4 PRs for sig-bbb ?  The original requests asked of me were something along the lines of: Which areas of Kube are our devs focused on?  And, which dev is working in each of those areas?

I'm trying to avoid having to iterate (manually) thru each repo group in the drop-down to see if any IBMers are working in it.

**Comment by lukaszgryglicki** [comment]
That would rather require some text report with specific criteria. I don't see a way to show all this info in a single table entry like:
Developer "xyz": 3 PRs on "repo group1", 4 PRs on "repo group2", ... N Prs on "repo group N".
Also note that we can also filter by country there, change the metric to something different than PRs etc. I don't want to change this dashboard so much. I can just add Company filter defaulting to 'All' to avoid breaking anything. I would suggest creating a separate dashboard to see more specific data that you want.
This dashboard just shows top developers by given metric, in a specific repository group and country (both can be 'All'). Maybe you want something like [this](https://all.devstats.cncf.io/d/48/users-stats) ported to k8s (this one shows developer centered stats but for all CNCF projects combined). If you need something different, please describe your requirements for a new dashboard.

**Comment by duglin** [comment]
To be clear... I'm not necessarily looking to edit an existing dashboard, if creating a new one would be easier for this request (or my other request) I'm ok with that. I was just focused on that dashboard because it seemed to come closest to what I was looking for.

To be honest, I have a hard time getting info from graphical dashboards like https://all.devstats.cncf.io/d/48/users-stats?orgId=1&var-period=w&var-metric=prs&var-repogroup_name=All&var-users=All  
I tend to prefer tabular view of the data. 

When I look at: https://all.devstats.cncf.io/d/9/developers-summary?orgId=1 (and the SQL behind it, if I'm looking at the right link), I believe the "Number" column is determined by grouping all PRs by the login, and then doing a count() of all PRs for all selected repos for that login - in essence doing another "group" on the repos to get a single value/PR-count.  What I was thinking of was to remove some of the groupings that span repos (I guess for the "All" repo-group case). This would then also require the table to show the same login on more than one row - so remove the grouping by login across repos too. 

It's been a long time since I did some serious SQL :-)  but in my head I'm thinking of it as:
- for each selected repo...
- for each github login in that repo...
- get/count the metric we're interested in (grouped by github login)

I think that would give something like:

| Repo | Login | Number |
| --- | --- | --- |
| Sig-aaa | dev1 | 5 |
| Sig-aaa | dev2 | 3 |
| Sig-bbb | dev1 | 10 |

And if there was a Company column that I could sort (or filter) on then I could easily see which areas of Kube folks in my company were working and how much work they're doing in each.

Not sure if this is possible, but that's my thinking.

**Comment by lukaszgryglicki** [comment]
I will take a closer look and decide between adding this to the current developer table or create another dashboard that displays that. I will let you know when implemented.

**Comment by lukaszgryglicki** [comment]
@duglin dashboard will be ready later, but for now, I've created a tabular view on google sheets. See [this](https://docs.google.com/spreadsheets/d/1nDz9N10Uf-rzfHS3Dy6swg9r4b_FtEEuP6hgjPLqXlM/edit?usp=sharing). It was implemented here: 7eb447a608cc5f89b92bd19004305dc2e1654e31. The new script allows choosing 'recent range' period and a list of company names to process. Google sheet contains IBM's PR's authors for the last 5 years. Sort is by the company, then repo/SIG and finally PRs created count desc.

**Comment by duglin** [comment]
That's pretty cool!  I like it as part of sheets too because then I can adjust how it looks - e.g. sort by github ID to see all of a certain user's activities in one spot, but still keep each repo separate.  :-)

**Comment by lukaszgryglicki** [comment]
Added new dashboard: https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups
It allows choosing one, multiple or all companies from the drop-down.
It allows choosing one, multiple or all repository groups from the drop-down.
It displays company, repo group, GitHub id, known developer names, and emails and opened PRs count.
You can select date ranges from between releases and last X (X being a day, week, month etc.)
You can sort by any column.
Hope you will find it useful.
This dashboard is also added for all other CNCF projects, for example, Prometheus: https://prometheus.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1
"All CNCF" also supports it: https://all.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1
![screenshot 2019-01-14 at 10 07 13](https://user-images.githubusercontent.com/2469783/51103766-3a52d480-17e4-11e9-9cf0-0620de009d4d.png)
@duglin

**Comment by lukaszgryglicki** [comment]
@duglin @dankohn dashboard links were changed in the previous post due to ugly default `uid` value (some random string) - changed it to `55`.

**Comment by lukaszgryglicki** [comment]
Links:
- [Kubernetes](https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups)
- [Prometheus](https://prometheus.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1)
- [All CNCF](https://all.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1)

**Comment by duglin** [comment]
Will play with it more later today but so far it looks awesome!!!  thanks so much!!!

**Comment by lukaszgryglicki** [comment]
Closing, please let me know if you need to reopen.
