### ISSUE TITLE
Improving the Project Health dashboard

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#164]
Now that we have a Project Health dashboard, let's tweak it!

Dashboard: https://all.devstats.cncf.io/d/53/projects-health?orgId=1

Original Issue: https://github.com/cncf/devstats/issues/155

Please use this issue for your suggestions, questions, and tweaks.

@lukaszgryglicki @caniszczyk @mae

**Comment by jberkus** [comment]
My feedback, mainly aimed at Kubernetes usage but not exclusively:

1. I don't understand what the line for 6 months is doing there, e.g. "Number of Committers in the last 6 months".  It's not comparable with anything else on the chart.
2. I'd love to have a year vs year comparison as well as quarter vs quarter.  I'm aware that it wouldn't be applicable for some projects.
3. It would be terrific to make the up/down arrows somehow show the amplitude of the change, either via graphics (bigger arrows) or just a %
4. I'm not clear on what the % of top company contribution are supposed to show us in terms of project health.  If someone could explain the goal to me, I could probably suggest some better statistics for it.
5. What does "open to closed rate" mean, mathematically?
6. Last Release only seems to cover major releases, not update releases.  Seems like it should cover update releases.
7. Kubernetes has a thing where development slumps every December because of KubeCon + Holidays.  I'm not sure that there is any way to adjust for that, though, considering that other projects don't have this slump.

Thanks for building that, it's a great "at a glance" thing.

**Comment by lukaszgryglicki** [comment]
1. It is just one of the statistics, I can also add `vs previous 6 months` if needed.
2. I will add year statistics.
3. I can add % value next to the arrow, is this OK for you?
4. It is supposed to show project diversity. If some project has a top company contribution about 80% - it means that a given project is dominated by a single company. If the project has top company contribution about 30% - it means that no other company have a bigger value and given projects is not dominated by a single company.
5. The number of issues opened in a given date range divided by the number of issues closed. Value > 1 means that more issues are opened than closed, value < 1 mean that more issues are closed than opened.
6. We're showing the last release that is processed for a given project. Most projects have a special regular expression to define which `git tags` should be treated as a release. This is also used to show vertical `Release` lines in many graphical dashboards. The idea behind it is to allow skipping hundreds of tags that are not official releases. Regular expression for kubernetes is defined [here](https://github.com/cncf/devstats/blob/master/projects.yaml#L18).
7. I don't know how can we compensate this. I think we should not do that - stats should show the real data IMHO.

**Comment by jberkus** [comment]
1. Personally, I'm just as happy to skip the "6 months" entirely, but I'm not the one who asked for it.

3. Sure, WFM

4. I feel like there ought to be a better measure of this, but I'll have to think about what that would look like.  Beyond that, though, I don't think we really need 12 different calculations for company diversity; ideally, we want *one*.  I'll do some thinking about math.

5. Cool, thanks!  I thought it was something like that, but couldn't figure out if higher or lower was better.

6. OK, I'll look at the regex.

Thanks, this looks like a really good start.
