### ISSUE TITLE
Allow DataDir to be overwritten

### ISSUE THREAD

**Issue by jlewi** [cncf/devstats.archive#166]
feature request

Currently DataDir is hardcoded to `/etc/gha2db` it would be nice to allow this to be overwritten by environment variable.
https://github.com/cncf/devstats/blob/d4d1408924569d77d0eff823a556573a633ac6c6/const.go#L7

**Comment by lukaszgryglicki** [comment]
Good idea, I will work on it. Thanks.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Implemented in: 5ce45b4d21c9b7fdd526c30646a637bb448b936c
To specify other (non-default) data directory just prepend commands (even `make install`) with `GHA2DB_DATADIR="/path/to/some/other/directory" ...`.
