### ISSUE TITLE
Please remove the projects header from k8s.devstats.cncf.io [bug]

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#168]
Lukasz,

The "Devstats projects" header on the homepage for k8s.devstats has grown to be a screen-and-a-half of scrolling before the user can get to the actual menu of charts that they are there for.

If they are on k8s.devstats, they are there for Kubernetes, not for 80 other projects.  Please remove this from the home page. Thanks!

**Comment by lukaszgryglicki** [comment]
Only to confirm, speaking about those links?
Page:
![Screenshot 2019-03-10 at 07 22 40](https://user-images.githubusercontent.com/2469783/54081442-62067a80-4305-11e9-971c-ebe118fe4252.png)
Links:
![Screenshot 2019-03-10 at 07 22 47](https://user-images.githubusercontent.com/2469783/54081446-67fc5b80-4305-11e9-93c5-64174821b177.png)

**Comment by lukaszgryglicki** [comment]
Can you confirm which header should I remove?

**Comment by jberkus** [comment]
All the logos.  

The menu items are fine.  It's that giant block of logos that's the problem.

So no, not the links.

**Comment by lukaszgryglicki** [comment]
cc @dankohn

**Comment by lukaszgryglicki** [comment]
Done, closing.

**Comment by jberkus** [comment]
Thanks, that's much better!
