### ISSUE TITLE
[bug] Cannot show "v1.13.0 - v1.14.0" result

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#169]
I am seeing devstat for v1.14.
I can see range `v1.12.0 - v1.13.0` and `v1.14.0 - now` results on the devstat.

However it shows `No data to show` for `v1.13.0 - v1.14.0` as https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.13.0%20-%20v1.14.0&var-metric=contributions

**Comment by atoato88** [comment]
I'm facing same situation,too.

**Comment by lukaszgryglicki** [comment]
I'm on it now.

**Comment by lukaszgryglicki** [comment]
It's a bug, I see why it happens.
When a new release is added to the database, the previous period no longer is vx.y - now, it becomes vx.y - vx.z and vx.z - now. The old period is in the past so is treated as "calculated" but its name changed so it has no data. I need to handle this somehow. Will be fixed soon.

**Comment by lukaszgryglicki** [comment]
OK, I think I have a solution - this is a fix related to detecting if a given period was calculated. I don't want it to run on `prod` yet - it should auto-heal data automatically during the next 24 hours (annotations are calculated once a day). I'm leaving it to test on the `test` server now. Will check that tomorrow and if solution works I'll apply on `prod`: https://github.com/cncf/devstatscode/commit/99c4b39f9090eb202dae59f06ea309b74d3bc4b9

**Comment by lukaszgryglicki** [comment]
Fixed on both test & prod server. Closing. Thanks for reporting 👍

**Comment by oomichi** [comment]
@lukaszgryglicki Thanks for fixing this issue :-)
