### ISSUE TITLE
Prometheus dashboard has "Kubernetes" mention in graph title

### ISSUE THREAD

**Issue by juliusv** [cncf/devstats.archive#17]
The graph in https://prometheus.cncftest.io/dashboard/db/all-prs-merged?orgId=1&from=now-5y&to=now has the title "PRs merged in all Kubernetes repositories", while it should mention Prometheus instead.

**Comment by lukaszgryglicki** [comment]
I will fix it tomorrow, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Fixed by https://github.com/cncf/devstats/commit/f98575e18704f89e354004831564298917f259a6 closing.
