### ISSUE TITLE
[bug] Please track Windows devstats

### ISSUE THREAD

**Issue by craiglpeters** [cncf/devstats.archive#170]
We need to track the statistics for contributions to all the code and documentation for SIG-Windows. Thanks!

**Comment by PatrickLang** [comment]
I do see Windows in the per-SIG views. What areas are missing?

**Comment by PatrickLang** [comment]
the Kubernetes-sigs/windows-testing repo is tracked

**Comment by lukaszgryglicki** [comment]
Not sure what I can do.

**Comment by craiglpeters** [comment]
We can close this issue. I wasn't seeing the data for some reason. Bad eyes I suppose

**Comment by craiglpeters** [comment]
I see what's missing now. There is no 'SIG Windows' listed in 'Repository Group'.

**Comment by lukaszgryglicki** [comment]
Yes, there is no SIG Windows repository group defined. It was never defined. I can add it and regenerate data, but I need a list of repositories that will be mapped into 'SIG Windows'

**Comment by lukaszgryglicki** [comment]
This [PR](https://github.com/cncf/devstats/pull/167/files#diff-8edd0e6ac4b13658e73e02ece2d6a004R243) adds SIG Windows with just 2 repos: `kubernetes-sigs/windows-gmsa` and `kubernetes-sigs/windows-testing` but is not yet approved.

**Comment by PatrickLang** [comment]
Those are the only two SIG repos I'm aware of to date. Tracking contributions is going to be a bit hard overall because a lot of the files we're changing are in the kubelet & dockershim which have OWNERs set to SIG-Node.

**Comment by lukaszgryglicki** [comment]
Blocked by https://github.com/cncf/devstats/pull/167/files#diff-8edd0e6ac4b13658e73e02ece2d6a004R243

**Comment by lukaszgryglicki** [comment]
Fixed by #192
