### ISSUE TITLE
Questions on infosys contributions

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#172]
Hey @lukaszgryglicki, Infosys started to contribute and they don't show up on devstats on the company table:

Git PR                                                              Status as per K8s(Github)         ContributorEmailId
https://github.com/kubernetes/kubernetes/pull/73686     Approved        shivang.goswami@infosys.com     
https://github.com/kubernetes/website/pull/12512        Approved        rajesh.deshpande02@infosys.com  
https://github.com/kubernetes/website/pull/12652        Approved        Naresh_Lj@infosys.com           
https://github.com/kubernetes/community/pull/3171       Approved        Ramanarayana_M@infosys.com

**Comment by lukaszgryglicki** [comment]
Affiliations are imported about 1-2 times/month. A separate contractor is researching them. Every time new affiliations are imported I'm generating a new task with top-unknown contributors. You will probably see those contributions either when next affiliations are imported (if they were already processed) or at worst case the next one (I'll add those mentioned emails manually to `cncf/gitdm` on Monday).

**Comment by lukaszgryglicki** [comment]
For now I've added all of them to the main config file: https://github.com/cncf/gitdm/commit/b5f549a05963803b7d308b24024a256e23127013

**Comment by caniszczyk** [comment]
Thanks @lukaszgryglicki - now I realized why I was going crazy trying to track this down, we should probably add that info to the README about affiliations coming in only a couple times a month

**Comment by lukaszgryglicki** [comment]
README is updated on both `cncf/devstats` and `cncf/gitdm`. I'm importing new affiliations on the test server. If all is fine I'll also update `prod` soon.

**Comment by lukaszgryglicki** [comment]
new affiliations are imported, they include Infosys affiliations, closing.
