### ISSUE TITLE
Please fix broken link to repo renamed from apiserver-builder to apiserver-builder-alpha

### ISSUE THREAD

**Issue by yue9944882** [cncf/devstats.archive#173]
the repo has been renamed months ago here [kubernetes-incubator/apiserver-builder-alpha](https://github.com/kubernetes-incubator/apiserver-builder-alpha)

https://github.com/cncf/devstats/blob/2441d20143c5452d88b3757eb050a6a7b7995150/scripts/kubernetes/repo_groups.sql#L20

**Comment by lukaszgryglicki** [comment]
We have a big [issue](https://github.com/cncf/devstats/issues/158) and [PR](https://github.com/cncf/devstats/pull/167) pending about repo names/repo groups I'll mention this issue there so all those updates will come in a single PR merge. then I'll regenerate data - this will include past data too.

**Comment by lukaszgryglicki** [comment]
Fixed by #192
