### ISSUE TITLE
Missing Repos for Istio

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#175]
On the dashboard https://istio.teststats.cncf.io/d/dVM-cCCkk/new-prs-in-repository-groups?orgId=1 there is no option for https://github.com/istio/installer

The repo is fairly new (maybe a week)?

Is there anything we need to do to get this on the dashboard? I did a quick grep for the other repos and it doesn't look like we explicitly list them out, so I am not sure if there is a file we need to edit or something

**Comment by lukaszgryglicki** [comment]
That instance wasn't updated (it's not a part of a standard CNCF deployment), I'm updating it right now.

**Comment by lukaszgryglicki** [comment]
Done, see for example: https://istio.teststats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=d7&var-metric=activity&var-repogroup_name=istio%2Finstaller&var-companies=All&from=now-30d&to=now

**Comment by howardjohn** [comment]
Thank you!
