### ISSUE TITLE
Affiliation misattribution

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#179]
https://tikv.devstats.cncf.io/d/56/company-commits-table?orgId=1

It appears to be GitHub user "disksing" email i@disksing.com who as far as I can tell has no affiliation to Docker at all (definitely not in the Docker GitHub org) but the stats attribute to Docker.

**Comment by lukaszgryglicki** [comment]
I'll check that manually, we have so many affiliations (almost 100k atm) so mistakes may happen.

**Comment by lukaszgryglicki** [comment]
I'll change to PingCAP manually in this case: https://github.com/disksing, it will be visible after new affiliations are imported (probably after the KubeCon). I'm working on this now, but not sure if that will be finished before KC.

**Comment by lukaszgryglicki** [comment]
This was fixed.
