### ISSUE TITLE
PR Authors Table seems inaccurate

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#182]
https://istio.teststats.cncf.io/d/23/prs-authors-table?panelId=1&fullscreen&orgId=1&var-period_name=Last%20decade&var-repogroup_name=istio%2Fistio

On this table it shows that I have 314 PRs opened, but it seems like it should be about 1/3 of this (https://github.com/istio/istio/pulls?q=is%3Apr+author%3Ahowardjohn+is%3Aclosed)

golangcibot also has 350 PRs, but they don't actually open PRs, they just comment on them

**Comment by lukaszgryglicki** [comment]
I'll take a look on Monday. Sorry for the delay, I was at KubeCon this week. I'll also add `golangcibot` to the bots list.

**Comment by lukaszgryglicki** [comment]
Yes this is true, current approach just counts PR creations but also comments (any activity on a PR) then groups by activity authors (so if you commented on a PR it will count that). I'll fix this and regenerate data, thanks for reporting!
The actual SQL is [here](https://github.com/cncf/devstats/blob/master/metrics/shared/hist_pr_authors.sql) - I just need to filter events by type `create`).

**Comment by lukaszgryglicki** [comment]
I've made full research on all deployments, all projects, and all dashboards and this also requires fixing (in addition to PRs authors table):
- PRs authors companies table
- Company PRs in repository groups
- New contributors table
- PR authors repository group

On it now.

**Comment by lukaszgryglicki** [comment]
Fixed on bare metal deployments (test & prod), Istio in particular: https://istio.teststats.cncf.io/d/23/prs-authors-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=istio%2Fistio
Now fixing on CDF and then will fix on GraphQL (k8s), LF (k8s) and CDF (bare metal).

**Comment by lukaszgryglicki** [comment]
Updated CDF (bare metal) deployment, GraphQL (K8s) deployment, DevStats talk (K8s) deployment and LF headless (K8s + Aurora) deployment.
Istio on [bare metal](https://istio.teststats.cncf.io/d/23/prs-authors-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=istio%2Fistio)
Istio on [kubernetes](https://istio.devstats-demo.net/d/23/prs-authors-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=istio%2Fistio)

**Comment by lukaszgryglicki** [comment]
Closing, please reopen/comment here if you need more work on this.

**Comment by howardjohn** [comment]
Thanks! looks good now
