### ISSUE TITLE
Project Dashboard for Doc Contribution

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#183]
It would be great to get a dashboard reflecting contributions purely to documentation.

Maybe it's *.md, *.html etc?

**Comment by zacharysarah** [comment]
Consider [PRs merged to `kubernetes/website`](https://k8s.devstats.cncf.io/d/49/github-stats-by-repository?orgId=1&from=now-2y&to=now&var-period=w&var-repos=%22kubernetes%2Fwebsite%22&var-stat=prmerged). It lacks nuance in that it ignores contributions like reviews, but it's a place to start.

It would be great to get some cross-repo statistics that compiled this kind of data across all CNCF projects--though that may be difficult given projects that keep docs in the same repo as product code.

<img width="1519" alt="Screen Shot 2019-05-20 at 6 10 51 PM" src="https://user-images.githubusercontent.com/3210446/58036154-bb233380-7b2a-11e9-9d11-1d19a7897b37.png">

**Comment by caniszczyk** [comment]
@zacharysarah are there particular files outside of *.md that contain documentation?

**Comment by lukaszgryglicki** [comment]
I can track commit files and filter by known doc-related files (would need a list - or ideally a regex that defines a doc file). We can then assign commits as non-doc, only-doc, mixed and create a dashboard based on this.
Makes sense?
DevStats already track commit's files for every commit, so no data source updates/changes are needed at all, just use the data we already have.

**Comment by zacharysarah** [comment]
@caniszczyk The overwhelming majority of doc content resides in *.md* files. The federation API reference uses HTML files, but it’s a unique phenomenon. Some site config files also fall outside the lines, but yes, Markdown files are safely representative of doc contributions.

**Comment by lukaszgryglicki** [comment]
@caniszczyk @dankohn should I work on some example dashboard? If so please let me know how should it look like?
A table? A stacked chart? 
What filters/drop-downs?
A repository group drop-down? SIG drop-down? Others?

**Comment by lukaszgryglicki** [comment]
I would start to create a preview dashboard but I need those minimal details mentioned [here](https://github.com/cncf/devstats/issues/183#issuecomment-496075668) first...

**Comment by caniszczyk** [comment]
table with the ability to filter by repo group

**Comment by lukaszgryglicki** [comment]
Table showing doc contributors right?
like for example
- select date range
- select repo group or all

And then table:
- contributor1, N1 doc contributions
- contributor2, N2 doc contributions
...

Doc contribution defined as any commit that includes changes or creating to *.md file(s)?

**Comment by caniszczyk** [comment]
actually can we just make it two, basically model it after this:

https://all.devstats.cncf.io/d/7/companies-contributing-in-repository-groups?orgId=1 (for only docs)
https://all.devstats.cncf.io/d/5/companies-table?orgId=1 (for only docs)

**Comment by lukaszgryglicki** [comment]
So the first showing number of distinct docs contributors and distinct docs contributing companies and the second one showing the number of doc contribution grouped by companies? Both allowing filter by repo groups, right?

**Comment by lukaszgryglicki** [comment]
Added one new dashboard for all projects (excluding Kubernetes which requires explicit approval), for example [dashboard for All CNCF projects combined](https://all.devstats.cncf.io/d/61/documentation-committers-in-repository-groups?orgId=1).
Instead of adding new tabular dashboard (2nd request) I've added new drop-down filter values for the [existing dashboard](https://all.devstats.cncf.io/d/5/companies-table?orgId=1) they're [Documentation commits](https://all.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=documentationcommits) and [Documentation committers](https://all.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=documentationcommitters).

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed.
