### ISSUE TITLE
[bug] dashboard not working when filter value contains commas

### ISSUE THREAD

**Issue by idealhack** [cncf/devstats.archive#184]
e.g., https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=Korea,%20Republic%20of not working.

Not sure about other dashboards but this one works https://k8s.devstats.cncf.io/d/50/countries-stats?orgId=1&var-period_name=Quarter&var-countries=%22Korea,%20Republic%20of%22&var-repogroup_name=All&var-metric=rcommitters&var-cum=countries

**Comment by lukaszgryglicki** [comment]
Thanks for reporting, I'll check this.

**Comment by lukaszgryglicki** [comment]
This is not due to comma, this is due to dashboards metrics - one returns data for `Korea, Republic of` and another one doesn't - investigating.

**Comment by idealhack** [comment]
I forgot one point here that I checked other country names with a comma, not working as well

**Comment by lukaszgryglicki** [comment]
OK, fixed (it *was* due to comma), regenerate that dashboard and confirmed that it [works OK](https://k8s.teststats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=Korea%20Republic%20of). I'm now provisioning data on the prod server too.

**Comment by idealhack** [comment]
yeah, [it works](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=Korea%20Republic%20of), the `country_name` could be improved though.

**Comment by lukaszgryglicki** [comment]
Prod also [fixed](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=Korea%20Republic%20of).
