### ISSUE TITLE
[feature-request] Add jenkins-infra/jenkins-io to jenkins project metrics

### ISSUE THREAD

**Issue by MarkEWaite** [cncf/devstats.archive#185]
The Jenkins project keeps its documentation in the [jenkins-infra/jenkins.io repository](https://github.com/jenkins-infra/jenkins.io).  The [Jenkins Documentation Special Interest Group](https://jenkins.io/sigs/docs/) would like to recognize new contributors and encourage more contribution from all.  We think devstats metrics can be used to identify new contributors and highlight increasing contributions.

The [devstats site](https://jenkins.devstats.cd.foundation/d/8/dashboards?refresh=15m&orgId=1) provides a much deeper and broader set of results than the simple GitHub metrics we've been using.  We'd like the docs repository included in the analysis that is provided for the rest of the Jenkins project.

**Comment by lukaszgryglicki** [comment]
Will add, ETA - Monday.

**Comment by MarkEWaite** [comment]
Thanks very much!

**Comment by lukaszgryglicki** [comment]
Should I add entire jenkins-infra org, or just this single repo? Should I start tracking this from now (which can be done anytime)? Or regenerate all historical data with that repo included (which requires full regenerate on jenkins project data)?

**Comment by MarkEWaite** [comment]
That's a great question.  Considering the small number of repositories in the jenkins-infra organization, I would prefer that all the repositories be added.

Regenerating all the historical data for the entire Jenkins project (2000+ repos) seems like a lot of work for relatively little benefit.  

I'd prefer that we start tracking the data from now.  That will let me use the arriving data to discover new contributors and increased (or decreased) activity levels in the months ahead, without wasting your time or computer time regenerating all historical data for the entire Jenkins project.

**Comment by lukaszgryglicki** [comment]
No problem with regenerating, in any case I'll update on Monday.

**Comment by MarkEWaite** [comment]
If regenerating is not too painful, then full historical data is very attractive, since it will give me additional insights into the repository history.

I'll be delighted with either and trust your judgment to decide which makes the most sense in this situation.

**Comment by lukaszgryglicki** [comment]
I'll regenerate data on Monday. Tuesday worst case.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by MarkEWaite** [comment]
That looks great!  Thanks very much!
