### ISSUE TITLE
Pull Requests Created includes closing PRs

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#187]
Example: https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&from=now-30d&to=now&var-period=d&var-metric=prs&var-repogroup_name=istio%2Fistio&var-users=All

See user duderino on 6/1. The charts say 24 PRs were created on this day. If you look on Github, you can see this user has not made this many PRs total: https://github.com/istio/istio/pulls/duderino

I know they closed ~24 PRs on 6/1 (although don't know a good Github query to prove it), so I suspect these are getting mixed in with opened PRs

**Comment by lukaszgryglicki** [comment]
Will check this.

**Comment by lukaszgryglicki** [comment]
Yes this is true, dashboard calculates all PullRequests events (so opening, closing, merging) and then the number of distinct PRs from those events. I will update this dashboard data.

**Comment by lukaszgryglicki** [comment]
Fixed, also on all other projects. Now I'm only calculating opened PRs/issues.
