### ISSUE TITLE
[bug] No DevStats projects link on Dashbords works 

### ISSUE THREAD

**Issue by KeyboardNerd** [cncf/devstats.archive#188]
Goto: https://all.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m
Under All CNCF projects, DevStats projects: Click on any one project e.g. k8s
It fails with DNS_PROBE_FINISHED_NXDOMAIN.
example URLs:
https://linkerd.devstats-provision-all/
https://k8s.devstats-provision-all/

**Comment by lukaszgryglicki** [comment]
Will check tomorrow. thanks for reporting. This is due to switch to Kubernetes just about an hour ago. I'll correct that.

**Comment by lukaszgryglicki** [comment]
Fixed.
