### ISSUE TITLE
[feature request] Add ranking number of contribution table

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#189]
When seeing https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.14.0%20-%20now&var-metric=contributions it is a little difficult to understand what ranking number for each company because of no index on the table.

The following picture is a sample which contains the index on the left side of each company name:

![Capture](https://user-images.githubusercontent.com/1287154/59383030-f8d34080-8d13-11e9-8a50-479486950004.JPG)

**Comment by lukaszgryglicki** [comment]
OK will work on that soon.

**Comment by lukaszgryglicki** [comment]
@oomichi done.

**Comment by oomichi** [comment]
@lukaszgryglicki Thanks for your work. That is so faster than I expected ! :-)

**Comment by lukaszgryglicki** [comment]
You're welcome.
