### ISSUE TITLE
Drop down menu of projects

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#19]
Would it be possible to modify Grafana so that when you click the project logo at the top left, under the Pin option would be entries for every CNCF project (with logo and name). Selecting one would redirect you to that's project's page.

**Comment by lukaszgryglicki** [comment]
Will research on Monday, I expect that changes to Grafana would be needed - but this is a blind shot.

**Comment by lukaszgryglicki** [comment]
I have found something like this (but I cannot set custom icon), researching ...
![screen shot 2017-11-20 at 08 00 41](https://user-images.githubusercontent.com/2469783/33006010-f12d19b6-cdc8-11e7-961d-02d5aab22505.png)

**Comment by lukaszgryglicki** [comment]
Another option is to add panel drilldown links (I can't set icon there too):
![screen shot 2017-11-20 at 08 02 08](https://user-images.githubusercontent.com/2469783/33006075-40c6fb0e-cdc9-11e7-842a-d80455d94789.png)

Third option seems to be manually adding some code to Grafana (just like custom window titles and icons that are used now).

**Comment by lukaszgryglicki** [comment]
I will add links to all other projects from each project's home dashboard:
![screen shot 2017-11-20 at 08 19 44](https://user-images.githubusercontent.com/2469783/33006716-b9992cb2-cdcb-11e7-9f90-daa1d58cbc6c.png)
![screen shot 2017-11-20 at 08 19 58](https://user-images.githubusercontent.com/2469783/33006717-b9b44dc6-cdcb-11e7-8b14-1700debdbcd6.png)

**Comment by dankohn** [comment]
Thanks for researching. I'm worried that your solution takes up too much space, especially when we have a couple dozen projects. Instead, I might suggest a single dashboard that is identical across all DevStats instances and just includes a project per row with a link to the other dashboards. It would be great to include project icons in the table, but isn't essential.

**Comment by lukaszgryglicki** [comment]
OK I'll do this instead, just need to finish few started items.

**Comment by lukaszgryglicki** [comment]
Now created separate dashboard that lists all projects and imported this dashboard on all projects, like this:
https://fluentd.cncftest.io/dashboard/db/all-projects?refresh=15m&orgId=1
![screen shot 2017-11-20 at 15 05 32](https://user-images.githubusercontent.com/2469783/33022110-52f5920a-ce04-11e7-83a0-e54c2f365a56.png)
![screen shot 2017-11-20 at 15 05 42](https://user-images.githubusercontent.com/2469783/33022111-531264c0-ce04-11e7-8902-447a6ee75527.png)

**Comment by dankohn** [comment]
If you made it a table, could you include html images?

http://docs.grafana.org/reference/table_panel/

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Will do, I just have a long list of items to do.

**Comment by lukaszgryglicki** [comment]
Created HTML table with links and icons.
![screen shot 2017-11-29 at 07 50 43](https://user-images.githubusercontent.com/2469783/33361859-3ae11d88-d4da-11e7-8bc8-d921101fbe08.png)

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed.
