### ISSUE TITLE
Infosys Contributions count Not reflected at devstats

### ISSUE THREAD

**Issue by Mohit-Nain** [cncf/devstats.archive#190]
Hi @lukaszgryglicki , again there have been contributions from Infosys where PRs have been merged to Kubernetes website but the count is not reflect at devstats.
Below are the PRs: 
https://github.com/kubernetes/website/pull/14669
https://github.com/kubernetes/website/pull/14440
https://github.com/kubernetes/website/pull/14439
https://github.com/kubernetes/website/pull/14383
https://github.com/kubernetes/website/pull/14355
https://github.com/kubernetes/website/pull/14354

All of these have been contributed by rajesh.deshpande02@infosys.com in last 30 days.

We had reconfirmed the count to be 72 during month of April 2019, but even today the count remains 72, however there have been contributions from Infosys.

**Comment by lukaszgryglicki** [comment]
I don't have that user data imported into DevStats yet. It will be imported during the next affiliations import, ETA Monday. Please also let me know which dashboard you are referring to.

**Comment by Mohit-Nain** [comment]
https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1

this is the one we are referring

**Comment by lukaszgryglicki** [comment]
OK, will import new affiliations and then let you know when corrected. Please note that we're importing new affiliations data about 1-2 times/month.

**Comment by lukaszgryglicki** [comment]
The new affiliations are imported. It now shows [152 contributions](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions) from [5 contributors](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=contributors). I've also double checked [rajesh.deshpande02](https://raw.githubusercontent.com/cncf/devstats/master/github_users.json) user and He's affiliated to Infosys in JSOn file at 1121299 line.

**Comment by Mohit-Nain** [comment]
is there a way to check details of these 5 contributors?

**Comment by lukaszgryglicki** [comment]
There is no dashboard showing all those details, k8s community didn't want such company-related additional dashboards.
I've pulled this data for you manually:
```
allprj=# select a.login, a.name, ae.email, an.name from gha_actors a, gha_actors_emails ae, gha_actors_names an where a.id = an.actor_id and a.id = ae.actor_id and a.id in (select actor_id from gha_actors_affiliations where company_name = 'Infosys');
       login       |         name         |                        email                        |         name         
-------------------+----------------------+-----------------------------------------------------+----------------------
 rajeshdeshpande02 | Rajesh Deshpande     | 47311048+rajeshdeshpande02@users.noreply.github.com | Rajesh Deshpande
 rajeshdeshpande02 | Rajesh Deshpande     | rajesh.deshpande02@infosys.com                      | Rajesh Deshpande
 rajeshdeshpande02 | Rajesh Deshpande     | rajeshdeshpande02@users.noreply.github.com          | Rajesh Deshpande
 irfanjs           | Irfan Sayed          | irfanjs@users.noreply.github.com                    | Irfan Sayed
 irfanjs           | Irfan Sayed          | irfu.sayed@gmail.com                                | Irfan Sayed
 king-julien       |                      | jaisonpjohn@gmail.com                               | king-julien
 king-julien       |                      | king-julien@users.noreply.github.com                | king-julien
 King-Julien       |                      | king-julien@users.noreply.github.com                | king-julien
 rajeshdeshpande02 | Rajesh Deshpande     | 47311048+rajeshdeshpande02@users.noreply.github.com | Rajesh Deshpande
 rajeshdeshpande02 | Rajesh Deshpande     | rajesh.deshpande02@infosys.com                      | Rajesh Deshpande
 rajeshdeshpande02 | Rajesh Deshpande     | rajeshdeshpande02@users.noreply.github.com          | Rajesh Deshpande
 rajeshdeshpande02 | Rajesh Deshpande     | 47311048+rajeshdeshpande02@users.noreply.github.com | rajeshdeshpande02
 rajeshdeshpande02 | Rajesh Deshpande     | rajesh.deshpande02@infosys.com                      | rajeshdeshpande02
 rajeshdeshpande02 | Rajesh Deshpande     | rajeshdeshpande02@users.noreply.github.com          | rajeshdeshpande02
 irfanjs           | Irfan Sayed          | irfanjs@users.noreply.github.com                    | Irfan Sayed
 irfanjs           | Irfan Sayed          | irfu.sayed@gmail.com                                | Irfan Sayed
 Chids-gs          | Chidambaram Sundaram | chidambaram.g@gmail.com                             | Chidambaram Sundaram
 ramnar            |                      | raam.soft@gmail.com                                 | ramnar
 ramnar            |                      | ramanarayana_m@infosys.com                          | ramnar
 ramnar            |                      | ramnar@users.noreply.github.com                     | ramnar
 ljnaresh          |                      | ljnaresh@users.noreply.github.com                   | ljnaresh
 ljnaresh          |                      | naresh_lj@infosys.com                               | ljnaresh
(22 rows)
```
This is for all actors affiliated to Infosys - their details, emails and names. There can be more than 1 row for single actor - like multiple names, emails etc.

**Comment by lukaszgryglicki** [comment]
I'm closing this, please let me know if you need to reopen.
