### ISSUE TITLE
[feature request] Exclude All from company contribution ranking

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#191]
Now as the following, the table shows All is 1st on the ranking.
However All is not company and it is nice to exclude the ranking number from All.
![Capture](https://user-images.githubusercontent.com/1287154/59451327-0c3be580-8dc0-11e9-93f8-80b8a18d4284.JPG)

**Comment by lukaszgryglicki** [comment]
Have other stuff to do, will return to this next week, I can make All `rank 0` and eventually hide that 0 (will research that).

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Done. Closing.
