### ISSUE TITLE
[feature request] Add ranking number of Developer Activity Counts

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#193]
As the same as https://github.com/cncf/devstats/issues/189 it is nice to add ranking number to `Developer Activity Counts` as https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1

**Comment by lukaszgryglicki** [comment]
I'll work on this maybe next week, thanks.

**Comment by lukaszgryglicki** [comment]
Done, closing.

**Comment by oomichi** [comment]
@lukaszgryglicki Thanks for doing this, that is so fast :-)
I confirmed this works well as https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1
