### ISSUE TITLE
[question] The status of non-cncf projects

### ISSUE THREAD

**Issue by gaocegege** [cncf/devstats.archive#194]
I saw there are some directories in this repo, e.g. https://github.com/cncf/devstats/tree/master/kubeflow. Are we considering show these projects in the devstats?

In kubeflow community, we maintained a deployment of devstats. If we could support non-cncf projects in the cncf devstats, I think it will be betters.

Maybe we could refer to the design of https://www.stackalytics.com/.

![Screenshot from 2019-07-04 11-49-12](https://user-images.githubusercontent.com/5100735/60638655-cd92cb80-9e51-11e9-9b2a-fc31e3da7771.png)

**Comment by lukaszgryglicki** [comment]
DevStats only shows CNCF projects. You can take a look at `cncf/devstats-helm` and deploy your own installation for whatever project(s) you want.

**Comment by gaocegege** [comment]
Gotcha. Then what's the purpose of https://github.com/cncf/devstats/tree/master/kubeflow or https://github.com/cncf/devstats/tree/master/knative

**Comment by lukaszgryglicki** [comment]
There are some projects that were added to devstats but only on a test server. Some of them are still there and some of them are no longer maintained.

**Comment by gaocegege** [comment]
@lukaszgryglicki Thanks for your reply! I am closing it.
