### ISSUE TITLE
pq: permission denied for table gfa_vars

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#195]
When accessing https://istio.teststats.cncf.io/d/8/dashboards?orgId=1&refresh=15m, all dashboards fail to load with error `pq: permission denied for table gfa_vars`

**Comment by lukaszgryglicki** [comment]
Will work on that on Monday, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Fixed. Thanks for reporting, other projects were broken too - my bad.

**Comment by howardjohn** [comment]
Thanks! it is working well again
