### ISSUE TITLE
[feature request] Exclude Independent from company ranking index

### ISSUE THREAD

**Issue by oomichi** [cncf/devstats.archive#197]
Independent is 5th on company ranking as https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.14.0%20-%20v1.15.0&var-metric=contributions
But Independent is not a company, it is better to exclude it from company ranking index like putting empty as Independent's rank.

**Comment by lukaszgryglicki** [comment]
This needs discussion
cc @dankohn @spiffxp @jberkus

**Comment by dankohn** [comment]
One of the inspirations for DevStats was gitdm and the Who Writes Linux report. See [2017's report](https://go.pardot.com/l/6342/2017-10-24/3xr3f2/6342/188781/Publication_LinuxKernelReport_2017.pdf). None, meaning independent, has always been an entry there (see page 14), so I would suggest we keep it here.

**Comment by lukaszgryglicki** [comment]
I would also keep `Independent` in place, that's why I'm asking. It actually tells a story about how many un-affiliated developers are contributing to the project.

**Comment by oomichi** [comment]
@dankohn @lukaszgryglicki Thanks for your information, that makes sense for me.
