### ISSUE TITLE
[feature request] Summary dashboard for Falco project

### ISSUE THREAD

**Issue by mfdii** [cncf/devstats.archive#199]
The Falco maintainer team is trying to focus on improving a few key metrics, and thus we'd like to have these metrics in a single dashboard in order to make it easier to review the metrics on a regular basis. All these metrics exist as individual dashboards now, so it's just a matter of making one dashboard to combine them all.

We'd like to have a dashboard of the following:

- [x] Stars and Forks by Repository
- [x] Companies Contributing in Repository Groups
- [x] PRs Merged Repository Groups
- [x] PR Time to Engagement
- [x] Issues Age by Repository Group
- [x] Issues Opened/Closed by Repository Group

Please let us know if this is possible.

**Comment by lukaszgryglicki** [comment]
On it now, but please not the drop-downs can only be defined in the header row, so this big dashboard will have all drop-downs from the listed dashboards at the top and then all panels copied.

**Comment by lukaszgryglicki** [comment]
And possible drop-down values for the period will contain only values shared from all sub-dashboards.

**Comment by lukaszgryglicki** [comment]
Almost ready but the last problems:
One of those dashboards has "repository group" multi-select drop-down, while others have single value select.
I will create two:
- "Repository group" - for single value select
- "Repository groups" - for multi-value select.

Also, one dashboard used "priority" drop-down (based on labels), but I don't see any data when selecting a value from that priority drop-down (Falco doesn't seem to use priority labels in this way). I've removed that drop-down and assumed "all" is selected (which was the only option that shows reasonable values anyway).

**Comment by lukaszgryglicki** [comment]
@mfdii dashboard implemented [here](https://falco.devstats.cncf.io/d/65/summary-dashboard?orgId=1). 4 dropdowns finally needed: Period, repository (single repo for forks/stars, etc), repository group (single value select) and repository groups (multi-select for PRs merged in repo groups). The period drop-down contains minimal common set (7 Days MA, Week, Month, Quarter).

**Comment by mfdii** [comment]
Thanks for the fast response. This looks good to us. If we have any issue we'll reopen this issue.
