### ISSUE TITLE
Bug: company stats are not a sum of affiliated developers

### ISSUE THREAD

**Issue by tigrannajaryan** [cncf/devstats.archive#201]
I am affiliated with Omnition. The affiliation data in https://github.com/cncf/gitdm seems to be correct. Yet, my personal stats don't seem to contribute correctly to the company stats.

[Here](https://github.com/cncf/devstats/issues/new?assignees=&labels=&template=issue.md&title=) it shows that I (@tigrannajaryan) have 703 contributions to OpenTelemetry.

However when I check [company contributions](https://opentelemetry.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions) it shows that Omnition has only 634 contributions. Obviously this is cannot be the case if calculations are correct, company's contributions cannot be less than my own contributions while being affiliated with that company.

It appears that despite being affiliated with the company my contributions are not counted as company contributions.

**Comment by lukaszgryglicki** [comment]
Affiliations from `cncf/gitdm` are periodically imported into DevStats (usually 1-2 times per month). Seems like your affiliations are not imported yet. They will be correct after next import.

**Comment by tigrannajaryan** [comment]
I understand. Thank you.

**Comment by lukaszgryglicki** [comment]
Closing, please let me know if you need to reopen this.
