### ISSUE TITLE
Issues Opened/Closed (siopened/siclosed) include PRs as well

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#202]
This is likely due to GitHub API essentially treating them the same, seems like a common issues with things that consume Github APIs.

I am pretty sure this is the case, as if you look at https://istio.teststats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&fullscreen&panelId=3&var-period=d7&var-repogroup_name=istio%2Finstaller (if link doesn't work, this is [istio/installer](https://github.com/istio/installer), you can see issues are disabled for the repo.

Also it would be useful for this chart to not be stacked, so we can see closed relative to opened - very useful to see as we are aiming to have `Closed >= Opened`.

Thanks!

**Comment by lukaszgryglicki** [comment]
1. yes this counts both issues and PRs - I'll change this into 2 charts (PRs and issues).
2. I'll add non-stacked chart below the stacked one.

**Comment by lukaszgryglicki** [comment]
Preview (but very wip): https://istio.teststats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&var-period=d7&var-repogroup_name=istio%2Finstaller

**Comment by howardjohn** [comment]
Nice! looks great

**Comment by lukaszgryglicki** [comment]
Actually finished, forgot to close, thanks.
