### ISSUE TITLE
[feature request] add devstats for serverless projects

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#203]
This can be on teststats or another instance but I'm interested in adding:

AWS SAM: https://github.com/awslabs/aws-sam-cli + https://github.com/awslabs/serverless-application-model
AZF: https://github.com/Azure/Azure-Functions#github-repositories
Pivotal Riff: https://github.com/projectriff
Google KNative: https://github.com/knative
Oracle Fn: https://github.com/fnproject
Apache OpenWhisk: https://github.com/apache/incubator-openwhisk
OpenFaaS: https://github.com/openfaas

**Comment by lukaszgryglicki** [comment]
Will work on this as soon as I can.

**Comment by lukaszgryglicki** [comment]
Will work on this after adding Strimzi, start work on Wednesday.

**Comment by lukaszgryglicki** [comment]
Starting to work on this.

**Comment by lukaszgryglicki** [comment]
We already have Knative (a long long time): https://knative.teststats.cncf.io/d/8/dashboards?orgId=1&refresh=15m

**Comment by lukaszgryglicki** [comment]
Researched all repo names changes histore in all those projects to enable correct DevStats data retrieve params, see (old/historical names only): 
```
AWS SAM:
  awslabs/aws-sam-local -> awslabs/aws-sam-cli
AZF:
  Azure/azure-webjobs-sdk-script -> Azure/azure-functions-host
  Azure/azure-functions-cli -> Azure/azure-functions-core-tools
  projectkudu/AzureFunctions -> Azure/azure-functions-ux
  projectkudu/WebJobsPortal -> Azure/azure-functions-ux
  projectkudu/AzureFunctionsPortal -> Azure/azure-functions-ux
  projectkudu/azure-functions-ux -> Azure/azure-functions-ux
  Azure/azure-webjobs-sdk-templates -> Azure/azure-functions-templates
Pivotal Riff:
  markfisher/sk8s -> projectriff/riff
  ericbottard/sk8s-go
  ericbottard/sk8s-types
  ericbottard/kubernetes-model
  ericbottard/sk8s-http-gateway
  ericbottard/function-sidecar
  ericbottard/sk8s-topic-controller
  jldec/projectriff.io
  pivotal-cf/pfs-system-test
Oracle Fn:
  treeder/fn-plugin-example
  treeder/fn-ext-dns
  treeder/fn-ext-example
  treeder/fn-ext-auth
  fnhub/katacoda-scenarios
Apache OpenWhisk:
  apache/incubator-openwhisk -> apache/openwhisk
OpenFaaS:
  alexellis/faas -> openfaas/faas
  open-faas/nats-queue-worker -> openfaas/nats-queue-worker
  alexellis/faas-cli -> openfaas/faas-cli
  alexellis/java-afterburn
  alexellis/faas-netes
  alexellis/caddy-builder
  alexellis/openfaas-workshop
  alexellis/derek
  alexellis/java-openfaas-fast-fork
  alexellis/openfaas-cloud
  stefanprodan/caddy-builder
  alexellis/faas-nats
  alexellis/serverless-faas
  alexellis/faas-provider
  alexellis/nodejs-afterburn
```

**Comment by lukaszgryglicki** [comment]
Final PSQL configs taking into account all orgs/repos lists per serverless projects added here: 59b6eaa63193fcc41b50c3c9b1ad2a11fd127877

**Comment by lukaszgryglicki** [comment]
I'm also updating `cncf/velocity` project to correctly identify all those new serverless projects.

**Comment by lukaszgryglicki** [comment]
Finished:
- Oracle Fn https://fn.teststats.cncf.io
- Apache OpenWhisk: https://openwhisk.teststats.cncf.io
- AWS SAM: https://sam.teststats.cncf.io
- OpenFaaS: https://openfaas.teststats.cncf.io 
- Knative: https://knative.teststats.cncf.io
- AZF: https://azf.teststats.cncf.io
- Pivotal Riff fixed: https://riff.teststats.cncf.io
Closing.
