### ISSUE TITLE
PRs closed/opened may be inaccurate

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#205]
Slack conversation captured:

John Howard 8:55 AM
@lukaszgryglicki Is it possible the sprclosed table doesn't treat merged PRs as closed or something? It seems like there are some closed PRs missing somehow? From https://istio.teststats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&fullscreen&panelId=14&var-period=d7&var-repogroup_name=istio%2Fistio there are 4.7k total opened PRs and 2k closed PRs, but the repo only has about 100 open PRs right now not 2.7k.

lukaszgryglicki:house_with_garden: 8:56 AM
please see documentation panel at the bottom This dashboard shows the number of issues/PRs opened and closed in a given periods.
it counts PRs opened/closed in given periods
in this case this is a 7 days moving average
so this counts PRs opened/closed during the period 7 days long, moving in 1 day increments
John Howard 8:59 AM
No matter what time period I do PRs opened is always way more than closed. For issues opened/closed it looks perfect. For example if I do "day" and "last 5 years" (older than the repo), I get 1k more opened issues than closed, and the repo has 1k open issues currently so that makes sense. But I see 10k opened PRs and 3.5k closed PRs, when I would expect them to be within 100 of each other?
I am looking at the "Total" stat
lukaszgryglicki:house_with_garden: 8:59 AM
So this total is from the date range selected - last year
This looks for the last 5 years in monthly periods aggregation for i/i: https://istio.teststats.cncf.io/d/12/issues-opened-closed-by-repository-group?orgId=1&from=now-5y&to=now&var-period=m&var-repogroup_name=istio%2Fistio&fullscreen&panelId=13
John Howard 9:12 AM
The total is still 10k open  3.5k closed but there are only 103 open PRs. I would expect open - closed = currently opened?
new messages
lukaszgryglicki:house_with_garden: 9:17 AM
Please create an issue, I’ll take a closer look at the database and see what happens.
I’ve took a look on the SQL and it seems OK at the first glance, but I’ll play with the DB manually to see what’s. I just need to finish some urgent tasks and then I can get to it, so please create an issue.

One thing I didn't mention is in the past ~month or so it actually seems like it may be accurate? I remember around that time the "Github Events" dashboard started showing more events so maybe something related to that?

**Comment by lukaszgryglicki** [comment]
GitHub events will show more, because it counts all possible events. Anyway, I'll check this and eventually correct. Thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Will work on this on Friday.

**Comment by lukaszgryglicki** [comment]
@howardjohn I see what's wrong:
Issues and PRs are stored on the same table `gha_issues`.
There is `is_pull_request` flag in this table that specifies if a given issues is actually an issue or PR.
Now for "issues" flagged as PRs there is `gha_pull_requests` table, which holds data specific only to PRs. When PRs got closed/merged - `closed_at` is updated on this `gha_pull_requests` table but not always in `gha_issues` table (don't know why), see:
```
istio=# select count(distinct id) from gha_pull_requests where dup_repo_name = 'istio/istio' and created_at >= now() - '1 month'::interval;
 count 
-------
   436
(1 row)

istio=# select count(distinct id) from gha_pull_requests where dup_repo_name = 'istio/istio' and closed_at >= now() - '1 month'::interval;
 count 
-------
   410
(1 row)

istio=# select count(distinct id) from gha_issues where dup_repo_name = 'istio/istio' and is_pull_request = true and created_at >= now() - '1 month'::interval;
 count 
-------
   419
(1 row)

istio=# select count(distinct id) from gha_issues where dup_repo_name = 'istio/istio' and is_pull_request = true and closed_at >= now() - '1 month'::interval;
 count 
-------
   332
(1 row)
```
This means that for PRs I should query `gha_pull_requests` table instead of `gha_issues` + `is_pull_request = true` filter. I'll update SQL and regenerate all data.

Please note that this data comes for GitHub archives and is only copied to DevStats tables.

**Comment by lukaszgryglicki** [comment]
For issues (not PRs) data in `gha_issues` seems to be OK:
```
istio=# select count(distinct id) from gha_issues where dup_repo_name = 'istio/istio' and is_pull_request = false and created_at >= now() - '1 month'::interval;
 count 
-------
   324
(1 row)

istio=# select count(distinct id) from gha_issues where dup_repo_name = 'istio/istio' and is_pull_request = false and closed_at >= now() - '1 month'::interval;
 count 
-------
   351
(1 row)

istio=# 
```

**Comment by lukaszgryglicki** [comment]
Seems like after SQL fix all should be fine (data regenerate pending), see:
```
2019-09-05 07:40:28 root@teststats:~/dev/go/src/github.com/cncf/devstats# PG_PASS=[redacted] GHA2DB_LOCAL=1 PG_DB=istio runq ./metrics/shared/issues_closed.sql {{from}} 2019-08-01 {{to}} 2019-10-01 {{n}} 1 | grep 'istio/istio'
2019-09-05 07:40:40 /runq: |prclosed,istio/istio        |446.00 |
2019-09-05 07:40:40 /runq: |iclosed,istio/istio         |379.00 |
2019-09-05 07:40:40 root@teststats:~/dev/go/src/github.com/cncf/devstats# PG_PASS=[redacted] GHA2DB_LOCAL=1 PG_DB=istio runq ./metrics/shared/issues_opened.sql {{from}} 2019-08-01 {{to}} 2019-10-01 {{n}} 1 | grep 'istio/istio'
2019-09-05 07:40:53 /runq: |propened,istio/istio        |480.00 |
2019-09-05 07:40:53 /runq: |iopened,istio/istio         |359.00 |
2019-09-05 07:40:53 root@teststats:~/dev/go/src/github.com/cncf/devstats# 
```

**Comment by lukaszgryglicki** [comment]
SQL fixed here: 464ef491efef13484b7c7648aeec4545a0eb91a9, test coverage updated here: 267579f73560d05a02bba0d5675a59160cc51a7d

**Comment by lukaszgryglicki** [comment]
Finished, data regenerated on all 40+ projects on both test and prod servers. Closing.

**Comment by howardjohn** [comment]
thanks!! looks great now
