### ISSUE TITLE
[feature request] Please add Company to developer-activity-counts-by-repository-group page

### ISSUE THREAD

**Issue by dims** [cncf/devstats.archive#206]
Could we please add the company information to the following page:
https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1

**Comment by lukaszgryglicki** [comment]
@dankohn @spiffxp I can add this, but I need some approval I presume?

**Comment by dankohn** [comment]
Approved, thanks.

**Comment by lukaszgryglicki** [comment]
Done on [K8s](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1), other projects pending.

**Comment by lukaszgryglicki** [comment]
Other projects finished too, for example [KubeVirt](https://kubevirt.teststats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1)

**Comment by dims** [comment]
@lukaszgryglicki is it easy to add a drop down list box for “Company” alongside the “Country”?

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by liggitt** [comment]
Can we restore the ability to see a developer's activity count aggregated across their company memberships, and make that the default again? (with the recent change, I'm now both 6 and 26 on the decade view of the k8s list, which is really confusing). Having the dev+company view is useful, but maybe as a secondary or non-default view.

**Comment by dims** [comment]
+1 to what @liggitt said, we should be able to view across all companies as well!

**Comment by lukaszgryglicki** [comment]
To display company I must group data by the company if you take last decade you will see 2 entries for 2 companies you worked for. I can either roll back to what we have before this feature request or leave it as is. If I add another special entry like "All" companies it will be confusing with "All" selection that allows displaying all companies. If you want to see your recent rank, please select "last year" or last release.
Eventually, I can rename this dashboard to "stats per company" and restore the previous dashboard, so we will have two separate dashboards then.

**Comment by lukaszgryglicki** [comment]
Ohh, maybe I will just add another panel to this dashboard - one will show per company data and another summary data (regardless of the company).

**Comment by liggitt** [comment]
> Ohh, maybe I will just add another panel to this dashboard - one will show per company data and another summary data (regardless of the company).

That's what I was thinking

**Comment by lukaszgryglicki** [comment]
I've added another panel (on the test server), so now you have "per company stats" panel and "all companies combined" panel. See [here](https://k8s.teststats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1). Please let me know if that is ok for you, if so I'll update all CNCF projects (including K8s) on both test and prod servers.
@liggitt @dims

**Comment by liggitt** [comment]
it's a little confusing to have a company filter on the page the doesn't apply to one of the panels. maybe two dashboards would be better

**Comment by lukaszgryglicki** [comment]
That was my concern too, I'll create two dashboards and let you review that approach.

**Comment by liggitt** [comment]
sounds good. if possible, when this is all resolved, let's keep the original dashboard URLs intact (I know many people link to them)

**Comment by lukaszgryglicki** [comment]
Sure, please check this (currently on the test server):
- Original one: https://k8s.teststats.cncf.io/d/13/developer-activity-counts-by-repository-group
- A new one with companies: https://k8s.teststats.cncf.io/d/66/developer-activity-counts-by-companies

If this is OK, I'll update other projects and then prod site.

**Comment by liggitt** [comment]
That looks good to me, thanks!

**Comment by lukaszgryglicki** [comment]
OK, so I'll update everything.

**Comment by lukaszgryglicki** [comment]
OK, added on 'All CNCF': https://all.teststats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1, https://all.teststats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1, other projects will be updated soon, if all is fine then I'll update prod.

**Comment by lukaszgryglicki** [comment]
Updated everywhere, prod & test, all projects.
