### ISSUE TITLE
[feature request] Please add country information to company-prs-in-repository-groups

### ISSUE THREAD

**Issue by dims** [cncf/devstats.archive#207]
Can we please add country column to the following page:
https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1

**Comment by lukaszgryglicki** [comment]
Same here: @spiffxp @dankohn I can add this, but for K8s dashboards I need k8s team to approve that feature.

**Comment by dankohn** [comment]
Please feel free to mention on #devstats and see if anyone objects. But otherwise please go ahead. Note that the previous issue was concern about including email addresses, which this does not do.

**Comment by lukaszgryglicki** [comment]
OK will do and eventually start working on #206 and #207 tomorrow.

**Comment by lukaszgryglicki** [comment]
Done on [K8s](https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1), other projects pending.

**Comment by lukaszgryglicki** [comment]
Other projects finished too, for example [KubeVirt](https://kubevirt.teststats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1).

**Comment by dims** [comment]
@lukaszgryglicki Could we please add a Country Drop Down list? (next to the Companies)

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed.
