### ISSUE TITLE
CI?

### ISSUE THREAD

**Issue by mattfarina** [cncf/devstats.archive#21]
Would it be possible to use Travis CI or CircleCI to get automated testing?

I note this because I'm willing to help set that up if there's interest.

**Comment by lukaszgryglicki** [comment]
It is using Travis CI already.
And automatic deploys on "production" branch via custom Travis webhook handler.
See:
https://github.com/cncf/devstats/blob/master/CONTINUOUS_DEPLOYMENT.md
https://github.com/cncf/devstats/blob/master/.travis.yml
https://github.com/cncf/devstats/blob/master/cmd/webhook/webhook.go
https://github.com/cncf/devstats/blob/master/crontab.entry

**Comment by mattfarina** [comment]
@lukaszgryglicki sorry about that. When I submitted a PR it didn't display anything. I've noticed this is sometimes happening on GitHub lately.

**Comment by lukaszgryglicki** [comment]
No problem
