### ISSUE TITLE
[bug] Data missing for monthly rollups 

### ISSUE THREAD

**Issue by mfdii** [cncf/devstats.archive#210]
For some of [the Falco graphs](https://falco.devstats.cncf.io/d/24/prs-merged-repository-groups?orgId=1&from=now-1y&to=now&var-period=m&var-repogroups=All), monthly roll up data appears to be missing.

**How to recreate:**

1. Visit https://falco.devstats.cncf.io/d/24/prs-merged-repository-groups?orgId=1
2. Set the time period to `1 year`
3. Set the period to `Monthly`
4. Monthly data is missing for Dec 18, Jan 19, Feb 19. It is also incomplete for Nov 18.

I haven't looked at every project, but I saw the same months missing for [the OPA project](https://opa.devstats.cncf.io/d/24/prs-merged-repository-groups?orgId=1&from=now-1y&to=now&var-period=m&var-repogroups=All).

**Comment by lukaszgryglicki** [comment]
Thanks for reporting, I'll check this.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Fixed, also detected permission denied issue for `gha_vars` table for OPA - added script that ensures that read-only user has permissions to all tables that are needed.
