### ISSUE TITLE
[bug] Data missing from "developer activity counts by repository group"

### ISSUE THREAD

**Issue by liggitt** [cncf/devstats.archive#211]
The quarter, year, and decade views display "No data to show"

The day view currently only shows a single contributor, though many were active

https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All

**Comment by lukaszgryglicki** [comment]
I'll take a look, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
I can't replicate, maybe you have hit the time-frame when I was rebuilding data. I've scheduled such update during the last weekend.

**Comment by dankohn** [comment]
We have a goal of improving our processes so that we can rebuild data nightly (or so) without causing downtime.
