### ISSUE TITLE
[feature request] OpenTelemetry: finding active contributors with emails when possible

### ISSUE THREAD

**Issue by SergeyKanzhelev** [cncf/devstats.archive#212]
For the upcoming election in OpenTelemetry we need to get a list of OpenTelemetry active contributors.

We defined active contributors in the [document](https://github.com/open-telemetry/community/blob/master/governance-charter.md) as following:

> Standing in the OpenTelemetry community will be defined by the union of:
> 
> Active members - those with 20 contributions (PRs, Issues, Comments etc.) in the prior rolling year.
> All approvers, and maintainers in the OpenTelemetry organization

Since it's a first time we are doing it, it will also be great to get a full list of people ever contributed - writing comment, sending PR or reporting an issue. So we will understand the %% of active contributors.

For the active contributors, when possible we want to get the list of emails associated with the GitHub handle.

We consider contribution to any of [opentelemetry org](https://github.com/open-telemetry) repository as eligible contribution.

/cc: @lukaszgryglicki @caniszczyk 
/cc: @bhs, @bogdandrutu, @sarahnovotny, @yurishkuro

**Comment by lukaszgryglicki** [comment]
Your contributor definition is non-standard. I can pull that data for you tomorrow, but there is no such dashboard defined. I will just run custom SQL for this.

**Comment by SergeyKanzhelev** [comment]
Thank you!

@lukaszgryglicki what's the standard contributor definition? Is it code-contributions only?

**Comment by lukaszgryglicki** [comment]
Standard contributor is someone who did at least one of the following (you can see this in any dashboard showing contributions/contributors - it's in the dashboard documentation on the bottom of the page):
- Made a PR
- Created an issue
- Did a commit
- Commented on a PR/issue/commit

**Comment by SergeyKanzhelev** [comment]
This is exactly what we need for the overall number of contributors. On top of it we have set a bar of 20 contributions to define an "active" contributors in the past year. So stale or occasional contributors will not receive unwanted link to vote unless they will explicitly register themselves.

Thank you again for your help!

**Comment by lukaszgryglicki** [comment]
I'll provide data for you tomorrow, you will have a CSV file with the list of contributors with their emails and number of contributions - sorted by the number of contributions (all time). Another file will have the same, but only for the last year.

**Comment by lukaszgryglicki** [comment]
cc @dankohn - not sure if I can paste CSV file with email addresses here?

**Comment by dankohn** [comment]
No, please don't. Instead, please email cncf-opentelemetry-maintainers@lists.cncf.io

**Comment by lukaszgryglicki** [comment]
Email sent, data generated via:
```
PG_DB=opentelemetry GHA2DB_CSVOUT=opentelemetry_all_contributors.csv ./sh/run.sh contributors_data 2010-01-01 2020-01-01 {{top_n}} 1
PG_DB=opentelemetry GHA2DB_CSVOUT=opentelemetry_20180923_20190924_contributors_with_20.csv ./sh/run.sh contributors_data 2018-09-23 2019-09-24 {{top_n}} 20
```

**Comment by lukaszgryglicki** [comment]
Closing this, please let me know if you need to reopen.

**Comment by SergeyKanzhelev** [comment]
Thank you @lukaszgryglicki ! 

In the generated files there are sometimes multiple e-mails for a member. Is there a way to find out which one of these e-mails is more active? Perhaps, which one was associated with Linux Foundation CLA?

**Comment by SergeyKanzhelev** [comment]
Also, can this script mark people who are part of OpenTelemetry project and who is not? Mostly out of curiosity and so we can customize an e-mail to non-member voters

**Comment by lukaszgryglicki** [comment]
All I did was removing all addresses ending with `@users.noreply.github.com`.
Many users have multiple emails used for the same GitHub account. Git allows you to put any email address when committing and only on `git push` you need to authenticate to GitHub by login/password/oauth etc. Many users changed their email without changing GitHub ID. For many contributors who didn't commit at all - we only have their GitHub id (like for people who only commented etc.). We only have git-GitHub connection on commits.

I cannot tell you which email addresses are more popular, I'm collecting list of emails per GitHub login, and emails only come from commits, contributions are also PRs, issues, comments which come without email - so I basically cannot sort email by their popularity.

Even single commit can have different commit author and different person who pushed that commit, or for merge commits somebody else can create merging commit from many other people's commits and finally someone else (even bot) can push that to the repo.

I have no info who is associated with LF CLA at all.

Mark people who are part of OpenTelemetry?
I don't understand - all those contributors are from open telemetry project (I've used `open telemetry` database to generate this data) - I'm tracking all repos user `open-telemetry` org.

**Comment by SergeyKanzhelev** [comment]
My understanding that LF CLA check validates e-mails on commits and check if they are registered. @caniszczyk do you know if this information available anywhere? I would think that LF CLA e-mail should be more safe to send e-mail to if we have a choice of multiple e-mails.

For the people in OpenTelemetry - my understanding is that there are contributions by people who have not joined the org: https://github.com/orgs/open-telemetry/people So I wonder if there is a way to mark people in the org vs. outside the org in that list.

**Comment by lukaszgryglicki** [comment]
So I don't have CLA info, and for https://github.com/orgs/open-telemetry/people you have list of GitHub IDs, you just need to filter my CSV and check if every contributor is on that list or not. I don't have that list anywhere in the open telemetry DevStats database.

**Comment by SergeyKanzhelev** [comment]
thank you for checking!
