### ISSUE TITLE
teststats.cncf.io is down

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#213]
teststats.cncf.io is down

**Comment by lukaszgryglicki** [comment]
Working on this - 16 hours already.

**Comment by gmile** [comment]
FWIW https://devstats.cncf.io is down as well

**Comment by lukaszgryglicki** [comment]
Working on this, didn't sleep this night.

**Comment by gmile** [comment]
@lukaszgryglicki do you need any help?

**Comment by lukaszgryglicki** [comment]
No, I'm reprovisioning the cluster and struggling with SSL/nginx-ingress right now.

**Comment by gmile** [comment]
@lukaszgryglicki I see. Hope it won't take too much of your time! If you need any help, even if to vent off some steam over a call or chat – let me know.

**Comment by lukaszgryglicki** [comment]
Hopefully, all will be fixed today. I'm working on fixing cluster after failed update to `v1.16` - 2 days already without even sleeping.

**Comment by gmile** [comment]
@lukaszgryglicki were you able to have some sleep after all? How's `SSL/nginx-ingress` investigation going?

Again, not that devstats is causing me any trouble. Just wanted to see if there's anything I could help you.

**Comment by lukaszgryglicki** [comment]
All was fixed long time ago, just forgot to close this.
