### ISSUE TITLE
[bug] index w/ same score is reverse

### ISSUE THREAD

**Issue by atoato88** [cncf/devstats.archive#218]
When I access to [Companies table](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.16.0%20-%20now&var-metric=contributions), I get table in which index order of same score companies is reverse.

Example screenshot following.
![screenshot-k8s devstats cncf io-2019 10 11-08_36_53](https://user-images.githubusercontent.com/748740/66614599-9d06be80-ec04-11e9-80cc-5b39cb7a3ae7.png)

It should be 10 -> 11 -> 11, not 10 -> 12 -> 11.
Same with between 15 and 16.

This isn't a critlal one. but I will be happy if you fix ASAP.

**Comment by dankohn** [comment]
We need to push back on your kind of linear thinking. Who is to say what order ordinal numbers should be in.

(jk)

**Comment by atoato88** [comment]
@dankohn 
Thank you for comment.
I've updated issue message about ordinal numbers.

**Comment by lukaszgryglicki** [comment]
not sure what to do, those rows have the same number of contributions, so their order is not defined and if I click your link I see order number increasing in all records, so I can't replicate.

**Comment by atoato88** [comment]
@lukaszgryglicki 
Sorry for my poor explanation..
I have 2 suggestions.

First one is following. (just example against  screenshot above)
```
...
...
10  Meituan-Dianping  257
11  CNCF  213
11  Intel  213
13  Amazon  196
14  Target  187
15  TACC  176
15  Pivotal  176
17  BoCloud  171
...
...
```
I don't care about the order between CNCF and Intel. (same with TACC and Pivotal)
But the logic maybe complicate for implementation...

Second suggestion is following. (just example against screenshot above)
```
...
...
10  Meituan-Dianping  257
11  Intel  213
12  CNCF  213
13  Amazon  196
14  Target  187
15  Pivotal  176
16  TACC  176
17  BoCloud  171
...
...
```
In this suggestion, ordinal number is same with screenshot above.
It is just sort companies by ordinal number.

IMHO, It is confusing that `Rank` isn't sorted by ordinal number. (e.g. 10 -> 12 -> 11)

**Comment by lukaszgryglicki** [comment]
The problem here is that order comes from Grafana UI (which only sorts by single column) and rank comes from`rownumber()` Postgres call which internally orders by the number of contributions desc, so this may require some clever tricks, I'll try to find some solution for that.

**Comment by lukaszgryglicki** [comment]
Fixed, just changed the Rank type from `string` (which allowed an empty value for `All`) to `number` (so all have rank 0), then specified that Rank 0 should be hidden in dashboards options. So now default sort is by Rank. Fixed in all projects on both `test` and `prod` envs.

**Comment by atoato88** [comment]
Thanks to fix!
I'm really appreciate to this.
