### ISSUE TITLE
[feature request] Longhorn dashboard

### ISSUE THREAD

**Issue by amye** [cncf/devstats.archive#219]
We have a new sandbox project, Longhorn! 
https://github.com/longhorn/longhorn

**Comment by lukaszgryglicki** [comment]
OK, will add DevStats pages on Monday/Tuesday.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Added on the headless server, adding on the test server now. I also want to test new functionality to merge just added `Longhorn` into `All CNCF` automatically and regenerate `All CNCF` dashboards via single `helm install` call, I'm testing this, if all is fine will do the same on prod tomorrow. In any case, DevStats pages for Longhorn will be ready tomorrow.

**Comment by lukaszgryglicki** [comment]
Test page deployed (I will have to take a look at all dashboards to eventually adjust date ranges and default selections): https://longhorn.teststats.cncf.io, will continue tomorrow.

**Comment by lukaszgryglicki** [comment]
Adjusted dashboards, test site ready.

**Comment by lukaszgryglicki** [comment]
Prod page [added](https://longhorn.devstats.cncf.io/d/8/dashboards), also updated [first](https://all.teststats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Longhorn) and [second](https://all.teststats.cncf.io/d/53/projects-health-table?orgId=1) project health table sin `All CNCF` project.
Please note missing `Longhorn` artwork, I'll update once I have it.
cc @amye
