### ISSUE TITLE
Missing Company

### ISSUE THREAD

**Issue by mattfarina** [cncf/devstats.archive#22]
It appears as though Samsung is missing from the company listings. For example, from the company velocity page:
![screen shot 2017-11-20 at 12 01 30 pm](https://user-images.githubusercontent.com/62991/33030940-b18819a6-cdea-11e7-8713-167229b0eb47.png)

Yet, Samsung is listed as a company for the velocity metrics. See (under the values):
https://github.com/cncf/devstats/blob/5a08b45d33f4723e2746da45508586291c99481d/metrics/kubernetes/gaps.yaml#L110-L117

Not yet sure what's going on but wanted to report the bug.

**Comment by lukaszgryglicki** [comment]
Seems like they're not in Top 26 companies (Grafana names series from a to z) but of course I'll double check tomorrow.

**Comment by mattfarina** [comment]
@lukaszgryglicki Several of the companies listed have 0 contributions while I know that Samsung has had contributions even if no one else other than me is included.

**Comment by lukaszgryglicki** [comment]
Sure, must be a bug, will fix.

**Comment by lukaszgryglicki** [comment]
I'm back, but I'll first merge all affiliation related tasks on cncf/velocity and cncf/gitdm and then I'll return to this.

**Comment by lukaszgryglicki** [comment]
It was displaying top companies active recently, by counting all GitHub events. I see the problem, I'll change to Top N companies active during last 3 years by number of authors first and then by number of specific contributions (like commits, PRs, issues, reviews etc) - Samsung is in the top 25 then (it is about 21st - without reimporting new affiliations yet).
I need to finish HP/HPE cases first, regenerate cncf/gitdm data, then import it to cncf/devstats, regenerate data, update tags SQLs cron jobs etc. I'll put the final update here once finished.

**Comment by lukaszgryglicki** [comment]
OK, companies tags regenerated, it is live on test and new prod sites:
https://k8s.cncftest.io/dashboard/db/companies-stats?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/companies-stats?orgId=1

![screen shot 2017-11-21 at 15 15 39](https://user-images.githubusercontent.com/2469783/33077054-f7eaf654-cece-11e7-84c3-e6069b6203ec.png)
![screen shot 2017-11-21 at 15 16 27](https://user-images.githubusercontent.com/2469783/33077055-f807cd6a-cece-11e7-8cd3-85f9612eb37a.png)

Can't put it on devstats.k8s.now - it requires small downtime that I want to avoid, I'll put this on 
 devstats.k8s.io about 5AM UTC tomorrow.

**Comment by mattfarina** [comment]
@lukaszgryglicki thanks for the update. Now I have an idea what was going on.

**Comment by lukaszgryglicki** [comment]
Regenerated data now on production site: devstats.k8s.io:
https://devstats.k8s.io/dashboard/db/companies-stats?orgId=1
Closing this issue.
Please reopen if You see any problems.
