### ISSUE TITLE
[bug] Use new Jenkins X logo

### ISSUE THREAD

**Issue by MarckK** [cncf/devstats.archive#220]
Could we please replace the old Jenkins X logo (currently showing: https://jenkinsx.devstats.cd.foundation) with the new Jenkins X logo: https://github.com/cdfoundation/artwork/tree/master/jenkinsx/icon/color

**Comment by lukaszgryglicki** [comment]
Done:
![Screenshot 2019-10-21 at 09 06 49](https://user-images.githubusercontent.com/2469783/67183855-b963e180-f3e2-11e9-8002-91ee41170357.png)
![Screenshot 2019-10-21 at 09 10 57](https://user-images.githubusercontent.com/2469783/67183856-b963e180-f3e2-11e9-880c-929109d7796d.png)

**Comment by MarckK** [comment]
Awesome! Thank you, @lukaszgryglicki!
