### ISSUE TITLE
[bug] unable to fetch cncf database from backup

### ISSUE THREAD

**Issue by jiangkaihua** [cncf/devstats.archive#221]
I followed the [https://github.com/cncf/devstats/blob/master/INSTALL_UBUNTU18.md](url) to deploy devstats in Ubuntu18, and got stuck in `Automatic deploy of first database`. The log were as follows:

![image](https://user-images.githubusercontent.com/54176503/67662461-6ff53280-f99e-11e9-9a26-d95f08da78d3.png)

Then I checked the error code, which finally referred to
 `wget "https://teststats.cncf.io/$PROJDB.dump" || exit 9`,
in line 53 of [https://github.com/cncf/devstats/blob/master/devel/create_databases.sh](url), the .dump file could not be fetched.

So is there anything wrong with my network, or the .dump file is missed?

**Comment by lukaszgryglicki** [comment]
Actually, You don't need any database dumps unless you want to deploy all CNCF projects which is probably not something you want to do. Please fork, edit scripts and deploy projects you want to track.

**Comment by jiangkaihua** [comment]
> Actually, You don't need any database dumps unless you want to deploy all CNCF projects which is probably not something you want to do. Please fork, edit scripts and deploy projects you want to track.

So I can just modify the environment variables such as `ONLY=myProject` and so on, and follow the [https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md](url) file to track my own project that doesn't belong to cncf ?

**Comment by lukaszgryglicki** [comment]
Yes.

**Comment by jiangkaihua** [comment]
> Yes.

Thank you for your response. I'll try it : )

**Comment by lukaszgryglicki** [comment]
Closing this, please let me know if you need to reopen.
