### ISSUE TITLE
[feature request]Please add in additional Jenkins X repos

### ISSUE THREAD

**Issue by tracymiranda** [cncf/devstats.archive#223]
There are a few additional Jenkins X repos to include for Jenkins X stats, namely:
https://github.com/jenkins-x-quickstarts
https://github.com/jenkins-x-charts
https://github.com/jenkins-x-apps
https://github.com/jenkins-x-buildpacks

Could we please include these to the existing stats. 
We can start tracking from now (unless regenerating historical data is relatively painless)

**Comment by lukaszgryglicki** [comment]
Those are `orgs` not `repos`, please confirm that you want to track all those `orgs` (which means all their current/past and future `repos`).

**Comment by lukaszgryglicki** [comment]
Assuming you just want to track 4 new repos, working on this.

**Comment by lukaszgryglicki** [comment]
Done, including past history: https://jenkinsx.devstats.cd.foundation.
