### ISSUE TITLE
Failed to create relation "trepo_groups".

### ISSUE THREAD

**Issue by jiangkaihua** [cncf/devstats.archive#224]
I tried devstats on Ubuntu18.04 in a docker container, and succeeded to deploy and display CNCF programs on my server. But when I referred to my project, I got trouble in pq relations. I succeeded to sync my project to local postgresql database, then `gha2db_sync: select "repo_group_name" from "trepo_groups"` threw an error `Error: 'pq: relation "trepo_groups" does not exist'`. The logs are as follows:
![image](https://user-images.githubusercontent.com/54176503/68823323-640fad00-06ce-11ea-9a22-34a48c15dea0.png)

  Did I miss some steps or misuse arguments? Any comments would be appreciated!

By the way, in line 53 of [https://github.com/cncf/devstats/blob/master/devel/create_databases.sh](url) `wget "https://teststats.cncf.io/$PROJDB.dump" || exit 9`, the right place to get CNCF dumps may be [https://teststats.cncf.io/backups/](url)

**Comment by lukaszgryglicki** [comment]
You have no repo groups defined in any of your repositories. Repo groups are used to group similar repositories into logical groups, if you don't need such definition, you can fall back to defaults script: `scripts/shared/repo_groups.sql`

**Comment by jiangkaihua** [comment]
> You have no repo groups defined in any of your repositories. Repo groups are used to group similar repositories into logical groups, if you don't need such definition, you can fall back to defaults script: `scripts/shared/repo_groups.sql`

Thanks for your reply! 
The question is, I do copy the `repo_groups.sql` from old projects and update it following [ADDING_NEW_PROJECT.md](https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md). The `scripts/volcano/repo_groups.sql` is as follows:
![image](https://user-images.githubusercontent.com/54176503/68837180-fb88f600-06f6-11ea-8b29-a83574fd2960.png)

I added this sql to postgresql database manually using `psql -h localhost -U postgres -f scripts/volcano/repo_groups.sql`, and the psql throwed error `relation "gha_repos" does not exist`. Where can I attach this repo?

**Comment by lukaszgryglicki** [comment]
You need to follow the workflow from `ADDING_NEW_PROJECTS.md`.

**Comment by jiangkaihua** [comment]
> You need to follow the workflow from `ADDING_NEW_PROJECTS.md`.

I've repeated the guide of [ADDING_NEW_PROJECT.md](https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md) for several time but the error still exists. Could you please tell me which `.sh` file create the relations? Thank you!

By the way, there may be something wrong with server [devstats](https://devstats.cncf.io/) and [teststats](https://teststats.cncf.io/), I got `504 Gateway Time-out` today.

**Comment by lukaszgryglicki** [comment]
Will do but I'm now on KubeCon and then on the vacation, fixed server issues and regarding your question: see any projects `psql.sh` script, for example `envoy/psql.sh`: it calls
```
GHA2DB_PROJECT=envoy PG_DB=envoy ./shared/setup_repo_groups.sh 2>>errors.txt | tee -a run.log || exit 4
```
See `shared/setup_repo_groups.sh` and then `scripts/shared/repo_groups.sql`.

**Comment by jiangkaihua** [comment]
> Will do but I'm now on KubeCon and then on the vacation, fixed server issues and regarding your question: see any projects `psql.sh` script, for example `envoy/psql.sh`: it calls
> 
> ```
> GHA2DB_PROJECT=envoy PG_DB=envoy ./shared/setup_repo_groups.sh 2>>errors.txt | tee -a run.log || exit 4
> ```
> 
> See `shared/setup_repo_groups.sh` and then `scripts/shared/repo_groups.sql`.

Thanks for your suggestions! I'll try it myself. 
Enjoy your vacation! : )
