### ISSUE TITLE
[feature request] - Add `jenkins-zh` and `stapler` GitHub organizations to CDF/Jenkins

### ISSUE THREAD

**Issue by oleg-nenashev** [cncf/devstats.archive#225]
Currently there are 2 GitHub organizations for which the devstats are recorded: `jenkinsci` and `jenkins-infra`. It would be great to also add `jenkins-zh` and `stapler` which are also a part of the Jenkins project at the moment.

CC @LinuxSuRen @tracymiranda

**Comment by LinuxSuRen** [comment]
Hi, @oleg-nenashev . Thanks to you take the initiative action.

Put all related projects into one organization is a good practice. I'm on it. The only thing that I'm not very sure is about the quality. I did some research work, for example, the [mirror of Jenkins Update Center](https://github.com/jenkins-zh?utf8=%E2%9C%93&q=mirror&type=&language=). I don't know if it could be the official infra.

Another thing is that some projects which are only related to specific language users. Should we just keep it in another organization, or put all things into one.

Please don't hesitate to leave your comments.

**Comment by donhui** [comment]
I think it will be very useful to view some statistics.
https://jenkins.devstats.cd.foundation/

**Comment by LinuxSuRen** [comment]
It seems I have some misunderstanding. Part of my ideas beyond this scope of current discussion.

**Comment by oleg-nenashev** [comment]
@LinuxSuRen yes, I think it is a separate discussion.

**Comment by LinuxSuRen** [comment]
Put jenkins-zh and stapler here +1 from me.

**Comment by lukaszgryglicki** [comment]
Will do but I'm now on KubeCon and then on the vacation. I'll work on this in December.

**Comment by lukaszgryglicki** [comment]
Orgs added. Closing.

**Comment by oleg-nenashev** [comment]
Thanks a lot!
