### ISSUE TITLE
[bug]the portal of devstats have no data

### ISSUE THREAD

**Issue by timyinshi** [cncf/devstats.archive#226]
when i use url "https://all.devstats.cncf.io/d/5/companies-table?orgId=1",i have no data

![image](https://user-images.githubusercontent.com/35130894/71162459-39dd7c00-2286-11ea-8863-23e076e83063.png)

the error is :
![image](https://user-images.githubusercontent.com/35130894/71162498-4e217900-2286-11ea-9f81-b01ea945ca06.png)

please fix the bug.

**Comment by lukaszgryglicki** [comment]
Will fix that, this is because data is being regenerated due to new projects added. I'll let you know when it's done.

**Comment by lukaszgryglicki** [comment]
For now you can use the alternate link: https://all.teststats.cncf.io/d/5/companies-table

**Comment by lukaszgryglicki** [comment]
Fixed, closing.
