### ISSUE TITLE
[Feature Request] Add dashboard with summed stars, forks for all repos for a project

### ISSUE THREAD

**Issue by gcolliso** [cncf/devstats.archive#227]
As we have 70 public repos, it would be nice to have a dashboard where we can sum the total number of stars (forks, or issues) for the entire organization for a given period of time.

Specific example: NATS would like to use total organization (nats-io) star count for all repos to determine progress in GitHub from 2018 - 2019. 

Currently, we would need to look up each repo individually to compute the total star count.

**Comment by lukaszgryglicki** [comment]
Thanks, I'll implement that probably next week.

**Comment by lukaszgryglicki** [comment]
Implemented as a 2nd-panel showing "Community stats combined", for example here:
https://nats.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1

Details:
This aggregates forks, stars and open issues/PRs for all repos from the project. Each point in time aggregates the most up-to-date stars, forks, open issues/PRs value for a given repo in given moment in time (so it takes last known value of forks, stars, open issues/PRs for given repo at a given point in time). Note that most up-to-date value for given repo doesn't mean maximum from that time and the past, all of those values can go down, so assuming repo is "R" and date is "DT", current stars value will be stars count at "DT" or the most recent value for stars from the past.

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed.

**Comment by gcolliso** [comment]
Thanks for the prompt implementation!

Just confirming this is for public repos only correct?

-g

*Ging**er Collison* | NATS Community & Ecosystem
ginger@synadia.com
www.nats.io

Maintained by the good people of Synadia Communications, Inc.

**Comment by lukaszgryglicki** [comment]
Yes, GitHub archives doesn't contain private repos data.

**Comment by gcolliso** [comment]
Thanks - one more question for you.

The nats-io organization changed many of our repo names last year, e.g.
gnatsd -> nats-server. I see both listed in the dropdown which is fine, but
while I used to see the data stop on the old repo name on the date we
changed, I now see a line of data. Does the aggregate count the repo twice?

[image: image.png]

[image: image.png]

**Comment by lukaszgryglicki** [comment]
It may be the case, but I'm a bit busy to check that, I'll do follow up on this case when I have some time. Thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Yes, it can double count repo if repo changed its name. To solve that I need to move complex calculations out of Grafana into calc_metric part, so that will be complex and will calculate per repo data and overall sums separately. I'll definitely do that but next week the fastest, sorry :(.

**Comment by gcolliso** [comment]
Thank you for your attention - it's much appreciated. Just keep me posted
if you could.

Thanks!

*Ging**er Collison* | NATS Community & Ecosystem
ginger@synadia.com
www.nats.io

Maintained by the good people of Synadia Communications, Inc.

**Comment by lukaszgryglicki** [comment]
Implemented, now there are two panels in this dashboard. First is for a specified repo selected from the drop-down, 2nd is for summary across all repos.
https://nats.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1

**Comment by gcolliso** [comment]
This is awesome!! Thanks so much!
