### ISSUE TITLE
Adjust pagination

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#23]
20 results per page doesn't make a lot of sense, especially compared to the amount of data loaded in a typical graph. I would suggest paginating to 1000 rows per page or more, to facilitate on-page search (i.e., finding your company).

https://devstats.k8s.io/dashboard/db/prs-authors-companies-histogram?orgId=1&var-period=y&var-repogroup_name=All&var-repogroup=all

**Comment by lukaszgryglicki** [comment]
Added to my TODO list.

**Comment by lukaszgryglicki** [comment]
Fixed by https://github.com/cncf/devstats/commit/d268e108997c100ea10496da5c892cd0f4274c11
Updated test, old prod and new prod servers.
This is for k8s.
I'll update the remaining projects too.

**Comment by lukaszgryglicki** [comment]
Remaining Projects handled here: https://github.com/cncf/devstats/commit/ddea75e227f203fbe35b1699e1e30e69081562a4
Updated test, old prod and new prod servers.
