### ISSUE TITLE
[feature request] - Add option to exclude bots in the "New PRs" dashboard

### ISSUE THREAD

**Issue by oleg-nenashev** [cncf/devstats.archive#230]
https://github.com/cncf/devstats/blob/master/metrics/shared/new_prs.sql does not filter out bots at the moment. It generates nice trendy stats for communities which start adopting bots, but it would be great to have an option to get bots ignored.

Our graph:

![image](https://user-images.githubusercontent.com/3000480/72799791-46b70c00-3c46-11ea-9a1b-683935414113.png)

**Comment by lukaszgryglicki** [comment]
This chart count PRs, you want to skip PRs that were created by bots or skip bot activity on PRs?

**Comment by oleg-nenashev** [comment]
Yes, skipping bot activity like other queries do

**Comment by lukaszgryglicki** [comment]
The problem is that this particular dashboard is not counting "activity" or "comments" so skipping bots would make those numbers substantially lower. It counts distinct PRs created in specified periods. Skipping bots here means that we want to skip any PRs that were created by bots, which don't happen often. I'll implement this anyway but don't expect big changes due to that.

**Comment by oleg-nenashev** [comment]
With Dependabot & Co bot-created PRs become quite common, and this is one if the reasons for such quick growth in the chart I provided

**Comment by lukaszgryglicki** [comment]
OK, no problem. Can you tell me which project uses this very often? I'll also double-check my bots lists to be sure to exclude them, or maybe you can provide 3-4 most important bot's GitHub logins, so I can check if they're excluded?

**Comment by oleg-nenashev** [comment]
@lukaszgryglicki bots lile dependabot are excluded from the most of the stats dashboards, the current filters address it well. This particular dashboard just does not apply filters from what I have seen in SQL

I will provide a list of bots later today when I get to the laptop

**Comment by lukaszgryglicki** [comment]
OK, if they're already excluded from other dashboards then I'm all set, I'll let you know when this is implemented and data is regenerated. Thanks.

**Comment by oleg-nenashev** [comment]
Thanks! Ideally it would be great to have 2 metrics: with and without bots.

**Comment by lukaszgryglicki** [comment]
So now I've implemented without, to create a version that also counts with I need to update Grafana dashboards as well.

**Comment by lukaszgryglicki** [comment]
OK, implemented displaying values with and without bots, example [here](https://all.devstats.cncf.io/d/15/new-prs-in-repository-groups?orgId=1&from=now-2y&to=1577833199000&var-period=q&var-repogroup_name=All).
