### ISSUE TITLE
[feature request] Create dashboard that shows repo -> repo group mappings

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#235]
Following up on https://github.com/kubernetes/community/issues/3305
We would like to operationalize the auditing of repo -> repo group mappings. Having a dashboard that lists which repos belong to which repo groups would enable that without having to ping a CNCF staff member for a dump directly.

**Comment by lukaszgryglicki** [comment]
Great idea, will implement tomorrow.

**Comment by lukaszgryglicki** [comment]
Created new dashboard "Repository groups" under "Other folder" [here](https://k8s.devstats.cncf.io/d/12/dashboards) (see new dashboard under "Other" folder): [Repository groups](https://k8s.devstats.cncf.io/d/68/repository-groups).
The default selection is to display repositories that are assigned to the "Other" repository group and those without repository group assigned "Not specified" (null or empty - there are no such repositories, but this will eventually list such if there are some).
You can select any set of Repository groups from drop-down or select "All" to display everything.

**Comment by lukaszgryglicki** [comment]
You can now see repository/repository groups configuration using [new DevStats REST API](https://devstats.cncf.io/api/v1) (described [here](https://github.com/cncf/devstatscode#api)).

Example call to get that configuration for kubernetes and filter to show only repositories falling back to `Other` repository group: 
- `curl -H "Content-Type: application/json" https://teststats.cncf.io/api/v1 -d'{"api":"Repos","payload":{"project":"kubernetes", "repository_group":["Other"]}}' 2>/dev/null | jq`:
```
{
  "project": "kubernetes",
  "db_name": "gha",
  "repo_groups": [
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other",
    "Other"
  ],
  "repos": [
    "kubernetes/application-images",
    "kubernetes/common",
    "kubernetes-csi/external-health-monitor",
    "kubernetes/demos-and-tutorials",
    "kubernetes-graveyard/kube-mesos-framework",
    "kubernetes-incubator/application-images",
    "kubernetes-incubator/auger",
    "kubernetes-incubator/kube2consul",
    "kubernetes-incubator/kube-mesos-framework",
    "kubernetes-incubator-retired/kubedash",
    "kubernetes/kube2consul",
    "kubernetes/kubedash",
    "kubernetes-retired/application-images",
    "kubernetes-retired/community",
    "kubernetes-retired/contrib",
    "kubernetes-retired/kubedash",
    "kubernetes-retired/kube-mesos-framework",
    "kubernetes-sigs/auger",
    "kubernetes-sigs/foo",
    "kubernetes-sigs/go-open-service-broker-client",
    "kubernetes-sigs/secrets-store-csi-driver",
    "kubernetes-sig-testing/frameworks"
  ]
}
```
