### ISSUE TITLE
[feature request] [cdf devstats] Ability to see 15 or more contributions

### ISSUE THREAD

**Issue by bobcatfish** [cncf/devstats.archive#237]
In [Tekton](https://github.com/tektoncd) we have just kicked off our governing board election, and we've based our process on [the kubernetes election process](https://github.com/kubernetes/steering/blob/master/elections.md) but while kubernetes requires 20+ contributions to be eligible, we want to require 15+.

[This dashboard](https://tekton.devstats.cd.foundation/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All&var-country_name=All) shows user contributions, and the data (I think!) comes from [this query](https://github.com/cncf/devstats/blob/master/metrics/shared/project_developer_stats.sql) which [seems to be hardcoded](https://github.com/cncf/devstats/blob/7f0f99f9c7c4d1424a97cf65e4535f65cdadc51a/metrics/shared/project_developer_stats.sql#L996) to 20+.

We'd love to be able to change this dashboard at https://devstats.cd.foundation/ for tekton to show 15+ contributions instead of 20+ (even better would be if this was configurable, but no worries if it isn't reasonable).

Thanks!

@vdemeester @abayer @dlorenc

**Comment by lukaszgryglicki** [comment]
Workign on this.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by bobcatfish** [comment]
Looks great, thanks @lukaszgryglicki !! ❤️
