### ISSUE TITLE
Main Repo update for NATS

### ISSUE THREAD

**Issue by gcolliso** [cncf/devstats.archive#239]
While diving into DevStats for graduation due diligence, we noticed that our main repo is still listed as `nats-io/gnatsd` which is the previous repo name. It was renamed to `nats-io/nats-server` in June 2019. I'm not sure if this will make a difference with our stats. 
[https://github.com/cncf/devstats/blob/488dffe4b9be19587a1d298a203f99a7f2bd56c4/projects.yaml#L255](https://github.com/cncf/devstats/blob/488dffe4b9be19587a1d298a203f99a7f2bd56c4/projects.yaml#L255)
Currently, with the renamed repos, the stats stop on one name then carry on in the next in June 2019. We DO NOT want to lose the stats for the repo prior to the name change.

**Comment by lukaszgryglicki** [comment]
I actually have 4 names for this repo: `gnatsd`, `apcera/gnatsd`, `nats-io/gnatsd` and `nats-io/nats-server`. They all have the same repo ID and reflect name changes in history. This is all OK and only the final name used as "main" is not updated yet to the newest name. I'll change this, this won't affect any stats.

**Comment by lukaszgryglicki** [comment]
Fixed everywhere, closing.

**Comment by gcolliso** [comment]
Thanks!
