### ISSUE TITLE
One company at the bottom

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#24]
On https://devstats.k8s.io/dashboard/db/companies-stats?orgId=1

Sort by avg. Caicloud is still on the bottom, instead of the top.

**Comment by lukaszgryglicki** [comment]
Can't reproduce, if I sort by avg asc, desc or clear sort Caicloud is somewhere in the middle.

**Comment by dankohn** [comment]
<img width="1440" alt="screen shot 2017-11-28 at 8 20 41 am" src="https://user-images.githubusercontent.com/3083270/33322403-3c887b40-d417-11e7-8361-ada20d08bceb.png">

**Comment by lukaszgryglicki** [comment]
Hmm, I'll try to replicate somehow, but currently, I have this:
![screen shot 2017-11-28 at 14 49 34](https://user-images.githubusercontent.com/2469783/33323002-68f0465c-d44b-11e7-8080-960355a4c5aa.png)

**Comment by lukaszgryglicki** [comment]
I was able to reproduce but only in Chrome.
https://github.com/grafana/grafana/issues/9789#issuecomment-347778133
![screen shot 2017-11-29 at 08 41 26](https://user-images.githubusercontent.com/2469783/33363613-6887b34e-d4e1-11e7-8769-7e77f24d7211.png)

I've checked data for gaps (this was the problem last time, but there are no gaps, so all should work just fine) - screenshot of config showing that I'm not changing nulls into 0s.
![screen shot 2017-11-29 at 08 44 49](https://user-images.githubusercontent.com/2469783/33363651-98c96552-d4e1-11e7-9b44-bd328a8e66c8.png)

**Comment by lukaszgryglicki** [comment]
Provided a lot of details on Grafana Issue, hopefully it will be fixed.

**Comment by lukaszgryglicki** [comment]
It is fixed with new Grafana v5 release - installed now on both test & prod.
Closing.
