### ISSUE TITLE
[bug] github.com/buildpack to github.com/buildpacks rename causes devstats to no longer count

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#241]
we renamed our github org from github.com/buildpack to github.com/buildpacks recently, and it made the CNCF devstats page go stale. Could you point https://buildpacks.devstats.cncf.io at the new org? Thanks!

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Fixed, data regenerated.
