### ISSUE TITLE
[kubernetes] data export request

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#243]
We're doing a bit of auditing and clean up and would like to get a data export of the developer activity counts by repository group. Specifically, we would like the reports for each release cycle from 1.10 - 1.18 ([e.g. 1.10 - 1.11](https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=v1.10.0%20-%20v1.11.0&var-metric=contributions&var-repogroup_name=All&var-country_name=All)). 

When viewing them through devstats it looks like  their minimum threshold to report is 10 (They only show developers with > 10 events per cycle). For this report, we would like them for anything > 0. 

All in all it should be 9 different reports.

Thanks!

**Comment by lukaszgryglicki** [comment]
Will work on that tomorrow, thanks.

**Comment by lukaszgryglicki** [comment]
Generated contributions report (lists anybody who contributed in given version range).
- Data file [here](https://devstats.cncf.io/backups/gha_contributions_stats.csv)
- Imported into google sheet [here](https://docs.google.com/spreadsheets/d/1wQMxSHy53ASWOcRljgtAg3KRK0f1EzkxiAUIaqcFJJ8/edit?usp=sharing).
- SQL used for this report [here](https://github.com/cncf/devstats-reports/blob/master/sql/contributions_stats.sql), script [here](https://github.com/cncf/devstats-reports/blob/master/rep/contributions_stats.sh).
