### ISSUE TITLE
[bug] 7K contributors to fluentd?

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#244]
https://fluentd.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=contributors

This seems high given the # of independent contributors.

Any thoughts here @lukaszgryglicki ?

**Comment by lukaszgryglicki** [comment]
I think it's OK, please note that we have added *all* external plugins (see [here](https://github.com/cncf/devstats/blob/master/projects.yaml#L68) and that now Fluentd has [over 4500 repositories](https://fluentd.devstats.cncf.io/d/68/repository-groups?orgId=1) configured:
```
fluentd=# select count(*) from gha_repos;
 count 
-------
  4519
(1 row)
```

**Comment by lukaszgryglicki** [comment]
Closing because this data seems to be fine. Please reopen if needed.
