### ISSUE TITLE
[bug] KubeEdge commits data look not align with github contributions 

### ISSUE THREAD

**Issue by kevin-wangzefeng** [cncf/devstats.archive#245]
### From contributions page on github
https://github.com/kubeedge/kubeedge/graphs/contributors?from=2019-03-30&to=2020-04-13&type=c
![image](https://user-images.githubusercontent.com/6914660/79114190-39c53700-7db5-11ea-9507-8e33f8b773c1.png)

### Commits Repository Groups on devstats
https://kubeedge.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&from=1553875200000&to=1586793599000&var-period=w&var-repogroups=All

![image](https://kubeedge.devstats.cncf.io/render/dashboard-solo/snapshot/8TSkWzkhinv2ojTNe4RrvoKfaqOS15Wz?orgId=1&kiosk&panelId=2&from=1553875200000&to=1586793599000&var-period=w&var-repogroups=All&width=1000&height=500&tz=Asia%2FShanghai)

**Comment by kevin-wangzefeng** [comment]
Any thoughts @lukaszgryglicki ?

**Comment by lukaszgryglicki** [comment]
Contribution != Commit.
Commit is just a commit, while contribution is defined as: commit or comment (commit comment, issue/PR comment) or creating issue or PR or review.
So you are comparing totally different things.

**Comment by lukaszgryglicki** [comment]
Or maybe GitHub chart indeed shows commits as contributions, anyway, cannot check this now, it's a holiday, I'll take a look tomorrow or any other day, but do you miss any commits?

**Comment by kevin-wangzefeng** [comment]
"Contributions" in github here (https://github.com/kubeedge/kubeedge/graphs/contributors?from=2019-03-30&to=2020-04-13&type=c) only means commits I think. Github typically doesn't include comments when counting contributions.

I just checked with git command `git log --no-merges --since "Mar 30 2019" --pretty=oneline |wc -l` under main repo, there were 943 commits (merge commits excluded) checked-in. However from devstats, the number is 404.

**Comment by kevin-wangzefeng** [comment]
Ps. the KubeEdge main repo is https://github.com/kubeedge/kubeedge.git

**Comment by lukaszgryglicki** [comment]
If the main repo is wrong, I can check it. Numbers are quite OK IMHO because:
- DevStats skips all bots commits as defined [here](https://github.com/cncf/devstats/blob/master/util_sql/exclude_bots.sql).

**Comment by lukaszgryglicki** [comment]
But still, we can go down to single commits and count, I can generate an exact list from DevStats if that is a problem.

**Comment by kevin-wangzefeng** [comment]
Both bot commits and merge commits are excluded, still quite different with those shown on devstats.

![image](https://user-images.githubusercontent.com/6914660/79180227-f8c43580-7e3b-11ea-8cdd-f777d3e960be.png)

Full data here: https://docs.google.com/spreadsheets/d/1sEHuUg2yyYOSf887mlFoZWNb6Y1dhk0xRyODxpiKi1M/edit?usp=sharing

**Comment by lukaszgryglicki** [comment]
I see the problem, most commits are made by `kubeedge-bot` while the original author is different, so they're falsely identified as bot commits. I'll fix this and let you know when ready.

**Comment by kevin-wangzefeng** [comment]
Thanks, using author info instead of committer info from git history should help.

**Comment by lukaszgryglicki** [comment]
Fixed, now counting all commits excluding those where both author and somebody who merged that commit is not bot. Values will not be equal to GitHub because DevStats does not exclude merge commits

**Comment by lukaszgryglicki** [comment]
Closing this now, please reopen if needed.
