### ISSUE TITLE
[feature request]: move items to sig-cloud-provider for more accurate K8s/SIG data

### ISSUE THREAD

**Issue by lasomethingsomething** [cncf/devstats.archive#246]
Hello: on behalf of some efforts underway in the K8s ContribEx SIG to understand and measure PR velocity, I'm wondering if we might move to `sig-cloud-provider` some items listed as SIGs on some of the K8s dashboards? The items to move would be: 

These groups, which show up [here](https://k8s.devstats.cncf.io/d/34/pr-workload-per-sig-table?orgId=1):
- azure
- openstack
- aws
- gcp

From [this chart](https://k8s.devstats.cncf.io/d/41/sig-mentions?orgId=1):
- vmware
- ibmcloud

And from [this chart](https://k8s.devstats.cncf.io/d/33/pr-workload-per-sig-chart?orgId=1):
- ibmcloud  
- batchd

**FYI**: This last chart also lists additional entities that are not active SIGs (including one typo), as does [SIG mentions](https://k8s.devstats.cncf.io/d/41/sig-mentions?orgId=1). Let me know if I should provide more details here, or if you'd like to discuss it in a separate issue.

cc'ing @mrbobbytables and @jberkus for visibility.

Thanks!

**Comment by lukaszgryglicki** [comment]
I will take a detailed look tomorrow - those dashboards were not modified for a very long time, but one thing that I remember for sure:
- Some of those dashboards extract SIG from texts (like comments, reviews, issue/PR titles, etc.) from something like `@kubernetes/sig-...`
- Others get SIGs from GitHub labels

That was the original requirement. I don't think we can match data generated based on text analysis with a strict set of labels defined on GitHub.

**Comment by lukaszgryglicki** [comment]
[This](https://github.com/cncf/devstats/commit/e423a9712a8c0a59cd8fa448055f8e48015684d6) would group `azure`, `openstack`, `aws` and `gcp` under `cloud-provider` for the [first](https://k8s.devstats.cncf.io/d/34/pr-workload-per-sig-table?orgId=1) dashboard requested.

I'll do the update only on the test server and will send you links to both `test` and `prod` dashboard version for review. If you like it I'll apply to prod as well - now I'll regenerate test data and let u know.

**Comment by lukaszgryglicki** [comment]
So [here](https://k8s.teststats.cncf.io/d/34/pr-workload-per-sig-table?orgId=1) is a new test dashboard that merges those 4 into `cloud-provider` - let me know if that works for you.

**Comment by lasomethingsomething** [comment]
LGTM, because now all the listed entities are SIGs. Thanks!

**Comment by lukaszgryglicki** [comment]
Ok, continuing on this, will let you know when I implement the next steps.

**Comment by lukaszgryglicki** [comment]
So in GitHub labels I can only see two typos: `cluster-fifecycle` and `rktnetes` (I'm working on the label based charts first), please let me know if you see any other label typo in those results:
```
 api-machinery
 apps
 architecture
 auth
 autoscaling
 aws
 azure
 batchd
 big-data
 cli
 cloud-provider
 cluster-federation
 cluster-fifecycle
 cluster-lifecycle
 cluster-ops
 contrib-ex
 contributor-experience
 docs
 federation
 gcp
 ibmcloud
 instrumentation
 multicluster
 network
 node
 onprem
 openstack
 pm
 release
 rktnetes
 scalability
 scheduling
 service-catalog
 storage
 testing
 ui
 usability
 vmware
 windows
```
Actually, I will merge those `labels` into `cloud-provider` everywhere (maybe I'll detect more), so for example for already fixed chart 1 I will also add `batchd`, `ibmcloud` and `vmware` as `cloud-provider`:
```
      when 'aws' then 'cloud-provider'
      when 'azure' then 'cloud-provider'
      when 'batchd' then 'cloud-provider'
      when 'gcp' then 'cloud-provider'
      when 'ibmcloud' then 'cloud-provider'
      when 'openstack' then 'cloud-provider'
      when 'vmware' then 'cloud-provider'
```

**Comment by lasomethingsomething** [comment]
Hi @lukaszgryglicki -- thanks for your efforts. The bulk of the typos were showing up in the "SIG mentions" dashboard—let me know if you'd like to see those.

**Comment by lukaszgryglicki** [comment]
Made [this commit](https://github.com/cncf/devstats/commit/2c0f7d9714c82d2470eb2bd265822533ed36f09c) and [that commit](https://github.com/cncf/devstats/commit/e2f52e921e52e0d0bc1c5abda1add9121cbdd246) - tested locally and that should generate data needed for this feature. I'll update test server tomorrow and will wait with prod until this is accepted.
This actually changes 3 drop-downs (5 tags) and 6 dashboards:
- PR workload chart
- PR workload table
- SIG mentions
- Issues opened/closed by SIG
- Open issues/PR by milestone and repository
- Issues age by SIG and repository groups

data is *not* regenerated on the test server yet, will be done tomorrow and if all is correct I'll put all links here - so you will have test/prod dashboards to compare.

**Comment by lukaszgryglicki** [comment]
So I'm providing *new* dashboards (implemented on the test server) versus *old* dashboards (current prod server), let me know if all is OK, so I will update prod ones:
- SIG mentions: [new](https://k8s.teststats.cncf.io/d/41/sig-mentions) vs. [old](https://k8s.devstats.cncf.io/d/41/sig-mentions).
- Issues age by SIG and repository group: [new](https://k8s.teststats.cncf.io/d/15/issues-age-by-sig-and-repository-groups) vs. [old](https://k8s.devstats.cncf.io/d/15/issues-age-by-sig-and-repository-groups).
- Issues opened/Closed by SIG: [new](https://k8s.teststats.cncf.io/d/39/issues-opened-closed-by-sig) vs. [old](https://k8s.devstats.cncf.io/d/39/issues-opened-closed-by-sig).
- Open Issues/PRs by milestone and repository: [new](https://k8s.teststats.cncf.io/d/22/open-issues-prs-by-milestone-and-repository) vs. [old](https://k8s.devstats.cncf.io/d/22/open-issues-prs-by-milestone-and-repository).
- PR workflow per SIG chart: [new](https://k8s.teststats.cncf.io/d/33/pr-workload-per-sig-chart) vs. [old](https://k8s.devstats.cncf.io/d/33/pr-workload-per-sig-chart).
- PR workflow per SIG table: [new](https://k8s.teststats.cncf.io/d/34/pr-workload-per-sig-table) vs. [old](https://k8s.devstats.cncf.io/d/34/pr-workload-per-sig-table).

1) Please check `cloud-provider` SIG - in the new version it is merged from 7 SIG-like labels/texts.
2) Please also check all SIG related drop downs in those dashboards(Kind also changed - this is used in sig/kind groups - now kind label only shows when it was used > 30 times over last 2 years - same as with SIG by label or by text).

**Comment by lukaszgryglicki** [comment]
I see no rejections and data is OK (checked after 24 hours running), I'm updating prod as well.

**Comment by lasomethingsomething** [comment]
Thank you, this is great work!

**Comment by lukaszgryglicki** [comment]
OK, prod regenerated too, closing this, but please feel free to reopen if needed.
