### ISSUE TITLE
Affiliation not showing up as expected

### ISSUE THREAD

**Issue by kundan2707** [cncf/devstats.archive#247]
Company Affiliation of github login 'kundan2707' is not reflecting in devstat , shown as none as of now. It should be under NEC .

**Comment by lukaszgryglicki** [comment]
That user is not defined in the [affiliation source](https://github.com/cncf/gitdm#addingupdating-affiliation). Please create a PR against `cncf/gitdm` - once merged it will show up as NEC in DevStats after new affiliations are imported.
