### ISSUE TITLE
Can someone help me understand where devstats gets my employer detail?

### ISSUE THREAD

**Issue by krisnova** [cncf/devstats.archive#249]
Hi!

Can someone help me understand where devstats finds my "company" information. 

I am pretty sure that DevStats currently thinks I work for VMware, but it should now be Sysdig. 

I checked github and my profile there says Sysdig so I am not sure what else I can change on my end to fix this?

**Comment by caniszczyk** [comment]
It's here @kris-nova: https://github.com/cncf/gitdm#addingupdating-affiliation

See this example from Julius who recently updated his info: https://github.com/cncf/gitdm/pull/332

**Comment by krisnova** [comment]
Yay thank you! this is what I was looking for!
