### ISSUE TITLE
What are events?

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#25]
On https://devstats.k8s.io/dashboard/db/project-statistics?orgId=1 you show 3333 events.

Does this mean unique people who have done something on GitHub?

If so, event authors would be clearer. Similarly Commits would be Commit authors.

Can we also show the number of actual commits? Since most commits are done by bots, this does not seem like a good metric.

**Comment by lukaszgryglicki** [comment]
Events mean GitHub events: it can be issue creation, PR, commit, comment, review, watch, fork, etc.

**Comment by dankohn** [comment]
But that's not the number of events. It's the number of event authors, right?

**Comment by lukaszgryglicki** [comment]
No, it is the number of events, for authors values are split:
Committers, Commenters, Issue creators, PR creators, PR reviewers etc.

**Comment by dankohn** [comment]
Kubernetes alone has more than 58,000 commits. So, how could that be
correct? https://github.com/kubernetes/kubernetes

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
You have "API machinery" repo group selected, maybe this is the default value by mistake.
I'll change the default setting to All. If You select "All" there will be more than million events.
![screen shot 2017-11-28 at 14 45 35](https://user-images.githubusercontent.com/2469783/33322835-d9ce6e5e-d44a-11e7-828e-e8a6597a589e.png)
![screen shot 2017-11-28 at 14 45 46](https://user-images.githubusercontent.com/2469783/33322836-d9ecdf2e-d44a-11e7-915a-3a53aceb7aa1.png)

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if you have any other questions.
