### ISSUE TITLE
Issue in README.md

### ISSUE THREAD

**Issue by haardikdharma10** [cncf/devstats.archive#250]
In the **Repository Groups** section, the words "kubernetes psql dump" are linked to an old and outdated link. When clicked, it shows:

<img width="1440" alt="Screenshot 2020-05-17 at 8 59 39 PM" src="https://user-images.githubusercontent.com/53044263/82153368-9f10ba00-9884-11ea-844f-7dacf2207416.png">

I guess it should link to kubernetes/psql.sh ?

**Comment by lukaszgryglicki** [comment]
Fixed via https://github.com/cncf/devstats/commit/fddd5333e11374a71913d0ede37b625661297f34, thanks for reporting.
