### ISSUE TITLE
Missing companies

### ISSUE THREAD

**Issue by roidelapluie** [cncf/devstats.archive#252]
Please add `[feature request]` to the issue title when requesting new features, dashboards, projects etc.
Please add `[bug]` to the issue title when reporting a bug.

hello,

When looking at https://prometheus.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20quarter&var-metric=commenters

I do not see the companies Inuits or Robust Perception. Is that expected? How to add them?
Thanks

**Comment by caniszczyk** [comment]
@roidelapluie you can see this for info: https://github.com/cncf/gitdm#addingupdating-affiliation

My guess is those companies don't have proper dev affiliation data
