### ISSUE TITLE
[bug] Commits Repository Groups not showing data beyond 1 week

### ISSUE THREAD

**Issue by tsandall** [cncf/devstats.archive#253]
I was perusing devstats for OPA and noticed that the Commits Repository Groups dashboard shows no data beyond 1 week:

1 week (works):  https://opa.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=w&var-repogroups=All

Month (or quarter/year/etc. does not work): https://opa.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=m&var-repogroups=All

Am I doing something wrong or is there a bug? I looked at the same dashboard for other projects and the result was the same.

**Comment by lukaszgryglicki** [comment]
You have chosen month aggregation period, but date range (top right selector) is last 30 days, when you aggregate over "month" choose a longer date range, for example, 1 year: See "last 1 year" with "Period: month" aggregation: https://opa.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=m&var-repogroups=All&from=now-1y&to=now

**Comment by lukaszgryglicki** [comment]
Or for example "last 5 years" with "quarter aggregation" https://opa.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&from=now-5y&to=now&var-period=q&var-repogroups=All
In general, an aggregation period must be shorter than date range selector on the date picker.
