### ISSUE TITLE
[kubernetes] data export request

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#254]
Would it be possible to get a data export of the developer activity counts by repository group for the range [v1.18-now](
https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=v1.18.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-country_name=All), but for all contributions > 0?

For reference, this is similar to a previous request in #243

Thanks! :)

**Comment by lukaszgryglicki** [comment]
Will do tomorrow.

**Comment by lukaszgryglicki** [comment]
Generated contributions report (lists anybody who contributed in given version range).
- Data file [here](https://devstats.cncf.io/backups/gha_contributions_stats.csv)
- Imported into google sheet [here](https://docs.google.com/spreadsheets/d/1wQMxSHy53ASWOcRljgtAg3KRK0f1EzkxiAUIaqcFJJ8/edit?usp=sharing). (requested data `v1.18.0 - now` from 51415 row).
- SQL used for this report [here](https://github.com/cncf/devstats-reports/blob/master/sql/contributions_stats.sql), script [here](https://github.com/cncf/devstats-reports/blob/master/rep/contributions_stats.sh).
