### ISSUE TITLE
[feature request] Custom time period

### ISSUE THREAD

**Issue by craigbox** [cncf/devstats.archive#256]
I would like to be able to add a period of my choice, for example "1 Jan 2019 to 1 Jan 2020". I don't seem to be able to do this with a page like [this](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1) for example.

**Comment by lukaszgryglicki** [comment]
Unfortunately, this cannot be done in any easy way. All dashboards are precalculated, so the final data comes from a simple query from a table which contains preprocessed data. I cannot preprocess all possible time ranges, and the only solution for this would be to do full metrics queries on the fly, which is a lot too slow for usage. 

cc @dankohn - the only possible solution would be to create a separate dashboard that does full metric queries based on any arbitrary user data range, but that would be something totally new in DevStats, no dashboard works that way currently.

Or maybe a hybrid solution? Like, when a user uses "custom" range use full metric on the fly, while when a user uses any "predefined" range leave it "as is"

Thoughts?

**Comment by lukaszgryglicki** [comment]
Or maybe add some more predefined periods, like 2-3 periods covering full years and "current year", so it will contain additional ranges: "2018-2019", "2019-2020", and "2020 so far" etc. The same can be defined for quarters, months maybe?
And we can calculate them once because they're in the past (like 2019-2020), so we can treat them as between versions in the past (like v1.17.0 - v1.18.0) - but not like "v1.18.0 - now" which must be calculated always because it contains "now".

**Comment by craigbox** [comment]
If there's no easy path then don't worry; is it documented how to do queries against the data source to generate these kind of tables in a one-off?

**Comment by lukaszgryglicki** [comment]
The dashboard has a documentation panel that lists SQL file - this is the complex metric that is precalculated. The actual select which dashboard does is the precalculated table - you can see panel properties and see the query - everybody has a "read-only editor" role, so everybody can see everything but not edit.

**Comment by craigbox** [comment]
I couldn't immediately see which data source the SQL file needs to be run against.  I assume I could use BigQuery or similar, as it has the GitHub archive?

**Comment by lukaszgryglicki** [comment]
It uses its own Postgres database which is populated from GitHub archives, GitHub APIs, and git (each of those data sources has its own process that fetches data inside DevStats).
maybe you just need a spacial data request - like this exact dashboard but for your own data range.... if so, please give me your data range(s) and I'll generate that data for you and share in some google sheet.

**Comment by craigbox** [comment]
I'll come back to you if we need this.  Thanks!
