### ISSUE TITLE
[Feature Request] Please add knative-sandbox repositories to https://knative.teststats.cncf.io/

### ISSUE THREAD

**Issue by tcnghia** [cncf/devstats.archive#257]
Knative has two sets of repositories in https://github.com/knative/ and https://github.com/knative-sandbox respectively.

Can we please update https://github.com/cncf/devstats/tree/master/knative to include https://github.com/knative-sandbox in https://knative.teststats.cncf.io/ ? 

Thanks

**Comment by lukaszgryglicki** [comment]
Sure, will do.

**Comment by lukaszgryglicki** [comment]
Regenerating all Knative data, including history.

**Comment by lukaszgryglicki** [comment]
Done, all data regenerated. new org added.

**Comment by tcnghia** [comment]
Thanks a lot for the quick turn around!
