### ISSUE TITLE
[feature request] Improve phrasing of "committer" in Overall Project Statistics Table 

### ISSUE THREAD

**Issue by kevin-wangzefeng** [cncf/devstats.archive#258]
The "committer" in Overall Project Statistics Table is actually counting contributors who submitted code, we should give more proper phrasing, e.g. "code contributor" etc.

Ref1: https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc#L28
*A committer is defined as someone with the commit bit; i.e., someone **who can accept contributions** to some or all of the project.*

Ref2: https://en.wikipedia.org/wiki/Committer
*A committer is an individual who is **permitted to modify the source code** of a software project[1][2], that will be used in the project's official releases[3].*

Examples of "Overall Project Statistics Table":
- [Kubernetes devstats](https://k8s.devstats.cncf.io/d/24/overall-project-statistics?orgId=1&var-period_name=Last%20decade&var-repogroup_name=Kubernetes)
- [KubeEdge Devstats](https://kubeedge.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=kubeedge%2Fkubeedge)
- [Volcano Devstats](https://volcano.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=volcano-sh%2Fvolcano)

**Comment by lukaszgryglicki** [comment]
I'll rename to "Code committers" - code contributors may also mean "commit commenters" and reviewers IMHO.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by kevin-wangzefeng** [comment]
Cool, thanks.
