### ISSUE TITLE
[Bug] Missing reviewers on the pr-reviews-by-contributor dashboard

### ISSUE THREAD

**Issue by MrHohn** [cncf/devstats.archive#259]
I was browsing the "PR reviews by contributor dashboard" and was unable to filter on a few existing reviewers including myself (it simply shows no data): https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=All&var-reviewers=MrHohn

I wonder if this is a setup issue, or is this dashboard deprecated and not maintained?

Thanks.

**Comment by lukaszgryglicki** [comment]
We only show some top reviewers, not all of them.
