### ISSUE TITLE
Dashboard item to display open issues and PR for SIGs

### ISSUE THREAD

**Issue by spzala** [cncf/devstats.archive#26]
In the last ContribX SIG meeting (11/15/2017), we had a discussion about Kubernetes issues that are currently open but should have been closed based on some investigation done by a non-SIG member. Ideally SIG member should quickly close such an issues without spending much time per findings added as comments in the issue. However due to bandwidth limitation it's not always the case. One of the possible solutions was to display Open Issues and PR in the devstats per SIG to give a SIG idea about them. As I was looking at devstats, I guess the good place to display such stats for open issues can be under 'SIG issues' with new box for 'Open issue'? and something similar to PRs. (I am also working on possibilities of new labels to identify close candidates something that can be displayed on devstats in future)

ContribX meeting note for related action item under 11/15/2017: 
https://docs.google.com/document/d/1qf-02B7EOrItQgwXFxgqZ5qjW0mtfu5qkYIF1Hl4ZLI/edit?ts=5a0c7fbb

**Comment by lukaszgryglicki** [comment]
Labels would be great.
I can add a new dashboard that uses those labels to visualize data.

**Comment by spzala** [comment]
@lukaszgryglicki  thanks Lukas!! I will try to discuss this topic in today's contribX meeting.

**Comment by lukaszgryglicki** [comment]
OK.

**Comment by lukaszgryglicki** [comment]
Blocked until I have labels needed for this task.

**Comment by lukaszgryglicki** [comment]
[This](https://k8s.devstats.cncf.io/d/33/pr-workload?orgId=1) and [this](https://k8s.devstats.cncf.io/d/34/pr-workload-table?orgId=1) shows PR workload per SIgs.
Is this OK for this task?
If something other is neede, I'll need detailed description what to do.
What is the `labels` needed for this dashboard state?

**Comment by spzala** [comment]
@lukaszgryglicki thanks and I will be adding more info per my labels related PR which was merged early this week. In mid of travel/presentation prep for next week so please bear with me. Thanks!

**Comment by lukaszgryglicki** [comment]
OK, thx.

**Comment by spzala** [comment]
@lukaszgryglicki we might need to change the issue description based on this new labels related PR https://github.com/kubernetes/community/pull/1970  I will change the issue description as PR gets updated. Thanks!!

**Comment by lukaszgryglicki** [comment]
OK, will take a look, but there can be a delay, I have many items wip.

**Comment by spzala** [comment]
Thanks @lukaszgryglicki and OK, no rush with this at all!!

**Comment by lukaszgryglicki** [comment]
We do have dashboard "Open issues/PRs by milestones".
It allows to choose: repository, SIG, milestone (for any of then you can choose All) and displays open issues/PRs.
I think that dashboard implements this:
https://k8s.devstats.cncf.io/d/22/open-issues-prs-by-milestone?orgId=1

Closing this, please reopen if needed.

**Comment by spzala** [comment]
@lukaszgryglicki thanks and sounds good. I will open a separate issue for triage labels.

**Comment by lukaszgryglicki** [comment]
OK.
