### ISSUE TITLE
No graph for "all contributions" [feature request]

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#260]
In Contributor Growth for CNCF SIG-Contributor-Strategy we noticed that there is no graph showing all contributions by contribution type, or for all contributors by contribution type, that community managers can use to see if the general trends are going up or down.   We have ones for new contributors, and ones for just PRs, and tables listing contributors, but not trending graphs showing all types that I can find.

So this would involve two charts:

1) Contributions Count by Contribution Type, measuring all contributions across the project, with a metric selector like https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1   OPTIONAL: also include the ability to select repository group.

2) Contributor Count by Contribution Type: same as above, only counting contributors instead of contributions.

What would be even better is combining both of the above on one chart.  This would be for all CNCF projects.

Please wait for the following folks to comment before proceeding:

@geekygirldawn @LappleApple @carolynvs

**Comment by jberkus** [comment]
Ref: https://github.com/cncf/sig-contributor-strategy/pull/53

**Comment by lukaszgryglicki** [comment]
Contribution type, you mean to separate: Creating Issue, Creating PR, Commenting on Issue, Commenting on Commit, Reviewing a PR, Creating a Commit?
Can you provide a description of what data should be displayed and what should be the drop-down values?

**Comment by lasomethingsomething** [comment]
Thanks for filing and looping us in, @jberkus. Later today @castrojo and I will catch up on DevStats and we'll take a closer look at this.

**Comment by jberkus** [comment]
Lukasz: the same set of options as https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1

**Comment by lukaszgryglicki** [comment]
Yes, OK, but how about the graph, what should be plotted o the Y-axis (X being the time).?

**Comment by jberkus** [comment]
Either number of contributions or number of contributors, depending on which chart.

**Comment by lukaszgryglicki** [comment]
OK, I'll work on this on Friday, thanks!

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
First test server [preview](https://k8s.teststats.cncf.io/d/74/contributions-chart?orgId=1)
What do you think?
cc @jberkus

**Comment by lukaszgryglicki** [comment]
The right y-axis always shows the number of contributions (reviews, approves, commits, PRs, comments, etc).

The left y-axis always shows the number of contributors (authors of contributions) (reviewers, approvers, committers, PR creators, commenters, etc.). 

You can choose a moving average (7 Days MA). In that mode, it shows the number of distinct contributors in a moving 7 Days window and the average number of contributions per day (so this is the number of contributions in 7 days window divided by 7).

You can specify the aggregation period of 7 Days MA, Week, Month.

You can select any repository group or summary for all of them combined.

You can select any country or summary for all countries combined.

You can select any company or summary for all of them combined.

There are 13 possible metrics (contributions/contributors pairs):

- Approves/Approvers
- Reviews/Reviewers
- Comments/Commenters
- Commit comments/Commit commenters
- Commits/Committers
- GitHub events/Event authors
- GitHub pushes/Pushers
- Contributions/Contributors (contribution is a commit, PR, issue, comment, review, commit comment - all of them)
- Issue comments/Issue commenters
- Issues/Issue creators
- PRs/PR creators
- Merged PRs/PR merge authors
- Review comments/Review commenters (not the same as reviewers in K8s: `Review is defined when someone adds /approve or /lgtm comment or adds 'approved' or 'lgtm' label or adds PR review comment.`)

**Comment by lukaszgryglicki** [comment]
When you look at [this](https://k8s.teststats.cncf.io/d/74/contributions-chart?orgId=1&from=now-5y&to=now&var-period=m&var-metric=contributions&var-repogroup_name=Other&var-country_name=All&var-company_name=All&var-company=all) (repo group = Other), you can see that recently more and more repos fall to "Other" repo group - so repo group definitions should be revisited IMHO cc @jberkus

**Comment by lukaszgryglicki** [comment]
Also added a new chart to `All CNCF`: [test server preview](https://all.teststats.cncf.io/d/74/contributions-chart?orgId=1).

**Comment by lukaszgryglicki** [comment]
Added on `prod` server:
- [Kubernetes](https://k8s.devstats.cncf.io/d/74/contributions-chart?orgId=1).
- [All CNCF](https://all.devstats.cncf.io/d/74/contributions-chart?orgId=1).

Now adding on all remaining projects on the `test` env.

**Comment by lukaszgryglicki** [comment]
Added this new dashboard for all CNCF project pages on both test & prod servers.
Closing, please reopen if needed.

**Comment by jberkus** [comment]
looks great, thanks!

**Comment by jberkus** [comment]
wait, question: if you search on Merged PRs, the number of contributors is 3X the number of PRs.  How does this work, exactly?  Is that all commentors on those PRs?

**Comment by lukaszgryglicki** [comment]
See docs (bottom panel) about Moving averages.
For 7 days MA - it displays the number of distinct contributors over 7 days moving average window, but the number of contributions is the sum from that window divided by 7.

**Comment by jberkus** [comment]
aha, I see!   Yah, I get what I expect if I switch to week summary.  Thanks!
