### ISSUE TITLE
[bug] Cycle View Mode leads to unable to change view mode.

### ISSUE THREAD

**Issue by mwlang** [cncf/devstats.archive#261]
I was experimenting with cycling view modes when I suddenly lost the header bar altogether and could no longer cycle any more view modes.

The upper righthand corner completely loses the menu where this cycle view mode option lives:

![image](https://user-images.githubusercontent.com/18387/92055179-447c6a80-ed5c-11ea-8ea9-06d886c6505f.png)

I could find no ready way to get back to a working header menu.

**Comment by lukaszgryglicki** [comment]
Not sure how to replicate this, and this actually looks like a Grafana issue, not a DevStats issue.
