### ISSUE TITLE
[bug] Broken link in dev stats dashboard

### ISSUE THREAD

**Issue by gkarthiks** [cncf/devstats.archive#262]
When clicking on the link `Metrics SQL File` under the `Dashboard Documentation` section  from the Dev Stats dashboard for `Stars and Forks by repository`, it results in 404 Page Not Found error.

Seems the file is missing. The link its trying to open is https://github.com/cncf/devstats/blob/master/metrics/kubernetes/watchers.sql but the `watchers.sql` file is present in https://github.com/cncf/devstats/blob/master/metrics/shared/watchers.sql

Link for the dashboard: https://k8s.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1

![image](https://user-images.githubusercontent.com/30545166/92154758-ef1b8880-ee43-11ea-8480-57a3afe5bd36.png)

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
Fixed.
