### ISSUE TITLE
Question: what the meaning of `last` (month, quarter, ...)?

### ISSUE THREAD

**Issue by kobaji** [cncf/devstats.archive#263]
Hi there, I am reading this article.
https://github.com/cncf/devstats/blob/master/docs/periods.md#devstats-metrics-ranges-definitions

Then could you please tell me the meaning of `last`?
I could not find a document which describes this, although I am looking for...

Especially I am wondering the following.
If it is 2020-09-07-13:00:00 now, ...

- last week
  - from 2020-08-31-13:00:01 to now?
  - or any other?

- last month
  - from 2020-08-07-13;00:01 to now?
  - or any other?

- last quarter
  - from 2020-06-07-13;00:01 to now?
  - or any other?

- last year
  - from 2019-09-07-13:00:01 to now?
  - or any other?

- last decade
  - from 2010-09-07-13:00:01 to now?
  - or any other?

As I asked above, I'd be very grateful if you kindly showed the document which describes this (if you have).

Thanks in advance,
Koji

Please add `[feature request]` to the issue title when requesting new features, dashboards, projects etc.
Please add `[bug]` to the issue title when reporting a bug.

**Comment by kobaji** [comment]
I guess this issue can be related with [this](https://github.com/cncf/devstats/issues/29) but my question could not be resolved.

**Comment by lukaszgryglicki** [comment]
DevStats is synced hourly. If the last sync was running say 30 minutes ago, then "last week" means "now-1week-30minutes - now-30minutes" and so on for a month, day, etc.

**Comment by kobaji** [comment]
@lukaszgryglicki Thank you so much for your kind answer.
I understood completely!!

For example,
if the last sync was running 5min ago, the range says `Last year`, it mens the duration from "now-1year-5min" to "now-5min".

Thank you again for your kind help!!
