### ISSUE TITLE
[question]:How can I reflect my contribution to Tekton, to the ranking?

### ISSUE THREAD

**Issue by kobaji** [cncf/devstats.archive#266]
Hi there, could you please help me my contribution to Tekton be reflected in the following ranking?
https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%2010%20days&var-metric=issues

Somehow I cannot find my contribution (published some issues) reflected in that ranking.

# What I have done

- added my information to developers_affiliations.txt (on 2020/Sept/16th)
  - [PR](https://github.com/cncf/gitdm/pull/463)
- checked my affiliation was listed in [devstats/github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json#L1731160) (on 2020/Sept/16th)
  - We can find `kobaji` and the company I'm working for from this file.
- opend some issues in tektoncd, for example...
  - https://github.com/tektoncd/pipeline/issues/3036 (on 2020/July/31th)
  - https://github.com/tektoncd/community/issues/209 (on 2020/Sept/16th)

# What I have asked

- I have already asked Tekton community about it (on 2020/Sept/16th)
  - [issue in tektoncd/community](https://github.com/tektoncd/community/issues/209)
  - And got an answer my question might be resolved if I asked CNCF.
      - That's why I opened this issue.
  - The answer said [cncf/devstats/cdf](https://github.com/cncf/devstats/tree/master/cdf) was related to my question, but I cannot find any documents to make me understand how I can treat it.

Thank you very much for your kind help.

**Comment by lukaszgryglicki** [comment]
Affiliations are imported weekly. Data is already there in `cncf/gitdm` but it is possible its not in DevStats yet:
```
k get po -n devstats-prod | grep tekton | grep affiliations
devstats-affiliations-tekton-1599621300-c7vv6               0/1     Completed   0          9d
devstats-affiliations-tekton-1600226100-6bvw7               0/1     Completed   0          2d1h
```
Last import was 2d1h ago, so it is possible it was before JSON was updated. Please wait a bit and check again.

**Comment by kobaji** [comment]
Thanks again and again @lukaszgryglicki 
I'm very grateful for your kind help!!

I understand I have already done all I need and just need to wait a bit!
I'll close this issue but can reopen if my contribution has not been reflected to the ranking within a week.

**Comment by kobaji** [comment]
Btw should you have any documents about this in GitHub, I strongly hope to get it.

Those documents might be helpful for everyone need to know about this, as well as me.

**Comment by lukaszgryglicki** [comment]
https://github.com/cncf/gitdm#addingupdating-affiliation
Please note this info `Please note that cncf/gitdm affiliations are imported into DevStats (cncf/devstats) weekly.`.

**Comment by kobaji** [comment]
Thanks a lot!!

Though I have read that article but I misunderstood it!!
My information has been listed in [devstats/github_users.json](https://github.com/cncf/devstats/blob/master/github_users.json#L1731160), therefore I wondered why my contribution has not been reflected to the ranking.

Anyway, I'll inform some my fellows or Japanese engineers about this!!

Thank you again, @lukaszgryglicki !!

**Comment by lukaszgryglicki** [comment]
Sure, if you have any suggestions on how to reformat the README so this is more clear to you - go ahead and create a PR.
Thanks!

**Comment by kobaji** [comment]
Certainly I found my contribution has been listed in the ranking!!
Thank you @lukaszgryglicki again and again.
