### ISSUE TITLE
Companies don't seem to be listed in the Tekton ranking.

### ISSUE THREAD

**Issue by kobaji** [cncf/devstats.archive#267]
Hi there, thank you very much for every your kind help.

I am wondering something is wrong with [the tekton ranking](https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1
) because of the following reasons:

- Currently no companies' name is listed, like this:

Company | Number
-- | --
All | 58297

- In last week I found the ranking was like this:

Company|Number
-- | --
All | 4275
Red Hat | 1230
IBM | 1113
Google | 753
:|:

- In another ranking, for example CDF, we can see the companies's name and number.
  - https://allcdf.devstats.cd.foundation/d/5/companies-table?orgId=1

Company | Number
-- | --
All | 858566
CloudBees | 280275
Google | 77078
Netflix | 58813
Red Hat | 26887
:|:

That's why I am wondering if something is wrong with the Tekton ranking

If I should submit this issue in the different community, I would aplogize for trouble you.
Thank you.

**Comment by lukaszgryglicki** [comment]
We had disk pressure issues, seems like affiliations import failed on Tekton, I'll fix this asap. Thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Fixed.
Thanks for reporting.

**Comment by kobaji** [comment]
Thank you very much @lukaszgryglicki , it seems to be okay!!

Thank you again for your help.
