### ISSUE TITLE
[feature request][kubernetes] Update kubernetes repo groups

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#268]
Would it be possible to update the repo group mappings for these groups? They were previously under 'Other'.
If it'd be easier I can cut a PR to the kubernetes/repo_groups.sql file directly :) 

| Repo                                                                   | Repo Group                 |
|------------------------------------------------------------------------|----------------------------|
| kubernetes-client/c                                                    | SIG API Machinery          |
| kubernetes/controller-manager                                          | SIG API Machinery          |
| kubernetes-sigs/apiserver-runtime                                      | SIG API Machinery          |
| kubernetes-sigs/clientgofix                                            | SIG API Machinery          |
| kubernetes-sigs/kubebuilder-release-tools                              | SIG API Machinery          |
| kubernetes/application-images                                          | SIG Apps                   |
| kubernetes-incubator/application-images                                | SIG Apps                   |
| kubernetes-retired/application-images                                  | SIG Apps                   |
| kubernetes/component-helpers                                           | SIG Architecture           |
| kubernetes-sigs/seccomp-operator                                       | SIG Auth                   |
| kubernetes-sigs/secrets-store-csi-driver                               | SIG Auth                   |
| kubernetes-sigs/wg-policy-prototypes                                   | SIG Auth                   |
| kubernetes-sigs/cloud-provider-baiducloud                              | SIG Cloud Provider         |
| kubernetes-sigs/cloud-provider-huaweicloud                             | SIG Cloud Provider         |
| kubernetes-retired/kube-deploy                                         | SIG Cluster Lifecycle      |
| kubernetes-sigs/cluster-api-provider-nested                            | SIG Cluster Lifecycle      |
| kubernetes-sigs/cluster-api-provider-packet                            | SIG Cluster Lifecycle      |
| kubernetes-client/.github                                              | SIG Contributor Experience |
| kubernetes-csi/.github                                                 | SIG Contributor Experience |
| kubernetes/.github                                                     | SIG Contributor Experience |
| kubernetes-sigs/contributor-tweets                                     | SIG Contributor Experience |
| kubernetes-sigs/.github                                                | SIG Contributor Experience |
| kubernetes-sigs/instrumentation-tools                                  | SIG Instrumentation        |
| kubernetes-sigs/mcs-api                                                | SIG Multicluster           |
| kubernetes-sigs/cluster-proportional-autoscaler                        | SIG Network                |
| kubernetes-sigs/cluster-proportional-vertical-autoscaler               | SIG Network                |
| kubernetes-sigs/iptables-wrappers                                      | SIG Network                |
| kubernetes-sigs/security-profiles-operator                             | SIG Node                   |
| kubernetes-sigs/downloadkubernetes                                     | SIG Release                |
| kubernetes-sigs/mdtoc                                                  | SIG Release                |
| kubernetes-sigs/zeitgeist                                              | SIG Release                |
| kubernetes-sigs/go-open-service-broker-client                          | SIG Service Catalog        |
| kubernetes-csi/csi-driver-smb                                          | SIG Storage                |
| kubernetes-csi/external-health-monitor                                 | SIG Storage                |
| kubernetes/mount-utils                                                 | SIG Storage                |
| kubernetes-retired/external-storage                                    | SIG Storage                |
| kubernetes-sigs/blob-csi-driver                                        | SIG Storage                |
| kubernetes-sigs/container-object-storage-interface-controller          | SIG Storage                |
| kubernetes-sigs/container-object-storage-interface-csi-adapter         | SIG Storage                |
| kubernetes-sigs/container-object-storage-interface-provisioner-sidecar | SIG Storage                |
| kubernetes-sigs/container-object-storage-interface-spec                | SIG Storage                |
| kubernetes-sigs/gluster-block-external-provisioner                     | SIG Storage                |
| kubernetes-sigs/gluster-file-external-provisioner                      | SIG Storage                |
| kubernetes-sigs/nfs-ganesha-server-and-external-provisioner            | SIG Storage                |
| kubernetes-sigs/nfs-subdir-external-provisioner                        | SIG Storage                |
| kubernetes-sigs/boskos                                                 | SIG Testing                |
| kubernetes-sigs/k8s-gsm-tools                                          | SIG Testing                |
| kubernetes-sigs/kubetest2                                              | SIG Testing                |
| kubernetes-sigs/secret-sync-rotation                                   | SIG Testing                |
| kubernetes-sig-testing/frameworks                                      | SIG Testing                |
| kubernetes-sigs/sig-windows-samples                                    | SIG Windows                |

Additionally 2 others need to moved, they were previously under `SIG-PM`, but that group has spun down and their repos have been migrated under SIG-Architecture.

| Repo                    | Repo Group       |
|-------------------------|------------------|
| kubernetes/features     | SIG Architecture |
| kubernetes/enhancements | SIG Architecture |

**Comment by lukaszgryglicki** [comment]
Will do on Monday.

**Comment by mrbobbytables** [comment]
Thanks!

**Comment by lukaszgryglicki** [comment]
Implemented, data regenerated.
