### ISSUE TITLE
[bug][kubernetes] Company Statistics by Repo Group error

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#269]
When viewing the [Company Statistics by Repository Group](https://k8s.devstats.cncf.io/d/8/company-statistics-by-repository-group) dashboard, it fails and surfaces this error:
```
pq: column "Deloitte" does not exist
Object
status:400
statusText:""
data:Object
results:Object
message:"pq: column "Deloitte" does not exist"
message:"pq: column "Deloitte" does not exist"
```

Please let me know if I can provide more info or if theres anything I can do to help 👍

**Comment by lukaszgryglicki** [comment]
Will fix tomorrow, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Fixed.
