### ISSUE TITLE
Rename self

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#27]
Please rename independent to self.

**Comment by spzala** [comment]
Thanks for taking care of it Dan!

**Comment by lukaszgryglicki** [comment]
Will rename on cnf/gitdm then also do the newest import of cncf/gitdm data and regenerate company related charts.
Just when I got back home.

**Comment by lukaszgryglicki** [comment]
Actually, @radoslaw can You take a look at cncf/gitdm:cncf-config/email-map and search for "independent" (any case) and change it to Self?
I see You have a lot of email-map updates, so You can just add this single change, and I'll review all stuff when I return?

**Comment by radoslaw** [comment]
sure, if there aren't that many, I can search for company affiliations on those. Set to Self if can't be found

**Comment by spzala** [comment]
Actually the issue is to set "Self" to "Independent". i.e. Rename "Self" to "Independent". Thanks!

**Comment by lukaszgryglicki** [comment]
So I would leave "Self" then.
This is what we decided at the beginning.
I do agree that we shouldn't have multiple names for the same "assignmemnt" but I would like to keep name "Self" as-is and rename all "independent" etc to Self.

**Comment by dankohn** [comment]
No, the group decided that Independent was clearer than Self. Please change
all occurrences of Self to Independent.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
OK, I saw all other emails.
Sorry for delays, but I just got to LA using AMTRAK, took the 11-mile walk to Dockweiler Beach and just returned to the hotel.
I have a ton of email to review.

**Comment by lukaszgryglicki** [comment]
Added to my TODO list, I'll work on this soon.

**Comment by lukaszgryglicki** [comment]
Data regenerated, "Self" renamed to "Independent", please see:
https://k8s.devstats.cncf.io/dashboard/db/companies-stats?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/companies-summary?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/companies-velocity?orgId=1
etc.
Closing.
