### ISSUE TITLE
[bug] Update "packet" and "packet.net" branding to Equinix Metal

### ISSUE THREAD

**Issue by vielmetti** [cncf/devstats.archive#270]
Packet has been acquired by Equinix, and the new brand is Equinix Metal.

Update references throughout the web site and the documentation to the new site, and to the new logo.

https://metal.equinix.com

**Comment by vielmetti** [comment]
Reference https://github.com/cncf/devstats/commit/f8eed559f8f6ad94ef321eb12097778515f45cca which had the original acknowledgement (thanks!)

**Comment by vielmetti** [comment]
Also see https://github.com/cncf/devstats/commit/8a4fd909d5fad3a95218af84e3719e3414e26bb0 with the ack in the README file.

**Comment by lukaszgryglicki** [comment]
Will do after my PTO this week and KubeCon next week, thanks for reporting!

**Comment by lukaszgryglicki** [comment]
Updated references in [devstats repo](https://github.com/cncf/devstats/commit/5bbc4befcc4889f66622682ca9dd32ff39572f9f), [devstats-helm repo](https://github.com/cncf/devstats-helm/commit/9560d54ab7347f9c267fdbae5324bdbfb5aacecb), rebuilt docker images (grafana and pages) and redeployed with new branding.

See https://devstats.cncf.io (you may need to clear cache or do some similar operation depending on the browser used). Closing, please reopen if needed.

cc @vielmetti

**Comment by lukaszgryglicki** [comment]
@vielmetti I've updated the main description of [DevStats](https://devstats.cncf.io) page to include information that we run on the Equinix platform.
See the screenshot attached:
![Screenshot 2020-12-04 at 13 54 33](https://user-images.githubusercontent.com/2469783/101166312-607ff880-3638-11eb-8062-4ef9a0ae858f.png)
![Screenshot 2020-12-04 at 13 54 43](https://user-images.githubusercontent.com/2469783/101166315-62e25280-3638-11eb-85c7-49102a651784.png)
