### ISSUE TITLE
[feature request] Add Tinkerbell (new sandbox project)

### ISSUE THREAD

**Issue by vielmetti** [cncf/devstats.archive#271]
https://tinkerbell.org and @tinkerbell are newly added sandbox projects to the CNCF. It would be great to see them on the DevStats pages.

**Comment by lukaszgryglicki** [comment]
This one and 6 others are wip. Just returned from my PTO and because there are 6 projects at a time it will take a few days (also KubeCon is happening this week), so this will definitely be done, just wait a bit.
Thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Forgot this issue, added 5 days ago, closing.
