### ISSUE TITLE
[feature request] Cluster API and the Providers aren't represented

### ISSUE THREAD

**Issue by craiglpeters** [cncf/devstats.archive#273]
It would be great to have both CAPI itself, and each of the providers represented on the [dashboard](https://k8s.devstats.cncf.io/d/12/dashboards?orgId=1&refresh=15m)

**Comment by lukaszgryglicki** [comment]
I think it's just a matter of [repo groups](https://github.com/cncf/devstats/blob/master/scripts/kubernetes/repo_groups.sql) definitions.
