### ISSUE TITLE
[feature request] Add Open Service Mesh to the dashboard

### ISSUE THREAD

**Issue by craiglpeters** [cncf/devstats.archive#274]
It would be great if [OSM](https://github.com/openservicemesh/osm) was represented on the dashboard

**Comment by lukaszgryglicki** [comment]
This is probably a repository group definition request. I'm not quite sure where you want to update it... "All CNCF", "Open Service Mesh"?

**Comment by caniszczyk** [comment]
@craiglpeters this already exists? https://openservicemesh.devstats.cncf.io/
