### ISSUE TITLE
[bug] User affilitation incorrect

### ISSUE THREAD

**Issue by fabiand** [cncf/devstats.archive#275]
@maiqueb is now working for Red Hat, but his mapping is incorrect in https://github.com/cncf/devstats/blob/master/github_users.json.

How can this be fixed?

**Comment by fabiand** [comment]
Ah, it can be addressed here:
https://github.com/cncf/gitdm#addingupdating-affiliation

@maiqueb can you please update your entry?

**Comment by lukaszgryglicki** [comment]
Please create a PR against [cncf/gitdm](https://github.com/cncf/gitdm#addingupdating-affiliation).
