### ISSUE TITLE
[feature request] Add a deshboard for PR merger

### ISSUE THREAD

**Issue by rmohr** [cncf/devstats.archive#276]
It would be great for us the see who actually merges PRs in devstats. For instance in our case it would be intersting to see how much we merge via our robot and how much we merge by different people.

**Comment by lukaszgryglicki** [comment]
You need something like a table of PR mergers sorted by the number of merge PR right?
I can create such a dashboard.
Just need o confirm that this is something you want...

**Comment by rmohr** [comment]
> You need something like a table of PR mergers sorted by the number of merge PR right?

Yes a table similar to the PR Authors table: https://kubevirt.teststats.cncf.io/d/22/prs-authors-table?orgId=1

> I can create such a dashboard.

Thanks a lot.

**Comment by rmohr** [comment]
> Yes a table similar to the PR Authors table: https://kubevirt.teststats.cncf.io/d/22/prs-authors-table?orgId=1
>

I just see that our kubevirt-bot is not in this dashboard (is it explicitly removed?).

**Comment by lukaszgryglicki** [comment]
Yes, bots are usually removed, but I can create a dashboard with bots included.

**Comment by rmohr** [comment]
> Yes, bots are usually removed, but I can create a dashboard with bots included.

That would be awesome.Maybe they can be marked with `username (robot)` or so to make clear that it is a bot.

**Comment by lukaszgryglicki** [comment]
Will work on this on Friday.

**Comment by lukaszgryglicki** [comment]
A bit late, but starting work on this.

**Comment by lukaszgryglicki** [comment]
Ready, here is the [Mergers Table](https://all.devstats.cncf.io/d/75/prs-mergers-table?orgId=1) for All CNCF projects DevStats instance (the single project is a single repository group there), and [here](https://kubevirt.devstats.cncf.io/d/75/prs-mergers-table?orgId=1) is the Mergers Table for `KubeVirt`. Bot users are marked as `*bot: bot-name*`. Closing this, let me know if you need to reopen.

**Comment by rmohr** [comment]
@lukaszgryglicki thanks a lot. That is very helpful.
