### ISSUE TITLE
Categories items on the home page

### ISSUE THREAD

**Issue by spzala** [cncf/devstats.archive#28]
The items displayed on the home page (https://devstats.k8s.io) are several and they probably going to increase. We may end up with lots of scrolling. This can be confusing. Can we Categories related items e.g. have all issues related items under "Issue" or companies related items under 'Companies' (for example, have 'Companies stats", "Companies summary" and "Companies velocity" under main item "Companies". Thanks!

**Comment by spzala** [comment]
Created this issue per some discussion at the devstats session at KubeCon Austin.

**Comment by lukaszgryglicki** [comment]
Thinking about tags, but they will only help to search dashboards, not to make a list shorter. Will need to think about this, maybe ask Grafana guys what to do using currently available Grafana UI tools.

**Comment by spzala** [comment]
Thanks Lukas!! Sounds good to me.

**Comment by lukaszgryglicki** [comment]
I'll work on this.

**Comment by lukaszgryglicki** [comment]
I've created few categories, please let me know if this is something You want?
You can select categories on the main dashboards dropdown by choosing tags (it filters list of dashboards):
https://k8s.cncftest.io
(only on the test environment atm, if LGTY I'll apply to production as well)
![screen shot 2017-12-18 at 13 05 58](https://user-images.githubusercontent.com/2469783/34105464-9ae08dd0-e3f4-11e7-8f33-2e596ffc8e0d.png)
![screen shot 2017-12-18 at 13 06 04](https://user-images.githubusercontent.com/2469783/34105465-9afca088-e3f4-11e7-9fd1-2c29fe85dded.png)
![screen shot 2017-12-18 at 13 06 10](https://user-images.githubusercontent.com/2469783/34105466-9b179596-e3f4-11e7-9cd8-6ea2340a0825.png)
![screen shot 2017-12-18 at 13 06 16](https://user-images.githubusercontent.com/2469783/34105467-9b3721f4-e3f4-11e7-810b-6b0a5b120f7e.png)
![screen shot 2017-12-18 at 13 06 25](https://user-images.githubusercontent.com/2469783/34105468-9b50f372-e3f4-11e7-81bf-73491b420af5.png)

**Comment by spzala** [comment]
Thanks @lukaszgryglicki for a quick work on it. I have couple questions and I will be pinging you.

**Comment by lukaszgryglicki** [comment]
So I'm porting those tags from test to prod (in the meantime). I'm assuming that tags are OK?

**Comment by lukaszgryglicki** [comment]
New tags also on prod:
https://k8s.devstats.cncf.io

**Comment by lukaszgryglicki** [comment]
Tags implemented, closing this issue. Please let me know if I need to reopen or open new issues to "ping" me if unrelated to this.

**Comment by spzala** [comment]
@lukaszgryglicki hi Lukas, sorry because of being on a scheduled vacation since last few days and with family,  I wasn't able to test it but thanks a much for your quick work. I will be testing it once get back and let you know my feedback. Thanks!

**Comment by lukaszgryglicki** [comment]
No problem. Thanks for the info.
