### ISSUE TITLE
[feature request] More granular range values for contribution chart

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [cncf/devstats.archive#280]
## Description
The current graphs have a static set of values for the range drop down. It would be valuable to be able to define a custom range eg( start date to end date ) or if more granular data (monthly for the last year) that would be very helpful.

## Motivation
I'd like to generate monthly stats and aggregate them across custom 3 month periods and the current range values wouldn't be able to generate such data.

**Comment by lukaszgryglicki** [comment]
Hi, which chart, can you paste a link?
Some of those charts (like the tabular ones) are pre-calculated and we can only do that for a fixed set of values - data is not coming from a complex query that is too slow to calculate "on the fly" - I'll check what I can do here, but I can also do a one-time calculation of the exact data you need - I just need detailed specs what is needed.

**Comment by xtreme-sameer-vohra** [comment]
I was trying to get monthly numbers from July-Dec for the stats for [this](https://knative.teststats.cncf.io/d/5/companies-table?orgId=1) chart

**Comment by lukaszgryglicki** [comment]
The closest thing will be:
- monthly
- contributions
- last year
Selected those values [here](https://knative.teststats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&from=now-1y&to=now&var-period=m&var-metric=contributions&var-repogroup_name=All&var-companies=All). I can also pull the exact number manually from DB.

**Comment by xtreme-sameer-vohra** [comment]
Thanks, thats perfect
I was able to download the tabulate data in csv format from that view

**Comment by lukaszgryglicki** [comment]
Great, thanks...
BTW: you can download all dashboards data as CSV.
