### ISSUE TITLE
[bug] KubeVirt dashboard - very long urls lead to syntax errors/empty responses

### ISSUE THREAD

**Issue by dhiller** [cncf/devstats.archive#282]
After [PR for KubeVirt repogroups](https://github.com/cncf/devstats/pull/281) was merged we played around with the dashboards.

It seems that selecting lots of companies does not work somehow. What we encountered were syntax errors and even empty responses. Can someone please have a look and help us understand what is wrong here?

Example URL:

https://kubevirt.devstats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1&var-period_name=Last%20decade&var-repogroups=All&var-companies=SAP&var-companies=CNCF&var-companies=SUSE&var-companies=Cisco&var-companies=Google&var-companies=ARM&var-companies=Inspur&var-companies=Intel&var-companies=Ericsson&var-companies=Kubermatic&var-companies=Deutsche%20Telekom&var-companies=CloudFlare&var-companies=ZTE&var-companies=Microsoft&var-companies=Huawei&var-companies=(Robots)&var-companies=Amazon&var-companies=Amdocs&var-companies=Sandvine&var-companies=StackPath&var-companies=Telef%C3%B3nica&var-companies=Apple&var-companies=NVidia&var-companies=Nokia&var-companies=Stratus&var-companies=TmaxA%26C&var-companies=Thales&var-companies=VMware&var-companies=Platform9&var-companies=Samsung&var-companies=Jetstack&var-companies=HP&var-companies=CERN&var-companies=Mellanox&var-companies=Mirantis&var-companies=Luminis&var-companies=Hays&var-companies=Intuit&var-companies=Wolters%20Kluwer&var-companies=Zalando&var-companies=Edgewise%20Networks&var-companies=SilverSky&var-companies=Storiant&var-companies=Wayfair&var-companies=PeerApp&var-companies=Wind%20River&var-companies=InQool&var-companies=42six&var-companies=Catalytic&var-companies=Synamedia&var-companies=FAYN&var-companies=SDE&var-companies=Yahoo&var-companies=Israeli%20Air%20Force&var-companies=Israeli%20Navy&var-companies=Seznam.cz&var-companies=Codewise&var-companies=UBS&var-companies=Odysii&var-companies=Akamai%20Technologies&var-companies=SolidFire&var-companies=Assured%20Information%20Security&var-companies=Citrix&var-companies=Axeos&var-companies=Mogujie&var-companies=Dell&var-companies=Teradata&var-companies=zooplus&var-companies=ContainerShip&var-companies=Canonical&var-companies=Giant%20Swarm&var-companies=Grupo%20HOLA&var-companies=Bareket&var-companies=Collective%20Sense&var-companies=Ocado&var-companies=SoftLayer&var-companies=Scytl&var-companies=DataMiner&var-companies=Neoway&var-companies=Softplan&var-companies=PubNative&var-companies=ThreatMark&var-companies=One%20Source&var-companies=Raleigh&var-companies=Tembo&var-companies=Lacoda&var-companies=Newstex&var-companies=NTT&var-companies=Infosys&var-companies=Publet&var-companies=NETA%C5%9E&var-companies=Capgemini&var-companies=Juniper%20Networks&var-companies=Istuary%20Innovation&var-companies=%E4%BA%9A%E4%BF%A1%E7%A7%91%E6%8A%80%EF%BC%88%E4%B8%AD%E5%9B%BD%EF%BC%89%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&var-companies=Concord%20Systems&var-companies=vectorized&var-companies=Yieldmo&var-companies=CSULB%20Alumni%20Association&var-companies=Panasonic&var-companies=Deposit&var-companies=inovex&var-companies=Silpion&var-companies=Penta&var-companies=Tiger&var-companies=ETH%20Z%C3%BCrich&var-companies=Metaswitch&var-companies=Winter%20Circle&var-companies=Uber&var-companies=PicsArt&var-companies=Sierra%20Wireless&var-companies=CS2C&var-companies=Kumina&var-companies=Aparna%20Systems&var-companies=EPAM&var-companies=Fandom&var-companies=Netskope&var-companies=Nordea&var-companies=SKOK&var-companies=Trader%20Joe%27s&var-companies=Lloyd%27s%20Register&var-companies=Nordic%20IT&var-companies=Stibo%20Systems&var-companies=AppOrbit&var-companies=KashYOO&var-companies=PNNL&var-companies=Bell&var-companies=Tucows&var-companies=Altran&var-companies=Aricent&var-companies=Baidu&var-companies=BoCloud&var-companies=Bull&var-companies=Oxyliom&var-companies=Oxyliom%20Solutions&var-companies=THALES%20COMMUNICATIONS%20%26%20SECURITY%20SA&var-companies=LogicMonitor&var-companies=Mesosphere&var-companies=Talos%20Systems&var-companies=Virtustream&var-companies=Codemancers&var-companies=Josh&var-companies=Parcelled&var-companies=Tableau%20S&var-companies=Comverse%20Technology&var-companies=Mavenir&var-companies=Quamotion&var-companies=Circ&var-companies=commercetools&var-companies=Elastic%20Path&var-companies=EQuinix&var-companies=Macy%27s&var-companies=Stratoscale&var-companies=Three%20Crickets&var-companies=Xerox&var-companies=FNST&var-companies=A2%20Hosting&var-companies=Arkena&var-companies=Brainloop&var-companies=Cornered%20Rat&var-companies=deepc&var-companies=Fairwinds&var-companies=InfraCloud%20Technologies&var-companies=Mauswerks&var-companies=Nirmata&var-companies=Open%20Source&var-companies=Plixer&var-companies=UnitedStack&var-companies=WeScale&var-companies=ATEME&var-companies=Baja%20NITK%20Racing&var-companies=In%20August&var-companies=ISTE%20NITK&var-companies=Niji&var-companies=UTi%20Worldwide&var-companies=Casa%20do%20Cadigo&var-companies=Chaordic%20Systems&var-companies=Dusty%20Mabe&var-companies=Former03&var-companies=Grafana%20Labs&var-companies=Here&var-companies=Jd.Com&var-companies=Mattermost&var-companies=Meltwater&var-companies=Midokura&var-companies=NEC&var-companies=Picsolve&var-companies=Redes&var-companies=%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81%20%D0%A2%D1%80%D0%B5%D0%BD%D0%B4&var-companies=ALTEN%20Calsoft%20Labs&var-companies=Basho&var-companies=Bharat%20Electronics&var-companies=Brickshare&var-companies=Bytes%20and%20Butter&var-companies=Civo&var-companies=CodiLime&var-companies=Coop%20i%20Danmark&var-companies=Danske%20Spil%20A%2FS&var-companies=Digital&var-companies=Facebook&var-companies=Fidelity%20Investments&var-companies=Fujitsu&var-companies=Inventio.IT%20A%2FS&var-companies=LF%20Networking&var-companies=NASA&var-companies=NEXTGEN&var-companies=Potential&var-companies=Reflec&var-companies=Safe%20Route&var-companies=Stream.io&var-companies=Twitter&var-companies=Umi%20Kitchen&var-companies=UnboundID&var-companies=Wipro&var-companies=Amadeus&var-companies=Ant%20Financial&var-companies=Banker%27s%20Toolbox&var-companies=CitusData&var-companies=Credera&var-companies=Cvent&var-companies=Global%20IT%20Solutions&var-companies=Help&var-companies=ISEO&var-companies=Linaro&var-companies=Maon&var-companies=MeePo&var-companies=Musikum%20E.V.&var-companies=NFP&var-companies=None&var-companies=Orange&var-companies=Packet&var-companies=Perceptyx&var-companies=Poltloc&var-companies=PPI%20AG&var-companies=Rohde%20%26%20Schwarz%20GmbH%20%26%20Co.%20KG&var-companies=SmartX&var-companies=Tecbeast&var-companies=Temenos&var-companies=Terracotta&var-companies=4xLabs%20Pte&var-companies=Alstom&var-companies=American%20Electric%20Power&var-companies=AT%26T&var-companies=AVI%20Limited&var-companies=B1%20Systems&var-companies=Beatport&var-companies=Bownty&var-companies=Brankas&var-companies=CCC&var-companies=CloudBees&var-companies=Cohesity&var-companies=Crowe&var-countries=All

TIA!

FYI @fabiand

**Comment by lukaszgryglicki** [comment]
Please report this to Grafana - DevStats uses Grafana and this is how it passes variable values in URL. There is nothing I can do here.

**Comment by lukaszgryglicki** [comment]
Closing for now, action must be taken on the Grafana side, where I've already provided all info I have.
