### ISSUE TITLE
[BUG][Kubernetes] Missing data from pre 2021 on PR Reviews Dashboard

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#285]
The [PR Reviews by Contributor Dashboard](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1) is missing data from pre-2021 for quite a few contributors.

Example query:
https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&from=1569913200000&to=1601535599000&var-period=d&var-repo_name=All&var-reviewers=All

If you scroll down in the list on the right, there will be a bunch of folk with 0's across each column. A few specific contributors that definitely should have entries there:
- johnbelamaric
- xmudrii
- divya-mohan0209

**Comment by lukaszgryglicki** [comment]
I can take a look at this next week, this week I have a vacation.

**Comment by lukaszgryglicki** [comment]
I hope, I'll be able to check this tomorrow.

**Comment by lukaszgryglicki** [comment]
Finally on it.

**Comment by lukaszgryglicki** [comment]
I can see data for `johnbelamaric` and `divya-mohan0209`, see [this](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=All&var-reviewers=%22johnbelamaric%22&var-reviewers=%22divya-mohan0209%22&from=now-90d&to=now).
I'll check `xmudrii` and also those 2 to be sure that the data is OK.
Note that (dashboard documentation):
```
- This dashboard shows number of reviews and lgtms for most active reviewers.
- LGTM means user added /lgtm comment or lgtm label.
- Review means user added PR review comment.
- You can select reviewer from the reviewers drop-down, it shows top active reviewers from last 3 months.
- To find top active reviewers we sum number of reviews and lgtms per user.
```

So to [calculate](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/reviews_per_user.sql) something as a review it must be a comment (not necesarily a review comment) with `/lgtm` somewhere in its body, or adding `lgtm` label or adding a PR review comment (commend body doesn't matter in this case).
Drop down show [top active reviewers](https://github.com/cncf/devstats/blob/master/metrics/shared/reviewers_tags.sql) from the last quarter, so there can be reviewers that were active before tlast quarter or just landed out of top ones - they won't show in the drop-down.

**Comment by lukaszgryglicki** [comment]
So `johnbelamaric` had 194 reviews in the last quarter, `divya-mohan0209` had 54, `xmudrii ` had 21.
This makes `xmudrii` about 330th reviewer - we're only [showing](https://github.com/cncf/devstatscode/blob/master/tags.go#L61-L65) top 255 reviewers from the last quarter, so thaty user is not listed. The first and the second rank is < 255th so they show up and you can see their reviews [here](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=All&var-reviewers=%22johnbelamaric%22&var-reviewers=%22divya-mohan0209%22&from=now-90d&to=now)
I think the data is OK, can we close this @mrbobbytables ?

**Comment by mrbobbytables** [comment]
Ahhh, I did not realize that it was only the top 255.

Yup, should be good to close.
