### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by kobaji** [cncf/devstats.archive#286]
Hi @lukaszgryglicki and all,
I tried to access the following URL but something seemed to be wrong.
https://tekton.devstats.cd.foundation/

It says "503 Service Temporarily Unavailable".

N.B.
Aside from Tekton, k8s or any other Devstats seem to have some problems.

Are there any server side problems??
Hope it will get well soon~

Please add `[feature request]` to the issue title when requesting new features, dashboards, projects etc.
Please add `[bug]` to the issue title when reporting a bug.

**Comment by xtreme-sameer-vohra** [comment]
Seeing the same thing for https://devstats.cncf.io as well

**Comment by lukaszgryglicki** [comment]
Investigating...

**Comment by lukaszgryglicki** [comment]
This was a node failure, no idea why, will keep observing, fixed this for now by restarting a bare metal node.
The node was kinda misbehaving. Calling `df` command was never returning. Any ideas why `df` command can behave like this?

**Comment by kobaji** [comment]
Thanks all,
First of all I am glad to be able to access the URLs.
Anyway I will look for the best way to solve this.

**Comment by xtreme-sameer-vohra** [comment]
> This was a node failure, no idea why, will keep observing, fixed this for now by restarting a bare metal node.
> The node was kinda misbehaving. Calling `df` command was never returning. Any ideas why `df` command can behave like this?

Were other commands that target the filesystem such as `ls` working ? Which file system is the bare metal node using ?

**Comment by lukaszgryglicki** [comment]
`ls` was working just fine, root filesystem is on `ext4`, there is no swap, and all DevStats data lives in `OpenEBS` using local storage. `OpenEBS` is set up to use mount directory of `LVM`. LVM is made from two 3.5T `NVMe` disks. The `LVM` volume is formatted using `ext4` filesystem too. All 4 bare metal nodes have the same configuration, OS is Ubuntu 20.04 LTS.

**Comment by kobaji** [comment]
Please let me ask you one. Is devstats working now?
Honestly, I found my fellow's commits in Feb/26th 12:00PM UTC does not seem to be appeared in the following ranking.
https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=commits

I would like to find out the cause (e.g. [My PR](https://github.com/cncf/gitdm/pull/463/files#diff-4350264dd72e265347ea8c08fd9c99dfc6140b1641b564857fe3bfe2eb365de5R23843-R23844) was incorrect, the committer information was incorrect, and so on)

**Comment by lukaszgryglicki** [comment]
I've been on the vacation, just two days, Friday and Monday, please give me some time to investigate this when I'm back, in the meantime, can you provide more details about what PRs/commits are wrong in your opinion? I'll check the DB, GitHub archives to see if I have that data, or GitHub archives have that data correct/incorrect, etc.

**Comment by kobaji** [comment]
Thank you for your kindness @lukaszgryglicki !!
If I should Open another issue, please let me know. I'd be opening as soon as possible.

#### Expected Behavior
In the following commit ranking, Fujitsu should have 7 commits.
https://tekton.devstats.cd.foundation/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=commits

#### Actual Behavior
Fujitsu have 6 commits (A range is `last year` but it does not matter. Actually our first commit was done 5 months ago).

#### Additional Info

The related [commit](https://github.com/tektoncd/dashboard/commit/248053beddd602ddda3a7bcc7ffbcc8b82463ec9) and [PR](https://github.com/tektoncd/dashboard/pull/1955).
  - This commit was authored by `kkosaka` and committed by `yamaken1343`. Both are my teammate.
  - Another [commit](https://github.com/tektoncd/dashboard/commit/2f860eb8762202d54f987e900c440fd3e596af79) 7 days ago, by my teammate `watanabeyk`, was certainly reflected in the commit ranking.

Thank you again for your kindness.

**Comment by xtreme-sameer-vohra** [comment]
> `ls` was working just fine, root filesystem is on `ext4`, there is no swap, and all DevStats data lives in `OpenEBS` using local storage. `OpenEBS` is set up to use mount directory of `LVM`. LVM is made from two 3.5T `NVMe` disks. The `LVM` volume is formatted using `ext4` filesystem too. All 4 bare metal nodes have the same configuration, OS is Ubuntu 20.04 LTS.

Gotcha, in the past have seen bugs with btrfs, however, that doesn't seem to be what you're running into. Sorry, I cant be of more help

**Comment by lukaszgryglicki** [comment]
I think I've found something, I'll try to fix and get back to you @kobaji

**Comment by lukaszgryglicki** [comment]
Should be fixed by [this commit](https://github.com/cncf/devstatscode/commit/b43c2dc0f07c826e6fd00b30a1e802bbe506dc87).
@kobaji let me know if the data looks OK now.

**Comment by kobaji** [comment]
Hi @lukaszgryglicki , thank you very much for your comment.
The data looks OK now.

Thank you again!!
