### ISSUE TITLE
[Feature Request][Kubernetes] Add additional filters to dashboards

### ISSUE THREAD

**Issue by mrbobbytables** [cncf/devstats.archive#289]
## Problem

DevStats currently does not provide enough granular signal on many of the dashboards to make meaningful inferences from the data. This is largely because `repo_group` is not a good mapping to a particular SIG, and does not provide insight into the subprojects that are repo specific or reflect the work that occurs in shared repos such as [kubernetes/kubernetes], or [kubernetes/enhancements].

This issue outlines 3 problems/requests that could help resolve those problems and make the boards much more useful. It largely boils down to: where `repo_group` is present, add filters for repo, sig/wg label, and Company.

 
---

## Problem 1 - lack of per repo visibility

**Feature Request:** On dashboards where `repo_group` is present, allow further filtering by individual repo.

SIGs have many repos and the work is delegated to subproject owners that own those repos. The current dashboards using `repo_group` do not offer a per-repo breakdown and cannot be used to evaluate the health of a partcular subproject.

**Examples:**
- [Developer Activity Counts by Repository Group] - Without the possibility of a per-repo breakdown, it's difficult to see which repos activity may have dropped.
- [Inactive Issues by SIG] - - While this gives a holestic view of the SIG, without further breakdown by repo it's not possible to see where the problem might actually exist.
- [Awaiting PRs by SIG] - Same as the above Inactive Issue board.

[Developer Activity Counts by Repository Group]: https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1
[Inactive Issues by SIG]: https://k8s.devstats.cncf.io/d/73/inactive-issues-by-sig?orgId=1
[Awaiting PRs by SIG]: https://k8s.devstats.cncf.io/d/70/awaiting-prs-by-sig?orgId=1

---

## Problem 2 - lack of per SIG/WG break down in shared repos

**Feature Request:** on dashboards where `repo_group` is present, allow further filtering by SIG label.

Some SIGs/WGs work almost exclusively out of shared repos such as [kubernetes/kubernetes] or [kubernetes/enhancement]; repo_group does not capture their work.

**Examples:**
- [SIG Scalability Repository Groups] - SIG Scalability is near 100% out of [kubernetes/kubernetes].
- [SIG Auth Repository Groups] - The majority of SIG Auth's work occurs in [kubernetes/kubernetes] with the repos listed here being subprojects or initatives under a working group.

[SIG Scalability Repository Groups]: https://k8s.devstats.cncf.io/d/68/repository-groups?orgId=1&var-repogroups=Not%20specified&var-repogroups=SIG%20Scalability
[SIG Auth Repository Groups]:  https://k8s.devstats.cncf.io/d/68/repository-groups?orgId=1&var-repogroups=SIG%20Scalability&var-repogroups=SIG%20Auth

---

## Problem 3 - Companies cannot reasonably measure their involvement

**Feature Request:** On dashboards where `repo_group` is present, allow further filtering by Company.

As a company trying to gauge our involvement within a particular SIG or subproject, we cannot establish what areas we are contributing to because `repo_group` does not provide enough detail (the previous two requests).

Being able to look at the areas, and check company investment helps highlight areas that need potential headcount, or internal re-alignment to ensure the upstream group/repo/subproject remains healthy.

(No examples, please see above requests examples, but think of company metric)

[kubernetes/kubernetes]: https://github.com/kubernetes/kubernetes
[kubernetes/enhancements]: https://github.com/kubernetes/enhancements

**Comment by lukaszgryglicki** [comment]
So I can't just show repos and repo groups at the same time.
I can create a separate dashboard9s) that use repos instead of repo groups if that can help.
Also repo groups can have "file-level" granularity (it's already implemented) so the single repo like `k/k` can belong to different repo groups.
Actually, it's hard for me to decide what exactly should be done here.

**Comment by mrbobbytables** [comment]
separate dashboards for repo vs repo_group would help, are the other items implementable? being able to add filters for sig/wg label and company? k/enhancements filepaths might work but for k/k it'd be much more of a challenge and things do change there :(

**Comment by lukaszgryglicki** [comment]
Labels and company filter will be do-able, just need a list of dashboards to update, so I know which ones should have an additional filters and which ones should also be implemented per repo instead of per repo group. Anyway, will take a bit because I also need to implement LF items.

**Comment by mrbobbytables** [comment]
No worries, I can get you that list by the end of the week at the latest :)

**Comment by lukaszgryglicki** [comment]
OK, thanks.

**Comment by mrbobbytables** [comment]
Here are the dashboards we'd like to be able to have an additional per-repo breakdown:

- Community sizing and health assessment dashboards
  - Companies contributing to repository groups
  - Company Statistics by Repository Group
  - GitHub Stats by Repository Group
  - Overall Project Statistics
- Contributor statistics dashboards
  - Bot commands by repository group
  - Company PRs in repository groups
  - Contributions chart
  - Developer Activity Counts by Companies
  - Developer Activity Counts by Repository Groups
  - New and Episodic PR Contributors
  - New contributors
  - PR Reviews by Contributor
  - PR authors repository groups
 - Issue velocity dashboards
   - Inactive Issues by SIG
   - Issues age by SIG and repository groups
   - Issues Opened/Closed by SIG
   - New And Episodic Issue Creators
- PR velocity dashboards
  - Awaiting PRs by SIG
  - Blocked PRs by repository groups
  - Inactive PRs by SIG
  - Open PR Age by Repository Group
  - PR Time to Approve and Merge
  - PR Time to Engagement
  - PR Workload per SIG Chart
  - PR Workload per SIG Table
  - PR approval repository groups
  - PR labels by SIG
  - PR labels repository groups
  - PRs opened by SIG

**Comment by lukaszgryglicki** [comment]
Wow, a lot of them, can I just add another "repo" drop-down on each of them and then duplicate all panels on each of them, so for example if a given dashboard has repository group drop-down and 3 panels, it will have repository group and repository drop-downs and 6 panels - 3 for repo groups and 3 for repositories?
Otherwise the number of dashes will become so overwhelming...

Makes sense?

**Comment by lukaszgryglicki** [comment]
On it, at least in `data` level - so then I can decide about UI changes: new dashboards or new panels within existing dashboards (my preference).

**Comment by mrbobbytables** [comment]
On the same dashboard in panels is fine 👍

**Comment by lukaszgryglicki** [comment]
OK, so I'll be updating one by one (first to get data), then I'll update the UI and finally I'll let u know.

**Comment by lukaszgryglicki** [comment]
Regarding [GitHub Stats by Repository Group](https://k8s.devstats.cncf.io/d/48/github-stats-by-repository-group?orgId=1) it already have repos version: [GitHub Stats by Repositories](https://k8s.devstats.cncf.io/d/49/github-stats-by-repository?orgId=1).

**Comment by mrbobbytables** [comment]
Oh woops, I might have accidentally included that on my list^^;;

**Comment by lukaszgryglicki** [comment]
Back on this...

**Comment by lukaszgryglicki** [comment]
`Community sizing and health assessment dashboards` data part finished, now updating `Contributor statistics dashboards` dashboards... when I finish data part for all dashboards I'll run data-sync and add new panels (per-repo basis) in all of them.

**Comment by lukaszgryglicki** [comment]
`PR Reviews by Contributor` is already bease on repo not repo group - [see this](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1), skipping.

**Comment by lukaszgryglicki** [comment]
`Contributor statistics dashboards` section finished (data part), proceeding to `Issue velocity dashboards`.

**Comment by lukaszgryglicki** [comment]
@mrbobbytables for `Inactive Issues by SIG` I will need some feedback. This dashboard has no repository groups nor repositories dropdown. So this is not about adding "repositories" in addition to "repository groups" - but considering both options. Should I create a dashboard for repo groups? repos? both? separate dashboard? new panels within this one?

This will also be a case for some other dashboards - what should I do?

Here is the list of such dashboards:
- Inactive Issues by SIG
- Issues Opened/Closed by SIG
- Awaiting PRs by SIG
- Inactive PRs by SIG
- PR Workload per SIG Chart
- PR Workload per SIG Table
- PR labels by SIG
- PRs opened by SIG

Note that all of them are "per SIG" and I think if something is already split by SIG (which are defined as repo groups) then we should not add repo group drop down there. Say you have `PR labels by SIG` dashboard - you choose `SIG Node` SIG and then you also have `repository` drop-down - and you choose a repo unrelated to anything from SIG node - like some repo from AWS EBS storage driver, etc. This makes no sense to me.

Some of those dashboards have a corresponding "repository group" one (but without SIG in them obviously), some not. For those having a corresponding "repository group" I can just add a "repository" dropdown and that will work. But for those which don't have a "repository group" version should I just create new ones which will have both "repo group" and "repository" drop-downs instead of "SIG" one?

Need feedback to proceed. Data for 2 first groups `Community sizing and health assessment dashboards` and `Contributor statistics dashboards`.

Thanks!

**Comment by mrbobbytables** [comment]
> @mrbobbytables for Inactive Issues by SIG I will need some feedback. This dashboard has no repository groups nor repositories dropdown. So this is not about adding "repositories" in addition to "repository groups" - but considering both options. Should I create a dashboard for repo groups? repos? both? separate dashboard? new panels within this one?

Repos I think would be the preferred option - the main thing this would let us do is get a break down for the larger shared repos such as kubernetes/kubernetes and kubernetes/enhancements. As far as separate dashboard or panel, that shouldn't matter too much - whichever method is easiest to implement.

> Note that all of them are "per SIG" and I think if something is already split by SIG (which are defined as repo groups) then we should not add repo group drop down there. 

I thought most of those dashboards were filtering by the `sig/*` and `wg/*` labels based off this description at the bottom of the dashboards and not repo groups:

_"PR belongs to SIG by using `sig/*` labels. List of SIGs to display in drop-down comes from all `sig/*` labels."_

If so, I'd be okay omitting repo_group, but repo would still be nice to drill down into the larger shared repos. 

Thinking about it a bit further, a separate dashboard that'd be something like: "Inactive Issues by Repo" with an additional filter for `sig/*` and `wg/*` labels might be a better way represent the problem. That way people could look at both the shared repos (kubernetes/kubernetes) and the other repos where the work is delegated to subproject owners. Examples for both personas:
-  As a SIG lead that works out of a shared repo (e.g. kubernetes/kubernetes), I'd like to know if we're improving our response time to issues for items that only belong to my SIG. (filter by `sig/*` label)
- As a subproject owner (e.g. kubernetes/contributor-site) I'd like to see if we're improving our response time for the subproject (everything in that specific repo).

> Some of those dashboards have a corresponding "repository group" one (but without SIG in them obviously), some not. For those having a corresponding "repository group" I can just add a "repository" dropdown and that will work. But for those which don't have a "repository group" version should I just create new ones which will have both "repo group" and "repository" drop-downs instead of "SIG" one?

I think a separate one would be good and would align with the thought I had above. BTW - if you think it'd be easier to have a convo, I'm happy to follow up in slack or hop on a call or something 👍 

Seriously, thanks for all your work on this @lukaszgryglicki. I know this has been quite a large ask.

**Comment by lukaszgryglicki** [comment]
@mrbobbytables yes you're right, some dashboards distinguish SIG via labels, some via sig-metions. Repo groups are defined sets of repos just named "SIG XYZ" - I'll do what you suggested. I'll just take each dashboard one-by-one and try to figure out the best approach for all of them. WIll continue on this on Monday, but because I also work on other projects it may take a bit to completely finish this task.

**Comment by lukaszgryglicki** [comment]
So for example `Inactive Issues by SIG` I'll add another dashboard `Inactive Issues by SIG & Repository`.

**Comment by lukaszgryglicki** [comment]
Looks like I'm finishing the data part, next I'll generate the data and finally update dashboards - will continue this today and then on Friday.

**Comment by lukaszgryglicki** [comment]
SQLs for all new dashboards finished, now data is being added to `test` DevStats instance, and while data is adding I'm updating dashboards (adding `repo` drop-down, `repo` related panels and updating docs), 1st dashboard finished (on the `test` instance).
- [PR Time to Engagement](https://k8s.teststats.cncf.io/d/14/pr-time-to-engagement?orgId=1).

If all new SQL works c orrectly I'll update the hourly sync to also calculate new data (so we will keep this new data up-to-date) and I'll be updating dashboards one after another. Will let you know when all finished on the test.

**Comment by lukaszgryglicki** [comment]
2nd dashboard (and fixed two SQL bugs on the way): https://k8s.teststats.cncf.io/d/11/companies-contributing-in-repository-groups?orgId=1.

**Comment by lukaszgryglicki** [comment]
3rd dashboard: https://k8s.teststats.cncf.io/d/8/company-statistics-by-repository-group?orgId=1 (a bit more complex, per-repo panels on the bottom).

**Comment by mrbobbytables** [comment]
Thanks! The per repo break down is a big improvement already - I do have a few follow-up questions:
1) For some of these do you still plan to do a separate dashboard for repo + sig/wg label? e.g. for the `PR Time to Engagement` dashboard, the per-repo breakdown solves the problem for subprojects that have their own repo, but not issue for the large shared repos where a SIG would like to view how they're doing in there >_<
2) Following up on problem 3, is it still possible to add a company filter to all the dashboards where appropriate?

**Comment by lukaszgryglicki** [comment]
1. So I would have to create other panels with SIG data
2. I can, but will need a list of dashboards for that.

I suggest that I'll finish with adding repo where requested, you'll check it then, and let me know where else I need to add SIG and/or company filters.

**Comment by mrbobbytables** [comment]
> 2. I can, but will need a list of dashboards for that.

I can do that, but as a heads up it will be most of them - similar to https://github.com/cncf/devstats/issues/289#issuecomment-796263127

> I suggest that I'll finish with adding repo where requested, you'll check it then, and let me know where else I need to add SIG and/or company filters.

kk

**Comment by lasomethingsomething** [comment]
Seconding @mrbobbytables' point that the filters would pretty much apply to most of the dashboards listed in [#289 (comment)](https://github.com/cncf/devstats/issues/289#issuecomment-796263127).

**Comment by lukaszgryglicki** [comment]
I'm working on that, but only Fridays and Mondays. Last Monday was a holiday and I had some family emergency on Friday - so no progress was made, but I will finish this and let you know.

**Comment by lasomethingsomething** [comment]
Sounds good @lukaszgryglicki -- and I hope everything is ok with your family.

**Comment by lukaszgryglicki** [comment]
Yeah, my son fell from a fence with a sharp metal ending. He had a very big arm would - we called 911 and an ambulance took him to a hospital. Tomorrow we have another visit to remove 18 stitches.

**Comment by lasomethingsomething** [comment]
Oh my, that sounds stressful for you and painful for him. Sending you all best wishes for tomorrow.

**Comment by lukaszgryglicki** [comment]
Back on this - needed to add 5 new CNCF projects in the meantime (so I had no time to work on this).

**Comment by lukaszgryglicki** [comment]
Bot commands on the [test site](https://k8s.teststats.cncf.io/d/5/bot-commands-repository-groups?orgId=1).

**Comment by lukaszgryglicki** [comment]
- [Contributions chart](https://k8s.teststats.cncf.io/d/74/contributions-chart) updated.
- [New and episodic PR contributors](https://k8s.teststats.cncf.io/d/18/new-and-episodic-pr-contributors) updated.
- [New and episodic Issue creators](https://k8s.teststats.cncf.io/d/19/new-and-episodic-issue-creators) updated.

**Comment by lukaszgryglicki** [comment]
- [New conributors](https://k8s.teststats.cncf.io/d/52/new-contributors?orgId=1) updated.
- [PRs authors](https://k8s.teststats.cncf.io/d/30/prs-authors-repository-groups) updated.

**Comment by lukaszgryglicki** [comment]
Finishing data generation part for other dashboards (it failed due to some bug, investigating).

**Comment by mrbobbytables** [comment]
Thanks for all your effort on this @lukaszgryglicki :) It's very much appreciated.

**Comment by lukaszgryglicki** [comment]
I will continue on Monday, then I need to switch to LF tasks and then again Friday and so on...

**Comment by lukaszgryglicki** [comment]
- [Overall Project Statistics](https://k8s.teststats.cncf.io/d/24/overall-project-statistics?orgId=1) updated.
- [Company PRs](https://k8s.teststats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1) updated.
- [Developer Activity Counts by Repository Group](https://k8s.teststats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1) updated.
- [Developer Activity Counts by Companies](https://k8s.teststats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1) updated.
- [PR Workload Table](https://k8s.teststats.cncf.io/d/34/pr-workload-per-sig-table?orgId=1) updated.

Updated them on the `test` env, before I'll be done for a day I'll update `prod` ones as well.

**Comment by lukaszgryglicki** [comment]
- [Blocked PRs](https://k8s.teststats.cncf.io/d/4/blocked-prs-repository-groups?orgId=1) updated.
- [Open PR Age](https://k8s.teststats.cncf.io/d/25/open-pr-age-by-repository-group?orgId=1) updated.
- [PRs approval](https://k8s.teststats.cncf.io/d/26/prs-approval-repository-groups?orgId=1) updated.
- [PR Time to Approve and Merge](https://k8s.teststats.cncf.io/d/44/pr-time-to-approve-and-merge?orgId=1) updated.

**Comment by lukaszgryglicki** [comment]
9 dashboards updated on the `test` also updated in `prod`.

**Comment by lukaszgryglicki** [comment]
- [PRs labels by repository](https://k8s.teststats.cncf.io/d/76/prs-labels-repositories) added.

**Comment by lukaszgryglicki** [comment]
Few more complex dashboards need some data format fixes - just detected this, so I'm regenerating data for them and fixing SQLs first.

**Comment by lukaszgryglicki** [comment]
- [Inactive Issues by SIG and repository](https://k8s.teststats.cncf.io/d/77/inactive-issues-by-sig-and-repository?orgId=1).

**Comment by lukaszgryglicki** [comment]
- [Inactive PRs by SIG and repository](https://k8s.devstats.cncf.io/d/78/inactive-prs-by-sig-and-repository).

**Comment by lukaszgryglicki** [comment]
- [Awaiting PRs by SIG and repository](https://k8s.devstats.cncf.io/d/79/awaiting-prs-by-sig-and-repository).

**Comment by lukaszgryglicki** [comment]
- [PR workload per SIG and repository Chart](https://k8s.teststats.cncf.io/d/80/pr-workload-per-sig-and-repository-chart).

**Comment by lukaszgryglicki** [comment]
- [Issues age by SIG and repository groups](https://k8s.teststats.cncf.io/d/15/issues-age-by-sig-and-repository-groups).

**Comment by lukaszgryglicki** [comment]
- [Issues age by SIG and repository groups](https://k8s.devstats.cncf.io/d/15/issues-age-by-sig-and-repository-groups).
- [Issues opened/closed by SIG](https://k8s.devstats.cncf.io/d/39/issues-opened-closed-by-sig).
- [PRs opened by SIG](https://k8s.devstats.cncf.io/d/69/prs-opened-by-sig).

**Comment by lukaszgryglicki** [comment]
With this, all requested dashboards now have `Repository` drop-down added.

**Comment by mrbobbytables** [comment]
Thank you @lukaszgryglicki \o/

**Comment by lukaszgryglicki** [comment]
Sorry for being a bit slow on this one, but I also have other projects...

**Comment by mrbobbytables** [comment]
No worries, I understand - it was also a big one^^;;;

**Comment by mrbobbytables** [comment]
btw...not to immediately add more work :x but for problem 3 (companies), would you still like a list of dashboards where it'd be desired?

**Comment by lukaszgryglicki** [comment]
Yeah, give me a list of those that need a company drop-down too - I can try to handle by a similar approach (add company drop-down where needed), but maybe it would be better to give such a list in a separate issue (to distinguish that work) and close this one?

**Comment by mrbobbytables** [comment]
I'll get you that list by end of the week 👍

**Comment by lasomethingsomething** [comment]
Thank you @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Can we close this and continue adding the company filter in a separate feature request?

**Comment by mrbobbytables** [comment]
> Can we close this and continue adding the company filter in a separate feature request?

I think so, I'll copy out the part about it in the original comment

**Comment by lukaszgryglicki** [comment]
Thanks.

**Comment by mrbobbytables** [comment]
I know this is closed, but going through and using several this weekend I have a few follow ups where it'd be ideal to add additional filters for sig labels (e.g. on the [contributions chart](https://k8s.devstats.cncf.io/d/74/contributions-chart?orgId=1) for breakdown in large shared repos)

I'll think about it and put together a follow up issue, but wanted to give a heads up 👍

**Comment by lukaszgryglicki** [comment]
OK, no problem. Please reopen then.
