### ISSUE TITLE
[bug] Devstats for Backstage is outdated

### ISSUE THREAD

**Issue by OrkoHunter** [cncf/devstats.archive#291]
Hello from @spotify and @backstage !

We noticed that Backstage's stats on https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1 is not being updated since November 2020.

It's possible that this is due to us moving the project from `github.com/spotify/backstage` to `github.com/backstage/backstage`.

I'm not familiar with how this project is setup, but my initial guess is that on line
https://github.com/cncf/devstats/blob/master/backstage/psql.sh#L16

`spotify/backstage` should be `backstage/backstage`.

Although, leaving this on experts to review!

<img width="175" alt="Screenshot 2021-04-20 at 1 31 26 PM" src="https://user-images.githubusercontent.com/8065913/115360847-a3a0c980-a1dd-11eb-9b0f-719681d9f122.png">

**Comment by lukaszgryglicki** [comment]
yes, this will be the reason, I'll fix this - thanks for reporting.

**Comment by OrkoHunter** [comment]
Awesome, thank you so much! 🤞

**Comment by lukaszgryglicki** [comment]
This is also because the release tag format changed around here: https://github.com/backstage/backstage/tags?after=release-2021-01-09
DevStats was expecting somethis like `vX.Y.Z` [here](https://github.com/cncf/devstats/blob/master/projects.yaml#L935).

**Comment by OrkoHunter** [comment]
Aah, I see!

**Comment by lukaszgryglicki** [comment]
Updated regexp, will reinit that DevStats instance and let you know when ready.

**Comment by OrkoHunter** [comment]
Hi @lukaszgryglicki ! Wondering if the investigation on this is still ongoing? Thank you!

**Comment by lukaszgryglicki** [comment]
yes, but I can only work on this in some limited time, so I've fixed the config and regenerated a backstage DevStats instance, now I will also need to update "All CNCF" to include new versions - will do when I can - added to my TODO list for the next week.

**Comment by OrkoHunter** [comment]
Thanks for sharing the update @lukaszgryglicki - appreciate it. 🙏

**Comment by lukaszgryglicki** [comment]
Should be fixed now, thanks for reporting.

**Comment by OrkoHunter** [comment]
Thank you so much for your swift actions on resolving this. 👏
