### ISSUE TITLE
[bug] Sandbox project vineyard has been migrated to v6d-io/v6d

### ISSUE THREAD

**Issue by sighingnow** [cncf/devstats.archive#296]
Hi @lukaszgryglicki,

I'm from the team behind project vineyard. During our [onboarding process](https://github.com/cncf/toc/issues/645), we have transfer our repo from `alibaba/v6d` to a neutral org [`v6d-io/v6`](https://github.com/v6d-io/v6d).

Could you please us to update related devstats settings to make it work again?

Thanks in advance!

**Comment by lukaszgryglicki** [comment]
Will do on Monday, today is a holiday.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by sighingnow** [comment]
Thank you Łukasz!
