### ISSUE TITLE
[feature request] Argoproj-albs added to Argo 

### ISSUE THREAD

**Issue by amye** [cncf/devstats.archive#297]
From @edlee2121: 
Is it possible to do a devstat dashboard for the https://github.com/argoproj-labs org similar the one that exists for the main argo (aroproj) org at https://argo.devstats.cncf.io/dashboards?

**Comment by caniszczyk** [comment]
@lukaszgryglicki will add it to the argo dashboard but have argoproj-labs as a repogroup to allow filtering

**Comment by lukaszgryglicki** [comment]
On it now.

**Comment by lukaszgryglicki** [comment]
All files updated, now generating historical data for all `argoproj-labs` repos starting at 2019-04-12 (which is the first activity date for any repo from that org according to BigQuery).

**Comment by lukaszgryglicki** [comment]
Done.
