### ISSUE TITLE
[feature request] Add companies filter to Opened to Merge chart

### ISSUE THREAD

**Issue by tdcmeehan** [cncf/devstats.archive#298]
I am looking at Presto's  dashboards: https://prestodb.devstats.prestodb.io/d/8/dashboards?orgId=1&refresh=15m (I reached this repository by following the link on the top right.)

It would be very useful to filter by company in the Opened to Merged chart:

https://prestodb.devstats.prestodb.io/d/16/opened-to-merged?orgId=1

The reasoning is, we want to make sure all community contributors have a good, fast time to merge, and to help understand this it would be useful to filter by company.

**Comment by lukaszgryglicki** [comment]
Makes sense, I'll try to implement asap, expect something around few days.

**Comment by lukaszgryglicki** [comment]
On it now.

**Comment by lukaszgryglicki** [comment]
Done [click](https://prestodb.devstats.prestodb.io/d/16/opened-to-merged?orgId=1).
