### ISSUE TITLE
How to use devstats on a Cloud Grafana instance? 

### ISSUE THREAD

**Issue by kristydv** [cncf/devstats.archive#300]
Hi there. I am a community manager with limited developer knowledge. Devstats looks awesome and exactly what I need.. I have a Grafana cloud instance though - I couldn't find any instructions on how I use this on on cloud? I've read https://github.com/cncf/devstats/blob/master/GRAFANA.md but that doesn't seem to apply.

Would love to get a bit of help on how I would set this up on my cloud instance..

Thanks!

**Comment by lukaszgryglicki** [comment]
Devstats is designed to run on Kubernetes, it includes Grafana then (no need for cloud instance), older Devstats implementation used a Grafana deployed locally (on your machine) - I have no knowledge about what Grafana Cloud is and how to use it, you can always try to adopt Devstats to it - it's totally open source so you can just fork and make any changes that are necessary.

**Comment by kristydv** [comment]
Thanks for the info @lukaszgryglicki
