### ISSUE TITLE
[feature request] remove independent from Ranking it in devstat

### ISSUE THREAD

**Issue by RA489** [cncf/devstats.archive#301]
Independent is given 6th on company ranking as per https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.21.0%20-%20now&var-metric=prs

we can keep independent and number but can we just remove from ranking it like we do in openstack community https://www.stackalytics.io/

**Comment by RA489** [comment]
cc @lukaszgryglicki

**Comment by caniszczyk** [comment]
uh I'd like to leave it in

**Comment by lukaszgryglicki** [comment]
Same with me, what's the problem with subtracting just `1`.

**Comment by xmulligan** [comment]
I agree with leaving it in. I think it is important to show how valuable individual contributors are to the community
