### ISSUE TITLE
[bug] Tekton stats suddenly stop in May (CDF devstats)

### ISSUE THREAD

**Issue by tracymiranda** [cncf/devstats.archive#303]
Tekton folks noticed that devstat data suddenly stops at some point in May https://tekton.devstats.cd.foundation/d/48/users-statistics-by-repository-group?orgId=1 - any idea what happened or how we can fix it?

**Comment by lukaszgryglicki** [comment]
Will take a look after my PTO.

**Comment by afrittoli** [comment]
@vdemeester

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
[Fixed](https://tekton.devstats.cd.foundation/d/48/users-statistics-by-repository-group?orgId=1). Thanks for reporting!

**Comment by tracymiranda** [comment]
Awesome, thank you so much!
