### ISSUE TITLE
"New & Occasional PR" chart displaying issues, not PRs, and vice-versa

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#304]
[bug]

See: https://kubevirt.devstats.cncf.io/d/14/new-and-episodic-pr-contributors?orgId=1&var-period=w&var-repogroup_name=All

The chart is at least showing labels for issues and not for PRs.  Not sure what the data is.

And the Issue chart is displaying PRs as labels:

https://kubevirt.devstats.cncf.io/d/13/new-and-episodic-issue-creators?orgId=1

**Comment by lukaszgryglicki** [comment]
I'm on PTO- will investigate this when I'm back, but every PR is also an issue - and labels can (technically) be only added on issues, not PRs - so each PR has a corresponding issue-type object (issue with a PR flag).

**Comment by jberkus** [comment]
Look at it when you're back, if you actually look at the charts, the problem is obvious.

**Comment by lukaszgryglicki** [comment]
Ohhh I've checked the data and is OK - this is just an UI labels issue - right, will fix it and let u know.

**Comment by lukaszgryglicki** [comment]
Fixed.
