### ISSUE TITLE
`column "perezjasonr" does not exist` on teststats user statistics page

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#305]
https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group gives error `db query error: pq: column "perezjasonr" does not exist`. Other pages seem to load fine.

This was working at least a few weeks ago, so seems like something recently may have broken things?

**Comment by lukaszgryglicki** [comment]
Works fine for me - there is a `columns` program that makes sure all columns needed on UI are present - maybe there was just a temporary issue? can you eventually confirm that you can still replicate the issue?

**Comment by howardjohn** [comment]
Hmm, seems good now. I think `perezjasonr` is a github user btw. When it was not working, I manually switched "Users: all" to "Users: (some single user)" and it worked. Closing since it seem to be temporary...
