### ISSUE TITLE
https://all.devstats.cncf.io/d/50/countries-statistics-in-repository-groups is broken

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#306]
no data

https://all.devstats.cncf.io/d/50/countries-statistics-in-repository-groups?

**Comment by Mini256** [comment]
I think it's because this metric has not been calculated yet, and it should be accessible correctly after a period of time.

Similar issue: https://github.com/cncf/devstats/issues/305

**Comment by lukaszgryglicki** [comment]
Seems so, because it is available now, and "All CNCF" was being fully regenerated due to new Sandbox projects.
