### ISSUE TITLE
[Question] How to know the top x contributors by company? 

### ISSUE THREAD

**Issue by Jeffwan** [cncf/devstats.archive#307]
Please add `[feature request]` to the issue title when requesting new features, dashboards, projects etc.
Please add `[bug]` to the issue title when reporting a bug.

https://k8s.devstats.cncf.io/d/9/companies-table

I am checking this table and I would like to know the top x contributors of my current company. Is there's a page I can find the information?

**Comment by lukaszgryglicki** [comment]
The closest thing would be [click - example for IBM](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=IBM).

You can select a company there, then keep "repository group = all" (so it will count all kubernetes repos across all orgs), then you can choose "metric = contributions". Look at the first table (it's for repository groups, the 2nd one is for specific repo chosen from the "repository" drop down). In my example, it displays stats for IBM.

If you need anything else - you can browse all companies related dashboards by clicking `Developer Activity Counts by Companies` (dashboard name at the top) and then click "Filter by tag" -> companies.

If you still cannot find the correct data you can create a feature request for a new dashboard or ask me to generate some specific data for you (I can create custom reports of whatever data you may need).

**Comment by Jeffwan** [comment]
@lukaszgryglicki Thanks for your quick response. I just check the example you gave to me and it works fine. Seems there're only "kubernetes" and probably sig repos. checkbox doesn't show other CNCF projects. I am not sure if that's expected? Does CNCF have another global dashboard?

**Comment by lukaszgryglicki** [comment]
You are on the `Kubernetes` DevStats instance (see URL, it starts k8s.devstats). Each CNCF project has its own instance, for example [gRPC](https://grpc.devstats.cncf.io).

There is also a "summary" instance for [All CNCF](https://all.devstats.cncf.io) projects combined - in this instance, each CNCF project is defined as a separate repository group, so you can use [this](https://all.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Red%20Hat) (this is a per company contributors statistics for all CNCF projects combined) - there you can play with different companies, different projects (select anything other than "All" from repo group drop-down) and with different metrics (contributions, commits, PRs, etc.)

**Comment by Jeffwan** [comment]
Thanks @lukaszgryglicki a lot for you guidance!
