### ISSUE TITLE
[bug] Specifics of "last quarter" doesn't show up

### ISSUE THREAD

**Issue by mewzherder** [cncf/devstats.archive#308]
When I look up "last quarter" here:
https://all.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20quarter&var-metric=contributions

I can't tell if it means the last 90 days starting today, or if it means April 1 - June 30, 2021. Maybe I'm missing something but it seems that the dev stats isn't showing this clarification. Maybe an error?

I hope my question makes sense and thanks in advance for your help.
❤ 🤗

**Comment by lukaszgryglicki** [comment]
Hmm, I do have data in that chart... maybe you hit a moment when new affiliations were being imported?

**Comment by Mini256** [comment]
@mewzherder, If I understand correctly, it means the last 90 days starting today.

You can refer to the documentation on [annotations](https://github.com/cncf/devstats/blob/master/docs/annotations.md):

```
       time         |                quick_ranges_data                 | quick_ranges_suffix |  quick_ranges_name  
--------------------+--------------------------------------------------+---------------------+---------------------
2014-01-01 04:00:00 | q;3 months;;                                     | q                   | Last quarter
```
The format of `quick_ranges_data` is `suffix;period;from;to`, `Last quarter` corresponds to period `3 months`, this period value will eventually be passed to the metric SQL statement:

https://github.com/cncf/devstatscode/blob/7db39d84210ea63d01086a8f01724202a7da756d/string.go#L15

**Comment by lukaszgryglicki** [comment]
Actually, this is "last 90 days" starting when that metric was actually calculated - we pre-compute some data, otherwise, this won't be able to run live. So that data might be "Last 90 days" calculated say 2 days ago.

**Comment by lukaszgryglicki** [comment]
You can request this as an API.
