### ISSUE TITLE
 [feature request] Allow any arbitrary date range based data.

### ISSUE THREAD

**Issue by RA489** [cncf/devstats.archive#309]
K8s devstat dashboard should allow contribution or PR data based on any arbitrary date range.
https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&from=now-7d&to=now
It should respect data based on any arbitrary date range. 

PS:  Currently dashboard is pre-calculated for some specified date ranges from range dropdown.

**Comment by lukaszgryglicki** [comment]
This dashboard (as all other tabular dashboards) is pre-calculated for a set of date ranges (Last X periods and between versions etc.). This is because they are complex and calculating them in real-time/on the fly is too slow. I cannot *guess* all possible date periods needed, so it's impossible to allow any date range there unless I rebuild the entire dashboard not to use any kind of pre-calculation and do its math in real-time instead.
My suggestion is to add this in DevStas [API](https://github.com/cncf/devstatscode/blob/master/API.md) instead, what do you think? cc @caniszczyk

**Comment by RA489** [comment]
> My suggestion is to add this in DevStas [API](https://github.com/cncf/devstatscode/blob/master/API.md)

+1 on adding this in Devstats API.

**Comment by lukaszgryglicki** [comment]
OK, I'll add this in API, I'll try to do this till end of this week.

**Comment by RA489** [comment]
> OK, I'll add this in API, I'll try to do this till end of this week.

Thanks!!

**Comment by lukaszgryglicki** [comment]
Implemented, also updated API [documentation](https://github.com/cncf/devstatscode/blob/master/API.md), APIs that you will need are called:
- `DevActCnt` (search for `Companies contributing in Repository Groups/Repositories` in the docs).
- `DevActCntComp` (search for `"Developer Activity Counts by Companies" DevStats dashboards` in the docs).

There are also example `cURL` scripts (note that scripts ending with `_repos.sh` use "repositories" (like `kubernetes/kubernetes`) not repository groups (like `SIG Node`). Also note there are versions for companies (`_comp.sh` and `_comp_repos.sh`) - basically those scripts correspond to two dashboards (one split by companies and one without company split) - both of them have two tabular views (one for repo groups and one for repositories) - that gives 2 x 2 = 4 scripts:
- [no companies, repo groups](https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt.sh).
- [no companies, repsitories](https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt_repos.sh)
- [companies, repo groups](https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt_comp.sh).
- [companies, repositories](https://github.com/cncf/devstatscode/blob/master/devel/api_dev_act_cnt_comp_repos.sh).

Parameters are the same as corresponding UI drop-down values, companies allow to specify multiple companies.

Example calls:
- `API_URL="https://devstats.cncf.io/api/v1" ./devel/api_dev_act_cnt.sh kubernetes 'range:2021-08-20,2021-09-01' 'Commits' 'SIG Node' 'United States' ''`.
- `API_URL="https://devstats.cncf.io/api/v1" ./devel/api_dev_act_cnt_repos.sh kubernetes 'range:2021-08-20,2021-09-01' 'Commits' 'kubernetes/test-infra' 'United States' ''`.
- `API_URL='https://devstats.cncf.io/api/v1' ./devel/api_dev_act_cnt_comp.sh kubernetes 'range:2021-08-20,2022' 'Reviews' 'SIG Node' 'All' '["Google", "Red Hat"]' ''`.
- `API_URL='https://devstats.cncf.io/api/v1' ./devel/api_dev_act_cnt_comp_repos.sh kubernetes 'range:2021-08-20,2022' 'Reviews' 'kubernetes/test-infra' 'All' '["Google", "Red Hat"]' ''`.

And finally, If you want a raw cURL example:
```
curl -s -H 'Content-Type: application/json' https://devstats.cncf.io/api/v1 -d'{"api":"DevActCntComp","payload":{"project":"kubernetes","range":"range:2021-08-20,2021-09","metric":"Reviews","repository_group":"SIG Node","country":"All","companies":["Google", "Red Hat"],"github_id":"","bg":""}}' | jq -rS '.'
```

Hope that helps @RA489 , cc @caniszczyk

**Comment by RA489** [comment]
Thanks for the API @lukaszgryglicki . Much appreciated.
