### ISSUE TITLE
Add exporting options

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#31]
Would it be possible to add an exporting feature to dashboards? If it's a matter of selecting a 'top 10' dashboards of importance to do this, I can select those. Looking for excel, csv, etc. options. json is fine for devs and the like but people using this tool may not have experience with that format. This will allow for others to easily consume the data in the format that they feel comfortable with.

**Comment by lukaszgryglicki** [comment]
This is a feature that I can write, but I need many details, like for which dashboards (maybe all), some suggestion where to put that feature in the UI, maybe a link somewhere? But what should it export? For which data periods etc. etc.?
I may require some Grafana support, or maybe some suggestion how exactly should it work?
@dankohn ?

**Comment by dankohn** [comment]
I would perhaps model on the download (down arrow) feature in Google
Trends:
https://trends.google.com/trends/explore?date=2016-01-01%202017-10-01&q=kubernetes,mesos,docker%20swarm,cloud%20foundry,openstack

You click the link and it downloads a CSV containing all data points used
to construct the graph. Note that CSV opens in Excel by default on Mac and
Windows.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by dankohn** [comment]
Seems like this functionality is already built into Grafana: https://community.grafana.com/t/export-csv-data/2233/6

**Comment by lukaszgryglicki** [comment]
Nice, will take a look.

**Comment by lukaszgryglicki** [comment]
Every dashboard can be exported top CSV using panel menu like this:
![screen shot 2017-12-18 at 09 43 17](https://user-images.githubusercontent.com/2469783/34097061-fa3023b2-e3d7-11e7-82ea-7289ab7f69eb.png)
Let me know if this is enough or do we need some custom export to be implemented.

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if Grafana's Export to CSV is not enough.

**Comment by dankohn** [comment]
What's the first step to access the Export to CSV widget? Is it available in an incognito window?

**Comment by lukaszgryglicki** [comment]
Yes, it is available - you need to click on the upper part of a chart/table - any dashboard.
Window like this one on screenshot appears and then You can export - there are two options "Series as rows" and "Series as columns"
In case of a home dashboard you need to click on the header: "Hourly Kubernetes activity on GitHub" and the menu icon on the left.
Generated CSV file LGTM.

**Comment by dankohn** [comment]
Clicking on the chart title is what worked for me.

Please create an export.md or similar that gives directions and is linked
from the readme. Also, most of what is on the readme should go in a
development.md and the readme should be targeted toward more casual users.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Added link in the main README.
https://github.com/cncf/devstats/blob/master/EXPORT.md
Closing, please reopen if needed.
