### ISSUE TITLE
[bug] Countries don't list 

### ISSUE THREAD

**Issue by xmulligan** [cncf/devstats.archive#311]
Both the countries table and map don't work under all CNCF projects 
![image](https://user-images.githubusercontent.com/29048870/132692251-99b42c45-be7f-46bd-b2c6-05ac68c95aaa.png)

**Comment by lukaszgryglicki** [comment]
On it...

**Comment by lukaszgryglicki** [comment]
Should be [fixed](https://all.devstats.cncf.io/d/50/countries-statistics-in-repository-groups?orgId=1) now.

**Comment by xmulligan** [comment]
Thanks!
