### ISSUE TITLE
[bug] Certificate on devstats.cncf.io is expired

### ISSUE THREAD

**Issue by atoato88** [cncf/devstats.archive#313]
when I access to devstats page as following:
https://devstats.cncf.io

It says certificate is expired.
And I could not get the page.

**Comment by lukaszgryglicki** [comment]
There was a problem with `cert-manager` auto-renewal. No idea why it failed and didn't auto-retry. I've dropped the cert and then `cert-manager` succeeded with another auto-renewal.

**Comment by atoato88** [comment]
Thank you to quick fix! 😄
