### ISSUE TITLE
[Question] Replace the dragonfly github repo

### ISSUE THREAD

**Issue by gaius-qi** [cncf/devstats.archive#314]
The Dragonfly project will migrate the github repo from https://github.com/dragonflyoss/Dragonfly to https://github.com/dragonflyoss/Dragonfly2.

I have changed the repo address of dragonfly in the project [cncf/landscape](ttps://github.com/cncf/landscape/pull/2272).

Do I need to change the repo address associated with general(https://github.com/cncf/devstats) statistics?

**Comment by lukaszgryglicki** [comment]
No changes should be needed inside devstats because it tracks the entire `dragonflyoss` org.

**Comment by lukaszgryglicki** [comment]
Closing, please reopen if needed.
