### ISSUE TITLE
[kubernetes] Data export request

### ISSUE THREAD

**Issue by coderanger** [cncf/devstats.archive#316]
Hi there, we're setting up the voter rolls for the next Kubernetes elections round. Can I get a dump of everyone who has at least 50 contributions in the system between 2020-09-15 and 2021-09-15? Alternatively if this is a thing I can write SQL for myself in Grafana, I'm happy to :)

**Comment by lukaszgryglicki** [comment]
I'll generate this data and send it to you.

**Comment by lukaszgryglicki** [comment]
generated spreadsheet for you - shared on the slack channel.
Also providing CSV:
[k8s_yearly_contributors_with_50.csv](https://github.com/cncf/devstats/files/7183327/k8s_yearly_contributors_with_50.csv)
