### ISSUE TITLE
Change to the repos that are in k3s devstats

### ISSUE THREAD

**Issue by cjellick** [cncf/devstats.archive#319]
Hi,

I'm one of the maintainers of k3s. I think we need some tweaks to the GitHub projects that are included on our devstats page.

First, only projects in the `k3s-io` organization need to be included. When the devstats page was setup originally, it looks like some projects from the `rancher` org and from `ibuildthecloud`'s personal org were also included. See: https://github.com/cncf/devstats/blob/master/k3s/psql.sh#L16

Second, the k3s-io org has some repos that are forks of upstream projects. These should be excluded because I think including them is throwing off our stats:
- klog
- containerd
- cri-tools
- kubernetes
- etcd
- cri
- protobuf
- continuity
- flannel
- go-powershell
- nocode

If it is easier to just whitelist the repos we DO want to track, rather than exclude the above forks, here's the list of projects that should be tracked:
- image-mirror
- docs
- test-plans
- k3s-root
- helm-set-status
- kine
- k3s-ansible
- helm-controller
- klipper-lb
- k3s-upgrade
- k3s-selinux
- klipper-helm
- k3s

**Comment by lukaszgryglicki** [comment]
Will work on that, but please note that if you only include a hardcoded set of repos, this won't track any new repos under an org. It's better to specify exclude list or regexp.

**Comment by cjellick** [comment]
Makes sense. If you can make the exclude list I provided work, that would be great.

**Comment by lukaszgryglicki** [comment]
On it, will add exclusion list

**Comment by lukaszgryglicki** [comment]
DevStats [page](https://cilium.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m) added.

**Comment by lukaszgryglicki** [comment]
Done, [instance](https://k3s.devstats.cncf.io) data regenerated.
