### ISSUE TITLE
Contributors by Release

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#32]
Similar to the Top Comments Dashboard, it would be very beneficial for easily accessible data on who contributed to each release by their handle, including # of PRs, and the repo that they went into. We can then filter by the repo and the release date/number.

**Comment by jberkus** [comment]
If Lukas can't do this soon, it sounds like a good starter project for me.

**Comment by lukaszgryglicki** [comment]
Who is a contributor?
PR creator?
Issue creator?
Committer?
Commenter?
Commit commenter?
Issue commenter?
PR reviewer?
Any combination of this?
Somebody not listed above?
We need a clear definition.

**Comment by parispittman** [comment]
I'd say PR&issue creators that have merged. Most likely combinations of what you are describing. I'm opening up this convo in sig-release, more soon.

**Comment by lukaszgryglicki** [comment]
Great, thanks.

**Comment by lukaszgryglicki** [comment]
While working on #36 I've implemented new dashboard.
Please see this comment: https://github.com/cncf/devstats/issues/36#issuecomment-353025837
Closing because this should be enough.
Please reopen if needed.
