### ISSUE TITLE
[bug] missing data for k3s

### ISSUE THREAD

**Issue by cjellick** [cncf/devstats.archive#320]
Sorry for the flurry of issues!

I was looking at some of our stats and I think for some reason we aren't see expected data for k3s.

For example, the k3s-io/k3s repo is pretty active with contributions [as can be seen on the GH contributors page](https://github.com/k3s-io/k3s/graphs/contributors), but it shows no data for the past year on the contributions page:
https://k3s.devstats.cncf.io/d/74/contributions-chart?var-period=m&var-metric=issues&var-repogroup_name=k3s-io%2Fk3s&var-country_name=All&var-company_name=All&var-company=all

Am I doing something wrong or is it missing data?

**Comment by lukaszgryglicki** [comment]
Will take a look when I can, there can be a delay because I'm on the KubeCon and also have other projects...

**Comment by lukaszgryglicki** [comment]
`k8s-io/k3s` is defined as `K3s` [here](https://github.com/cncf/devstats/blob/master/scripts/k3s/repo_groups.sql#L36) - so you can check its status [here](https://k3s.devstats.cncf.io/d/74/contributions-chart?var-period=m&var-metric=issues&var-repogroup_name=K3s&var-country_name=All&var-company_name=All&var-company=all&orgId=1), but in any case there should not be `k8s-io/k3s` repo group then. I'll check this while removing some repos from that project - requeste don the other issue, I'll close this and handle on that [other issue](https://github.com/cncf/devstats/issues/319).

**Comment by lukaszgryglicki** [comment]
It was comming from `ibuildthecloud/k3s` repo that will be removed anyway (just debugged this).
