### ISSUE TITLE
[feature request][kyverno] Create a  Community health Dashboard graph

### ISSUE THREAD

**Issue by Anita-ihuman** [cncf/devstats.archive#321]
In addition to existing dashboards,  I would like to request a new dashboard to track Community Health.
The dashboard will have similar features to this [dashboards](https://kyverno.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1), except it will take a graph format.

 **Metrics to track**:
- Stargazers 
-  Issue creators
-  Code committers
-  Code commenters

**Comment by lukaszgryglicki** [comment]
Ok so to clarify the specs:
You want charts for those 4 values:
- Per repository? (so there will be a `repository` dropdown)?
- Plus (eventually) summary for all repositories combined?
- Per aggregation periods (bar chart) or cumulative values (like a line chart of values changing in time)?
- If aggregation periods, then which ones?: (Day, Week, Month, Quarter, Year, 7 Days moving average, 24 hours moving average)? Any subset of them can be selected, including all of them
- If line chart then how often data points are needed? Hourly, Daily, Weekly, Monthly?
- By stargazers you mean the number of GitHub repo stars, right?
- By all those 4 metrics you mean numbers like 10 stars, 20 issue creators, 5 code committers, 15 code commenters.
- By code commenters you mean all people who comment on PR, issue, commit or make a review - or just people who make PR reviews or any combination of those - like: people who commented on a PR, commit or made a review (but excluding issue comments)?

Need exact specs to avoid implementing this many times ...

**Comment by Anita-ihuman** [comment]
- Yes, if the charts for each value can be in form of a dropdown, that would be great.
- Yes, a summary of all repositories combined as well.
- Yes, Cumulative Value
- the aggregation periods can be a dropdown too, so we can select the different time intervals as a dropdown.
- Yes line chart, Daily.
- Yes, No of GitHub repo stars.
- Yes,  I meant numbers like 10 stars, 20 issue creators, 5 code committers, 15 code commenters.
- By code commenters I mean a combination of everything you listed, excluding issue comments

**Comment by lukaszgryglicki** [comment]
- So there will be a `repository` drop-down with the `All` option.
- So if this is a cumulative value, then the `aggregation` period makes no sense - this will just display value over time - I'm suggesting daily resolution (so this will be 4 line charts each having data points every day). Aggregations would only be useful when doing a bar chart, say with month resolution - each bar will just have a non-cumulated number of issue creators, commenters, etc in that bar only (not cumulated).
- What do you mean yes - line chart - I've asked about: line chart or bar chart? Or maybe you want two panels - one with line charts (cumulated) and another with bar charts - but, actually, I think that line charts would be enough.
- OK GitHub repo stars.
- OK so code commenters will exclude issue comments.

ETA to start working on this on Monday. Hopefully can finish on Monday as well.

**Comment by Anita-ihuman** [comment]
Alright, then that works. 
Looking forward to it.

**Comment by lukaszgryglicki** [comment]
`Issue creators` - in GitHub PR is also an Issue, so `issue creators` would actually be `PR & Issue creators`. 
Each issue has a flag specifying if this is an issue or PR, so for this report, I'm counting `Issue creators` for issues that aren't PRs.

**Comment by Anita-ihuman** [comment]
That’s issues that are not PR’s

**Comment by lukaszgryglicki** [comment]
Dashboard [implemented](https://kyverno.devstats.cncf.io/d/81/community-health?orgId=1).
