### ISSUE TITLE
[feature request] Improve on Community Health  dashboard 

### ISSUE THREAD

**Issue by Anita-ihuman** [cncf/devstats.archive#323]
We want the Devstat [dashboard](https://kyverno.devstats.cncf.io/d/81/community-health?orgId=1) to have a dropdown similar to the repository dropdown.
The aim is to single out the graph of each metric we select in the dropdown.
The Dropdown will consist of:
- All metrics
- Stargazers
- Code commenters
- Issue Creators
- Code Committers

**Comment by lukaszgryglicki** [comment]
`All metrics`? I think you rather mean to add `All repositories combined` to `Repository` drop-down.
So you would have:
- Repository drop-down, having all possible repos + `All repositories combined` option
- Metric drop-down having: `Stargazers`, `Code commenters`, `Issue Creators`, and `Code Committers`.
That way you will just need a single panel.
If we put `All metrics` in `metric` drop-dow I would need to have a panel that either has a single line or has 4 lines - I don't think this is possible in Grafana to have a variable number of plots depending on the drop-down value.

**Comment by Anita-ihuman** [comment]
Well in the  `All metrics`, I actually meant it should display the 4 metrics in one panel the way it does currently.

**Comment by lukaszgryglicki** [comment]
OK so let me know if my suggestion is OK for you, if not I will try to dig Grafana docs if this is possible.

**Comment by Anita-ihuman** [comment]
Yes, your suggestions sound ok.

**Comment by lukaszgryglicki** [comment]
OK, added "All" option to repository drop-down (so the bottom panel is no longer needed), also added "Metric" drop-down so it doesn't need to display 4 line carts anymore - just one line for currently selected metric.
Implemented [here](https://kyverno.devstats.cncf.io/d/81/community-health?orgId=1).

**Comment by lukaszgryglicki** [comment]
Closing now, please reopen if needed.
