### ISSUE TITLE
[bug] can't get a working share link

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#325]
I'm trying to pull a chart for all PR reviewers in all repos in the last two years and getting a super long URL that doesn't resolve (below) and I tried the shortener as well and that also doesn't load on safari or chrome. http://kubernetes.devstats-grafana-kubernetes-6c45bfb94d-kqd6b:3000/goto/EqRCUpcnz?orgId=1. I've also tried a few other charts and can't seem to get a working link on anything that is a large string. 

https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=q&var-repo_name=All&var-reviewers=%22sbueringer%22&var-reviewers=%22liggitt%22&var-reviewers=%22robscott%22&var-reviewers=%22fabriziopandini%22&var-reviewers=%22sftim%22&var-reviewers=%22wojtek-t%22&var-reviewers=%22aojea%22&var-reviewers=%22vincepri%22&var-reviewers=%22tengqm%22&var-reviewers=%22anubha-v-ardhan%22&var-reviewers=%22alculquicondor%22&var-reviewers=%22Huang-Wei%22&var-reviewers=%22spiffxp%22&var-reviewers=%22CecileRobertMichon%22&var-reviewers=%22thockin%22&var-reviewers=%22ameukam%22&var-reviewers=%22rikatz%22&var-reviewers=%22killianmuldoon%22&var-reviewers=%22msau42%22&var-reviewers=%22ahmetb%22&var-reviewers=%22MikeSpreitzer%22&var-reviewers=%22sttts%22&var-reviewers=%22jpbetz%22&var-reviewers=%22pohly%22&var-reviewers=%22xing-yang%22&var-reviewers=%22cheftako%22&var-reviewers=%22ehashman%22&var-reviewers=%22oomichi%22&var-reviewers=%22sozercan%22&var-reviewers=%22marquiz%22&var-reviewers=%22dims%22&var-reviewers=%22serathius%22&var-reviewers=%22natasha41575%22&var-reviewers=%22lavalamp%22&var-reviewers=%22jsturtevant%22&var-reviewers=%22sashrith%22&var-reviewers=%22enxebre%22&var-reviewers=%22hbagdi%22&var-reviewers=%22marosset%22&var-reviewers=%22deads2k%22&var-reviewers=%22justaugustus%22&var-reviewers=%22apelisse%22&var-reviewers=%22rpanduranga%22&var-reviewers=%22chaodaiG%22&var-reviewers=%22ykakarap%22&var-reviewers=%22randomvariable%22&var-reviewers=%22tam7t%22&var-reviewers=%22hakman%22&var-reviewers=%22pacoxu%22&var-reviewers=%22KnVerey%22&var-reviewers=%22reylejano%22&var-reviewers=%22khenidak%22&var-reviewers=%22neolit123%22&var-reviewers=%22alvaroaleman%22&var-reviewers=%22ahg-g%22&var-reviewers=%22swatisehgal%22&var-reviewers=%22tkashem%22&var-reviewers=%22karlkfi%22&var-reviewers=%22jichenjc%22&var-reviewers=%22puerco%22&var-reviewers=%22dgrisonnet%22&var-reviewers=%22shannonxtreme%22&var-reviewers=%22jihoon-seo%22&var-reviewers=%22nilekhc%22&var-reviewers=%22youngnick%22&var-reviewers=%22cici37%22&var-reviewers=%22smarterclayton%22&var-reviewers=%22shu-mutou%22&var-reviewers=%22wongma7%22&var-reviewers=%22saschagrunert%22&var-reviewers=%22SergeyKanzhelev%22&var-reviewers=%22aramase%22&var-reviewers=%22schneesu%22&var-reviewers=%22kerthcet%22&var-reviewers=%22nilo19%22&var-reviewers=%22gnufied%22&var-reviewers=%22jsafrane%22&var-reviewers=%22soltysh%22&var-reviewers=%22prameshj%22&var-reviewers=%22freehan%22&var-reviewers=%22codenrhoden%22&var-reviewers=%22jiahuif%22&var-reviewers=%22brendandburns%22&var-reviewers=%22ramineni%22&var-reviewers=%22tallclair%22&var-reviewers=%22mrbobbytables%22&var-reviewers=%22ravisantoshgudimetla%22&var-reviewers=%22feiskyer%22&var-reviewers=%22divyenpatel%22&var-reviewers=%22kbhawkey%22&var-reviewers=%22lauchokyip%22&var-reviewers=%22cjwagner%22&var-reviewers=%22danwinship%22&var-reviewers=%22mdbooth%22&var-reviewers=%22damemi%22&var-reviewers=%22shivanshu1333%22&var-reviewers=%22jayunit100%22&var-reviewers=%22strongjz%22&var-reviewers=%22johngmyers%22&var-reviewers=%22invidian%22&var-reviewers=%22yliaog%22&var-reviewers=%22mkimuram%22&var-reviewers=%22bowei%22&var-reviewers=%22mittalyashu%22&var-reviewers=%22pjhwa%22&var-reviewers=%22cpanato%22&var-reviewers=%22sedefsavas%22&var-reviewers=%22jpeach%22&var-reviewers=%22bobbypage%22&var-reviewers=%22andyzhangx%22&var-reviewers=%22kishorj%22&var-reviewers=%22nckturner%22&var-reviewers=%22spowelljr%22&var-reviewers=%22jingxu97%22&var-reviewers=%22shysank%22&var-reviewers=%22edsoncelio%22&var-reviewers=%22mauriciopoppe%22&var-reviewers=%22ccfishk%22&var-reviewers=%22BenTheElder%22&var-reviewers=%22seokho-son%22&var-reviewers=%22justinsb%22&var-reviewers=%22caesarxuchao%22&var-reviewers=%22chethanv28%22&var-reviewers=%22M00nF1sh%22&var-reviewers=%22seans3%22&var-reviewers=%22mattcary%22&var-reviewers=%22marunachalam%22&var-reviewers=%22eddiezane%22&var-reviewers=%22olemarkus%22&var-reviewers=%22lingxiankong%22&var-reviewers=%22devigned%22&var-reviewers=%22electrocucaracha%22&var-reviewers=%22rifelpet%22&var-reviewers=%22MaciekPytel%22&var-reviewers=%22vedant-kakde%22&var-reviewers=%22medyagh%22&var-reviewers=%22chendave%22&var-reviewers=%22verma-kunal%22&var-reviewers=%22RinkiyaKeDad%22&var-reviewers=%22howieyuen%22&var-reviewers=%22edreed%22&var-reviewers=%22jackfrancis%22&var-reviewers=%22alexeldeib%22&var-reviewers=%22sharifelgamal%22&var-reviewers=%22Jefftree%22&var-reviewers=%22mrunalp%22&var-reviewers=%22geoffcline%22&var-reviewers=%22ArangoGutierrez%22&var-reviewers=%22atoato88%22&var-reviewers=%22ityuhui%22&var-reviewers=%22mboersma%22&var-reviewers=%22dcantah%22&var-reviewers=%22mborsz%22&var-reviewers=%22fpetkovski%22&var-reviewers=%22RaunakShah%22&var-reviewers=%22camilamacedo86%22&var-reviewers=%22JoelSpeed%22&var-reviewers=%22humblec%22&var-reviewers=%22mengjiao-liu%22&var-reviewers=%22yangjunmyfm192085%22&var-reviewers=%22ingvagabund%22&var-reviewers=%22PushkarJ%22&var-reviewers=%22steven-my%22&var-reviewers=%22cristicalin%22&var-reviewers=%22endocrimes%22&var-reviewers=%22fromanirh%22&var-reviewers=%22ash2k%22&var-reviewers=%22tobiasgiese%22&var-reviewers=%22kavyashree-r%22&var-reviewers=%22kevindelgado%22&var-reviewers=%22estroz%22&var-reviewers=%22dashpole%22&var-reviewers=%22BaluDontu%22&var-reviewers=%22leiyiz%22&var-reviewers=%22richardcase%22&var-reviewers=%22LochanRn%22&var-reviewers=%22mortent%22&var-reviewers=%22logicalhan%22&var-reviewers=%22howardjohn%22&var-reviewers=%22matthyx%22&var-reviewers=%22mrueg%22&var-reviewers=%22manugupt1%22&var-reviewers=%22corneliusweig%22&var-reviewers=%22richardchen331%22&var-reviewers=%22wlan0%22&var-reviewers=%22pravarag%22&var-reviewers=%22BobyMCbobs%22&var-reviewers=%22rosskirkpat%22&var-reviewers=%22mpherman2%22&var-reviewers=%22mcluseau%22&var-reviewers=%22Jiawei0227%22&var-reviewers=%22Mr-DG-Wick%22&var-reviewers=%22mkumatag%22&var-reviewers=%22karuppiah7890%22&var-reviewers=%22petr-muller%22&var-reviewers=%22monopole%22&var-reviewers=%22floryut%22&var-reviewers=%22LuckySB%22&var-reviewers=%22ahmedyarub%22&var-reviewers=%22mikebz%22&var-reviewers=%22zshihang%22&var-reviewers=%22adrianludwin%22&var-reviewers=%22droslean%22&var-reviewers=%22iamNoah1%22&var-reviewers=%22roycaihw%22&var-reviewers=%22awgreene%22&var-reviewers=%22palnabarun%22&var-reviewers=%22denkensk%22&var-reviewers=%22249043822%22&var-reviewers=%22deepakkinni%22&var-reviewers=%22MadhavJivrajani%22&var-reviewers=%22elmiko%22&var-reviewers=%22derekwaynecarr%22&var-reviewers=%22kl52752%22&var-reviewers=%22yosshy%22&var-reviewers=%22jberkus%22&var-reviewers=%22enj%22&var-reviewers=%22longwuyuan%22&var-reviewers=%22sanposhiho%22&var-reviewers=%22shaneutt%22&var-reviewers=%22listx%22&var-reviewers=%22cynepco3hahue%22&var-reviewers=%22alan-kut%22&var-reviewers=%22tao12345666333%22&var-reviewers=%22marseel%22&var-reviewers=%22atiratree%22&var-reviewers=%22jyz0309%22&var-reviewers=%22RA489%22&var-reviewers=%22mengqiy%22&var-reviewers=%22klueska%22&var-reviewers=%22JaneLiuL%22&var-reviewers=%22cblecker%22&var-reviewers=%22andrewsykim%22&var-reviewers=%22knabben%22&var-reviewers=%22saikat-royc%22&var-reviewers=%22shalini-b%22&var-reviewers=%22SandeepPissay%22&var-reviewers=%22johananl%22&var-reviewers=%22boenn%22&var-reviewers=%22adrienjt%22&var-reviewers=%22chris-short%22&var-reviewers=%22coderanger%22&var-reviewers=%22champtar%22&var-reviewers=%22perithompson%22&var-reviewers=%22bishtsaurabh5%22&var-reviewers=%22stevekuznetsov%22&var-reviewers=%22adisky%22&var-reviewers=%22jeremyrickard%22&var-reviewers=%22yoonian%22&var-reviewers=%22amwat%22&var-reviewers=%22vinaykul%22&var-reviewers=%22YuikoTakada%22&var-reviewers=%22mmiranda96%22&var-reviewers=%22gochist%22&var-reviewers=%22dlipovetsky%22&from=1573594139724&to=1636752539724&viewPanel=1

**Comment by lukaszgryglicki** [comment]
Hi @parispittman - you can try to use [this](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=All&var-reviewers=All) instead (just select All) or [just select 5 first](https://k8s.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=All&var-reviewers=%22sbueringer%22&var-reviewers=%22liggitt%22&var-reviewers=%22fabriziopandini%22&var-reviewers=%22robscott%22&var-reviewers=%22wojtek-t%22).

Unfortunately for this kind of bug, I cannot do anything other than report to Grafana - this is internal Grafana representation, my idea is that they can use something like a "short URL" library internally when the URL is too long or something like this...
Do you want me to report this to Grafana?

Sorry for late answer but I was on PTO.

**Comment by lukaszgryglicki** [comment]
I'm closing this, let me know if you want me to report this or to do anything - you can also reopen if needed.
