### ISSUE TITLE
Missing data since 11/15

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#326]
https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&from=now-30d&to=now&var-period=d7&var-metric=contributions&var-repogroup_name=istio%2Fistio&var-users=All

Starting on 11/15 we stopped getting data for this dashboard. Other dashboards for Istio seem to work, as does the same dashboard for other projects (ex https://envoy.teststats.cncf.io/d/1/activity-repository-groups?orgId=1&from=now-90d&to=now)

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
Dashboard [fixed](https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1), thanks for reporting.

**Comment by howardjohn** [comment]
Awesome, thanks!
