### ISSUE TITLE
Heptio missing from company stats dashboard

### ISSUE THREAD

**Issue by castrojo** [cncf/devstats.archive#33]
Heptio seems to be missing from:

https://devstats.k8s.io/dashboard/db/companies-stats?orgId=1
https://devstats.k8s.io/dashboard/db/companies-velocity?orgId=1

However if I URL hack I can find our activity:

https://devstats.k8s.io/dashboard/db/companies-stats?orgId=1&var-period=d7&var-metric=activity&var-repogroup_name=All&var-repogroup=all&var-companies=Heptio

Any ideas?

**Comment by dankohn** [comment]
@lukaszgryglicki is off for a few days as he returns from Austin to Poland (via train!). But he'll get back to you next week.

**Comment by lukaszgryglicki** [comment]
I'm now in Rome, quite close to Poland (Warsaw-NYC-Pittsburgh-Chicago-Austin-LA-Rome-Warsaw).
Possibly Heptio is not in the top 26 (a-z) companies selected for stacked series.
Of course, I'll investigate this.

**Comment by lukaszgryglicki** [comment]
Heptio is back:
https://k8s.devstats.cncf.io/dashboard/db/companies-stats?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/companies-summary?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/companies-velocity?orgId=1
Closing.

I've expanded list of companies to show by default (now 40) and regenerated drop down values using new data pulled from Kubernetes repos.
