### ISSUE TITLE
[bug]Devstats data for Meshery not getting updated.

### ISSUE THREAD

**Issue by debo19** [cncf/devstats.archive#331]
Recently, the missing data for Meshery was fixed in #330.
However, the stats are not getting updated automatically since then.
It shows `Days since last commit: 14 days`, which is not the case. Same for the other fields as well.

Ref: https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Meshery

**Comment by lukaszgryglicki** [comment]
On PTO till 11th Feb, will check after my vacations.

**Comment by lukaszgryglicki** [comment]
Already fixed in the [test](https://all.teststats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Meshery) env, fixing prod now...

**Comment by lukaszgryglicki** [comment]
Fixed.

**Comment by debo19** [comment]
Thank you😄 @lukaszgryglicki
