### ISSUE TITLE
[feature request] cert-manager Repo Migration

### ISSUE THREAD

**Issue by SgtCoDFish** [cncf/devstats.archive#332]
We recently migrated the main cert-manager GitHub repository from [`jetstack/cert-manager`](https://github.com/jetstack/cert-manager) to [`cert-manager/cert-manager`](https://github.com/cert-manager/cert-manager). Redirects are in place, so I'd _assume_ that DevStats will continue to work just fine, but still it might be worth updating; I can see the [references to jetstack](https://github.com/cncf/devstats/blob/master/certmanager/psql.sh) in the certmanager/psql.sh script.

There's also a reference to `jetstack-experimental/cert-manager` which I think can safely be removed; that repo doesn't seem to exist and in any case isn't used.

I'd gladly raise a PR for this but there's a lot of stuff going on in this repo which is out of my regular comfort zone and I wouldn't really know where to start!

(Wasn't really sure whether this was a feature request or a bug, sorry!)

**Comment by lukaszgryglicki** [comment]
Some changes will be needed, I'll do it soon (I'm on vacation now).

**Comment by SgtCoDFish** [comment]
Great, thanks @lukaszgryglicki ! Enjoy your vacation :beach_umbrella: !

**Comment by lukaszgryglicki** [comment]
Done.
