### ISSUE TITLE
grpc maintainers: Bogdan Drutu affiliation is incorrect

### ISSUE THREAD

**Issue by SergeyKanzhelev** [cncf/devstats.archive#334]
https://github.com/cncf/foundation/blob/master/project-maintainers.csv

Bogdan Drutu's affiliation is now Splunk

cc: @bogdandrutu

**Comment by caniszczyk** [comment]
moving this to devstats repo

**Comment by lukaszgryglicki** [comment]
Will update manually today.

**Comment by lukaszgryglicki** [comment]
OK, I wonder if I should put Splunk for `bogdandrutu` for the all-time range, or Google until some YYYY-MM-DD and then Splunk - the `project-maintainers.csv` file only allows one affiliation.
For now, I'll just leave Google till 3/1/22 and then I'll set Splunk.
cc @SergeyKanzhelev

**Comment by lukaszgryglicki** [comment]
Actually, I already have:
```
bogdandrutu Google LLC < 2020-01-22
bogdandrutu Splunk Inc.
```
So is it bad? If so please create a PR against cncf/gitdm setting the correct affiliations companies & ranges.
Closing this, please let me know if I ned to change anything.

**Comment by SergeyKanzhelev** [comment]
the issue was about this particular page: https://github.com/cncf/foundation/blob/main/project-maintainers.csv

I don't know if there is a process of updating that table and who manages it. I'd assume gRPC maintainers should as I updated for OpenTelemetry.

If you can move the issue back to cncf/foundation repo, it would be great

**Comment by lukaszgryglicki** [comment]
Ohh, OK I saw this on DevStats repo, so the fix needs to be done on cncf/foundation repo.

**Comment by SergeyKanzhelev** [comment]
yes, and again, I'm not sure what's the process for these updates. grpc maintainers list looks stale
