### ISSUE TITLE
[bug] kubers maintainers: affiliation for clux is incorrect

### ISSUE THREAD

**Issue by clux** [cncf/devstats.archive#338]
not sure how to fix this myself, greps and searches turn up nothing.

I should be unaffilated, but all my commits are linked to a [former employer](https://kubers.devstats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1) from >2 years go.

**Comment by lukaszgryglicki** [comment]
Basically, you open a PR against `cncf/gitdm` fixing/adding/updating your affiliations.

**Comment by clux** [comment]
ah, thank you, clear from there. closing in favour of linked pr.
