### ISSUE TITLE
[bug] Users Statistics by Repository Group page showing errors

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#340]
https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group

Throwing error: `db query error: pq: column "sachithmuhandiram" does not exist`

I assume that is some github username.

If I filter users to a single user like https://istio.teststats.cncf.io/d/48/users-statistics-by-repository-group?var-period=w&var-metric=contributions&var-repogroup_name=All&var-users=howardjohn&orgId=1 there is no error but it shows no data

**Comment by lukaszgryglicki** [comment]
On it.

**Comment by lukaszgryglicki** [comment]
Fixed, thanks for reporting.
