### ISSUE TITLE
[bug] Data outage since 4/13

### ISSUE THREAD

**Issue by howardjohn** [cncf/devstats.archive#342]
https://istio.teststats.cncf.io/d/47/github-events?orgId=1

Looks like we lost all data for the past week or so

**Comment by lukaszgryglicki** [comment]
After the last manual data regenerate (to add new reviews data), I forgot to unsuspend the cron job - did it now - it should sync within a few hours from now.

**Comment by howardjohn** [comment]
Awesome thanks for the quick fix. Appreciate it!

**Comment by lukaszgryglicki** [comment]
SO the data is there, but Grafana is not showing it - never seen something like this - even in grafana query editor I can see data, but it is not displayed starting from date you specified. Same with random other projects on `teststats.cncf.io` - strange but on `devstats.cncf.io` they're OK. Will investigate this as soon as I can - possibly after about 8 hours from now.
Can you just confirm that you can't see data too? I mean to discard some browser cache issues on my side - but I've tried 2 different browsers...

**Comment by lukaszgryglicki** [comment]
Fixed, there was a failing replica - I'm usually using R/W service which was OK, but Grafana uses RO connection, so it was falling to a replica that became out of sync, I've recreated that replica from master, and all looks good now.
