### ISSUE TITLE
[bug] Dapr contributors graph is not loading anymore

### ISSUE THREAD

**Issue by artursouza** [cncf/devstats.archive#344]
Go to https://dapr.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=dapr%2Fcommunity&var-users=All

You will see an error message. Something like "db query error: ..." as per screenshot below.

<img width="913" alt="image" src="https://user-images.githubusercontent.com/130954/171252369-13e50716-76cc-4572-9a98-d4b7c7eed0c6.png">

Yes, this used to work before:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/130954/171252925-f4a8ae4d-3972-4dba-b2ba-2ef62268ebf7.png">

**Comment by lukaszgryglicki** [comment]
Hi, thanks for reporting, will work on this tomorrow.

**Comment by lukaszgryglicki** [comment]
Fixed:
![Screenshot 2022-06-01 at 07 33 44](https://user-images.githubusercontent.com/2469783/171334737-c88a3708-491f-4e30-943c-df2a5819ef29.png)
