### ISSUE TITLE
[feature request] Monthly Active Unique Contributors

### ISSUE THREAD

**Issue by JimBugwadia** [cncf/devstats.archive#346]
I am trying to see a trend line for our project's monthly active unique contributors.

Seems like the data is available, but I am not sure how to properly view it.

Any help would be greatly appreciated. Thanks!

**Comment by lukaszgryglicki** [comment]
What exactly is needed? I can take a closer look on Friday or during the weekend.

**Comment by JimBugwadia** [comment]
Thanks @lukaszgryglicki!

We would like to see a graph of monthly unique contributors (issue creators, issue commenters, pull request makers, pull request commenters, committers, and commit commenters) for each repo and across all repos.

**Comment by lukaszgryglicki** [comment]
Not sure which project you want, this is an example for `Opentelemetry`: https://opentelemetry.devstats.cncf.io/d/74/contributions-chart

You can choose any other CNCF project just replace `opentelemetry` in the URL with another project or click the project icon on https://all.devstats.cncf.io/d/8/dashboards.

While in this view you can choose:
- Repository group (in most CNCF projects they are mapped to separate repositories, so you can choose any repo or All - for stats across the entire project. In the `All CNCF` project each repository group is just a full single CNCF project and if you choose `All` - you will see stats for All CNCF projects combined).
- You can choose a metric from the drop-down (for example `Issues` - you will see a red line for issue creators number and blue bars for a number of issues, same when you choose PRs, Contributions, Comments, and so on).
- You can choose the period: week or Month (you requested monthly).
- Finally, you can also filter by country and company (or choose All there).
- You can also click on the panel title and choose:  -> Inspect -> Data and click Download CSV.

Hope that helps.

**Comment by JimBugwadia** [comment]
This is great! Thanks @lukaszgryglicki!
