### ISSUE TITLE
[bug] Contributions not updated for long time and sometimes missing

### ISSUE THREAD

**Issue by kundan2707** [cncf/devstats.archive#347]
I am doing contribution is SIg-Network 
mostly 
- cluster-proportional-autoscaler
- external-dns
- gateway-api
- ingress-nginx
- kpng
- network-policy-api
I observed mostly my contribution take too much time to get updated and sometime lost and never updated.

**Comment by lukaszgryglicki** [comment]
I will take a look but I would help a lot if you can specify which dashboard and some example contributions that are missing...

**Comment by lukaszgryglicki** [comment]
Please provide more details, also please note that I'll be on PTO starting tomorrow evening, so I will probably be able to take a look at this next week.

**Comment by lukaszgryglicki** [comment]
Closing this, please reopen if you have more details.
