### ISSUE TITLE
[bug] change kubedl project's repos

### ISSUE THREAD

**Issue by jian-he** [cncf/devstats.archive#348]
looks like it is currently tracking alibaba/kubedl,   https://github.com/cncf/devstats/blob/master/kubedl/psql.sh#L16

would like to change it to 

"kubedl-io/kubedl"
"kubedl-io/morphling"
"kubedl-io/website"
"kubedl-io/morphling-website"

@lukaszgryglicki would you help make that change ?

**Comment by lukaszgryglicki** [comment]
Sorry, I've missed this, I'll update config tomorrow or on Monday.

**Comment by lukaszgryglicki** [comment]
I will add the entire org: `kubedl-io` as it is the case in all CNCF projects when they move to their own github org.

**Comment by lukaszgryglicki** [comment]
This is done in all DevStats repos and gitdm. New org will be now tracked, closing.

**Comment by lukaszgryglicki** [comment]
I've regenerated full data for `KubeDL` (including past data), see: [KubeDL](https://kubedl.devstats.cncf.io).

**Comment by jian-he** [comment]
thank you !
