### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by tpepper** [cncf/devstats.archive#35]
Add to readme or github wiki a DevStats User Guide describing how to use the site and some example workflows to find and interpret data.

**Comment by lukaszgryglicki** [comment]
We already have a bunch of `*.MD` files, but I'll think about something like this.

**Comment by lukaszgryglicki** [comment]
Would be great to have some help here...
Why?
If somebody "from outside" tries to use this, it is more clear for Him/her what to put in this kind of documentation, of course I can help with that as much as possible.

**Comment by lukaszgryglicki** [comment]
Would be great if somebody help with this (I mean general user guide - I think it will be best to have somebody from outside write this, for example, based on my current work on very detailed documentation #74 )

**Comment by jonasrosland** [comment]
I think this is a fantastic idea. There's so much data collected and presented it can be overwhelming if you're new to it and not sure what the graphs mean. Having a "getting started" guide could prove to be very useful.

**Comment by bpfSockOps** [comment]
I am seeing that this issue hasn't been updated for a while, if this is still needed I can work on it.

**Comment by lukaszgryglicki** [comment]
Sure, I'm in the process of splitting DevStats into multiple smaller repositories.

**Comment by vnktram** [comment]
@lukaszgryglicki I can pick this up.

**Comment by lukaszgryglicki** [comment]
Sure, go ahead.
