### ISSUE TITLE
[feature request] update kubevela repo org

### ISSUE THREAD

**Issue by wonderflow** [cncf/devstats.archive#350]
Hi, kubevela repo has migrated from `oam-dev/kubevela` to `kubevela/kubevela`, I hope there's any way to update the devstats data?

The org link is here: https://github.com/kubevela

**Comment by lukaszgryglicki** [comment]
Thanks for the info, I'll update DevStats and let you know.

**Comment by wonderflow** [comment]
Much appreciated! Thanks. @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
Conflig updated, DevStats will be tracking new org starting now. LMK if you want to regenerate all data (including past) if so - I can do it but there will be a few hours downtime.

**Comment by lukaszgryglicki** [comment]
Closing this @wonderflow please reopen or just ping me if you want me to regenerate instance data.

**Comment by wonderflow** [comment]
@lukaszgryglicki Yes, please re-generate it, thanks!

**Comment by lukaszgryglicki** [comment]
Will do as a part of https://github.com/cncf/devstats/issues/352
