### ISSUE TITLE
[question] organization renaming

### ISSUE THREAD

**Issue by tormath1** [cncf/devstats.archive#351]
Hi,

Thanks for this project - by curiosity I successfully set up a test instance to fetch data from `flatcar-linux` github organization (https://github.com/flatcar-linux/).

Repo in this organization moved from `flatcar-linux` -> `kinvolk` -> `flatcar-linux`. We can still see the redirects:
```
$ curl -I https://github.com/kinvolk/coreos-overlay
...
location: https://github.com/flatcar-linux/coreos-overlay
```

On the devstat instance, there is a gap during the `kinvolk` period because the `projects.yml` is defined for `flatcar-linux` org. What should be the way to get data from both organization ?

I tried to edit the `companies.yml`, thinking that `kinvolk/*` activities would be ingested by `flatcar-linux` but no more luck.

Thanks!

**Comment by lukaszgryglicki** [comment]
DevStats doesn't do any redirects, I parses files from GHA archives.
To track org and repo you can specify in `projects.yaml`: `command_line` like: `a,b/c` etc.
See CNCF's projects projects.yaml file for details, also see per any project `project-name/psql.sh`.

**Comment by tormath1** [comment]
Ouh nice, it seems to do the job, thanks. Just for my knowledge: `command_line` and the value in `psql.sh` - for example `cilium,noironetworks/cilium-net` in:
https://github.com/cncf/devstats/blob/4cdfd0572055a094cb935692e660e6f4e780ac13/cilium/psql.sh#L16

Are the same things ?

**Comment by lukaszgryglicki** [comment]
Almost the same:
In`project-name/psql.sh` you define "historical" command - that is used for 1st sync - so you also list old names/regexps to get repos/orgs
In `projects.yaml` you define `current` command, so you can skip anything that is already historical now.

**Comment by tormath1** [comment]
Ok perfect. Closing this issue, thanks for your support. :star:

**Comment by lukaszgryglicki** [comment]
Also note that you can specify `regexps` - grep for `regexp` in `projects.yaml` and `*/psql.sh`.
