### ISSUE TITLE
[feature request] update logo of KubeVela in devstats to dark mod

### ISSUE THREAD

**Issue by wonderflow** [cncf/devstats.archive#352]
![image](https://user-images.githubusercontent.com/2173670/176578150-203817e8-338c-4c32-ab9f-22fe212aa908.png)

Here's the dark mod logo:

https://kubevela.io/img/logoDark.svg

Please also regenerate the activity data, thanks!

**Comment by wonderflow** [comment]
![image](https://user-images.githubusercontent.com/2173670/176578291-d35514b6-62aa-4f0a-968a-b6c644fd3432.png)

**Comment by lukaszgryglicki** [comment]
I can use this: https://github.com/cncf/artwork/blob/master/projects/kubevela/icon/black/kubevela-icon-black.svg
DevStats only uses logos from `cncf/artwork`.

**Comment by wonderflow** [comment]
Sure , if so, please use the png version, then it will display a white background https://github.com/cncf/artwork/blob/master/projects/kubevela/icon/color/kubevela-icon-color.png

> I can use this: https://github.com/cncf/artwork/blob/master/projects/kubevela/icon/black/kubevela-icon-black.svg DevStats only uses logos from `cncf/artwork`.

**Comment by lukaszgryglicki** [comment]
Already updated, grafanas are being restarted and I'm regenerating instance data - I'll LYK once ready.

**Comment by lukaszgryglicki** [comment]
This is done. Closing.

**Comment by wonderflow** [comment]
Thanks
