### ISSUE TITLE
[bug] kubevela devstats is not refresh after 7/16

### ISSUE THREAD

**Issue by wonderflow** [cncf/devstats.archive#356]
The devstats link:  https://kubevela.devstats.cncf.io/d/3/stars-and-forks-by-repository?orgId=1

We can refer stars as example, the devstats show:

![image](https://user-images.githubusercontent.com/2173670/180902245-07fab367-a3dc-4149-aab0-0f84890a7f65.png)

While the actual data is 3981 for now:

![image](https://user-images.githubusercontent.com/2173670/180902352-0acbdc9e-aa48-405a-9302-06c955ace78f.png)

It could be possiblly affected by this changes https://github.com/cncf/devstats/issues/352

**Comment by wonderflow** [comment]
If there's anything I can do, just ping me, thanks @lukaszgryglicki

**Comment by wonderflow** [comment]
The contributions chart is also stop at 6.30 https://kubevela.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=m&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-company_name=All&var-company=all&from=now-1y&to=now

**Comment by lukaszgryglicki** [comment]
I was on PTO last week, I'll chekc this today.

**Comment by lukaszgryglicki** [comment]
I've found the bug, fixed it, but I need to regenerate data sice switchover to `kubevela` org - I forgot to update `project.yaml` config to track the new org :(

**Comment by lukaszgryglicki** [comment]
Both problems resolved, closing. Please reopen if needed.
cc @wonderflow

**Comment by wonderflow** [comment]
@lukaszgryglicki Thanks very much!
