### ISSUE TITLE
[bug] blank Flux graph data

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#357]
Flux data 2022-01-01 to 2022-3-31 shows no data for that time period. 
<img width="1329" alt="Screen Shot 2022-07-10 at 6 11 02 PM" src="https://user-images.githubusercontent.com/36166779/182691306-a4424483-8b81-41f6-9181-bc5f14bffa81.png">

**Comment by lukaszgryglicki** [comment]
Fixed [see the dashboard](https://flux.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1) - sorry I had some major node outage and was fixing this for a few hours...
