### ISSUE TITLE
[bug] no data for Falco graph

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#358]
No data for time period 2022-04-01 to 2022-06-30. Here is the link: [https://falco.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=w&var-metric=activity&var-repogroup_name=All&var-companies=All&from=1648796400000&to=1656658799000]

<img width="1338" alt="Screen Shot 2022-08-03 at 1 26 47 PM" src="https://user-images.githubusercontent.com/36166779/182705523-5d4d59ef-9abd-4cd0-9a21-265c5de2a45e.png">

**Comment by lukaszgryglicki** [comment]
Fixed [see the dashboard](https://falco.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1) - sorry I had some major node outage and was fixing this for a few hours...
