### ISSUE TITLE
Query by individual

### ISSUE THREAD

**Issue by tpepper** [cncf/devstats.archive#36]
Querying for company stats exists, but individuals does not.  There are multiple workflows where this is useful, but a particular near term need is to measure activity towards membership ladder progression.  Devstats appears to offer a more powerful path to insights than looking at a user's activity on a github page.

**Comment by lukaszgryglicki** [comment]
I'll implement this, it will take some time because now I have many other issues/feature requests to work on.

**Comment by lukaszgryglicki** [comment]
Starting work on this

**Comment by lukaszgryglicki** [comment]
Implemented "Developers summary"
https://k8s.devstats.cncf.io/dashboard/db/developers-summary?orgId=1
Now I'll implement this on all remaining CNCF projects as well.
Closing.
Please reopen if You have any new questions, feedback or feature requests about this dashboard.

**Comment by lukaszgryglicki** [comment]
Implemented on all projects
Prometheus: https://prometheus.devstats.cncf.io/dashboard/db/developers-summary?orgId=1
OpenTracing: https://opentracing.devstats.cncf.io/dashboard/db/developers-summary?orgId=1
Fluentd: https://fluentd.devstats.cncf.io/dashboard/db/developers-summary?orgId=1
linkerd: https://linkerd.devstats.cncf.io/dashboard/db/developers-summary?orgId=1
gRPC: https://grpc.devstats.cncf.io/dashboard/db/developers-summary?orgId=1

**Comment by tpepper** [comment]
Wow that was fast!  Thank you!  Only thing I'd note is https://k8s.devstats.cncf.io/dashboard/db/developers-summary?orgId=1 first column says "Company" instead of something like "GitHub Name".

**Comment by lukaszgryglicki** [comment]
My bad, fixed on k8s dashboard.
Will fix remaining projects tomorrow.
Thanks for the feedback.
