### ISSUE TITLE
[kubernetes] Data export request for 2022 Kubernetes Election

### ISSUE THREAD

**Issue by coderanger** [cncf/devstats.archive#360]
It's that time of year again that we need to pull voter rolls for Kubernetes, anyone with 50 or more contributions on any Kubernetes project. Last year I got pointed here (#316) so figured I would start here again. If I can do a bulk export of this type myself from Devstats I'm happy to do that too!

**Comment by coderanger** [comment]
Oh and timing wise, the cutoff time is this Friday so if we can pull it around then, that would be great :)

**Comment by lukaszgryglicki** [comment]
I will generate this data tomorrow, but next time, please inform me a bit earlier than a day before the deadline.

**Comment by lukaszgryglicki** [comment]
Done, spreadsheet is generated in usual place, ping me on slack or email me for a link because that spreadsheet contains sensitive data.
