### ISSUE TITLE
[bug] No data shown -  Company Statistics by Repository Group for Knative

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#361]
Error message: db query error: pq: column "Mattermost Inc." does not exist

Link [here](https://knative.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&from=1648796400000&to=1656658799000&var-period=w&var-metric=activity&var-repogroup_name=All&var-companies=All).

**Comment by lukaszgryglicki** [comment]
Fixed.
