### ISSUE TITLE
[bug] No data for company Statistics by Repository Group - in-toto

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#362]
db query error: pq: column "Ntt Pc Communications Incorporated" does not exist

Link [here](https://intoto.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=All&var-companies=All&from=1641024000000&to=1648796399000).

**Comment by lukaszgryglicki** [comment]
Fixed.
