### ISSUE TITLE
[bug] No data: Flux - Company Statistics by Repository Group

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#363]
Error message: db query error: pq: column "Buoyant Inc." does not exist

Link [here](https://flux.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&from=1648796400000&to=1656658799000&var-period=w&var-metric=contributions&var-repogroup_name=All&var-companies=All).

**Comment by lukaszgryglicki** [comment]
fixed, but this seems to happen more often - I think there is some workflow error (I suspect that when new tags are generated I'm not (always?) updating columns and that kind of issue happens - will investigate more on Friday (tomorrow) but for now I've just fixed data manually).

**Comment by levbogusiewicz** [comment]
Thank you!

**Comment by lukaszgryglicki** [comment]
I think this shoudl be fixed by [this commit](https://github.com/cncf/devstatscode/commit/16ebbcc0ef06af1b3c68153f5b3a670cc0e35080) - I'll rerun `columns` on all projects now and then I'll be observing, hope this shouldn't happen again.
cc @levbogusiewicz

**Comment by lukaszgryglicki** [comment]
`columns` re-run manually for all projects, now it should correctly be called after all `tags` recalculation which should solve the issue.
