### ISSUE TITLE
[feature request] Crossplane has two different organizations that should be taken into account

### ISSUE THREAD

**Issue by muvaf** [cncf/devstats.archive#364]
Crossplane project has both [crossplane](https://github.com/crossplane) and [crossplane-contrib](https://github.com/crossplane-contrib) organizations under its governance as stated here in its governance document: https://github.com/crossplane/crossplane/blob/master/GOVERNANCE.md#crossplane-governance

However, devstats does not take [crossplane-contrib](https://github.com/crossplane-contrib) into account. Since we moved a few repositories like [provider-aws](https://github.com/crossplane-contrib/provider-aws) that are fairly popular, the last report indicated drop in certain dimensions. We should take both organizations into account when the report is produced.

**Comment by lukaszgryglicki** [comment]
Will work on this on monday, but note that this is not a `bug` - this is a `feature request` - how can I know that any of over 100 projects just added a new org to their config?
Every time this happens, somebody needs to create `feature request` to add that org to devStats configuration.

**Comment by muvaf** [comment]
@lukaszgryglicki Thank you! Sorry for the title, fixed it. Let me know if I can help 🙂

**Comment by lukaszgryglicki** [comment]
No problem. I will just do it and update past data, regenerate docker images, k8s deployments all this stuff... but on Monday - today s already 6:20 PM Friday (weekend :D).

**Comment by muvaf** [comment]
Oh great, I was just about to ask if we can update the past data so that the trajectory is not distorted. Thank you!!

**Comment by lukaszgryglicki** [comment]
On it now: ETA: today.

**Comment by lukaszgryglicki** [comment]
Added, data regenerated in all dashboards, including past data since first activity detected on the new org (`crossplane-cotribub`) which is `2020-07-14`.

**Comment by lukaszgryglicki** [comment]
cc @muvaf

**Comment by muvaf** [comment]
I checked the devstats page and all seems updated. The report we got from CNCF contains static images of these graphs so no updates there, but I guess that would require creating another report, which is not really necessary IMO but would be nice-to-have.

Thank you so much for tackling this very quickly @lukaszgryglicki !!
