### ISSUE TITLE
[bug] error message: Dapr Company Statistics by Repository Group

### ISSUE THREAD

**Issue by levbogusiewicz** [cncf/devstats.archive#366]
Error message: db query error: pq: column "Intuit Inc." does not exist

link [here](https://dapr.devstats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&from=1648796400000&to=1656658799000&var-period=w&var-metric=activity&var-repogroup_name=All&var-companies=All)

**Comment by lukaszgryglicki** [comment]
Looks like my fix didn't work automaticaly, will re-iterate on this on Friday, for now I'll fix manually :( :/

**Comment by lukaszgryglicki** [comment]
Fixed, but not closing - will reiterate when I can, maybe manual pre-init didn't run for this project (or more) before applying fix...

**Comment by lukaszgryglicki** [comment]
there was one more shell script that could execute `tags` without calling `columns` - hope this will fix it: eaebe7828772dc11d31ec07c2d33bd5631e667e4

**Comment by levbogusiewicz** [comment]
Thank you!
