### ISSUE TITLE
bug: Devstats can't pull data

### ISSUE THREAD

**Issue by xmulligan** [cncf/devstats.archive#367]
<img width="1503" alt="Screenshot 2022-08-29 at 10 49 39" src="https://user-images.githubusercontent.com/29048870/187174516-4eec04a6-6475-40d5-b5b1-25e75aaa1335.png">

All of the data is missing from https://cilium.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=y&var-repogroups=All

**Comment by lukaszgryglicki** [comment]
Your link specfies aggregation period 1 year see: var-period=y` while you request data for last 30 day - so there is no data.
Change aggregation period to 24 Hours MA or Dayor 7 days MA or or Week, oe even Month (1 period in 30 days) or change date rangeto something longer that year to have Year average, like last 5 years or so

Example: [Last 5 years with yearly aggregation](https://cilium.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=y&var-repogroups=All&from=now-5y&to=now) or [Last 30 day with 24 Hour MA aggregation](https://cilium.devstats.cncf.io/d/2/commits-repository-groups?orgId=1&var-period=h24&var-repogroups=All&from=now-30d&to=now).

I see no issue, you just selected aggregation period (1 year) longer that date range 930 days), closing.
