### ISSUE TITLE
[bug] - Incomplete data on CNCF/k8s contributions chart

### ISSUE THREAD

**Issue by rhockenbury** [cncf/devstats.archive#370]
It looks like my company (Mastercard) might be missing some historical contributions data on the [contributions chart](https://k8s.devstats.cncf.io/d/74/contributions-chart?orgId=1&var-period=w&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes&var-country_name=All&var-company_name=Mastercard%20International%20Incorporated&var-company=mastercardinternationalincorporated).  On that chart, the contributions start in September 2022 while we should have contributions going back quite a bit further.  

Is there a way to run a backfill or understand why that data might be missing?  

I believe [Contribution count data](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-repo_name=kubernetes%2Fkubernetes&var-country_name=All&var-companies=Mastercard%20International%20Incorporated) looks correct.  And as you can see, the total number of contributions doesn't seem to line up with what's shown on the contributions chart.

**Comment by lukaszgryglicki** [comment]
WIll work on this as soon as I can, may be even a week from now unfortunately.

**Comment by lukaszgryglicki** [comment]
I have regenerated past data for this dashboard, closing, please reopen if still needed - but I see data in the past.
