### ISSUE TITLE
[update][flux] please use fluxcd/flux2

### ISSUE THREAD

**Issue by dholbach** [cncf/devstats.archive#372]
`fluxcd/flux2` is the official repository for Flux now. `fluxcd/flux` hasn't reached its EOL just yet, but will be archived some time soon.

**Comment by lukaszgryglicki** [comment]
Added to my TODO.
WIll get to this when I can, I'm currently really busy :/

**Comment by dholbach** [comment]
Sure, no worries!

**Comment by lukaszgryglicki** [comment]
Trying to dop as much as I can now before I would have to be on other tasks again...

**Comment by lukaszgryglicki** [comment]
We already btask `fluxcd` org so thsi new repo's data is automatically added, I only need to update references of "main repo" everywhere...

**Comment by lukaszgryglicki** [comment]
Updated everywhere, closing this, please LMK if any other action is needed.
