### ISSUE TITLE
[feature request] [update] Istio has joined the CNCF

### ISSUE THREAD

**Issue by craigbox** [cncf/devstats.archive#373]
Hi Łukasz,

We are now ready to copy everything from https://istio.teststats.cncf.io/ to https://istio.devstats.cncf.io/. 🙂

**Comment by lukaszgryglicki** [comment]
Thanks, currently busy, will work on this first time I can.

**Comment by lukaszgryglicki** [comment]
I'm hoping to work on this on Friday.

**Comment by lukaszgryglicki** [comment]
On it, there is more to do than just copy. Will update you with a final status.

**Comment by lukaszgryglicki** [comment]
Done some work on this, but have not copied the data yet. Removing the `wip` label - will be continuing this later.

**Comment by lukaszgryglicki** [comment]
Prod [page](https://istio.devstats.cncf.io) added, now adding Istio data to `All CNCF` instance.

**Comment by lukaszgryglicki** [comment]
Added [Istio](https://istio.devstats.cncf.io) DevStats instance, and added Istion in [All CNCF](https://all.devstats.cncf.io) - those are [Project Health](https://all.devstats.cncf.io/d/54/project-health-table?orgId=1&var-repogroup_name=Istio) & [Projects Health](https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1) dashboards that include Istio. Closing this, please reopen if needed.
