### ISSUE TITLE
[feature request] DevStats dashboard for number of downloads

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/devstats.archive#374]
[feature request] Can we add a DevStats dashboard for number of downloads for the Kyverno project? We'd like to see the latest total as well as the total number by time period so we can see a chart of the growth of number of downloads.
Thank you!

**Comment by lukaszgryglicki** [comment]
We don't have that value in GitHub archives which is a datasource for DevStats. So we rather can't, unless you have a way of getting this value from GitHub archives or eventually GitHub APIs.

**Comment by lukaszgryglicki** [comment]
Closing for now, please reopen if you have any ideas about how to get this data from GitHub.
