### ISSUE TITLE
[bug] - Developer Activity Counts by Companies gets wrong time

### ISSUE THREAD

**Issue by shalevr** [cncf/devstats.archive#375]
When I use the [Developer Activity Counts by Companies](https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?var-period_name=Last%20day&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All) for all contributions for the last day and I get the wrong time.

I edit this [query](https://opentelemetry.devstats.cncf.io/explore?left=%7B%22datasource%22:%22psql%22,%22queries%22:%5B%7B%22alias%22:%22%22,%22dsType%22:%22influxdb%22,%22format%22:%22table%22,%22group%22:%5B%5D,%22groupBy%22:%5B%7B%22params%22:%5B%22$__interval%22%5D,%22type%22:%22time%22%7D,%7B%22params%22:%5B%22null%22%5D,%22type%22:%22fill%22%7D%5D,%22metricColumn%22:%22none%22,%22orderByTime%22:%22ASC%22,%22policy%22:%22default%22,%22query%22:%22SELECT%20%5C%22name%5C%22,%20%5C%22value%5C%22%20FROM%20%5C%22developers_hist_%5B%5Bmetric%5D%5D_%5B%5Brepogroup%5D%5D_%5B%5Bperiod%5D%5D%5C%22%20WHERE%20$timeFilter%22,%22rawQuery%22:true,%22rawSql%22:%22select%20%5Cn%20%20time,%5Cn%20%20sub.%5C%22Rank%5C%22,%5Cn%20%20split_part(sub.name,%20%27$$$%27,%201)%20as%20name,%5Cn%20%20split_part(sub.name,%20%27$$$%27,%202)%20as%20%5C%22Company%5C%22,%5Cn%20%20sub.value%20%5Cnfrom%20(%5Cn%20%20select%20row_number()%20over%20(order%20by%20value%20desc)%20as%20%5C%22Rank%5C%22,%5Cn%20%20%20%20name,%5Cn%20%20%20%20value,%5Cn%20%20%20%20time%5Cn%20%20from%5Cn%20%20%20%20shdev%5Cn%20%20where%5Cn%20%20%20%20series%20%3D%20%27hdev_contributionsallall%27%5Cn%20%20%20%20and%20period%20%3D%20%27d%27%5Cn%20%20%20%20and%20(%27null%27%20%3D%20%27null%27%20or%20split_part(name,%20%27$$$%27,%202)%20in%20(null))%5Cn)%20sub%22,%22refId%22:%22A%22,%22resultFormat%22:%22table%22,%22select%22:%5B%5B%7B%22params%22:%5B%22value%22%5D,%22type%22:%22field%22%7D,%7B%22params%22:%5B%5D,%22type%22:%22mean%22%7D%5D%5D,%22tags%22:%5B%5D,%22timeColumn%22:%22time%22,%22where%22:%5B%7B%22name%22:%22$__timeFilter%22,%22params%22:%5B%5D,%22type%22:%22macro%22%7D%5D,%22datasource%22:%7B%22type%22:%22postgres%22,%22uid%22:%22P172949F98CB31475%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-5y%22,%22to%22:%22now%22%7D%7D&orgId=1) so I will get the time also and I see dates from 2012 instead of the date today.

<img width="2014" alt="image" src="https://user-images.githubusercontent.com/65566801/198276089-9653a33e-087d-49c6-9d01-cf3ec79519cd.png">

It seems that all the values are actually from the last day and just the time that mentions there is wrong

**Comment by lukaszgryglicki** [comment]
Hi, will take a look on this next week, I'm on KubeCon, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
I checked this, `time` value here is for internal usage, and note that the table is not displaying this - this time is for internal ordering and it always differs by 1 hour.
I could close this now, but I will just refresh this dashboard manually to ensure that you are getting 100% up-to-date data.

**Comment by shalevr** [comment]
Thank you for the check!
Do you know maybe how I can convert this time to time that I can work with?
or do you know the time format?

**Comment by lukaszgryglicki** [comment]
This dashboard is not displaying time, it counts contributions per contributor so there is no single time. You cannot get time from this recalculated table, actually, you are just trying to use the `snapshot` table used to display data on the dashboard for your purposes, but there is nothing you can do with this table - it is "display only" snapshot table so Grafana get display data with single select. If you want to play with data, see the documentation panel at the bottom - there is an `SQL` link there which will point you to the actual query that is used to generate (precalculate) data for this dashboard (this is run periodically to update dashboards).

**Comment by lukaszgryglicki** [comment]
All data refreshed for this dashboard.
