### ISSUE TITLE
Clarification regarding contirbution metrics

### ISSUE THREAD

**Issue by ranrib** [cncf/devstats.archive#376]
Hi there!

Thanks for having devstats, it's amazing :)
I wanted to ask a few questions regarding the contribution metric since sometimes it isn't clear
* What other (exact) metrics is contribution sum up (or what are the exact gharchive events)? I tried to look at my team stats from the past week, but I couldn't get to a decisive point - see spreadsheet:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/24767098/200127984-fea3b8da-8f56-45f2-87e1-0ecf9654eb95.png">

* I believe that when a PR is being closed, that should be counted as a contribution to the owner of the PR, no? However, when gharchive.org tracks this event, it attributes the one who started the merge event. Is this the intended behavior? You can see an example here (I've loaded gharchive data) - pr 1180 created by `samimusallam`  but the contribution ends up with `amirblum`:
<img width="960" alt="image (1)" src="https://user-images.githubusercontent.com/24767098/200128525-dbffd2da-a26a-4ecc-bbb7-6a326f5d3ed8.png">
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/24767098/200128526-cd90a823-6b3d-4fef-b9e6-56001738d9cb.png">

Thanks,

**Comment by lukaszgryglicki** [comment]
So we are counting `authors` of events, and only some events are considered `contributions`, namely:
- 'PushEvent'
- 'PullRequestEvent'
- 'IssuesEvent'
- 'PullRequestReviewEvent'
- 'CommitCommentEvent'
- 'IssueCommentEvent'
- 'PullRequestReviewCommentEvent'

This is a system-wide definition and applies everywhere.
In the case of a PR merge (event = `PullRequest`, action = `merged`) GHA indeed assigns the author to somebody who actually merged a PR. So in case of a PR merge, it will be assigned to somebody who did that merge, PR creator will "get" a contribution when he/she opens a PR. Sorry but this is how GitHub archives (and GitHub APIs) work, can't do anything with it.

**Comment by lukaszgryglicki** [comment]
I'm closing this, please reopen it if needed, also note that there are more dashboards that allow insights into more specific metrics that contributors. I'm also letting you know that I won't change the definition of what contributors is because it is used everywhere and was agreed upon a long time back.
If you need something specific for you, like the count of the number of given contributor's PRs opened and then merged by someone else, etc - that can be done as a separate dashboard specific to this need (feature request).

**Comment by ranrib** [comment]
Thanks @lukaszgryglicki! it helps
