### ISSUE TITLE
[feature request] Regenerate data for inclavare-containers for all time

### ISSUE THREAD

**Issue by Xynnn007** [cncf/devstats.archive#377]
Hi, we are working for CNCF project [inclavare-containers](https://github.com/inclavare-containers) and need to regenerate devstat data for all time, since got help from @lukaszgryglicki  to add monitoring for all sub-projects inside the org. Could anyone help? Thanks!

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Done, see for example [this dashboard](https://inclavarecontainers.devstats.cncf.io/d/1/activity-repository-groups?orgId=1&from=now-1y&to=now&var-period=d7&var-repogroups=All). @Xynnn007 
<img width="2223" alt="Zrzut ekranu 2022-11-7 o 10 27 18" src="https://user-images.githubusercontent.com/2469783/200275083-4fb2e581-f8c8-4687-b2a6-c5928b723cc3.png">
