### ISSUE TITLE
containerd logo

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#38]
Please use the white logo to make it legible.

https://containerd.devstats.cncf.io/dashboard/db/all-cncf-projects?refresh=15m&orgId=1
https://github.com/cncf/artwork/blob/master/containerd/icon/white/containerd-icon-white.png

Favicon looks good, though.

**Comment by lukaszgryglicki** [comment]
OK will change on Tuesday.

**Comment by lukaszgryglicki** [comment]
Working on that.

**Comment by lukaszgryglicki** [comment]
Fixed everywhere (all projects on test & prod).
Please let me know if you see any issues, closing.

**Comment by dankohn** [comment]
White logo looks good at the top-left of Grafana. But please change the logo in the all projects panel to use white as well. https://containerd.devstats.cncf.io/

Using black logo for favicon is good.

**Comment by lukaszgryglicki** [comment]
Hmm, not sure what you mean. "All projects" already use white logo...
![screen shot 2018-01-02 at 13 28 30](https://user-images.githubusercontent.com/2469783/34483776-f43ac2ce-efc0-11e7-9ff9-a653d80b6da6.png)
Maybe you need to clear caches/etc. ?

I needed to use Safari's "Develop -> Empty caches" to see any changes, including login, top-left, all projects and fav icon.

**Comment by dankohn** [comment]
Yes, clearing cache fixed it, thanks.
