### ISSUE TITLE
[feature request] queries with fixed range selections: can we add "Last 6 months"?

### ISSUE THREAD

**Issue by estesp** [cncf/devstats.archive#381]
For non-graphed data (e.g. "Developer Activity Counts by Repository Group"), there is no custom Grafana range selector in the upper right like on the graph visualizations.

Instead, there is a "Range" pull-down with fixed ranges like Last day, week, 10 days, month, quarter, 1 yr, 2 yrs, decade as well as release tag data and other options. If there can be no custom-specified ranges for these views of the data (which would be the most useful option), the one seemingly obvious entry in timescales that is missing is half a year or "Last 6 months".

Thanks for any insight/guidance here if there is an easier way to look at 6 mo data for Developer Activity Counts or other tabular data views like it.

**Comment by lukaszgryglicki** [comment]
I can add such a fature in rather far future, I have a lot of tasks to do before I can get to this, I've added on my TODO list.
cc @caniszczyk

**Comment by lukaszgryglicki** [comment]
ETA for this is rather far away - this would require changing almost all dashboards (not that really difficult, just adding a new period) - but then regenerate data for all those dashboards in all projects on test & prod and we're quite close to migrate to new instances, so don't expect this in 2022 at all, possibly somewhere in 2023 if @caniszczyk approves this.

**Comment by lukaszgryglicki** [comment]
I will add this after switchover to new cluster.

**Comment by lukaszgryglicki** [comment]
I still don't have a new cluster, this will be implemented after the switchover.

**Comment by lukaszgryglicki** [comment]
Looks like it will take time to get a new cluster, so I'm starting work on this - will add a new range support and let it calculate for all projects in a normal schedule (instedad of adding value for this date period immediatelly in all projects & dashboards right before adding support - that way it should cause no issues).

**Comment by lukaszgryglicki** [comment]
Support added, now it will be populated gradually during the next weeks. Closing, please reopen if needed.

**Comment by lukaszgryglicki** [comment]
One dashboard calculated manually, just for example: https://all.devstats.cncf.io/d/18/overall-project-statistics-table?orgId=1&var-period_name=Last%206%20months&var-repogroup_name=All
