### ISSUE TITLE
Update developer country

### ISSUE THREAD

**Issue by raphink** [cncf/devstats.archive#383]
I am currently listed in France, even though I have changed all my profiles (GitHub, LF, CNCF Community) to Switzerland a few years ago already.

Is there a way for me to change that?

**Comment by lukaszgryglicki** [comment]
I will do this manually on cncf/gitdm on Monday. Added to my TODO.

**Comment by raphink** [comment]
Thank you!

**Comment by lukaszgryglicki** [comment]
Done.
