### ISSUE TITLE
[feature request] Can I add two repos to the devstas for Aeraki Mesh project?

### ISSUE THREAD

**Issue by zhaohuabing** [cncf/devstats.archive#387]
Aeraki Mesh acctually has two main repos:  [Aeraki](https://github.com/aeraki-mesh/aeraki) for the control plane and [MetaProtocol Proxy](https://github.com/aeraki-mesh/meta-protocol-proxy) for the data plane.  Both of the two repos are under active development. Just collecting  metrics on Aeraki repo is incomplete. Is it possible to also add MetaProtocol Proxy repo to the devstats of Aeraki Mesh project? Thanks !

**Comment by lukaszgryglicki** [comment]
DevStats already tracks the entire org `aeraki-mesh` - one of the repos needs to be selected as main repo - this is the one where we get annotations (tags) to generate date ranges for histogram metrics. This must be a single repo, not two repos.

Please link to a place where you miss this second repo, as I sxaid we track the entire ors, see: https://aerakimesh.devstats.cncf.io/d/1/activity-repository-groups?orgId=1 - many repos there

Maybe you just mean name mapping in repository groups https://aerakimesh.devstats.cncf.io/d/68/repository-groups?orgId=1 ?
It maps name: `aeraki-framework/aeraki` into `Aeraki Mesh` - but thsi si the default repository groups definition for projects that didn't provide any, I can remove this alias name so `aeraki-framework/aeraki` will always show up us `aeraki-framework/aeraki` - or you can propose you own mapping between repositories from your org and their repo groups, you can see how it is done in Kubernetes for example: https://k8s.devstats.cncf.io/d/68/repository-groups?orgId=1&var-repogroups=All

**Comment by zhaohuabing** [comment]
@lukaszgryglicki Thanks for the clarification. https://aerakimesh.devstats.cncf.io/d/1/activity-repository-groups?orgId=1 looks correctly. 

Maybe we can remove this alias name of aeraki-framework/aeraki to avoid confusion.

Thanks a lot for your help.

**Comment by lukaszgryglicki** [comment]
Will remove name mapping on Friday.

**Comment by lukaszgryglicki** [comment]
Done.
