### ISSUE TITLE
[feature request] Where do I know the update timestamp on devstats?

### ISSUE THREAD

**Issue by atoato88** [cncf/devstats.archive#388]
I usually check the scores on k8s.devstats.cncf.io 1 time on every week.
Recently, I sometimes confirmed the scores are exact same for 2 weeks.
If I remember correctly, the scores were updated at least once a week.

I want to know the timestamp when the devstats score is updated at.

Could you suggest some instructions for knowing the timestamp?
Or, could you add timestamp field to each page on k8s.devstats.cncf.io?

This may not be the feature request.. :thinking:

**Comment by lukaszgryglicki** [comment]
There is no such field, dashbioards are just regenrating. Can you point me to a dashboard that is not updated, maybe there is a problem with it - I'll check tomorrow or Friday?

**Comment by lukaszgryglicki** [comment]
And yes, last sync time would be a feature request - it will require quite a bit of work as all projects & dashboards would have to be udpated and recalculating logic would have to be updated to to store that value somewhere in DB - like table: `last_update(dashboard, timesdtamp)`.

**Comment by atoato88** [comment]
Thank you for quick response. :rocket: 
When I checked on today, the scores were updated.. :sweat_smile:

But I usually check [this page(Community sizing and health assessment / Companies table)](https://k8s.devstats.cncf.io/d/9/companies-table?orgId=1&var-period_name=v1.26.0%20-%20now&var-metric=contributions) and [this page(Contributor Statistics / Developer Activity Counts by Companies)](https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.26.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All&var-repo_name=kubernetes%2Fkubernetes).

I remember this situation sometimes happens from end of the 2022.
I will update this PR when I confirm this situation.

I wonder if the load(something score calculation) is so high in k8s repos, and the score is not updated..?

**Comment by lukaszgryglicki** [comment]
We are in progress of adding more nodes to DevStats - currently we struggle at on an old cluster with small numbe rof nodes and 140+ projects for both test & prod environments. Sometimes scores aren't updated and if anybody reports this I'm checking and fixing manually.
This process of adding nodes cannot be faster - it's not depending on me, I'll update as soon as I get those new nodes - then I'll update to newest Kubernetes possible, move data around.
Currently we're sometimes killed becaus eof too many pods/processes or OOM.

**Comment by atoato88** [comment]
Wow... I see.
I think it's so tough.

**Comment by shu-mutou** [comment]
@lukaszgryglicki 
Thank you for your efforts in maintaining and improving devstats.
Reporting reliable data to the company is very important for us to continue contributing.
It would be best if the data was updated daily, but I would be really happy if there was a data acquisition date even if it was updated once a week.

**Comment by lukaszgryglicki** [comment]
I will check and update on Friday or earlier.

**Comment by lukaszgryglicki** [comment]
Will check on Friday and will trey to add "last sync date" on Friday (not sure if I manage to do this in one day).

**Comment by lukaszgryglicki** [comment]
Manually imported newest affiliations (just to be sure they're up-to-date) and now regenerating requested dashboards. Then will add a table to keep last sync date and a dashboard allowing to check when given metric was last synced.

**Comment by lukaszgryglicki** [comment]
Update:
- 1) imported newest affiliations.
- 2) regenerated requested metrics for those 2 dashboards.
- 3) added support for storing last calculation date (per metric and time period given metric was called for), see: https://github.com/cncf/devstatscode/commits/master, https://github.com/cncf/devstats/commits/master, https://github.com/cncf/devstats-docker-images/commits/master.

Now there is an extra documentation line (in the main page per project in `Dashboard documentation` section:
```
You can use 'Last updated' dashboard too see when given SQL metric was calculated - each dashboard has a list of its SQL metrics
```

There is also a new dashboard `Last updated` in each project, for example: https://all.devstats.cncf.io/d/82/last-updated?orgId=1 or https://k8s.devstats.cncf.io/d/82/last-updated?orgId=1

This dashboard lists which emtric were last calculated for a selected time range.
Not all of them are refreshed yet - I'll do a final post when this is finished.

**Comment by lukaszgryglicki** [comment]
Example such dashboard in Thanos project:
<img width="2359" alt="Zrzut ekranu 2023-01-26 o 14 48 46" src="https://user-images.githubusercontent.com/2469783/214852130-6dd9ff47-da1e-413a-9695-c59615a7d33d.png">

**Comment by lukaszgryglicki** [comment]
For k8s it `will` be: https://k8s.devstats.cncf.io/d/82/last-updated?orgId=1 (has no data yet, since I just added a table and k8s sync didn't happen yet).

**Comment by lukaszgryglicki** [comment]
those dashboards will now slowly popupate as new calculations come in. Closing this ticket as "done".

**Comment by atoato88** [comment]
Thank you for quick update!
I wait for the `Last updated` calculation to complete on k8s.

**Comment by lukaszgryglicki** [comment]
This will take some time because I decided to recalculate all k8s metrics. But this recalculation started before support was added, so they first need to recalculate all (without status in this dashboard) an dthe following syncs will appera there.
here is example for `All CNCF`: https://all.devstats.cncf.io/d/82/last-updated?orgId=1
I will also add dashboard documentation describing what are all those `time periods`.

**Comment by lukaszgryglicki** [comment]
Dashboard documentation added, see k8s or all cncf for example: 
- https://k8s.devstats.cncf.io/d/82/last-updated?orgId=1.
- https://all.devstats.cncf.io/d/82/last-updated?orgId=1.

**Comment by lukaszgryglicki** [comment]
Also live-patched K8s reinit pod to provide last update date to, I'm considering this ticket as `done`.

**Comment by lukaszgryglicki** [comment]
Updated dashboards everywhere to add new columns:
- `Started at`.
- `Took`.
- `Command`.

In addition to:
- `Metric name`.
- `Finished at`.

So now you will be able to see how long a given metric took to calculate and command used to calculate it (arguments to `calc_metric` call).

Note that because I added this just now, data generated so far don't have it, so I'm defaulting this to:
- `Started at` - copying from `Finished at` (so calc time is 0).
- `Took`: `unknown`.
- `Command`: `unknown: ` + `Metric name`.

This will slowly be replaced with new version of `calc_metric` which fills that data.
<img width="2359" alt="Zrzut ekranu 2023-01-27 o 16 56 27" src="https://user-images.githubusercontent.com/2469783/215131353-bda7749e-2d0b-480a-9cb7-ab4c65fcd754.png">

cc @caniszczyk @atoato88 @shu-mutou

**Comment by lukaszgryglicki** [comment]
Added one more column `Milliseconds` - it is easier to sort by numeric value than string representation `Took`, this is how it looks like:
<img width="2359" alt="Zrzut ekranu 2023-01-27 o 17 43 02" src="https://user-images.githubusercontent.com/2469783/215143852-564f8b65-c207-4b49-9492-1830f283d412.png">
<img width="2359" alt="Zrzut ekranu 2023-01-27 o 17 43 42" src="https://user-images.githubusercontent.com/2469783/215143892-c7ebce92-f7a2-4374-a19d-818630bc9509.png">

**Comment by atoato88** [comment]
It looks perfect!! :smiley:
I think this issue is closed as `done`.

I will some comments if I have extra questions.

**Comment by atoato88** [comment]
@lukaszgryglicki 

I checked the values because it looks new score is applied.

I have one question.
What timezone is used for displaying `Finished at` and `Started at` ?
Is it UTC? or It depends on browser setting I use? or Other?

**Comment by lukaszgryglicki** [comment]
It is server's timezone, which happens to be UTC, now it is:
```
Thu Feb  2 06:34:17 UTC 2023
```

**Comment by atoato88** [comment]
Thank you for quick response😃
