### ISSUE TITLE
[feature request] Naming collision with Capsule

### ISSUE THREAD

**Issue by maxgio92** [cncf/devstats.archive#389]
Hi all,
in Clastix we would like to propose our [clastix/capsule](http://github.com/clastix/capsule) project, at the same time we realized that an homonymous project ([capsule-rs/capsule](https://github.com/capsule-rs/capsule)) is currently being tracked with the same name "capsule".

Is there a way we avoid this naming collision?

Thank you

**Comment by lukaszgryglicki** [comment]
If you mean just the repo name, then I can map repo to alternate name.
If you mean DevStats instance URL then you need to pick up something not used yet - yes, there is https://capsule.devstats.cncf.io/d/8/dashboards?orgId=1&refresh=15m - I can probably update ingress to rename it to somethign else, but thsi requires changes in many places (like all links referring to it).
So, i n reality, the question is where exactly (list all) you want to do that change, possibly with examples and screenshots.
It would be much easier to add your new project under different name - if we are speaking about new to-be-added CNCF project...
cc @caniszczyk

**Comment by lukaszgryglicki** [comment]
Also note that in https://github.com/capsule-rs/capsule the name is `Capsule` so renaming it woudl not be a good idea for this project's maintainers - they come first, so maybe you need to use different name for your to-be-proposed project...

Actually I cannot decide, because we already have `Capsule` - maybe @caniszczyk can help?

**Comment by lukaszgryglicki** [comment]
I'm closing this, there is no such project yet with name collision and even if there will be such we cannot change the current one - it was just 1st.

**Comment by maxgio92** [comment]
Thank you @lukaszgryglicki
