### ISSUE TITLE
All Dashboards

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#39]
Can you get the panel of All CNCF Projects (with their logos) to appear below the list of all dashboards on the homepage?

If not, please add it to the list of all views visible on the homepage.

**Comment by lukaszgryglicki** [comment]
I think I can, I'll check.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
This can be done, implemented now on the k8s test server:
https://k8s.cncftest.io/dashboard/db/dashboards?refresh=15m&orgId=1
Now applying to all other test servers home dashboards and then on prod server.

**Comment by dankohn** [comment]
Great. Please also create a new panel that goes below the graph and above the list of dashboards and says: "Please report any bugs by opening an issue on https://github.com/cncf/devstats" with the URL being a real link.

Then, change the title of the Dashboards table just below to "All K8s Dashboards".

And don't forget #38 while doing the updates.

**Comment by lukaszgryglicki** [comment]
OK. The logo is a separate issue, it is just a matter of replacing image file within Grafana installation.

**Comment by lukaszgryglicki** [comment]
OK, https://github.com/cncf/devstats/issues/39#issuecomment-354714044 feedback addressed.
Now I'll take a look at the icon issue, to have everything correct before applying this to the remaining projects.
https://k8s.cncftest.io/dashboard/db/dashboards?refresh=15m&orgId=1

**Comment by lukaszgryglicki** [comment]
Implemented on all 16 test & prod sites.
Closing.
Please reopen if needed.
