### ISSUE TITLE
[Bug]CNCF and K8s devstats doesn't show correct affiliation

### ISSUE THREAD

**Issue by divya-mohan0209** [cncf/devstats.archive#396]
Hello team,

In April 2022, I raised a [PR](https://github.com/cncf/gitdm/pull/1051/files) to update my affiliation. This doesn't seem to have been reflected since my contributions seem to be counted against my previous employer. Please could you take a look?

Cheers,
Divya

**Comment by caniszczyk** [comment]
hey @lukaszgryglicki take a look when you have a minute

**Comment by lukaszgryglicki** [comment]
I will check data in our JSON but also note that you have time range based affiliations, so can you show an example where it is wrong? I will debug then, otherwise it's hard to check anything othe rthan just JSON.

**Comment by lukaszgryglicki** [comment]
For some reason you rolls currentlky look like this:
```
  {
    "login": "divya-mohan0209",
    "email": "divya-mohan0209!users.noreply.github.com",
    "affiliation": "iGATE Corporation < 2015-12-01, HSBC",
    "source": "manual",
    "commits": 2301,
    "location": "Pune",
    "country_id": "in"
  },
  {
    "login": "divya-mohan0209",
    "email": "divya.mohan0209!gmail.com",
    "affiliation": "iGATE Corporation < 2015-12-01, HSBC",
    "source": "manual",
    "commits": 2301,
    "location": "Pune",
    "country_id": "in"
  },
```

SO they are not the same as in PR you linked - I will manually update then and next affiliations import will fix this. Possibly there was a PR later that changed this? Or they got overwritten by some bug?

**Comment by lukaszgryglicki** [comment]
Can you also link to DevStats instancew you want to import new affiliations? I can do it manually right after the fix if this is urgent.
@divya-mohan0209

**Comment by divya-mohan0209** [comment]
Thank you so much @caniszczyk for your quick help!
@lukaszgryglicki : By devstats instance, I assume you mean the projects. They are K8s, Kubewarden, and k3s. However, this is not at all urgent. I just thought I should flag it because the appropriate values weren't being reflected against my current employer. Thank you so much for picking this up!

**Comment by lukaszgryglicki** [comment]
Ok so if not urgent then each of them will import affiliations in up to 4 weeks from now (I've fixed and updated JSON already).
If you need any of them to be regenerated now - LMK, I can do this tomorrow "in the meantime".

**Comment by lukaszgryglicki** [comment]
I'm closing this, please LMK if you want me to do anything more on this (like manual import faster than scheduled).
