### ISSUE TITLE
Are "All PRs ..." dashboards redundant?

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#41]
Trying to reduce cognitive load from too many dashboards.

Comparing [PRs merged](https://k8s.devstats.cncf.io/dashboard/db/prs-merged?orgId=1) to [All PRs merged](https://k8s.devstats.cncf.io/dashboard/db/all-prs-merged?orgId=1) it seems like the same information is available.  Ditto for [Need Rebase PRs](https://k8s.devstats.cncf.io/dashboard/db/need-rebase-prs?orgId=1) vs [All Need Rebase PRs](https://k8s.devstats.cncf.io/dashboard/db/all-need-rebase-prs?orgId=1).  I prefer the more detailed non-all variants.

What do folks think about dropping the "All" dashboards? If people use them or prefer it to the more detailed dashboards, could we instead move the "all" graph to be another graph in the non-all dashboards?

**Comment by tpepper** [comment]
I was actually thinking the same thing earlier this week.  The “All” variants are veeery minimally interesting and redundant versus the other.  But the worse thing for me is that “A” comes first in the alphabet so on first glance at the devstats page you see that and click and find very little info.

**Comment by dankohn** [comment]
I'm very supportive of shooting as many as dashboards in the head as
possible. I find the current selection overwhelming. Also note that if you
certain dashboards would make sense combined together, Lukasz can do that.

Hopefully, we can eventually slim down to one dashboard that just flashes
"42" [0].

[0]
https://en.wikipedia.org/wiki/Phrases_from_The_Hitchhiker%27s_Guide_to_the_Galaxy#Answer_to_the_Ultimate_Question_of_Life,_the_Universe,_and_Everything_(42)

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
All dashboards with "All" in their name can be added as the 2nd panel to their non-All counterparts.
No problem here - easy to do. Just let me know if we need that or not.
I'm just back from the weekend and will work on the biggest issue/feature request https://github.com/cncf/devstats/issues/34 next few days.

**Comment by dankohn** [comment]
SGTM

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Added to my `TODO` list. This is a pure JSON task -> move some panels from one dashboard to another.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
- Merged `All PRs merged` --> `PRs merged` on all non-k8s dashboards.
On k8s dashboards:
- Merged `All PRs merged` --> `PRs merged`.
- Merged `All PRs merged` --> `PRs merged repository groups`.
- Merged `All Need Rebase PRs` --> `Need Rebase PRs`.

Updated 8 test sites and 8 prod sites.
Closing.
