### ISSUE TITLE
Dashboard request: New/Episodic contributors

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#45]
Here's some graphs I'd like to have:

Top request:

New Contributors: count of the number of PRs and count of unique individuals submitting a PR for the first time this month/week/day in repo history.

Also like to have, but less important:

Episodic Contributors: people/PRs from contributors who have not submitted a PR for a prior 3 months, and not more than 12 PRs ever.

New Issue Filers: count of the number of people and the number of issues from folks who are filing an issue for the first time in their history.

It would also be really nice if all of the above was divisible by SIG label.

**Comment by lukaszgryglicki** [comment]
Added to my TODO.

**Comment by jberkus** [comment]
Modifying Episodic contributors:  Not more than 6 PRs this year.

**Comment by dankohn** [comment]
Josh, Lukasz is going to first finish DevStats for the remaining 6 CNCF projects and then will circle back to this. It will hopefully be in under a month.

**Comment by lukaszgryglicki** [comment]
I have 6 new projects to implement.
It should take from 6 to max 12 days.
Then I'll be back on this.
Should be less than 2 weeks IMHO.

**Comment by jberkus** [comment]
I don't have a specific deadline for this stat.  It would be *nice* to have it before Kubecon.EU.

**Comment by lukaszgryglicki** [comment]
I'm almost sure it will be there before KubeCon.eu.
When I switch to this I may ask some more questions about details.

**Comment by jberkus** [comment]
Sure.

**Comment by lukaszgryglicki** [comment]
Starting researching this.

**Comment by lukaszgryglicki** [comment]
SQL that calculates 'new/episodic contributors' here: https://github.com/cncf/devstats/commit/df84f3bdeccd9c63fadd45c3d12847038bc53dc5
Test coverage here: https://github.com/cncf/devstats/commit/1c53f5d93134d7b875e0173f140cc69aee8222c8

Now adding this metric to YAML, cron, influx etc and finally Grafana JSON.

It is not divisible by SIGs because there will be some new method to identify SIG AFAIK, currently, this is only possible by using the label or searching for /sigxxx text in the comments, but there was a discussion somewhere here in devstats about changing this.

**Comment by lukaszgryglicki** [comment]
Implemented: https://k8s.devstats.cncf.io/d/rCYj6D3kz/new-and-episodic-contributors?orgId=1
Feedback welcomed.

Now working on the "Issue" dashboard - it will be very similar.

**Comment by lukaszgryglicki** [comment]
Similar dashboard for Issues: https://k8s.devstats.cncf.io/d/ey0DOdqzz/new-and-episodic-issues?orgId=1

**Comment by lukaszgryglicki** [comment]
Will add those dashboards on the remaining CNCF projects. Should be ready tomorrow.

**Comment by jberkus** [comment]
This looks great to me.  Thanks so much for adding this.

Go ahead and close the issue when you're done deploying it.

**Comment by lukaszgryglicki** [comment]
I think I forgot to check `is_pull_request` for excluding past issue creators. 
And I will add it to the remaining projects.
Then I'll close.

**Comment by lukaszgryglicki** [comment]
Implemented everywhere, closing.
