### ISSUE TITLE
When to use bar or line charts.

### ISSUE THREAD

**Issue by bergquist** [cncf/devstats.archive#5]
I guess its a matter of taste but when visualizing time spent and percentiles I think line charts are more explicit then bar charts. ( ex https://cncftest.io/dashboard/db/opened-to-merged ) Bar charts are more suitable when the values can be stacked. (like https://cncftest.io/dashboard/db/companies-stats ) Otherwise the viewer always have to consider if the values are stacked or not.

**Comment by lukaszgryglicki** [comment]
Thanks for suggestion. I'll change it.

**Comment by lukaszgryglicki** [comment]
Changed to a line chart and 15th percentile moved to 2nd Y-axis (it was very low compared to median and 85th percentile).

**Comment by lukaszgryglicki** [comment]
Closing - feedback addressed.
