### ISSUE TITLE
Some enhancements and corrections required for - ubuntu16 setup guide.

### ISSUE THREAD

**Issue by kmova** [cncf/devstats.archive#50]
I am trying to setup a local devstats environment using the instructions provided in:
https://github.com/cncf/devstats/blob/master/INSTALL_UBUNTU16.md

It will be good to include the following:
- Minimum System Requirements and recommended settings (like sysctl) for running postgres and influxdb on the same machine. (Currently I got into an issue where influx db is not starting the http service due to default limits on the openfiles etc. Still trying to get past this stage.)

Also, noticed the following minor items that needs to be updated:
- GOPATH needs to be fixed throughout the doc. For example /data/dev or $HOME/data/dev
- Need Go 1.7+. Using 1.6 default on Ubuntu 16.04 causes error at step : go get github.com/google/go-github/github
- sysctl: cannot stat /proc/sys/net/ipv4/tcp_tw_recycle: No such file or directory (not sure if this is expected)
- /etc/github/aoauth -> /etc/github/oauth

**Comment by lukaszgryglicki** [comment]
Well, this install worked on Ubuntu 16 (but it was a long time ago).
Now all my sites use Ubuntu 17.
After I finish new projects, I'll install Ubuntu 16 in some VM and then install DevStats updating documentation on the way.
I'll also fix items already listed in this issue.
And yes Go 1.7 is a minimum AFAIK - I remember some stuff needed Go 1.7 but I can't remember which one.
Ubuntu 16 install guide is outdated - I know that.

**Comment by dankohn** [comment]
@kmova Please feel to open a pull request to improve the documentation, if you don't mind.

**Comment by kmova** [comment]
Thanks @dankohn. Will do.

**Comment by lukaszgryglicki** [comment]
Great, thanks for the help!
