### ISSUE TITLE
Add "All" project and a metric for the unique number of people who have made a commit, PR or issue

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#52]
- Add "all.cncftest.io" project that aggregates data from all CNCF projects
- Add a metric for the unique number of people who have made a commit, PR or issue - especially to be used on 'All' project, but also usable on all other projects

**Comment by lukaszgryglicki** [comment]
- 'All' project already done: https://all.cncftest.io/dashboard/db/dashboards?refresh=15m&orgId=1

Need to update all other projects to have links to recently added projects and fix PRs merged in all projects
After that, I'll proceed to "Add a metric for the unique number of people who have made a commit, PR or issue"

**Comment by lukaszgryglicki** [comment]
@dankohn "Add a metric for the unique number of people who have made a commit, PR or issue" - this is supposed to be a chart - like it will show a non-descending number of such authors in time?

**Comment by dankohn** [comment]
OK. But can I please also get it as a number on
https://all.cncftest.io/dashboard/db/project-statistics

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Even better - so I'll just add this to "project statistics"
It will count such authors in a range selected from the drop-down - great!

**Comment by lukaszgryglicki** [comment]
Added new metric on all 17 projects on the test server.
Metric is under "project statistics" named: "Contributors (issue creators, PR creators, committers)".

Closing.
