### ISSUE TITLE
Please add github.com/crosscloudci into the cncf calculation

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#57]
Please add github.com/crosscloudci into the CNCF calculation

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Wasted some time :-(
GitHub Archives didn't return any args like "crosscloudci" and it is now processing 2017-11 - but I see that such or exist now.

I should have data at least 8 months old - according to this repo: https://github.com/crosscloudci/cross-cloud

probably name change, or maybe something else?
Anyway - need to investigate this case using Google BigQuery.

**Comment by lukaszgryglicki** [comment]
Hmmm, first data for 'crosscloudci' seems to be at 2017-12-27.
But why?
ttps://github.com/crosscloudci/cross-cloud has commits 8 months old?
Was it a private repo before 2017-12-27? @dankohn ?
If so - I'm only able to get data starting at 2017-12-27 - because before that date, GHA returns nothing.
![screen shot 2018-02-01 at 12 40 33](https://user-images.githubusercontent.com/2469783/35676750-4965555e-074d-11e8-9fd6-922f7adeb136.png)

**Comment by lukaszgryglicki** [comment]
Confirmed - BigQuery and GitHub Archives has only data starting at 2017-12-27 - and that data will be included in CNCF Project (and in 'All' project too).

**Comment by lukaszgryglicki** [comment]
This is even crazier
 - first GHA events appear 2017-12-27 - but they include past data (just like changing private -> public publishes all past private data), see:
![screen shot 2018-02-01 at 13 05 57](https://user-images.githubusercontent.com/2469783/35677650-c6de7c6a-0750-11e8-94ec-c2f975c8084c.png)

First GHA event is 2017-12-27, but it creates for example comment from 2017-05-18:
![screen shot 2018-02-01 at 13 09 55](https://user-images.githubusercontent.com/2469783/35677810-5fff43c0-0751-11e8-80f0-99ff35f3e385.png)


Anyway, all looks good - will now update 'All' project (merge with a new CNCF database).

**Comment by dankohn** [comment]
It was a name change. Repo had been in CNCF org. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Right, that probably explains all. Thanks.
