### ISSUE TITLE
Wrap projects in two lines (now we will soon have 16 CNCF projects)

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#58]
Wrap projects in two lines (now we will soon have 16 CNCF projects)

**Comment by lukaszgryglicki** [comment]
Working on this with https://github.com/cncf/devstats/issues/53

**Comment by lukaszgryglicki** [comment]
Done, closing.

**Comment by dankohn** [comment]
Please use this trick for closing issues, if you can, as it links issues and commits. 

https://help.github.com/articles/closing-issues-using-keywords/

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com
