### ISSUE TITLE
Add Vitess project

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#59]
Add Vitess project.

**Comment by lukaszgryglicki** [comment]
Will start tomorrow or in best case today.

**Comment by lukaszgryglicki** [comment]
Starting working on this

**Comment by lukaszgryglicki** [comment]
Will also add this project to 'All' project on the [test server](https://all.cncftest.io).
Vitess icons are non-existent yet on [artwork](https://github.com/cncf/artwork).

**Comment by dankohn** [comment]
@alexcontini Please comment here when you've uploaded the Vitess icons.

**Comment by lukaszgryglicki** [comment]
Vitess project added on the test server and on the prod server.
- https://vitess.devstats.cncf.io
- https://vitess.cncftest.io

Only the final image is missing, but once I have it it is just a single script call to update this image everywhere.
Closing.
