### ISSUE TITLE
Change default role to readonly editor

### ISSUE THREAD

**Issue by bergquist** [cncf/devstats.archive#7]
I suggest you edit the default anonymous role to `Read Only Editor` ( http://docs.grafana.org/installation/configuration/#auto-assign-org-role )

This makes it possible for viewer to inspect queries and settings but without giving them the power so save the dashboards. Makes it easier for people like me to find issues or just see how you the build the dashboards.

**Comment by lukaszgryglicki** [comment]
Will do.

**Comment by lukaszgryglicki** [comment]
Done.
