### ISSUE TITLE
Dump PG database as binary, not text

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#70]
Currently, the downloadable PostgreSQL database dump is in "text mode", that is it dumps the whole database as unicode text.  While such dumps are usable, they present more loading issues than "binary mode" dumps.

To do this, you would:

1. pass pg_dump the "-Fc" flag
2. drop tar.gz compression, since binary mode dumps are already compressed.

If these dumps are created by code in this repo, I'll be happy to submit a PR.  Not sure where that would be, though.

**Comment by lukaszgryglicki** [comment]
Dumps are created by scripts from [cron](https://github.com/cncf/devstats/tree/master/cron) directory.
I didn't see any issues with text mode dumps.
Current dumps are text + XZ compression:

**Comment by dankohn** [comment]
Lukasz, Josh is one of the top experts on Postgres. If he says we'd be
better off with binary mode, I suspect he's correct.

Josh, please feel free to do a PR and we can change the backup format.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
No problem. So I'll change to binary.

**Comment by lukaszgryglicki** [comment]
Done, dumps are about 3x bigger on average, but dumping time is a *LOT* faster.

**Comment by jberkus** [comment]
Since I never think anyone should make a change on my word alone, let me show you what the change in format enables:

```
pg_restore -l gha.dump
;
; Archive created at 2018-02-13 06:55:30 PST
;     dbname: gha
;     TOC Entries: 324
;     Compression: -1
;     Dump Version: 1.12-0
;     Format: CUSTOM
;     Integer: 4 bytes
;     Offset: 8 bytes
;     Dumped from database version: 9.6.6
;     Dumped by pg_dump version: 9.6.6
;
;
; Selected TOC Entries:
;
2830; 1262 14854400 DATABASE - gha postgres
6; 2615 2200 SCHEMA - public postgres
2831; 0 0 COMMENT - SCHEMA public postgres
1; 3079 12393 EXTENSION - plpgsql 
2832; 0 0 COMMENT - EXTENSION plpgsql 
425; 1259 14854401 TABLE public gha_actors gha_admin
426; 1259 14854404 TABLE public gha_actors_affiliations gha_admin
427; 1259 14854407 TABLE public gha_actors_emails gha_admin
428; 1259 14854410 TABLE public gha_assets gha_admin
429; 1259 14854416 TABLE public gha_branches gha_admin
430; 1259 14854422 TABLE public gha_comments gha_admin
431; 1259 14854428 TABLE public gha_commits gha_admin
432; 1259 14854434 TABLE public gha_commits_files gha_admin
433; 1259 14854440 TABLE public gha_companies gha_admin
...
```

also this:

```
 pg_restore -t gha_orgs -h 172.17.0.2 -U postgres -O -x -d postgres gha.dump
```

... that command says "load just the table gha_orgs with no ownership/permissions information into the database postgres".  Stripping out the permissions/ownership info is especially valuable for the download, since others will not have the same DB/user setup that CNCF has in production.

**Comment by lukaszgryglicki** [comment]
Yes, the `.dump` format is more flexible.
Thanks for the info!
