### ISSUE TITLE
Prioritize tasks in this repo

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#71]
Per @lukaszgryglicki's request, Contribex needs to prioritize requests in this repo.

I think the best way to do this is for Lukasz to add a set of priority labels, and then @tpepper @spiffxp @castorojo and I can set priorities on them.  We'll need permission to add labels as well.

**Comment by dankohn** [comment]
@jberkus I made you an admin. Could you please add the rest and then close the issue.

**Comment by jberkus** [comment]
Thanks!

I'll want to leave this issue open until we're done prioritizing.  @lukaszgryglicki, please ignore priority flags until then.  Thanks!

**Comment by lukaszgryglicki** [comment]
OK.

**Comment by jberkus** [comment]
The existing graph is good, closing this.

**Comment by jberkus** [comment]
All requests from ContribEx have been given priorities now.
