### ISSUE TITLE
Port DevStats to Kubernetes

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#72]
Port current bare metal DevStats implementation to Kubernetes.

**Comment by jberkus** [comment]
I'll help with this.

**Comment by lukaszgryglicki** [comment]
OK, but currently this is postponed, @dankohn said that this has low priority.

**Comment by lukaszgryglicki** [comment]
Actually, the biggest "issue" for me would be to have a Kubernetes test cluster to start working on it.
It can even be just a few nodes cluster, I can imagine architecture something like this:

- "DevStats" pod(s) - each of them containing all Go binaries. Not sure if we need one or many. If many, then each one can handle a single project. If one - then it will handle all projects. But we can scale this according to needs I suppose.
- "Postgres database" pods - one for each project, if more than one for each project then I have no idea how to sync instances for the same project. This, of course, requires some storage per each pod. 
- "influx database" pods - one for each project, if more than one for each project then I have no idea how to sync instances for the same project. This, of course, requires some storage per each pod.
- "Grafana" pods - one for each project, or maybe more (to scale if needed). This may include apache proxy to server https, or maybe nginx (if preferred). Maybe configure Grafana pod to support SSL natively (if possible?)

And a lot of config manifests, communications between all pods, ton of environment variables, secrets, storage, replication(s)?.

My biggest concern is how to handle storage.

But I'm a **TOTAL beginner** in k8s stuff. 

I'm totally open to suggestions how to make it kubernetes app. I think it has quite a good potential to be containerized. It was (at least a big) designed to be moved to k8s finally.
I can also describe current architecture in very deep details if needed, but please take a look at all *.md files - most of the arch is already documented.

I would take a look at README.md, USAGE.md, ARCHITECTURE.md, ADDING_NEW_PROJECT.md and INSTALL_*.md - this is a good place to start thinking about Kubernetes port.
I would also leave current "bare metal" install as another possible option (so it would be possible to deploy to bare metal and/or kubernetes cluster).

**Comment by dankohn** [comment]
Lukasz, when we're ready, you can setup your own Kubernetes cluster on
Packet. I'm just not sure there's much to be gained doing so right now.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by jberkus** [comment]
My plans are to set up a complete toolchain for k8s devstats, since I don't really have a strong interest in the other projects.  However, if you copy my pattern, you can then set up toolchains for each project.

Warning: I *may* use Openshift for this, because routes are easier than ingress.

**Comment by lukaszgryglicki** [comment]
So so let me know when I should start thinking/working on this.

**Comment by lukaszgryglicki** [comment]
It is decided not to do this ATM, maybe in the future, so marking as `wontfix` now.

**Comment by jberkus** [comment]
Assigning to self

**Comment by lukaszgryglicki** [comment]
OK, if you need any help just ask me.
Email, slack, skype, anything...

**Comment by jlewi** [comment]
@lukaszgryglicki I'm part of [Kubeflow](https://github.com/kubeflow/kubeflow). We'd like to get devstats setup for Kubeflow (kubeflow/community#34). We aren't part of CNCF (hopefully one day). 

So the expectation was that we'd have to set it up and run it ourselves. We will deploy it on K8s. If you'd be interested in helping us with that it would be greatly appreciated.

@jberkus Did you ever get a complete tool chain set up for K8s?

**Comment by lukaszgryglicki** [comment]
I have no experience with K8s, so I can help with anything related to DevStats.
Just ping me here on email (lgryglicki@cncf.io) or slack.

**Comment by lukaszgryglicki** [comment]
Any news here? progress?
Influx is no more needed, so this makes porting easier.
Maybe this is stalled? I can start work on this if this is stalled.
cc @dankohn

**Comment by lukaszgryglicki** [comment]
This is currently wip.
I'll split devstats code to one repo, CNCF bare metal deployment to the another, example bare metal deployment to third and Kubernetes deployment to 4th (possibly also create 5th with example Kubernetes deployment).

**Comment by jberkus** [comment]
@lukaszgryglicki where's your code?  I'll test it.

**Comment by lukaszgryglicki** [comment]
This is not yet ready to be tested. All code is inside `k8s/` directory and details are in `k8s/README.md`, but again - this is very `wip` atm, give me a few days to clean up make it look good etc.

**Comment by jberkus** [comment]
ok, I'll take a look and try to improve it

**Comment by lukaszgryglicki** [comment]
Sure, this is just a work in progress state.
It is missing `PVs` (persistent volumes) config to keep `git repos` clones state across calls (I just need a team friend to set up AWS PVs for that) and it also misses `Helm` charts. I will work on this (and many more) tomorrow.
The almost completed sections are described here:
- https://github.com/cncf/devstats/blob/master/k8s/README.md#secrets
- https://github.com/cncf/devstats/blob/master/k8s/README.md#deploy-on-kubernetes
the rest of the `README.md` contains some information about how to manually run pods interactively, test them, create docker images etc. That will probably be removed from the `README.md` and moved to a separate `md` document.
More changes include:
- Create a script that will provision everything (just like a script to create all cron jobs at once)
- Create a script to delete all devstats cron jobs (just like the script that removes all completed pods)
- Create cron job script that will periodically clear completed pods
- Add all CNCF projects to k8s/projects.yaml, provision them and add their cron jobs (k8s deployment is for the LF, it outputs data into the elastic search in AWS and do not use Grafana)
- Add Helm charts
- Add PVs and use them
- Possibly many more.

I think you can review this state and eventually give feedback, but I would avoid improving it at this moment because our work will collide. You can also wait a few days (possibly till the end of the week) when this should be more mature, the current state contains my 2-3 days work.

**Comment by jberkus** [comment]
Yeah, I see creating this as an operator eventually, but that's a longer-term effort.

**Comment by lukaszgryglicki** [comment]
@jberkus this is something a bit more mature, but will still work on the next days (it is not yet tested for instance). It was only tested by the `helm install --dry-run` to see if correct YAMLs are generated:
[helm chart](https://github.com/cncf/devstats/tree/master/devstats-helm).
BTW: Devstats repo will be split into multiple parts, as requested [here](
https://github.com/cncf/devstats/issues/165#issuecomment-467525981)

**Comment by lukaszgryglicki** [comment]
With last few days update, I almost have DevStats ported to Kubernetes. Grafana is ported, deployment and service too.
Currently missing part is:
- Some real DNS instead of service type LoadBalancer which just outputs some random elb based name  (EKS default).
- SSL/HTTPS support.
- Some dashboards (namely home dashboard for all projects) are using links to images/icons based on the hostname. In this simplest deployment using default EKS elb based LoadBalancer those links are broken (only on the home dashboard).
I would say DevStats is 90% ported to Kubenrtes.
Example Zephyr project exposed to the outside world (note the crazy URL that I cannot control atm):
-  http://a1ab28809433611e98f5602de9aa28f2-1477584054.us-west-2.elb.amazonaws.com:3000/

Helm chart is here: https://github.com/cncf/devstats/tree/master/devstats-helm

**Comment by lukaszgryglicki** [comment]
Work happens mainly on those repos:
- https://github.com/cncf/devstats-helm-example
- https://github.com/cncf/devstats-docker-images
- https://github.com/cncf/devstats-helm-lf (already existing deployment on EKS)
- https://github.com/cncf/devstats-k8s-lf

**Comment by bpfSockOps** [comment]
Actually, I have started working on this without knowing that there is an issue associated for it. 
I have been working on a docker image (minimal Ubuntu 18.04) including all the steps needed to deploy devstats. 
- I am now trying to setup all the components to talk with each other (Postgresql, Grafana and the docker image) as pods.
- I am also working on setting all the needed environment variables through configmaps.
- Also, I am implementing velero to backup all the data. 

I would like to help with this issue.

**Comment by jberkus** [comment]
I'm  going to close this issue because the primary work is done.  We need to improve the current implementation, but that is better done through specific issues.

@nzoueidi, if you want to add a backup tool or similar, please open an issue or PR for it?

**Comment by lukaszgryglicki** [comment]
We already support backups. Bare metal had full backups. I could do the same for Kubernetes deployments, but we don't really need to have full backups because almost all data comes from GHA (GitHub archives) and git, so it's 100% redoable. the only data that is not redoable is the data coming from GitHub API every hour. This data requires GitHub API tokens to be used and can only be run for the current time, not the history. This is why I've decided to backup only GitHub API events.
See [devstats-helm](https://github.com/cncf/devstats-helm) for full Kubernetes DevStats port, backup part is [here](https://github.com/cncf/devstats-helm/blob/master/devstats-helm/templates/devstats-backups.yaml) and [there](https://github.com/cncf/devstats-helm/blob/master/devstats-helm/templates/devstats-backups-pv.yaml). It is missing the UI part (no links to those backups) but I'll add them today.
