### ISSUE TITLE
Add all dashboards and tables documentation

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#74]
Working on this.

**Comment by lukaszgryglicki** [comment]
All work in this directory: https://github.com/cncf/devstats/tree/master/docs
Started first dashboard "Reviewers", see:
https://github.com/cncf/devstats/blob/master/DASHBOARDS.md
"documentation" link for 1st "Reviewers": https://github.com/cncf/devstats/blob/master/docs/dashboards/kubernetes/reviewers.md

**Comment by dankohn** [comment]
Please hold up. I'm concerned that the documentation is so detailed that it
won't be of use to anyone who wouldn't already want to read the code.
Please get some external reviews here of usefulness.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
OK, I can make it less detailed of course, but I wanted to make it maximum useful for anybody to understand how it works.

**Comment by dankohn** [comment]
Maybe having this for one, but writing it up fro each dashboard just seems
like duplicating the SQL queries.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Well, the plan was to put everything in separate files and then only link them together.
This may see complex ATM because I'm just adding the first dashboard, so it may have a lot of data in its own description, but my intention was that I will be splitting shared/common info into files.
The initial plan was to have a separate file for each table and dashboard.
And a bunch of common items in separate files like annotations, tags, repository groups etc. etc.

**Comment by dankohn** [comment]
It seems like a lot of work. I would love to hear from others who would
find that useful.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Sure!
I will just make first dashboard docs complete, it is now 90-95% ready.

**Comment by lukaszgryglicki** [comment]
Can you ping the person(s) who should do a review?
Just a review of first dashboard documentation - few tables are marked TODO now, but this is a detail, I just want to know if I'm going in the right direction.

**Comment by jberkus** [comment]
I'm fine with super-detailed docs from Lukasz; I can then add a more general summary to each doc.  But -- for example -- Contribex does want to know the underlying SQL and InQL queries so that we can data mine.

**Comment by lukaszgryglicki** [comment]
So I will continue work on this tomorrow unless decided otherwise ( by @dankohn ).

**Comment by dankohn** [comment]
Josh, you're the customer here. Could you please just spend a couple more
minutes reviewing the PR and specifying the ideal level of detail. If you
want what he's doing, that's fine with me. If you're happier with links to
the SQL and InQL, that's also fine.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by jberkus** [comment]
Ah, I was hunting for the PR and not finding it because there isn't one.

The super-detailed information is useful, although it's more detailed than I actually need.  So one question is how easy it is for Lukasz to generate that; if it's all manual, I'd say that he doesn't need to have every single step in data generation, we'd be OK with links to the queries and notes on anything that's special about the chart generation.  If those are useful for some other reason, though, then knock yourself out.

The second part of this is going to be having the Contribex team add descriptive paragraphs to each chart, based on Lukasz's detail.  One of the challenges there is that the current chart page layout doesn't have a spot for a description, so that needs to go into the template somehow.

HOWEVER, Contribex is in the middle of drafting a list for chart consolidation and elimination.  If you wait for us to finish that, then it'll cut down on the number of charts that need to be documented.

**Comment by dankohn** [comment]
It's all manual, and felt like the wrong level of detail. Instead, you
might consider having Lukasz give a try on the "purpose" or "meaning" of
each graph, which ContribX folks could then edit (or rewrite).

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
I will try to adjust next dashboards descriptions.

**Comment by lukaszgryglicki** [comment]
After reading other issue comments, I'm stopping work on this, I'll focus on a new dashboard.
This is because some big feedback about dashboard will be available soon and many changes will probably need to be done.
So I'll avoid updating dashboards, test coverage and additional update of docs.

**Comment by jberkus** [comment]
@dankohn @lukaszgryglicki so what contribex needs to write Kube-dev-friendly descriptions is really just two-to-three lines about what the graph shows, links to the queries/code for that graph, and a quick callout by Lukasz on anything that might be "weird" about that particular graph.  So yeah, less detail than the example.

However, Contribex needs to get through the graph consolidation/elimination first, to avoid a bunch of wasted work.

One thing @lukaszgryglicki could take a look at right now: we want a way to display extended descriptions without leaving the graph screen.  Currently there's just the (?) link, which (a) permits only a very short descritpion, and (b) the user needs to remember to click on.  We'd rather have descriptions which were on-screen and could be a couple paragraphs long.

**Comment by lukaszgryglicki** [comment]
I'm back on this, all tables docs are already there, so I will now document dashboards one-by-one.
I'll try to keep docs without too much details - as requested.

**Comment by lukaszgryglicki** [comment]
Added "SIG mentions" dasboard [documentation](https://github.com/cncf/devstats/blob/master/docs/dashboards/kubernetes/sig_mentions.md).
Working on the other SIG related dashboards.

**Comment by jberkus** [comment]
@lukaszgryglicki any thougts on how to display the docs on the graph page?

**Comment by lukaszgryglicki** [comment]
You mean on the dashboards?
I can put link to a specific dashboard, but I don't know how can I put entire documentation there.
Is just the link OK?

**Comment by lukaszgryglicki** [comment]
Added "Reviewers" and "SIG mentions" documentation as HTML (that is fetched from postgres datasource)

Special "user documentation" (no development info, just few lines for casual users) put on the DevStats panel, it contains link to more detailed "developer documentation" (more detailed developer oriented version). 

All links open in a new tab (this is why I had to change MD to HTML, MD doesn't support opening links in new tabs, I did a long research on the net).

- [Reviewers](https://k8s.devstats.cncf.io/d/38/reviewers).
- [SIG mentions](https://k8s.devstats.cncf.io/d/41/sig-mentions?orgId=1).

Also I wanted to avoid storing HTML directly in Grafana's JSON files. HTML is escaped then and all contents is put in a single line, so it is basically non-editable, and even if it would be editable, all changes require reimporting JSON from Grafana UI.

I've decided to put entire HTML in a Grafana template variable.

To do so I've created normal HTML file, that is editable and is committed into repo.

Then I wanted `idb_vars` tool to put its contents into InfluxDB, so Grafana can fetch it (Grafana template variable called [[docs]]).

It was a dead end - Influx was not able to store long HTML in a series tag. Researched this a bit and resigned.

Next I've noticed that new v5.0.0 Grafana **supports Postgres OOTB** !! Hurray !! (that was not the case for v4).

I've decided to add a new tool `pdb_vars` that allows to store some user-defined variables in Postgres and then Grafana can use them.
Tool is created, fetches HTML and stores in PSQL, then Grafana fetches this from "psql" datasource as [[docs]] template variable, all full documentation is just a template variable call `[[docs]]`.

For more details just take a look at my commits from today.
Also all new stuff is documented.

**Comment by lukaszgryglicki** [comment]
This is how it looks now:
![screen shot 2018-03-14 at 14 48 15](https://user-images.githubusercontent.com/2469783/37406209-e640063a-2796-11e8-9659-5a88f05c270b.png)
![screen shot 2018-03-14 at 14 48 45](https://user-images.githubusercontent.com/2469783/37406210-e65cdbac-2796-11e8-8687-ca83598e2e34.png)

[This](https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/sig_mentions.json#L304-L322) is how we get documentation HTML from new [Postgres](https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/sig_mentions.json#L11-L18) datasource, to display dashboard [documentation](https://github.com/cncf/devstats/blob/master/grafana/dashboards/kubernetes/sig_mentions.json#L193-L205) (entire documentation content is in `[[docs]]` template variable).
It uses new [pdb_vars](https://github.com/cncf/devstats/blob/master/cmd/pdb_vars/pdb_vars.go) tool to create HTML using [this](https://github.com/cncf/devstats/blob/master/metrics/kubernetes/pdb_vars.yaml#L8-L12) postgres variable definition, which fetches [this](https://raw.githubusercontent.com/cncf/devstats/master/docs/dashboards/kubernetes/sig_mentions.md) file (I've used raw GitHub link to show real HTML content)
When file is saved with '.md' extension GitHub shows [rendered HTML](https://github.com/cncf/devstats/blob/master/docs/dashboards/kubernetes/sig_mentions.md) which is exactly what we want to show on GitHub.
What is interesting - when I save HTML file with `.html` extension, GitHub UI will show HTML code.
This is why I've saved HTML file with `.md` extension - to make better UX.
Documentation is [here](https://github.com/cncf/devstats/blob/master/docs/vars.md).

**Comment by lukaszgryglicki** [comment]
Also added documentation to the main home dashboard.
Removed `wip` because I'm working on adding `OPA` project atm, waiting for feeback about currently implemented dashboards.

**Comment by lukaszgryglicki** [comment]
Added 'SIG mentions categories user & developer' docs:
https://k8s.devstats.cncf.io/d/40/sig-mentions-categories?orgId=1

**Comment by lukaszgryglicki** [comment]
Added 'SIG mentions using labels' dashboard user & developer docs: https://k8s.devstats.cncf.io/d/42/sig-mentions-using-labels?orgId=1

**Comment by lukaszgryglicki** [comment]
@jberkus would be great to have some feedback about documentation added.
It is placed on the dashboards as requested, but I don't know if feedback is positive or not....
Few dashboards already have user & devel docs - mentioned in this thread.

**Comment by jberkus** [comment]
These are looking pretty good, at least the ones I've seen.  Where does the Contribex team edit them?  I'd like to add narrative descriptions for users, and it makes sense for our team to just go through them and get them done.

cc @Phillels

**Comment by lukaszgryglicki** [comment]
Please fork the repo and edit files in [docs](https://github.com/cncf/devstats/tree/master/docs/dashboards/kubernetes directory).
Those ending with _devel.md are for developers, remaining ones are user docs that are directly shown on the dashboards (4 so far).

**Comment by lukaszgryglicki** [comment]
Added docs for:
- GitHub stats per repo/Github stats per repo groups (it only had docs when reviewers metric was selected, now it has docs for all possible stats).
- PR reviews by contributors
- PR workload per SIG chart
- PR workload per SIG table

Working on the remaining dashboards.

**Comment by lukaszgryglicki** [comment]
Added docs:
- Blocked PRs
- Bot cmmands.

**Comment by lukaszgryglicki** [comment]
Added:
- Open issues/PRs by milestone
- Contributing companies in repo groups
- Companies table
- Company statistics by repository groups
- Developers activity counts by repo groups
- Issues age by SIG and repo groups docs

**Comment by lukaszgryglicki** [comment]
Added:

- Issues opened/closed by SIG
- New and episodic issue creators
- New and episodic contributors
- Open PRs age by repo group
- Overall projects statistics
- PR comments
- PR reviews by contributor

**Comment by lukaszgryglicki** [comment]
Added:

- PR time approve to merge
- PR time to engagement
- PR approval repo groups
- PR authors repo groups
- PR labels repo groups
- Stars and forks by repos

Closing this (all dashboards now have docs).
Let me know if you need to reopen this.
