### ISSUE TITLE
Contributing Developers data

### ISSUE THREAD

**Issue by parispittman** [cncf/devstats.archive#75]
Looking at the contributing companies and developer graph, it's showing ~11k developers over a period of 4 quarters MA (all repos) - where is this data coming from? If you use the PR Authors graph (all repos) for the year, we only have ~3.5k for 2017 and ~1k in 2018. 

Is the contributing developers how many have signed the CLA and PR Authors those who have made a commit?

**Comment by lukaszgryglicki** [comment]
Contributing companies & developers show max about:
- 821 companies
- 5201 developers
See:
![screen shot 2018-02-21 at 07 48 05](https://user-images.githubusercontent.com/2469783/36466691-a75285c2-16db-11e8-9af4-77168c0d469f.png)
I'm now wrting detailed documentation for all dashboards - it will explain all cases, but for this issue.
This dashboard calculates number of distinct "actors" who made at least one of
- PR review comment
- GitHub push/commit
- PR
- Issue
- Issue comment
- Commit comment
in a given aggregation period.

PR authors indeed shows about 4k authors in 2017:
![screen shot 2018-02-21 at 07 58 07](https://user-images.githubusercontent.com/2469783/36467018-05eff4a6-16dd-11e8-8f50-c2cfccb04e67.png)

But "PR author" != "developer"
PR authors chart is showing the number of unique PR creators from that period.
So this is expected that those values will be different.

**Comment by lukaszgryglicki** [comment]
Closing this, please let me know if more work is needed on this.

**Comment by parispittman** [comment]
I think my concern with this dashboard is it's picking up folks who are only filing issues and not contributing upstream - I do consider issue triage and commenting upstream. How can we differentiate between those just filing issues vs everything else?

**Comment by jberkus** [comment]
Short of semantic analysis, I don't see any way to differentiate between issue triage and just commenting on things.
