### ISSUE TITLE
Consider using app.theroocause.io for tracking runtime errors

### ISSUE THREAD

**Issue by AndreyKozlov1984** [cncf/devstats.archive#76]
@lukaszgryglicki  Please contact me for details, I'll help you with set up and everything else

**Comment by lukaszgryglicki** [comment]
OK, I'm working on docs atm, when I would be able to leave it in a consistent state, I'll contact You.
Zoom? Skype?
My skype is lukaszgryglicki, you can ping me anytime.

**Comment by lukaszgryglicki** [comment]
We talked with @ZeusTheTrueGod and
- Our DevStats is not using any javascript code
- We're using 19 Grafana instances - and this is the place to put any javascript code for therootcause

There are two options:
- Make all our Grafana custom instances with this special code added (this requires recompiling all Grafanas, and doing so each time we update Grafana)
- Create plugin for Grafana that will allow using therootcause

I think the "plugin" way is the better.
It would work similar to Google Analytics support in Grafana.
- You are editing grafana.ini and uncommenting from `# google_analytics_ua_id = ` to ` google_analytics_ua_id =  UA-XXXXYYYY-1`.

The same way we can create Grafana TheRootCause plugin. Somebody will have to register on therootcause, get some "API key" and then put that key in Grafana config file.

**Comment by lukaszgryglicki** [comment]
This discussion is open, waiting for Andrey's feedback here.

**Comment by lukaszgryglicki** [comment]
Grafana's Google Analytics is implemented as follows:
```
2018-02-21 12:53:43 root@cncftest:~/dev/go/src/github.com/grafana/grafana# find . -type f -exec grep -HIn "google_analytics_ua_id" "{}" \;
./pkg/setting/setting.go:588:	GoogleAnalyticsId = analytics.Key("google_analytics_ua_id").String()
./conf/defaults.ini:150:google_analytics_ua_id =
./conf/sample.ini:141:;google_analytics_ua_id =
./docs/sources/http_api/admin.md:44:    "google_analytics_ua_id":"",
./docs/sources/installation/configuration.md:700:### google_analytics_ua_id
2018-02-21 12:53:53 root@cncftest:~/dev/go/src/github.com/grafana/grafana# find . -type f -exec grep -HIn "oogleAnalyticsId" "{}" \;
./public/app/core/services/analytics.ts:17:    ga('create', (<any>config).googleAnalyticsId, 'auto');
./public/app/core/services/analytics.ts:33:  if ((<any>config).googleAnalyticsId) {
./pkg/api/index.go:68:		GoogleAnalyticsId:       setting.GoogleAnalyticsId,
./pkg/api/frontendsettings.go:144:		"googleAnalyticsId":       setting.GoogleAnalyticsId,
./pkg/api/dtos/index.go:8:	GoogleAnalyticsId       string
./pkg/setting/setting.go:153:	GoogleAnalyticsId  string
./pkg/setting/setting.go:588:	GoogleAnalyticsId = analytics.Key("google_analytics_ua_id").String()
2018-02-21 12:54:03 root@cncftest:~/dev/go/src/github.com/grafana/grafana# 
```

You just need to take a look at all files listed by `grep`.
Especially JS code is generated by `./public/app/core/services/analytics.ts`:
```
  gaInit() {
    $.getScript('https://www.google-analytics.com/analytics.js'); // jQuery shortcut
    var ga = ((<any>window).ga =
      (<any>window).ga ||
      function() {
        (ga.q = ga.q || []).push(arguments);
      });
    ga.l = +new Date();
    ga('create', (<any>config).googleAnalyticsId, 'auto');
    return ga;
  }

  init() {
    this.$rootScope.$on('$viewContentLoaded', () => {
      var track = { page: this.$location.url() };
      var ga = (<any>window).ga || this.gaInit();
      ga('set', track);
      ga('send', 'pageview');
    });
  }
```
**Looks very like standard GA code just using some templating engine**.

We can do something very similar for TheRootCause (creating say therootcause.ts with @ZeusTheTrueGod 's code using templates) and then create PR on grafana/grafana.
Eventually, we can create the final patch from the PR (if not approved by the Grafna team) and then apply this patch end recompile Grafana after all updates.
That would be a combination of option 1 & 2.

I can try to create such PR & patch tomorrow, but there is no ETA for this, because I don't even know how to compile & install Grafana from sources ATM.

**Comment by lukaszgryglicki** [comment]
I'm unassigning from this, let me know if any help is needed.

**Comment by ZeusTheTrueGod** [comment]
I guess the only change is to inject it here 
- https://github.com/cncf/devstats/blob/master/apache/www/index_prod.html

**Comment by lukaszgryglicki** [comment]
No, this is the index of a static page that only contains links to all
projects, database dumps etc.
Actually, no one uses this page directly, it is just for keeping all things
together.
All projects have links to other projects but not to this page, this is
rather for admin, and for git repo cloners, to allow downloading production
databases dumps.

**Comment by lukaszgryglicki** [comment]
Closing this, everything was discussed.
please reopen if needed.
