### ISSUE TITLE
Table Request: LGTM+Review per user/repo

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#79]
To support the reviewer mentoring program, we'd like to have a table which offers counts of LGTM and PR Review comments per github handle, per repo.  Importantly, this needs to either offer filtering by github handle, or list all github handles for a user-defined period of time.  In order to avoid sprawl, this should replace either the Developers Summary or the Reviewers Histogram.  Here's what it needs different from those:

* ability to filter by specific repo and not just repo group
* count of lgtms

AsciiArt example:

```
reviewer        |      Review comments    |         LGTMs
@thocklin       |                  453    |          118
@liggit         |                  409    |          130
```

@chrislovecnm does that cover everything?

cc @parispittman

**Comment by chrislovecnm** [comment]
I like it.  Should work.  We may need to break down by owners file location @parispittman for a specific sig?  I am not certain how lgtm's are measured for that.

**Comment by lukaszgryglicki** [comment]
Will work on this, probably starting on Monday.

**Comment by lukaszgryglicki** [comment]
I think the best way to show it would be:
- chart (this allows to show any date range)
- single value select drop down for all repos (not repo groups)
- multi value select for github logins

I see only one problem: how many github logins should be listed in this drop down?
I suggest Top N one, N being ... ?

The other way to do this is to generate table as suggested in first post but... in this case we can't select any date range.

The other question is what date range means, lets assume date range is d1..d2
- Number of LGTMs/Reviews in d1..d2 range (so for the chart we can use day, week, 7 days MA, month, quarter, year etc.). This can be used in both chart. In a table thsi will contain (last week, month, decade and all between releases date ranges)
- Number of LGTMs/Reviews at a given point of time (here we can pick d1 or d2), in this case there will be no date range drop down, this only makes sense in a chart, and each value will show number of LGTMs/Reviews at given points (usually daily). Each point will count without date from (cumulative).

**Comment by jberkus** [comment]
@lukaszgryglicki 

The purpose of this table/chart is actually to check on *specific* github logins, rather than to see "top N" or anything of the sort.

We have reviewer mentoring initiatives, and we want to see if they're working.  As such, we'd like to see how many reviews/LGTMs the individual github handle did before the mentoring, during the mentoring, and after the mentoring.  I don't see a way to do this with a custom date range.  And it requires listing all github handles, or having a text-box filter for github handles.

We'd also like to see this for the whole "group" of reviewers, but that would require the selection of an arbitrary 3-10 github handles, which seems like a lot of work.

**Comment by lukaszgryglicki** [comment]
So I will create something special for this. No problem.
Do you have a list of such logins?
Or I can just create a chart version with:
- repo drop down (single value)
- actor drop-down (signe selection), shopwing all GitHub actors who did at least one LGTM or review
- period drop down: day, week, month, quarter, year - can even add hourly (but I think max values will be few LGTM/reviews / hour)
Chart will show number of PRs and numbe rof LGTMs in those period, but it will also show totals over selected date range from the top right.
So to see number of before, during and after the mentoring you will have to choose those 3 ranges and see totalk values. You will also have some aggregated period values

Makes sense?
If not, we must think about something more than Grafana allows.

**Comment by jberkus** [comment]
So, two things that I think would work, so we can do either of them:

1. Just displaying a total for the selected custom date range;
2. Displaying totals by day for a date range, which could be non-custom (i.e. a month or a quarter).

I'm a bit concerned about a drop-down which allows selection of any github handle; don't we have like 2000 of those?

Chris, you want to weigh in?

**Comment by lukaszgryglicki** [comment]
There is a lot less than 2000 reviewers.
I'll try to create first verision now, and then we can discuss it, request changes etc.

**Comment by lukaszgryglicki** [comment]
Correction, we do have 2500 reviewers overall in all K8s history.

**Comment by lukaszgryglicki** [comment]
First very wip preview on the test server: 
https://k8s.cncftest.io/d/46/user-reviews?orgId=1

**Comment by lukaszgryglicki** [comment]
Prod version (added 7 days MA period on the way):
https://k8s.devstats.cncf.io/d/46/user-reviews?orgId=1

Feedback welcomed.

**Comment by parispittman** [comment]
Thank you for this @lukaszgryglicki. Appreciate your help. 

Is it possible to clear out the handles that are pre-populating in that field?

**Comment by chrislovecnm** [comment]
Yes please clear the pre selected gh handles. A date range from this to this is what we will pull for mentoring. Otherwise it looks great.

The drop down menu is fine for me, what is your concern about it?

**Comment by lukaszgryglicki** [comment]
I need to leave at least one handle. I'll leave the top one.
So, is this dashboard OK? Can I add test coverage for it?

**Comment by lukaszgryglicki** [comment]
Ported to remaining CNCF projects too, for example, "All CNCF": https://all.devstats.cncf.io/d/29/user-reviews?orgId=1
Most active reviewer selected for every project, with the exception of "All CNCF" project - here I've selected reviewers who did at least 500 PR review comments since 2016-01-01.
Only K8s version uses LGTM text & lgtm label, other projects only count PR review events (because LGTM is k8s-specific).

**Comment by chrislovecnm** [comment]
Looks great! Thanks

**Comment by lukaszgryglicki** [comment]
Actually last [link](https://all.devstats.cncf.io/d/29/user-reviews?orgId=1) was broken (anonymous access was disabled).
Fixed.
So thanks for the comment - I've just fixed bug thanks to this.
