### ISSUE TITLE
Create playlist based on tags

### ISSUE THREAD

**Issue by bergquist** [cncf/devstats.archive#8]
I just wanted to make sure that you know about the [playlist feature](http://docs.grafana.org/reference/playlist). Starting a playlist will cycle dashboards at a set interval. Kinda nifty for tv monitors in the office or a booth at conferences. You can start a playlist by going to a specific url ex http://play.grafana.org/playlists/play/1

**Comment by lukaszgryglicki** [comment]
I saw that feature, but there was no request to use it yet.
I will make use of it if needed for our project.
Currently we are using templating and annotations.

**Comment by lukaszgryglicki** [comment]
This is just a new feature using default Grafana functionality - good as a starting point for anybody wanting to help.
Tests can be done on "k8s.cncftest.io" server, on any dashboard.
If anybody wants to work on this then:
- Email me for the test credentials on "k8s.cncftest.io" - then play with dashboards: first export one dashboard to JSON, then do the work.
- If anything is wrong reimport modified dashboard from saved ISON (or from `cncf/devstats:grafana/dashboards/kubernetes/dashboard_name.json`)
- Once your dashboard is ready, export it as JSON and create PR with that JSON added to: `cncf/devstats:grafana/dashboards/kubernetes`
- It should also be available on https://k8s.cncftest.io so anybody can directly review it.

**Comment by lukaszgryglicki** [comment]
I'm closing this for now. We're not planning dashboards playlists atm.
