### ISSUE TITLE
Add continuous deployment

### ISSUE THREAD

**Issue by lukaszgryglicki** [cncf/devstats.archive#81]
Add continuous deployment (CD), this is already a bit in progress.
Things needed:
- Add `deploy` call to `make install` on success CI build.
- Add `deploy` tool: `cmd/deploy/deploy.go`.
- This tool will read `deploy.yaml` file, and will attempt to deploy projects with `deployed: false`.
- All current projects will receive `deployed: true` initially.
- `NATS` (currently wip) will receive `deployed: false` and will be the first candidate to test automatic deploy.
- Postgres database can ge either generated or fetched from the test server's backup - this will be controlled by some flag in `deploy.yaml` file.
-  If deployment succeeds `deploy` tool will update `deploy.yaml` file: it will change `deployed: false`, to `deployed: true` for a given project(s). Then it will generate automatic commit `Project(s) [list] deployed successfully [ci skip]` and push it. It won't trigger CI and CD (see `[ci skip]`).
- Deploy part is to call `./projectname/deploy.sh`.
- Each item in this script must first check if it needs to do anything, and then if necesarry do it.
It also need to check if devstats instance is running, wait for it to finish (if needed) then disable cronjobs, do its work and finally reenable cronjobs. This is already implemented and entrire `./projectname/deploy.sh` script is guarded by `sync_lock.sh` at the beginning and `sync_unlock.sh` at the end (called as bash TRAP exit function).
- `create_databases.sh` entry already deals with detecting what needs to be done and support multiple run flags (ENV variables).
- `create_grafana.sh` also supports this, but isn't yet finished.
- `./all/add_project.sh` doesn't support this yet, so need to add detecting if a new projects was already added to 'All CNCF' project.
- Additional automatic tools needs to be implemented: Grafana branding, Copying final grafana.db from test to prod (so there are no manual JSON imports needed), creating Grafana sessions database (postgres), Apache proxy config for new project, update WWW index with new project, certbot SSL certificate issue, starting new grafana server, backing up all grafana's DBs.

ETA 2-3 days. cc @dankohn

**Comment by dankohn** [comment]
In the final version, the script should be able to detect whether each instance is already configured and add the missing ones. So no `deployed: true` should be necessary.

**Comment by lukaszgryglicki** [comment]
Yes, but this requires adding deploy scripts for all past projects.
Good idea.
I'll do so, and there will be no `deployed: true/false` at all (in any version).
This will take a longer time of course.

**Comment by lukaszgryglicki** [comment]
Script [deploy_all.sh](https://github.com/cncf/devstats/blob/master/devel/deploy_all.sh) added and tested.
Worked for 'NATS' case.
It "almost" implements CD, the only missing part is that it is *NOT* called on a Travis CI hook.
Why?
I want to test it one more time on some next project.
For now, we're adding project to the test server, update all repo files.
Once ready we push to "production" branch which installs all stuff on a success callback.
Then I login to prod and manually call this script - I see no obstacles to call it from webhook, but I just want to go through all of this once more.
There is still a bit of things to do on a freash auto-deployed instance, see [adding new project](https://github.com/cncf/devstats/blob/master/ADDING_NEW_PROJECT.md):
1st section about what to do on the prod (this cannot be done automatically, requires few Grafana UI clicks):

# To add new project on the production (when already added on the test), you should use automatic deploy script:

- Run `./devel/deploy_proj.sh` script with correct env variables or run deploy for all projects `./devel/deploy_all.sh`.
- Go to [new project site](https://newproject.devstats.cncf.io) and change Grafana and InfluxDB passwords (default deploy copies database from the test server, so it has test server credentials initially).
- Reimport Home dashboard (which now contains link to a new project) on all existing projects.

**Comment by lukaszgryglicki** [comment]
Marked as blocked until I have a chance to add another project and test this from `A` to `Z` (NATS case was wip all the time, so it was hard to test the final version from real beginning to end).

**Comment by lukaszgryglicki** [comment]
Now battle testing it on the test server with OPA deployment.

**Comment by lukaszgryglicki** [comment]
Worked OK, also implemented optional copying InfluxDB from the test server (when deploying on the prod server), that speedups a lot.

**Comment by lukaszgryglicki** [comment]
CI/CD works, tested on OPA/SPIFFE. Closing this.
