### ISSUE TITLE
NATS goes before Linkerd

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#85]
Please order graduated, incubating, sandbox, then CNCF.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
I've also separated projects by their graduation state, just like on https://www.cncf.io/projects:
![screen shot 2018-03-19 at 07 06 51](https://user-images.githubusercontent.com/2469783/37580480-2b0c2a86-2b44-11e8-9381-b04fdb7ed9db.png)
Now will reimport home dashboard on all test & prod projects.
HTML content comes from PSQL variable, so it needs to be changed only once to update everywhere.

**Comment by lukaszgryglicki** [comment]
Done everywhere, closing.

**Comment by dankohn** [comment]
That takes up a ton of space. You might do better to emulate the project layout here: https://docs.google.com/presentation/d/1BoxFeENJcINgHbKfygXpXROchiRO2LBT-pzdaOFr4Zg/edit#slide=id.g34ebcfa888_3_54

**Comment by lukaszgryglicki** [comment]
Ok will try to do something similar.
I'll finish my idb backup from remote machine first - that should speedup automatic deploy order of magnitude times imho.

**Comment by lukaszgryglicki** [comment]
Finished backup tool - 100x speedup :)
I'm back on this, ETA tomorrow.

**Comment by lukaszgryglicki** [comment]
Ok update home dashboards, now list of projects is different on the test server and on the prod server. Also separating by graduation state is added and panel height is 2x less.
This is on the prod server:
![screen shot 2018-03-20 at 09 50 23](https://user-images.githubusercontent.com/2469783/37644461-31a9dd30-2c24-11e8-878d-1bca10ddee0e.png)

This is on the test server (OPA will finally have different icon, CNCF icon sed as a stub now):
![screen shot 2018-03-20 at 09 50 30](https://user-images.githubusercontent.com/2469783/37644465-3475c8c6-2c24-11e8-9949-c700210ab00a.png)
