### ISSUE TITLE
Possible to get a "Needs OK to test PRs" dashboard?

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#86]
Equivalent to https://k8s.devstats.cncf.io/d/17/need-rebase-prs?orgId=1 but instead of looking for the `needs-rebase` label, look for `needs-ok-to-test`

Intent is to measure how much of a backlog we have of PR's waiting for an org member to verify the PR is ok to test.  We use http://not.oktotest.com/ to track what those PR's are at any given time, but it's still a human effort.

We can sort of track what that human effort is right now with https://k8s.devstats.cncf.io/d/5/bot-commands?orgId=1&var-commands=ok-to-test but I don't think we can see the impact it's having

**Comment by jberkus** [comment]
Seems like we should have a single dashboard which lets us pick from a list of labels.

**Comment by lukaszgryglicki** [comment]
I need a list of labels for a "select label" dropdown.

**Comment by lukaszgryglicki** [comment]
OK, I'll create version with those two labels now, but I'll implement it in such a way that adding a new label will be easy.

**Comment by lukaszgryglicki** [comment]
I've sorted labels on k8s project by their occurence, and identified some other "blocker" labels, I'll add them to the drop down. We can change that anytime:
```
    'needs-rebase',
    'needs-ok-to-test',
    'do-not-merge',
    'cla: no',
    'release-note-label-needed'
```

I'll rename dashboard to "PRs labels by repository groups" as requested on naming convention issue here: https://github.com/cncf/devstats/issues/88#issuecomment-375971776

**Comment by lukaszgryglicki** [comment]
Dashboard created: 
- https://k8s.devstats.cncf.io/d/47/prs-labels-by-repository-groups?orgId=1

Now I need to update outdated test coverage to support multiple labels and special values 'All repos/labels combined'.

**Comment by lukaszgryglicki** [comment]
Test coverage also updated @jberkus @spiffxp let me know if dashboard is ok for you?

**Comment by jberkus** [comment]
Hmmm, most of those are labels we don't use anymore.

@spiffxp should be able to provide a better list of labels.

**Comment by lukaszgryglicki** [comment]
No problem, I'll replace them once it is done.
This will be easy and fast - I'm prepared for this.

**Comment by lukaszgryglicki** [comment]
@jberkus I'll be fixing "PRs labels" dashboard soon (problem with detecting reopened issues/PRs and performance issues), please provide me a list of labels to display asap.
Thx.

**Comment by lukaszgryglicki** [comment]
Dashboard is fixed on both prod & test, but I still don't have new labels list for the drop-down, so currently I didn't change labels set.

**Comment by lukaszgryglicki** [comment]
Blocked until I have a final labels list.
After I have it, it is just a 2 replacements & regenerating data.

**Comment by lukaszgryglicki** [comment]
@spiffxp @jberkus ping...

**Comment by spiffxp** [comment]
@lukaszgryglicki labels list should be
```
cla: no
cncf-cla: no
do-not-merge
do-not-merge/blocked-paths
do-not-merge/cherrypick-not-approved
do-not-merge/hold
do-not-merge/release-note-label-needed
do-not-merge/work-in-progress
needs-ok-to-test
needs-rebase
release-note-label-needed
```

**Comment by lukaszgryglicki** [comment]
Thanks, will update soon.

**Comment by lukaszgryglicki** [comment]
Data regenerated but... `do-not-merge/cherrypick-not-approved` should actually be: `do-not-merge/cherry-pick-not-approved`, so regenerating again.

**Comment by lukaszgryglicki** [comment]
Fixed. Now both test and prod envs contain requested label set, closing.
