### ISSUE TITLE
Are we including or excluding staging repos?

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#87]
This issue was raised by @sttts in #devstats on Slack.

There are almost a dozen repos which are "staging" repos for team development.  These are effectively duplicates of parts of kubernetes/kubernetes, and importantly duplicate all merges via cherrypick.  As such, if they are being included in our stats, that results in duplicate counting of a lot of commits.

These repos are all under kubernetes/, and include all  repos whose names match directory names in this folder: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io  That is, kubernetes/api duplicates the api/ directory, and kubernetes/client-go duplicates the client-go/ directory, etc.

So, the question is, are these currently being included?  If so, what's involved in excluding them?

**Comment by lukaszgryglicki** [comment]
All repos from kubernetes org are included.
And also 3 other orgs AFAIK.
To remove then, I would have to update `projects.yaml` config (possibly add some code to deal with "exlude list").
Then regenerate all k8s data.
Not a problem, I can do it anytime.

**Comment by lukaszgryglicki** [comment]
Actually, I can use exlude repos env (Notary already uses this): https://github.com/cncf/devstats/blob/master/projects.yaml#L159

**Comment by lukaszgryglicki** [comment]
OK, I'm researching this.

**Comment by lukaszgryglicki** [comment]
OK all K8s data is regenerating from scratch on the test server. If all is fine, it will be executed on prod tomorrow.

**Comment by jberkus** [comment]
OK since this will retroactively change a lot of our stats, let's not make it live until after the Contribex meeting this week, where we can discuss it.

**Comment by lukaszgryglicki** [comment]
This shouldn't change a lot.
Any "authors" related stats count distinct actors, so no change here.
Same with commits/issues, they usually count distinct objects - like IDs/SHAs.
But no problem. I can skip production update.
I must also regenerate 'All CNCF' project "all.devstats.cncf.io" which contains all data combined.
Of course I'll do this on the test first.

**Comment by lukaszgryglicki** [comment]
Starting (test only) 'All CNCF' project regenerating (because of k8s sandbox repos exclusion), I'll do it by merging all other psql databases, but Influx db must be regenerated after this succeeds. 
In theory my auto deploy script supports that OOTB - now I'll test if it actually works!

K8s is already done on the test.

Once I have both k8s and 'All CNCF' regenerated on the test, I can dump & restore data on the prod.
@jberkus I need your green light to do that, you asked me recently to hold.
Anyway, I won't be able to do this before Tue.

**Comment by jberkus** [comment]
Per Devstats and Contribex meetings, please go ahead once you have time.

**Comment by lukaszgryglicki** [comment]
OK, so I'll update prod, probably tomorrow.

**Comment by lukaszgryglicki** [comment]
It's switching now, there will be a small downtime.

**Comment by lukaszgryglicki** [comment]
OK excluding sandbox repos also live on prod.
But I have a more serious issue now: https://github.com/cncf/devstats/issues/91
Hopefully GHA guys will fix this soon, so I can fix devstats too.
Closing this.
