### ISSUE TITLE
Consistent graph naming

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#88]
Cc @jberkus @spiffxp

One of the reasons I find DevStats hard to use is that I can never remember the name of the graph I'm looking for.

Could we rename every dashboard that is a table to have table at the end of it. So Companies table instead of Companies summary. And Project statistics table. Reviewers histogram table.

Before @lukaszgryglicki starts on this, are there any other consistent naming rules we could apply at the same time?

**Comment by jberkus** [comment]
Well, if we're going to go about renaming things, let's adopt naming conventions that are more descriptive.  LIke "Approver Activity By Repository Group" instead of just "Approvers".

However, I think I should float any naming scheme past other folks.

@Phillels @spiffxp @parispittman

**Comment by dankohn** [comment]
I love adding "By Repo Group" everywhere that it makes sense.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
So currently I have two requests:
- Add table for tabular views
- Add "by repo group" when dashboard has repo group drop-down.

**Comment by dankohn** [comment]
Can you suggest any other common terms that would give you a hint want to
expect?

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

**Comment by lukaszgryglicki** [comment]
Hmm, I don't see any other atm.
I'll be back on this once I finish two other dashboard requests.
This is more like a discussion issue.

**Comment by jberkus** [comment]
Yes, it is.  Renaming everything is one of those things we want to do only once, so no rush.

**Comment by lukaszgryglicki** [comment]
I'll switch to this tomorrow, unless something other will be needed first.
I'l, try to use new SQLite DB update tool `import_json` for this.

**Comment by lukaszgryglicki** [comment]
Also we do have "tags on dashboards. All histogram/tabluar dashboards already have "table" tag, will also add "repogroup" tag on those with repo groups.
I've just finally updated new 'sqlitedb' tool that allows to mass export, mass import, update by JSON title, user title and uid. It would save me all manual import/export from Grafana UI>
This tool allows to exchange data between Grafana SQLite DB <--> dashboards JSONs on the server side, with wildcards etc.
https://github.com/cncf/devstats/blob/master/cmd/sqlitedb/sqlitedb.go

**Comment by lukaszgryglicki** [comment]
Changed names on the test server, then exported all data as JSONs using `sqlitedb` tool, finally new jsons imported using `sqlitedb` tool on prod.
Renaming worked, but new tags were not imported.
Examined DB [structure](https://github.com/cncf/devstats/blob/master/sqlite/grafana_k8s.sql) for tags and now I see that I need to update one more table `dashboard_tag`.

**Comment by lukaszgryglicki** [comment]
OK I've managed to mass import tags too - by adding tags sync option to 'sqlitedb' tool see [here](https://github.com/cncf/devstats/blob/master/cmd/sqlitedb/sqlitedb.go#L44-L122).
This task should be ready now,  all changes are both on prod https://k8s.devstats.cncf.io and test: https://k8s.cncftest.io.
@dankohn @jberkus let me know if I should reopen this.

It looks like this now:
![screen shot 2018-04-06 at 15 17 04](https://user-images.githubusercontent.com/2469783/38423247-a7c39452-39ad-11e8-9d8d-799362e5710c.png)

**Comment by jberkus** [comment]
Cool, thanks, just noticed the change.
