### ISSUE TITLE
Spire

### ISSUE THREAD

**Issue by dankohn** [cncf/devstats.archive#90]
Please add Spire as a sandbox project separate from SPIFFE.

https://landscape.cncf.io/selected=spire

**Comment by lukaszgryglicki** [comment]
You mean somethig like Notary/TUF case?
So SPIFFE would be all from spiffe - spiffe/spire
And Spire would be spiffe/spire ?

**Comment by dankohn** [comment]
Spiffe is (https://github.com/spiffe/ - https://github.com/spiffe/spire)

Spire is https://github.com/spiffe/spire

It's just like Notary/TUF.

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation https://www.cncf.io
+1-415-233-1000 https://www.dankohn.com

On Thu, Mar 29, 2018 at 11:33 AM, Łukasz Gryglicki <notifications@github.com

**Comment by lukaszgryglicki** [comment]
Exactly as I thought, ok will work on it tomorrow.

**Comment by lukaszgryglicki** [comment]
Done.
