### ISSUE TITLE
Add filter that shows project stats since CNCF join data

### ISSUE THREAD

**Issue by caniszczyk** [cncf/devstats.archive#93]
It would be great to have a quick filter to show the progress of the project since joining CNCF. Each project has joined on different dates: https://github.com/cncf/toc#projects

I'm not sure how easy it is to expose this.

**Comment by lukaszgryglicki** [comment]
I already have CNCF join date as an annotation (can be seen on the charts for example [here](https://k8s.devstats.cncf.io/d/8/companies-statistics-repository-groups?orgId=1&from=1455730757185&to=1458144854593), so adding this to the period selection drop-down will be quite easy. Will work on this in this week, not sur eif tomorrow - I have some other small project to finish.

**Comment by lukaszgryglicki** [comment]
Working on this.

**Comment by lukaszgryglicki** [comment]
Done, now all tabular views include "Before joining CNCF" and "Since joining CNCF" periods.
Added in all projects on both test & prod.
![screen shot 2018-04-11 at 10 04 03](https://user-images.githubusercontent.com/2469783/38604142-c64d506e-3d6f-11e8-9a35-44e9a2995272.png)

Closing.
