### ISSUE TITLE
Docs correction for setting devstats locally in ubuntu 16

### ISSUE THREAD

**Issue by isamrish** [cncf/devstats.archive#94]
I am trying to setup a local devstats enviroment using the instructions provided in:
https://github.com/cncf/devstats/blob/master/INSTALL_UBUNTU16.md

While trying to setup devstats in freshly installed ubuntu 16.04 LTS system, scripts was showing error
`fatal: unknown date format unix`  during running `./git/git_tags.sh` which is executed by `annotations.go`

This is happening when you run `./shared/reinit.sh` script of any project or your proejct locally.

Initially git version was 2.7.4
The problem is solved when I updated github version to 2.17.0  in my freshly installed machine.

It will be good to include following in setup for ubuntu 16 :
  - update git version if you have freshly installed ubuntu 16

**Comment by lukaszgryglicki** [comment]
Somebody already reported this.
You need to update git - Ubuntu 16.04 has too old git version.
This helped for Him:
When you do that, can you open a PR with documentation update about upgrading git?
Issue is just becuase when I last time installed DevStats on Ubuntu 16.04, there was no `annotations/git_tags.sh` script yet, and I'm working on Ubuntu 17 server(s).
This git version is OK: `git version 2.11.0`.

Discussion for Slack devstats channel:
```
vharsh [12:58 AM]
Thanks Łukasz.
I am slightly confused with `./git/git_tags.sh` which is executed by `annotations.go`

The command doesn't work on my machine, `Ubuntu16.04`. 
This fails with an error which says,
```fatal: unknown date format unix```

I am stretching my imagination but is the `unix` in `creatordate` some sort of bash function or something to do with `fnmatch` ?
I read about it from https://explainshell.com/explain?cmd=git+tag+-l+--format%3D%22%25%28creatordate%3Aunix%29%22
```git tag -l --format="%(creatordate:unix)"```
In that case is `creatordate:unix` something which is only present in some machines ? (edited)


lukaszgryglicki [7:18 AM]
unix means date formatted as unix timestamp.
This is the numbe rof seconds since epoch 1970-01-01 00:00:00
Example
2018-04-06 13:16:01 root@cncftest:~/dev/go/src/devstats# git tag -l --format=“%(creatordate:unix)”
1517253128
1517253128
1517323837
1517411098
1518783408
1521618336
what is You git version?
*your
Mine is: git --version
git version 2.11.0

vharsh [7:24 AM]
Okay, I seem to have an older version of `git` Mine is `git version 2.7.4`

lukaszgryglicki [7:25 AM]
you should do man git-tags

vharsh [7:25 AM]
This is what I get without specifying the date format.
```harsh@athena:~/code/go/src/devstats$ git tag -l --format="%(creatordate)"
Mon Jan 29 19:12:08 2018 +0000
Tue Jan 30 14:50:37 2018 +0000
Wed Jan 31 15:04:58 2018 +0000
Fri Feb 16 13:16:48 2018 +0100
Wed Mar 21 07:45:36 2018 +0000```

lukaszgryglicki [7:26 AM]
and search for something similar, I believe that unix timestamp format should be supported, but maybe is named differently
I’ve used unix timestamp format because it is easiest to parse - this is just a number of seconds
or maybe just upgrade git

Amrish [8:43 AM]
by upgrading git , issue is resolved, thanks @lukaszgryglicki

lukaszgryglicki [8:43 AM]
no problem
```

**Comment by isamrish** [comment]
Sure , will do that.
