### ISSUE TITLE
Set up read-only access to test PostgreSQL database

### ISSUE THREAD

**Issue by jberkus** [cncf/devstats.archive#96]
Per discussion on #devstats, please set up read-only access to the test instance of the PostgreSQL github database.  Recommended way to do this is:

1. create a 2nd user under the role ro_user, with its own username/password.
2. set up some kind of key-based ssh bastion for devstats team members (could be a seperate host, could be a restricted homedir on the DB server host).
3. Accept SSH keys from members of the devstats team for this account.

This is not a solution for providing RO access to the general public, but rather a solution for providing secure access to just the folks who work on devstats.

**Comment by lukaszgryglicki** [comment]
I'm not sure if I can create user on cncftest or cncfprod - event to just provide RO access to postgres.
I think it will be more secure to open postgres port 5432 on the test machine and allow access only for one read only user from outside.
@dankohn do you have any opinions?
Or maybe just another extra small server (separate host) that would be whitelisted for postgres on cncftest?
I think (may be wrong) that adding new use to cncftest would be dangerous - even witthout any root access (no sudo) and no postgres write access - such user can just use CPU/mem/disk resources. Of course I can setup quata for this too - but after all, opening TEST server postgres port will be simpler/better?
Thoughts?

**Comment by dankohn** [comment]
My thoughts are to defer to @jberkus on the best setup. Using a small server as a bastion host sounds reasonable to me, but Josh is the Postgres expert.

**Comment by lukaszgryglicki** [comment]
OK thanks. So we will need another packet instance right? The smallest possible one?
So @jberkus can you give me a suggestion how to setup this?
Can I have two listen addresses in Postgres?
One for local access 127.0.0.1:5432 and another for bastion host X.Y.Z.V?
Or how should I setup this?
I'll do some googling tomorrow, but my current knowledge is that I can set inet address to listen (and 0.0.0.0 means any address) and port.
Separatelly I can setup local socket access...
But can I have multiple addresses and more - addresses limited to postgres users?

**Comment by jberkus** [comment]
Let's PM about this on Slack, because I want to do some security setup stuff and NOT in a public issue tracker.

**Comment by lukaszgryglicki** [comment]
It is done. Please contact me or @jberkus if access for more people is needed.

**Comment by lukaszgryglicki** [comment]
I was interested if DevStats compile on ARMv8 - I’ve installed postgres database, influx database, compiled and all tests passed. So now bastion host has PSQL database locally, Influx database locally - but I’ve didn’t setup my private GitHub OAuth tokens and didn’t installed Grafana and cron jobs. So it just contains data from 3AM today

To access Influx database use:
- `influx -username gha_admin -password ... -database gha`.

To access postgres database (local) use:
- `psql -h localhost -U devstats_team gha`
To access logs database use:
- `psql -h localhost -U devstats_team devstats`

Influx data is now generating for all k8s data, it will take 2-3 hours from now
There is also special script that generates data only for k8s: devel/kubernetes_only.sh (which is just running now)

To access K8s DevStats database from the real processing server use:
- `psql -h cncf -U devstats_team gha`
To access logs from the real server use:
- `psql -h cncf -U devstats_team devstats`
