### ISSUE TITLE
[go] Add vendor to make it easy to build Docker image

### ISSUE THREAD

**Issue by gaocegege** [cncf/devstats.archive#98]
See https://github.com/kubeflow/community/pull/91#discussion_r182616029

Hi, I am a part of Kubeflow and we are trying to dockerize devstats and port it on k8s. I think we could import vendor directory to avoid `go get` in the docker image.

**Comment by lukaszgryglicki** [comment]
I can work on this later, probably tomorrow.
Or alternatively - you can create PR.
Thanks for the suggestion.
